Repository OCA/l10n-brazil, pull requests merged in 2018-08, with the labels that each got.

#580 8.0 l10n br account payment mode
  l10n_br_account_payment_mode/README.rst
  l10n_br_account_payment_mode/__init__.py
  l10n_br_account_payment_mode/__openerp__.py
  l10n_br_account_payment_mode/demo/payment_demo.xml
  l10n_br_account_payment_mode/models/__init__.py
  l10n_br_account_payment_mode/models/payment_mode.py
  l10n_br_account_payment_mode/models/res_partner_bank.py
  l10n_br_account_payment_mode/views/account_invoice_view.xml
  l10n_br_account_payment_mode/views/payment_mode_view.xml
  l10n_br_data_base/data/res.bank.csv
Labels: 8.0, needs review

#598 8.0 l10n br account payment boleto
  l10n_br_account_payment_boleto/README.rst
  l10n_br_account_payment_boleto/__init__.py
  l10n_br_account_payment_boleto/__openerp__.py
  l10n_br_account_payment_boleto/data/boleto_data.xml
  l10n_br_account_payment_boleto/demo/account_invoice_demo.xml
  l10n_br_account_payment_boleto/demo/payment_demo.xml
  l10n_br_account_payment_boleto/models/__init__.py
  l10n_br_account_payment_boleto/models/account.py
  l10n_br_account_payment_boleto/models/account_invoice.py
  l10n_br_account_payment_boleto/models/account_move_line.py
  l10n_br_account_payment_boleto/models/payment_mode.py
  l10n_br_account_payment_boleto/models/res_company.py
  l10n_br_account_payment_boleto/views/account_move_line.xml
  l10n_br_account_payment_boleto/views/account_view.xml
  l10n_br_account_payment_boleto/views/payment_mode.xml
  l10n_br_account_payment_boleto/views/res_company.xml
  oca_dependencies.txt
Labels: 8.0, needs review

#615 10.0 oca mig/multi ie
  l10n_br_base/models/res_company.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/security/ir.model.access.csv
  l10n_br_base/tests/__init__.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_tools_fiscal.py
  l10n_br_base/views/res_company_view.xml
  l10n_br_base/views/res_partner_view.xml
Labels: 10.0, needs review

#617 10.0 mig l10n br stock
  l10n_br_stock/__init__.py
  l10n_br_stock/__manifest__.py
  l10n_br_stock/data/l10n_br_stock_data.xml
  l10n_br_stock/models/stock.py
  l10n_br_stock/views/stock_view.xml
Labels: 10.0, needs review

#632 [FIX]Validacao cnpj_cpf independente
  l10n_br_base/models/res_partner.py
  l10n_br_base/tools/fiscal.py
Labels: 10.0

#637 10.0 feature/melhorias localizacao
  l10n_br_base/views/res_company_view.xml
  l10n_br_base/views/res_partner_view.xml
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_crm/views/crm_lead_view.xml
  l10n_br_crm/views/crm_opportunity_view.xml
Labels: 10.0

#642 10.0 migration/l10n br data base kill
  l10n_br_base/__manifest__.py
  l10n_br_base/data/res.bank.csv
  l10n_br_data_base/README.rst
  l10n_br_data_base/__init__.py
  l10n_br_data_base/__manifest__.py
  l10n_br_data_base/i18n/pt_BR.po
  l10n_br_data_base/static/description/icon.png
Labels: 10.0, needs review

#641 10.0 migration/l10n br data account kill
  l10n_br_account/__manifest__.py
  l10n_br_account/data/l10n_br_account.cnae.csv
  l10n_br_account/data/l10n_br_account.service.type.csv
  l10n_br_account/demo/base_demo.xml
  l10n_br_data_account/README.rst
  l10n_br_data_account/__init__.py
  l10n_br_data_account/__manifest__.py
  l10n_br_data_account/demo/base_demo.xml
  l10n_br_data_account/static/description/icon.png
Labels: 10.0, needs review
