Repository OCA/l10n-brazil, pull requests merged in 2019-08, with the labels that each got.

#707 [10.0] [FIX] Error postgres and remove deprecated Transifex in Travis
  .travis.yml
Labels: approved

#709 [12.0][ADD] Added pot translation files
  l10n_br_crm/i18n/l10n_br_crm.pot
  l10n_br_zip/i18n/l10n_br_zip.pot
  l10n_br_zip_correios/i18n/l10n_br_zip_correios.pot
Labels: 12.0, approved

#708 [10.0][ADD] pot translation files
  l10n_br_account/i18n/l10n_br_account.pot
  l10n_br_account_payment_order/i18n/l10n_br_account_payment_order.pot
  l10n_br_account_product/i18n/l10n_br_account_product.pot
  l10n_br_base/i18n/l10n_br_base.pot
  l10n_br_crm/i18n/l10n_br_crm.pot
  l10n_br_crm_zip/i18n/l10n_br_crm_zip.pot
  l10n_br_hr/i18n/l10n_br_hr.pot
  l10n_br_resource/i18n/l10n_br_resource.pot
  l10n_br_stock/i18n/l10n_br_stock.pot
  l10n_br_zip/i18n/l10n_br_zip.pot
  l10n_br_zip_correios/i18n/l10n_br_zip_correios.pot
Labels: 10.0, approved
