Repository OCA/l10n-brazil, pull requests merged in 2019-05, with the labels that each got.

#679 [12.0] fix l10n_br_crm views
  l10n_br_crm/views/crm_lead_view.xml
  l10n_br_crm/views/crm_opportunity_view.xml
Labels: 12.0, approved, bug

#678 [12.0] Definir o formato da rua de parceiros de outros paises
  l10n_br_base/models/res_partner.py
Labels: 12.0, bug, needs review

#682 [10.0][FIX] BIC Field
  l10n_br_base/data/res.bank.csv
  l10n_br_base/models/res_bank.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/views/res_bank_view.xml
Labels: approved

#683 [12.0][NEW] módulo para atualizar cotações de moedas
  l10n_br_currency_rate_update/__init__.py
  l10n_br_currency_rate_update/__manifest__.py
  l10n_br_currency_rate_update/i18n/l10n_br_currency_rate_update.pot
  l10n_br_currency_rate_update/models/__init__.py
  l10n_br_currency_rate_update/models/res_currency_rate_provider_bcb.py
  l10n_br_currency_rate_update/readme/CONFIGURE.rst
  l10n_br_currency_rate_update/readme/CONTRIBUTORS.rst
  l10n_br_currency_rate_update/readme/DESCRIPTION.rst
  l10n_br_currency_rate_update/readme/USAGE.rst
  l10n_br_currency_rate_update/static/description/icon.png
  l10n_br_currency_rate_update/tests/__init__.py
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
  oca_dependencies.txt
Labels: 12.0, approved, enhancement

#680 [10.0][MIG] l10n br account banking payment
  .travis.yml
  l10n_br_account_banking_payment/README.rst
  l10n_br_account_banking_payment/__init__.py
  l10n_br_account_banking_payment/__manifest__.py
  l10n_br_account_banking_payment/demo/account_banking_payment_demo.xml
  l10n_br_account_banking_payment/i18n/pt_BR.po
  l10n_br_account_banking_payment/models/__init__.py
  l10n_br_account_banking_payment/models/account_move_line.py
  l10n_br_account_banking_payment/models/account_payment.py
  l10n_br_account_banking_payment/readme/CONFIGURE.rst
  l10n_br_account_banking_payment/readme/CONTRIBUTORS.rst
  l10n_br_account_banking_payment/readme/CREDITS.rst
  l10n_br_account_banking_payment/readme/DESCRIPTION.rst
  l10n_br_account_banking_payment/readme/HISTORY.rst
  l10n_br_account_banking_payment/readme/INSTALL.rst
  l10n_br_account_banking_payment/readme/ROADMAP.rst
  l10n_br_account_banking_payment/readme/USAGE.rst
  l10n_br_account_banking_payment/static/description/icon.png
  l10n_br_account_banking_payment/static/description/index.html
  l10n_br_account_banking_payment/tests/__init__.py
  l10n_br_account_banking_payment/tests/test_payment_order.py
  l10n_br_account_banking_payment/views/account_due_list.xml
  l10n_br_account_banking_payment/views/account_payment.xml
  l10n_br_account_product/models/account_invoice.py
  oca_dependencies.txt
Labels: 10.0, approved, needs review

#567 10.0 l10n br resource
  l10n_br_resource/README.rst
  l10n_br_resource/__init__.py
  l10n_br_resource/__manifest__.py
  l10n_br_resource/i18n/pt_BR.po
  l10n_br_resource/models/__init__.py
  l10n_br_resource/models/resource_calendar.py
  l10n_br_resource/models/resource_calendar_leaves.py
  l10n_br_resource/readme/CONFIGURE.rst
  l10n_br_resource/readme/CONTRIBUTORS.rst
  l10n_br_resource/readme/CREDITS.rst
  l10n_br_resource/readme/DESCRIPTION.rst
  l10n_br_resource/readme/HISTORY.rst
  l10n_br_resource/readme/INSTALL.rst
  l10n_br_resource/readme/ROADMAP.rst
  l10n_br_resource/readme/USAGE.rst
  l10n_br_resource/static/description/icon.png
  l10n_br_resource/static/description/icon.svg.oca
  l10n_br_resource/static/description/index.html
  l10n_br_resource/tests/__init__.py
  l10n_br_resource/tests/test_resource_calendar.py
  l10n_br_resource/views/resource_calendar_leaves_view.xml
  l10n_br_resource/views/resource_calendar_menu.xml
  l10n_br_resource/views/resource_calendar_view.xml
  l10n_br_resource/wizards/__init__.py
  l10n_br_resource/wizards/workalendar_holiday_import_views.xml
  l10n_br_resource/wizards/workalendar_holiday_import_wizard.py
Labels: 10.0, needs review, new feature

#643 [8.0][FIX] Fix import and field name of move line
  l10n_br_account/models/account_invoice.py
  l10n_br_account_product/models/account_invoice.py
Labels: approved

#685 [12.0][FIX] BIC field
  l10n_br_base/data/res.bank.csv
  l10n_br_base/models/__init__.py
  l10n_br_base/models/res_bank.py
  l10n_br_base/models/res_partner_bank.py
  l10n_br_base/views/res_bank_view.xml
  l10n_br_base/views/res_partner_bank_view.xml
Labels: approved

#687 [FIX] website key must be a valid URL
  l10n_br_resource/__manifest__.py
Labels: approved

#688 [FIX] Quantidade de dias para Atualizar ibpt
  l10n_br_account/models/res_company.py
Labels: approved

#689 [FIX] Travis error of l10n_br_resource
  l10n_br_resource/tests/test_resource_calendar.py
Labels: approved

#690 [8.0 -> 10.0] Migration scripts of l10n_br_base
  l10n_br_base/migrations/10.0.1.0.0/openupgrade_analysis.txt
  l10n_br_base/migrations/10.0.1.0.0/pre-migration.py
Labels: approved

#692 [REF] Closes #691 Removendo todos os caracteres não ascii
  l10n_br_resource/tests/test_resource_calendar.py
Labels: approved

#684 [10.0][MIG] l10n_br_account_payment_mode
  l10n_br_account_payment_mode/README.rst
  l10n_br_account_payment_mode/__init__.py
  l10n_br_account_payment_mode/__manifest__.py
  l10n_br_account_payment_mode/demo/payment_demo.xml
  l10n_br_account_payment_mode/models/__init__.py
  l10n_br_account_payment_mode/models/payment_mode.py
  l10n_br_account_payment_mode/models/res_partner_bank.py
  l10n_br_account_payment_mode/views/account_invoice_view.xml
  l10n_br_account_payment_mode/views/payment_mode_view.xml
  l10n_br_base/data/res.bank.csv
Labels: approved

#693 [FIX] 10.0 zip correios complemento2 + zeep
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/views/l10n_br_zip_view.xml
  l10n_br_zip_correios/__manifest__.py
  l10n_br_zip_correios/models/webservice_client.py
  requirements.txt
Labels: 10.0, approved, bug, needs review

#697 UserError: proper number of arguments
  l10n_br_zip_correios/models/webservice_client.py
Labels: 10.0, approved, bug, needs review

#695 [10.0][REF] Merged l10n_br_account_payment_mode and l10n_br_account_payment_banking
  l10n_br_account_payment_mode/README.rst
  l10n_br_account_payment_mode/__init__.py
  l10n_br_account_payment_mode/__manifest__.py
  l10n_br_account_payment_mode/models/__init__.py
  l10n_br_account_payment_mode/static/description/icon.png
  l10n_br_account_payment_mode/views/account_invoice_view.xml
  l10n_br_account_payment_order/README.rst
  l10n_br_account_payment_order/__init__.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/demo/account_payment_mode_demo.xml
  l10n_br_account_payment_order/demo/account_payment_order_demo.xml
  l10n_br_account_payment_order/i18n/pt_BR.po
  l10n_br_account_payment_order/models/__init__.py
  l10n_br_account_payment_order/models/account_move_line.py
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/models/res_partner_bank.py
  l10n_br_account_payment_order/readme/CONFIGURE.rst
  l10n_br_account_payment_order/readme/CONTRIBUTORS.rst
  l10n_br_account_payment_order/readme/CREDITS.rst
  l10n_br_account_payment_order/readme/DESCRIPTION.rst
  l10n_br_account_payment_order/readme/HISTORY.rst
  l10n_br_account_payment_order/readme/INSTALL.rst
  l10n_br_account_payment_order/readme/ROADMAP.rst
  l10n_br_account_payment_order/readme/USAGE.rst
  l10n_br_account_payment_order/static/description/icon.png
  l10n_br_account_payment_order/static/description/index.html
  l10n_br_account_payment_order/tests/__init__.py
  l10n_br_account_payment_order/tests/test_payment_order.py
  l10n_br_account_payment_order/views/account_due_list.xml
  l10n_br_account_payment_order/views/account_payment_line.xml
  l10n_br_account_payment_order/views/account_payment_mode.xml
Labels: approved
