Repository OCA/l10n-brazil, pull requests merged in 2019-04, with the labels that each got.

#653 [12.0] mig l10n br zip
  l10n_br_base/tests/test_valid_createid.py
  l10n_br_zip/README.rst
  l10n_br_zip/__init__.py
  l10n_br_zip/__manifest__.py
  l10n_br_zip/i18n/pt_BR.po
  l10n_br_zip/models/__init__.py
  l10n_br_zip/models/format_address_mixin.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/security/ir.model.access.csv
  l10n_br_zip/static/description/icon.png
  l10n_br_zip/tests/__init__.py
  l10n_br_zip/tests/test_l10n_br_zip.py
  l10n_br_zip/views/l10n_br_zip_view.xml
  l10n_br_zip/views/res_partner_address_view.xml
  l10n_br_zip/wizard/__init__.py
  l10n_br_zip/wizard/l10n_br_zip_search.py
  l10n_br_zip/wizard/l10n_br_zip_search_view.xml
Labels: 12.0, approved, needs review

#655 [12.0] mig l10n br crm
  l10n_br_crm/README.rst
  l10n_br_crm/__init__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/i18n/pt_BR.po
  l10n_br_crm/models/__init__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/static/description/icon.png
  l10n_br_crm/tests/__init__.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_crm/views/crm_lead_view.xml
  l10n_br_crm/views/crm_opportunity_view.xml
Labels: 12.0, approved, needs review

#654 [12.0] mig l10n br zip correios
  l10n_br_base/tests/test_valid_createid.py
  l10n_br_base/views/res_bank_view.xml
  l10n_br_zip_correios/README.rst
  l10n_br_zip_correios/__init__.py
  l10n_br_zip_correios/__manifest__.py
  l10n_br_zip_correios/i18n/pt_BR.po
  l10n_br_zip_correios/models/__init__.py
  l10n_br_zip_correios/models/l10n_br_zip.py
  l10n_br_zip_correios/models/webservice_client.py
  l10n_br_zip_correios/tests/__init__.py
  l10n_br_zip_correios/tests/test_webservice_client.py
Labels: 12.0, approved, needs review

#676 [12.0][FIX] l10n_br_base address tests
  l10n_br_base/data/base_data.xml
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/models/res_partner.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_zip/wizard/l10n_br_zip_search.py
Labels: 12.0, approved, bug

#613 [MIG] Script de migração v8 -> v10 l10n_br_base
  l10n_br_base/migrations/10.0.1.0.0/openupgrade_analysis.txt
  l10n_br_base/migrations/10.0.1.0.0/pre-migration.py
Labels: approved, needs review

#672 [12.0] l10n_br_base Update README infos
  l10n_br_base/README.rst
  l10n_br_base/readme/CONFIGURE.rst
  l10n_br_base/readme/CONTRIBUTORS.rst
  l10n_br_base/readme/DESCRIPTION.rst
  l10n_br_base/readme/INSTALL.rst
  l10n_br_base/readme/ROADMAP.rst
  l10n_br_base/readme/USAGE.rst
  l10n_br_base/static/description/index.html
Labels: 12.0, approved, enhancement

#673 [12.0] l10n_br_crm Update README infos
  l10n_br_crm/README.rst
  l10n_br_crm/readme/CONFIGURE.rst
  l10n_br_crm/readme/CONTRIBUTORS.rst
  l10n_br_crm/readme/DESCRIPTION.rst
  l10n_br_crm/readme/INSTALL.rst
  l10n_br_crm/readme/ROADMAP.rst
  l10n_br_crm/readme/USAGE.rst
  l10n_br_crm/static/description/index.html
Labels: 12.0, enhancement

#675 [12.0] l10n_br_zip Update README infos
  l10n_br_zip/README.rst
  l10n_br_zip/readme/CONFIGURE.rst
  l10n_br_zip/readme/CONTRIBUTORS.rst
  l10n_br_zip/readme/DESCRIPTION.rst
  l10n_br_zip/readme/INSTALL.rst
  l10n_br_zip/readme/ROADMAP.rst
  l10n_br_zip/readme/USAGE.rst
  l10n_br_zip/static/description/index.html
Labels: 12.0, enhancement

#674 [12.0] l10n_br_zip_correios Update README infos
  l10n_br_zip_correios/README.rst
  l10n_br_zip_correios/readme/CONFIGURE.rst
  l10n_br_zip_correios/readme/CONTRIBUTORS.rst
  l10n_br_zip_correios/readme/DESCRIPTION.rst
  l10n_br_zip_correios/readme/INSTALL.rst
  l10n_br_zip_correios/readme/ROADMAP.rst
  l10n_br_zip_correios/readme/USAGE.rst
  l10n_br_zip_correios/static/description/index.html
Labels: 12.0, enhancement
