Repository OCA/l10n-brazil, pull requests merged in 2020-11, with the labels that each got.

#1013 l10n_br_mis_report: Alpha -> Beta + picture fix
  l10n_br_mis_report/readme/DESCRIPTION.rst
Labels: 12.0, approved, bot is merging ⏳, needs review

#1018 [12.0][FIX] Name of field fiscal_operation_id
  l10n_br_account/wizards/account_invoice_refund.py
Labels: approved, bot is merging ⏳

#1011 [12.0] l10n_br_base README/manifest cleanup before migration
  l10n_br_base/__manifest__.py
  l10n_br_base/readme/DESCRIPTION.rst
  l10n_br_base/readme/HISTORY.rst
  l10n_br_base/readme/INSTALL.rst
Labels: 12.0, approved, bot is merging ⏳, needs review

#1012 [12.0] l10n_br_coa: added decent README about module design
  l10n_br_coa/__manifest__.py
  l10n_br_coa/readme/DESCRIPTION.rst
Labels: 12.0, approved, bot is merging ⏳, needs review

#1003 [FIX] l10n_br_account: Divisão dos itens em documentos fiscais diferentes
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/tests/test_customer_invoice_dummy.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs fixing

#980 [REF] Additional data for document and document line
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/migrations/12.0.4.0.0/pre-migration.py
  l10n_br_fiscal/models/comment.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/views/document_fiscal_mixin_view.xml
  l10n_br_fiscal/views/document_view.xml
Labels: 12.0, approved, bot is merging ⏳, needs fixing, needs review, ready to merge

#976 [12.0] Fiscal Document Menus
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/i18n/l10n_br_fiscal.pot
  l10n_br_fiscal/i18n/pt_BR.po
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/views/document_event_view.xml
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal/views/operation_dashboard_view.xml
Labels: 12.0, bot is merging ⏳, needs fixing

#1017 [12.0][FIX] Invoice quantity from sale order
  l10n_br_sale/models/sale_order_line.py
Labels: approved, bot is merging ⏳, bug, ready to merge

#1020 [12.0] Python 3.6 on Travis
  .travis.yml
Labels: approved, bot is merging ⏳, needs review

#1024 [ADD] Millimetre UOM
  l10n_br_fiscal/data/uom_data.xml
Labels: 12.0, approved, bot is merging ⏳

#1025 [NEW] Upgrade version of erpbrasil.base/assinatura/transmissao
  requirements.txt
Labels: approved, bot is merging ⏳

#902 [12.0][IMP] Padronização README e INDEX l10n_br_account
  l10n_br_account/README.rst
  l10n_br_account/readme/CONFIGURE.rst
  l10n_br_account/readme/CONTRIBUTORS.rst
  l10n_br_account/readme/DESCRIPTION.rst
  l10n_br_account/readme/HISTORY.rst
  l10n_br_account/readme/INSTALL.rst
  l10n_br_account/readme/ROADMAP.rst
  l10n_br_account/readme/USAGE.rst
  l10n_br_account/static/description/index.html
Labels: 12.0, approved

#1010 [12.0][l10n_br_base][BACKPORT] Improve demo data to easy migrate to version v14
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/demo/res_partner_demo.xml
  l10n_br_base/tests/test_base_onchange.py
Labels: approved, bot is merging ⏳

#1027 l10n_br_base faster tests: tracking_disable + SavepointCase
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_valid_createid.py
Labels: 12.0, approved, bot is merging ⏳, needs review

#1004 [FIX] l10n_br_sale: Correção do Tipo de Documento Fiscal
  l10n_br_sale/models/sale_order.py
Labels: 12.0, approved, bot is merging ⏳, bug

#942 [12.0] l10n_br_nfse_ginfes
  l10n_br_nfse/models/document.py
  l10n_br_nfse_ginfes/README.rst
  l10n_br_nfse_ginfes/__init__.py
  l10n_br_nfse_ginfes/__manifest__.py
  l10n_br_nfse_ginfes/constants/ginfes.py
  l10n_br_nfse_ginfes/models/__init__.py
  l10n_br_nfse_ginfes/models/document.py
  l10n_br_nfse_ginfes/models/res_company.py
  l10n_br_nfse_ginfes/readme/CONFIGURE.rst
  l10n_br_nfse_ginfes/readme/CONTRIBUTORS.rst
  l10n_br_nfse_ginfes/readme/DESCRIPTION.rst
  l10n_br_nfse_ginfes/readme/INSTALL.rst
  l10n_br_nfse_ginfes/readme/ROADMAP.rst
  l10n_br_nfse_ginfes/readme/USAGE.rst
  l10n_br_nfse_ginfes/static/description/icon.png
  l10n_br_nfse_ginfes/static/description/index.html
  l10n_br_nfse_ginfes/static/src/img/itajuba.png
  l10n_br_nfse_ginfes/tests/__init__.py
  l10n_br_nfse_ginfes/tests/nfse/001_50_nfse.xml
  l10n_br_nfse_ginfes/tests/test_fiscal_document_nfse_ginfes.py
  requirements.txt
Labels: approved, bot is merging ⏳, new feature, ready to merge

#1019 [12.0][FIX] Default values from stock_rule and stock_move in l10n_br_stock_account
  l10n_br_stock_account/README.rst
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/models/stock_rule.py
  l10n_br_stock_account/readme/CONTRIBUTORS.rst
  l10n_br_stock_account/static/description/index.html
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1028 [FIX] l10n_br_website_sale_tour lint
  l10n_br_website_sale/static/src/js/l10n_br_address.js
  l10n_br_website_sale/static/src/js/l10n_br_website_sale_tour.js
  l10n_br_website_sale/templates/portal_templates.xml
  payment_cielo/tests/fixtures/test_10_cielo_s2s.yaml
  payment_cielo/tests/test_cielo.py
Labels: approved, bot is merging ⏳

#1034 [FIX] Fix Unidade de medida CENTO
  l10n_br_fiscal/data/uom_data.xml
Labels: approved, bot is merging ⏳

#968 12.0 mig l10n br sale stock
  l10n_br_sale_stock/README.rst
  l10n_br_sale_stock/__init__.py
  l10n_br_sale_stock/__manifest__.py
  l10n_br_sale_stock/demo/l10n_br_sale_stock_demo.xml
  l10n_br_sale_stock/i18n/l10n_br_sale_stock.pot
  l10n_br_sale_stock/i18n/pt_BR.po
  l10n_br_sale_stock/models/__init__.py
  l10n_br_sale_stock/models/sale_order.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/models/stock_rule.py
  l10n_br_sale_stock/readme/CONFIGURE.rst
  l10n_br_sale_stock/readme/CONTRIBUTORS.rst
  l10n_br_sale_stock/readme/CREDITS.rst
  l10n_br_sale_stock/readme/DESCRIPTION.rst
  l10n_br_sale_stock/readme/HISTORY.rst
  l10n_br_sale_stock/readme/INSTALL.rst
  l10n_br_sale_stock/readme/ROADMAP.rst
  l10n_br_sale_stock/readme/USAGE.rst
  l10n_br_sale_stock/static/description/index.html
  l10n_br_sale_stock/tests/__init__.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/wizards/__init__.py
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: 12.0, approved, bot is merging ⏳, duplicate, migration, needs review
