Repository OCA/l10n-brazil, pull requests merged in 2020-08, with the labels that each got.

#935 [12.0] Load l10n br COA in Demo
  l10n_br_base/__init__.py
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_generic/data/account_tax_template_data.xml
  l10n_br_coa_generic/demo/account_chart_template.xml
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/demo/account_chart_template.xml
Labels: 12.0, approved, bot is merging ⏳, needs review

#933 [12.0] l10n_br_account: remove unused data file
  l10n_br_account/data/l10n_br_fiscal.xml
Labels: 12.0, approved, bot is merging ⏳, needs review

#934 [12.0] l10n_br_fiscal: fix module data and demo files
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/demo/operation_demo.xml
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/models/subsequent_document.py
Labels: approved, bot is merging ⏳

#929 [12.0][IMP] l10n_br_fiscal: Send email by document type and document state
  l10n_br_fiscal/README.rst
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/l10n_br_fiscal_email_template.xml
  l10n_br_fiscal/demo/l10n_br_fiscal_document_email.xml
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_email.py
  l10n_br_fiscal/models/document_type.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/security/fiscal_security.xml
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/views/document_email_view.xml
  l10n_br_fiscal/views/document_type_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
Labels: bot is merging ⏳

#940 [12.0] Fiscal features for NFS-e
  l10n_br_fiscal/README.rst
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/demo/city_taxation_code_demo.xml
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/city_taxation_code.py
  l10n_br_fiscal/models/document_eletronic.py
  l10n_br_fiscal/models/document_invalidate_number.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/views/city_taxation_code.xml
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal/wizards/wizard_document_cancel.py
  l10n_br_fiscal/wizards/wizard_document_correction.py
  l10n_br_fiscal/wizards/wizard_document_status.py
  l10n_br_fiscal/wizards/wizard_document_status_view.xml
Labels: bot is merging ⏳

#944 [FIX] Fiscal document number check constraint
  l10n_br_fiscal/models/document.py
Labels: 12.0, approved, bot is merging ⏳, bug
