Repository OCA/l10n-brazil, pull requests merged in 2020-05, with the labels that each got.

#824 Fix/portal testes2
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/static/img/res_partner_kmee.png
  l10n_br_portal/__manifest__.py
  l10n_br_portal/demo/res_users_demo.xml
  l10n_br_portal/static/src/js/l10n_br_portal_tour.js
  l10n_br_portal/tests/test_load_process.py
Labels: approved, bot is merging ⏳

#826 [12.0][FIX] Formatação CNPJ e CPF em crm_lead
  requirements.txt
Labels: approved, bot is merging ⏳

#827 [FIX] Rename Data
  l10n_br_simple/__manifest__.py
  l10n_br_simple/data/account_tax_group_data.xml
Labels: approved, bot is merging ⏳

#833 Pylint do l10n_br_hr_contract
  l10n_br_hr_contract/views/hr_contract_view.xml
Labels: 12.0, approved, bot is merging ⏳, needs review, refactoring

#830 Adicionar breve descrição ao módulo
  l10n_br_simple/README.rst
  l10n_br_simple/readme/DESCRIPTION.rst
  l10n_br_simple/static/description/index.html
Labels: approved, bot is merging ⏳

#829 Adequar nome de arquivos
  l10n_br_simple/__manifest__.py
  l10n_br_simple/data/account_chart_template_data.xml
  l10n_br_simple/data/account_tax_group_data.xml
Labels: approved, bot is merging ⏳

#838 [12.0][FIX] Tamanho do campo inscr_est de 16 para 17
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳

#840 [12.0][FIX][l10n_br_base] Ajuste na validação do cnpj_cpf
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳

#843 [REF] merge abstract fiscal documents and concrete fiscal documents
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_abstract.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_line_abstract.py
Labels: 12.0, approved, bot is merging ⏳, refactoring

#844 [12.0][FIX] Avoid delete demo data when update database.
  l10n_br_fiscal/hooks.py
Labels: approved, bot is merging ⏳

#839 mixin method extraction, inclusion in invoice line and synchro fixes
  l10n_br_account/models/__init__.py
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_fiscal/demo/fiscal_operation_demo.xml
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document_cancel.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_invalidate_number.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: 12.0, approved, bot is merging ⏳

#845 [REF] Fical Document Line mixin view to inject view in inherited views
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/document_line_view.xml
Labels: 12.0, approved, bot is merging ⏳, refactoring

#846 [FIX] Module description
  l10n_br_coa_simple/readme/DESCRIPTION.rst
  l10n_br_simple/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#841 Feature/l10n br coa
  l10n_br_account/__manifest__.py
  l10n_br_account/data/l10n_br_account_tax_data.xml
  l10n_br_account/data/l10n_br_account_tax_group_data.xml
  l10n_br_account/hooks.py
  l10n_br_account/models/__init__.py
  l10n_br_account/models/l10n_br_account_tax_template.py
  l10n_br_account/tests/test_account_taxes.py
  l10n_br_coa/README.rst
  l10n_br_coa/__init__.py
  l10n_br_coa/__manifest__.py
  l10n_br_coa/data/account_tax_group_data.xml
  l10n_br_coa/data/l10n_br_account_tax_template_data.xml
  l10n_br_coa/models/__init__.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/l10n_br_account_tax_template.py
  l10n_br_coa/readme/CONFIGURE.rst
  l10n_br_coa/readme/CONTRIBUTORS.rst
  l10n_br_coa/readme/DESCRIPTION.rst
  l10n_br_coa/readme/INSTALL.rst
  l10n_br_coa/readme/ROADMAP.rst
  l10n_br_coa/readme/USAGE.rst
  l10n_br_coa/security/l10n_br_account_tax_template.xml
  l10n_br_coa/static/description/icon.png
  l10n_br_coa/static/description/index.html
  l10n_br_coa/views/l10n_br_account_tax_template.xml
  l10n_br_coa_simple/__init__.py
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/data/account_tax_template_data.xml
  l10n_br_coa_simple/hooks.py
Labels: approved, bot is merging ⏳

#855 [12.0] Rename fiscal operation and fiscal operation line fields
  l10n_br_account/wizards/account_invoice_refund.py
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/i18n/l10n_br_fiscal.pot
  l10n_br_fiscal/i18n/pt_BR.po
  l10n_br_fiscal/migrations/12.0.2.0.0/pre-migration.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_dashboard.py
  l10n_br_fiscal/models/operation_document_type.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/tax_definition_operation_line.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/views/document_fiscal_mixin_view.xml
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/operation_line_view.xml
  l10n_br_fiscal/views/operation_view.xml
Labels: 12.0, approved, bot is merging ⏳

#856 [12.0][ADD] add openupgradelib in requirements.txt
  requirements.txt
Labels: approved, bot is merging ⏳

#874 [12.][FIX] Remove company from fiscal document dummy
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/views/document_view.xml
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#875 [12.0][ADD] fiscal document configuration settings
  l10n_br_fiscal/models/res_config_settings.py
  l10n_br_fiscal/views/res_config_settings_view.xml
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review

#873 [ADD] module category for l10n_br_fiscal permission groups
  l10n_br_fiscal/i18n/l10n_br_fiscal.pot
  l10n_br_fiscal/security/fiscal_security.xml
Labels: 12.0, approved, bot is merging ⏳, bug
