Repository OCA/l10n-brazil, pull requests merged in 2020-09, with the labels that each got.

#947 [12.][FIX] fiscal closing temp directory
  l10n_br_fiscal/models/closing.py
Labels: 12.0, approved, bot is merging ⏳, bug

#941 [12.0] l10n_br_nfse
  l10n_br_fiscal/demo/fiscal_document_nfse_demo.xml
  l10n_br_fiscal/demo/product_demo.xml
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/document_eletronic.py
  l10n_br_fiscal/models/product_template.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_fiscal_document_nfse.py
  l10n_br_fiscal/views/product_template_view.xml
  l10n_br_nfse/README.rst
  l10n_br_nfse/__init__.py
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/constants/nfse.py
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/demo/product_demo.xml
  l10n_br_nfse/models/__init__.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/product_template.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/readme/CONFIGURE.rst
  l10n_br_nfse/readme/CONTRIBUTORS.rst
  l10n_br_nfse/readme/DESCRIPTION.rst
  l10n_br_nfse/readme/INSTALL.rst
  l10n_br_nfse/readme/ROADMAP.rst
  l10n_br_nfse/readme/USAGE.rst
  l10n_br_nfse/report/danfse.xml
  l10n_br_nfse/security/ir.model.access.csv
  l10n_br_nfse/static/description/icon.png
  l10n_br_nfse/static/description/index.html
  l10n_br_nfse/static/src/img/itajuba.png
  l10n_br_nfse/tests/__init__.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/document_view.xml
  l10n_br_nfse/views/product_template_view.xml
  l10n_br_nfse/views/res_company_view.xml
  l10n_br_nfse/wizards/__init__.py
  l10n_br_nfse/wizards/wizard_document_status.py
  l10n_br_nfse/wizards/wizard_document_status.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#948 [12.0][REF] Export fiscal documents
  l10n_br_fiscal/models/closing.py
Labels: 12.0, approved, bot is merging ⏳, needs fixing, needs review

#952 [12.0] CNAE improvements
  l10n_br_fiscal/demo/product_demo.xml
  l10n_br_nfse/models/document_line.py
Labels: approved, bot is merging ⏳

#954 Fix/portal tests
  l10n_br_portal/static/src/js/l10n_br_portal_tour.js
  l10n_br_portal/tests/test_load_process.py
Labels: approved, bot is merging ⏳

#957 [REF] Rename Fiscal Operation Type Label
  l10n_br_fiscal/i18n/l10n_br_fiscal.pot
  l10n_br_fiscal/i18n/pt_BR.po
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/views/operation_view.xml
Labels: approved, bot is merging ⏳

#953 12.0 l10n br fiscal demo fix2
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/demo/fiscal_operation_demo.xml
  l10n_br_fiscal/demo/product_demo.xml
  l10n_br_fiscal/demo/subsequent_operation_demo.xml
  l10n_br_fiscal/models/document_event.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/subsequent_document.py
  l10n_br_fiscal/models/subsequent_operation.py
  l10n_br_fiscal/tests/test_fiscal_document_nfse.py
  l10n_br_fiscal/views/operation_line_view.xml
  l10n_br_fiscal/wizards/wizard_document_cancel.py
  l10n_br_fiscal/wizards/wizard_document_correction.py
  l10n_br_fiscal/wizards/wizard_document_invalidate.py
Labels: approved, bot is merging ⏳

#946 [12.0] Simplificação do módulo l10n_br_coa
  l10n_br_account/__manifest__.py
  l10n_br_account/data/account_tax_group.xml
  l10n_br_account/data/account_tax_template.xml
  l10n_br_account/models/__init__.py
  l10n_br_account/models/fiscal_tax_group.py
  l10n_br_account/models/l10n_br_account_tax_template.py
  l10n_br_account/views/fiscal_tax_group_view.xml
  l10n_br_coa/__manifest__.py
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/data/l10n_br_coa_template.xml
  l10n_br_coa/models/__init__.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax_group.py
  l10n_br_coa/models/l10n_br_account_tax_template.py
  l10n_br_coa/readme/CONTRIBUTORS.rst
  l10n_br_coa/security/l10n_br_account_tax_template.xml
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa/views/account_tax_template.xml
  l10n_br_coa/views/l10n_br_account_tax_template.xml
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_generic/data/account_fiscal_position_template.xml
  l10n_br_coa_generic/data/account_group.xml
  l10n_br_coa_generic/data/account_tax_group.xml
  l10n_br_coa_generic/data/l10n_br_coa_generic_template.xml
  l10n_br_coa_generic/data/l10n_br_coa_generic_template_post.xml
  l10n_br_coa_generic/hooks.py
  l10n_br_coa_generic/readme/CONTRIBUTORS.rst
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/data/account_group.xml
  l10n_br_coa_simple/data/account_tax_group.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template_post.xml
  l10n_br_coa_simple/hooks.py
Labels: 12.0, approved, bot is merging ⏳, ready to merge

#959 Feature/new users
  l10n_br_account/__manifest__.py
  l10n_br_account/demo/res_users_demo.xml
  l10n_br_base/__manifest__.py
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_base/demo/res_users_demo.xml
  l10n_br_fiscal/demo/res_users_demo.xml
  l10n_br_fiscal/hooks.py
  l10n_br_stock/__manifest__.py
  l10n_br_stock/demo/res_users_demo.xml
Labels: approved, bot is merging ⏳

#962 Close #961
  l10n_br_base/demo/res_users_demo.xml
Labels: approved, bot is merging ⏳

#963 [12.0] Add demo data to l10n_br_stock
  l10n_br_stock/__init__.py
  l10n_br_stock/__manifest__.py
  l10n_br_stock/demo/stock_inventory_demo.xml
  l10n_br_stock/demo/stock_location_demo.xml
  l10n_br_stock/hooks.py
  l10n_br_stock/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳, needs review, new feature

#966 [12.0] l10n_br_fiscal: fiscal documents
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/demo/fiscal_document_demo.xml
Labels: approved, bot is merging ⏳

#960 [12.0][FIX] fiscal document return
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
Labels: 12.0, approved, bot is merging ⏳, bug, needs review, ready to merge

#958 [12.0] l10n_br_nfse: fix cnae mask
  l10n_br_fiscal/demo/product_demo.xml
  l10n_br_fiscal/models/city_taxation_code.py
  l10n_br_fiscal/models/product_template.py
  l10n_br_fiscal/views/city_taxation_code.xml
  l10n_br_fiscal/views/product_template_view.xml
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/product_template_view.xml
Labels: approved, bot is merging ⏳

#928 Feature/dfe mdfe
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/constants/mdfe.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/attachment.py
  l10n_br_fiscal/models/dfe/__init__.py
  l10n_br_fiscal/models/dfe/dfe.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_eletronic.py
  l10n_br_fiscal/models/mdfe/__init__.py
  l10n_br_fiscal/models/mdfe/mdfe.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/views/dfe/dfe_views.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal/views/mdfe/mdfe_views.xml
  l10n_br_fiscal/wizards/__init__.py
Labels: approved, bot is merging ⏳
