Repository OCA/l10n-brazil, pull requests merged in 2020-10, with the labels that each got.

#975 [12.0] Add Document type prefix and sufix and update data
  l10n_br_fiscal/data/l10n_br_fiscal.document.type.csv
  l10n_br_fiscal/models/document_type.py
  l10n_br_fiscal/views/document_type_view.xml
Labels: 12.0, approved, bot is merging ⏳

#903 [12.0][IMP] Padronização README e INDEX l10n_br_account_payment_order
  l10n_br_account_payment_order/README.rst
  l10n_br_account_payment_order/readme/CONFIGURE.rst
  l10n_br_account_payment_order/readme/CREDITS.rst
  l10n_br_account_payment_order/static/description/index.html
Labels: approved, merged 🎉, ready to merge

#907 [12.0][IMP] Padronização README e INDEX l10n_br_portal
  l10n_br_portal/README.rst
  l10n_br_portal/readme/CONFIGURE.rst
  l10n_br_portal/readme/CREDITS.rst
  l10n_br_portal/readme/DESCRIPTION.rst
  l10n_br_portal/readme/HISTORY.rst
  l10n_br_portal/readme/INSTALL.rst
  l10n_br_portal/readme/ROADMAP.rst
  l10n_br_portal/readme/USAGE.rst
  l10n_br_portal/static/description/index.html
Labels: approved, bot is merging ⏳, ready to merge

#908 [12.0] Padronização README e INDEX l10n_br_hr_contract
  l10n_br_hr_contract/README.rst
  l10n_br_hr_contract/readme/CONFIGURE.rst
  l10n_br_hr_contract/readme/CONTRIBUTORS.rst
  l10n_br_hr_contract/readme/DESCRIPTION.rst
  l10n_br_hr_contract/readme/HISTORY.rst
  l10n_br_hr_contract/readme/INSTALL.rst
  l10n_br_hr_contract/readme/ROADMAP.rst
  l10n_br_hr_contract/readme/USAGE.rst
  l10n_br_hr_contract/static/description/index.html
Labels: approved, merged 🎉, ready to merge

#905 [12.0][IMP] Padronização README e INDEX l10n_br_fiscal
  l10n_br_fiscal/README.rst
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/readme/CONFIGURE.rst
  l10n_br_fiscal/readme/CONTRIBUTORS.rst
  l10n_br_fiscal/readme/DESCRIPTION.rst
  l10n_br_fiscal/readme/HISTORY.rst
  l10n_br_fiscal/readme/INSTALL.rst
  l10n_br_fiscal/readme/ROADMAP.rst
  l10n_br_fiscal/readme/USAGE.rst
  l10n_br_fiscal/static/description/index.html
Labels: approved, merged 🎉

#984 [12.0][FIX] Edoc Cancelada Workflow
  l10n_br_fiscal/models/document_cancel.py
Labels: approved, bot is merging ⏳

#956 12.0 mig l10n br stock account
  l10n_br_stock_account/README.rst
  l10n_br_stock_account/__init__.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_stock_account/data/l10n_br_stock_account_data.xml
  l10n_br_stock_account/demo/company_demo.xml
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/i18n/l10n_br_stock_account.pot
  l10n_br_stock_account/i18n/pt_BR.po
  l10n_br_stock_account/models/__init__.py
  l10n_br_stock_account/models/fiscal_operation.py
  l10n_br_stock_account/models/procurement_group.py
  l10n_br_stock_account/models/res_company.py
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/models/stock_picking_type.py
  l10n_br_stock_account/models/stock_rule.py
  l10n_br_stock_account/readme/CONFIGURE.rst
  l10n_br_stock_account/readme/CONTRIBUTORS.rst
  l10n_br_stock_account/readme/CREDITS.rst
  l10n_br_stock_account/readme/DESCRIPTION.rst
  l10n_br_stock_account/readme/HISTORY.rst
  l10n_br_stock_account/readme/INSTALL.rst
  l10n_br_stock_account/readme/ROADMAP.rst
  l10n_br_stock_account/readme/USAGE.rst
  l10n_br_stock_account/security/ir.model.access.csv
  l10n_br_stock_account/static/description/icon.png
  l10n_br_stock_account/tests/__init__.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/tests/test_stock_rule.py
  l10n_br_stock_account/views/fiscal_operation_view.xml
  l10n_br_stock_account/views/res_company_view.xml
  l10n_br_stock_account/views/stock_account_view.xml
  l10n_br_stock_account/views/stock_picking.xml
  l10n_br_stock_account/views/stock_picking_type_view.xml
  l10n_br_stock_account/views/stock_rule_view.xml
  l10n_br_stock_account/wizards/__init__.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping_view.xml
  l10n_br_stock_account/wizards/stock_return_picking.py
  l10n_br_stock_account/wizards/stock_return_picking_view.xml
  oca_dependencies.txt
  requirements.txt
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1000 [12.0] Adapt Multi company sale orders
  l10n_br_sale/__init__.py
  l10n_br_sale/__manifest__.py
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/hooks.py
Labels: approved, bot is merging ⏳

#1001 [12.0][FIX] Demo User Partner
  l10n_br_base/demo/res_users_demo.xml
Labels: approved, bot is merging ⏳

#986 [12.0][FIX] CST
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
Labels: approved, bot is merging ⏳

#964 [12.0][ADD] l10n_br_website_sale
  l10n_br_website_sale/README.rst
  l10n_br_website_sale/__init__.py
  l10n_br_website_sale/__manifest__.py
  l10n_br_website_sale/controllers/__init__.py
  l10n_br_website_sale/controllers/main.py
  l10n_br_website_sale/readme/CONFIGURE.rst
  l10n_br_website_sale/readme/CONTRIBUTORS.rst
  l10n_br_website_sale/readme/CREDITS.rst
  l10n_br_website_sale/readme/DESCRIPTION.rst
  l10n_br_website_sale/readme/HISTORY.rst
  l10n_br_website_sale/readme/INSTALL.rst
  l10n_br_website_sale/readme/ROADMAP.rst
  l10n_br_website_sale/readme/USAGE.rst
  l10n_br_website_sale/static/description/icon.png
  l10n_br_website_sale/static/description/index.html
  l10n_br_website_sale/static/src/js/l10n_br_address.js
  l10n_br_website_sale/static/src/js/l10n_br_website_sale_tour.js
  l10n_br_website_sale/templates/portal_templates.xml
  l10n_br_website_sale/tests/__init__.py
  l10n_br_website_sale/tests/test_sale_process.py
  l10n_br_website_sale/views/assets.xml
Labels: approved, bot is merging ⏳, needs review, new feature

#1005 [FIX] manifest website key
  l10n_br_website_sale/__manifest__.py
Labels: bot is merging ⏳, needs review

#1006 [12.0] [IMP] Validation of Before change state
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳

#982 Feature/fiscal tax adjustments fix
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/operation_view.xml
Labels: 12.0, approved, bot is merging ⏳, ready to merge

#1008 [12.0] Missing fields on nfse serialize dicts
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/res_partner.py
Labels: approved, bot is merging ⏳

#1007 [12.0] [IMP] Document Cancel workflow
  l10n_br_fiscal/models/document_cancel.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/wizards/wizard_document_cancel.py
Labels: 12.0, approved, bot is merging ⏳, bug

#943 [NEW] payment_cielo
  payment_cielo/README.rst
  payment_cielo/__init__.py
  payment_cielo/__manifest__.py
  payment_cielo/controllers/__init__.py
  payment_cielo/controllers/main.py
  payment_cielo/data/payment_acquirer_data.xml
  payment_cielo/models/__init__.py
  payment_cielo/models/payment_acquirer.py
  payment_cielo/models/payment_token.py
  payment_cielo/models/payment_transaction.py
  payment_cielo/readme/CONFIGURE.rst
  payment_cielo/readme/CONTRIBUTORS.rst
  payment_cielo/readme/CREDITS.rst
  payment_cielo/readme/DESCRIPTION.rst
  payment_cielo/readme/HISTORY.rst
  payment_cielo/readme/INSTALL.rst
  payment_cielo/readme/ROADMAP.rst
  payment_cielo/readme/USAGE.rst
  payment_cielo/static/description/icon.png
  payment_cielo/static/description/index.html
  payment_cielo/static/src/img/cielo_icon.png
  payment_cielo/static/src/xml/cielo_templates.xml
  payment_cielo/tests/__init__.py
  payment_cielo/tests/test_cielo.py
  payment_cielo/views/payment_cielo_templates.xml
  payment_cielo/views/payment_views.xml
Labels: 12.0, approved, bot is merging ⏳, help wanted, new feature, work in progress
