Repository OCA/l10n-brazil, pull requests merged in 2020-04, with the labels that each got.

#812 [FIX] remove field tax_withholding from tax.definition
  l10n_br_fiscal/models/res_company.py
Labels: approved, bot is merging ⏳

#809 [12.0] Funcionalidades adaptadas realizadas no fiscal no pr da nf-e
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_abstract.py
  l10n_br_fiscal/tests/test_fiscal_closing.py
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#814 [ADD] Partner Order and Partner Order Line in Fiscal Document Line Mixin
  l10n_br_account/models/account_tax.py
  l10n_br_account/models/fiscal_tax.py
  l10n_br_fiscal/constants/edoc.py
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_invalidate_number.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_line_abstract.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_line_view.xml
Labels: 12.0, bot is merging ⏳

#818 Fix Document button actions
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳

#819 [IMP] Add short CSV files to load NCM, NBM, NBS and CEST code lists.
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
  l10n_br_fiscal/data/l10n_br_fiscal_tax_icms_data.xml
  l10n_br_fiscal/demo/l10n_br_fiscal.cest-demo.csv
  l10n_br_fiscal/demo/l10n_br_fiscal.nbm-demo.csv
  l10n_br_fiscal/demo/l10n_br_fiscal.nbs-demo.csv
  l10n_br_fiscal/demo/l10n_br_fiscal.ncm-demo.csv
  l10n_br_fiscal/hooks.py
Labels: 12.0, approved, bot is merging ⏳, enhancement

#817 [FIX] Error in saving company
  l10n_br_fiscal/models/res_company.py
Labels: 12.0, approved, bot is merging ⏳, bug, good first issue

#823 [FIX] Remove tour user data
  l10n_br_fiscal/models/closing.py
  l10n_br_portal/static/src/js/l10n_br_portal_tour.js
  l10n_br_portal/tests/test_load_process.py
Labels: approved, bot is merging ⏳
