Repository OCA/l10n-brazil, pull requests merged in 2021-02, with the labels that each got.

#1112 12.0 sale ref order line view
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#1091 [12.0][IMP] l10n br fiscal: move city_taxation_code_id (fields, methods and views) from l10n_br_nfse to l10n_br_fiscal
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/product_template.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_fiscal/views/product_product_view.xml
  l10n_br_fiscal/views/product_template_view.xml
Labels: approved, bot is merging ⏳

#1092 [12.0][IMP] l10n_br_sale: add city_taxation_code_id sale_order_line form
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#1093 [12.0][REM] l10n_br_nfse: remove city taxation code from model and views
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/product_template.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/product_product_view.xml
  l10n_br_nfse/views/product_template_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1071 [12.0][ADD] 10n_br_coa_complete: proposta de novo plano contas ou substituição do genérico
  l10n_br_coa_complete/README.rst
  l10n_br_coa_complete/__init__.py
  l10n_br_coa_complete/__manifest__.py
  l10n_br_coa_complete/data/account.account.template.csv
  l10n_br_coa_complete/data/account_fiscal_position_template.xml
  l10n_br_coa_complete/data/account_group.xml
  l10n_br_coa_complete/data/account_tax_group.xml
  l10n_br_coa_complete/data/l10n_br_coa_complete_template.xml
  l10n_br_coa_complete/data/l10n_br_coa_complete_template_post.xml
  l10n_br_coa_complete/hooks.py
  l10n_br_coa_complete/readme/CONFIGURE.rst
  l10n_br_coa_complete/readme/CONTRIBUTORS.rst
  l10n_br_coa_complete/readme/DESCRIPTION.rst
  l10n_br_coa_complete/readme/INSTALL.rst
  l10n_br_coa_complete/readme/ROADMAP.rst
  l10n_br_coa_complete/readme/USAGE.rst
  l10n_br_coa_complete/static/description/banner.png
  l10n_br_coa_complete/static/description/icon.png
  l10n_br_coa_complete/static/description/index.html
  l10n_br_coa_complete/tests/__init__.py
  l10n_br_coa_complete/tests/test_l10n_br_coa_complete.py
Labels: approved, bot is merging ⏳, ready to merge

#1116 [FIX] purchase config view
  l10n_br_purchase_stock/views/res_config_settings.xml
Labels: 12.0, approved, bot is merging ⏳, bug

#1113 [12.0][REF] Update res.partner Akretion demo data.
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/tests/test_base_onchange.py
Labels: approved, bot is merging ⏳

#925 [12.0][ADD] l10n_br_repair : Add Brazilian Localization Repair
  l10n_br_repair/README.rst
  l10n_br_repair/__init__.py
  l10n_br_repair/__manifest__.py
  l10n_br_repair/data/res_company.xml
  l10n_br_repair/demo/repair_order.xml
  l10n_br_repair/demo/res_company.xml
  l10n_br_repair/i18n/l10n_br_repair.pot
  l10n_br_repair/i18n/pt_BR.po
  l10n_br_repair/models/__init__.py
  l10n_br_repair/models/fiscal_line_mixin.py
  l10n_br_repair/models/repair_fee.py
  l10n_br_repair/models/repair_line.py
  l10n_br_repair/models/repair_order.py
  l10n_br_repair/models/res_company.py
  l10n_br_repair/models/res_config_settings.py
  l10n_br_repair/readme/CONFIGURE.rst
  l10n_br_repair/readme/CONTRIBUTORS.rst
  l10n_br_repair/readme/CREDITS.rst
  l10n_br_repair/readme/DESCRIPTION.rst
  l10n_br_repair/readme/HISTORY.rst
  l10n_br_repair/readme/INSTALL.rst
  l10n_br_repair/readme/ROADMAP.rst
  l10n_br_repair/readme/USAGE.rst
  l10n_br_repair/security/l10n_br_repair_security.xml
  l10n_br_repair/static/description/banner.png
  l10n_br_repair/static/description/icon.png
  l10n_br_repair/static/description/index.html
  l10n_br_repair/tests/__init__.py
  l10n_br_repair/tests/test_l10n_br_repair.py
  l10n_br_repair/tests/test_l10n_br_repair_lc.py
  l10n_br_repair/tests/test_l10n_br_repair_sn.py
  l10n_br_repair/views/repair_fee.xml
  l10n_br_repair/views/repair_line.xml
  l10n_br_repair/views/repair_order.xml
  l10n_br_repair/views/res_company.xml
Labels: 12.0, approved, bot is merging ⏳, needs review, new feature, ready to merge

#1121 [UPG] erpbrasil.edoc.pdf: 0.1.1 -> 0.2.0
  requirements.txt
Labels: approved, bot is merging ⏳, needs review

#1122 [12.0][FIX] Library vcrpy used in tests by payment_cielo module was missing.
  requirements.txt
Labels: approved, bot is merging ⏳

#1120 [FIX] sub view context
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#1124 [FIX] Remover todos os campos obrigatórios do Fiscal Line Mixin
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1119 [12.0][FIX] View error
  l10n_br_repair/views/repair_fee.xml
  l10n_br_repair/views/repair_line.xml
Labels: approved, bot is merging ⏳

#1138 [FIX] _simulate_invoice_line_onchange method
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1128 [12.0][FIX] l10n_br_nfse_issnet: fix test
  l10n_br_nfse_issnet/tests/test_fiscal_document_nfse_issnet.py
Labels: approved, bot is merging ⏳

#1129 [12.0][FIX] l10n_br_nfse_ginfes: fix test
  l10n_br_nfse_ginfes/tests/test_fiscal_document_nfse_ginfes.py
Labels: approved, bot is merging ⏳

#1130 [NEW] Consumidor anonimo
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/res_partner_data.xml
Labels: approved, bot is merging ⏳

#1140 [FIX] Correção da consulta dos impostos estimados no IBPT via API
  l10n_br_fiscal/models/data_ncm_nbs_abstract.py
Labels: 12.0, approved, bot is merging ⏳, needs review

#1133 [FIX] Do not replace document type if it's defined
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳

#1127 [12.0][FIX] flake8
  spec_driven_model/models/spec_models.py
  spec_driven_model/models/spec_view.py
Labels: approved, bot is merging ⏳

#1134 [FIX] Fiscal State on tree
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1136 [ADD] Auto fill city
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#1114 [12.0][[REF] l10n_br_stock_account
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/models/__init__.py
  l10n_br_stock_account/models/fiscal_operation.py
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/models/stock_rule.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/views/fiscal_operation_view.xml
  l10n_br_stock_account/views/stock_account_view.xml
  l10n_br_stock_account/views/stock_picking.xml
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1131 [FIX] Constantes fiscais
  l10n_br_fiscal/constants/fiscal.py
Labels: approved, bot is merging ⏳

#1075 [REF] Replaced Tax field and included Total Amounts used in Sale Report
  l10n_br_sale/__manifest__.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/report/sale_report_templates.xml
Labels: approved, bot is merging ⏳, ready to merge

#1144 [FIX] wrong ensure_one call
  l10n_br_fiscal/models/document_event.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1143 [12.0] Data Abstract _search_name e filter_domain
  l10n_br_fiscal/models/data_abstract.py
  l10n_br_fiscal/models/document_type.py
Labels: 12.0, approved, bot is merging ⏳, needs review

#1117 [12.0][FIX] Some necessary fixes in l10n_br_contract
  l10n_br_contract/__manifest__.py
  l10n_br_contract/data/company.xml
  l10n_br_contract/demo/company.xml
  l10n_br_contract/models/contract_contract.py
  l10n_br_contract/models/res_company.py
  l10n_br_contract/views/res_company.xml
Labels: approved, bot is merging ⏳, ready to merge

#1145 [ADD] added field financial_move_line_ids on invoice object
  l10n_br_account/models/account_invoice.py
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳
