Repository OCA/l10n-brazil, pull requests merged in 2021-05, with the labels that each got.

#1320 [12.0][FIX] Field related should inform comodel_name to avoid errors.
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#1233 [12.0][ADD] Discount fixed
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/security/l10n_br_sale_security.xml
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/views/sale_view.xml
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1296 [FIX] Close #1249
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳, ready to merge

#1321 [ADD] Export tag fat
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#1329 [12.0][FIX] l10n_br_account: fix financial_move_line_ids compute method
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1328 [12.0][FIX] NF-E Export DIFAL fields to XML
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#1299 [12.0][FIX] Reports not finding field fiscal_operation_line_id
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_sale/models/sale_order_line.py
Labels: approved, bot is merging ⏳, ready to merge

#1323 [FIX] Get only active account tax
  l10n_br_account/models/fiscal_tax.py
Labels: approved, bot is merging ⏳

#1324 [12.0] l10n_br_coa_generic - Atualizaçao do Plano de Contas Genérico
  l10n_br_coa/data/account_type_data.xml
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/account_group.xml
  l10n_br_coa_generic/data/account_tax_group.xml
  l10n_br_coa_generic/data/l10n_br_coa_generic_template_post.xml
  l10n_br_coa_generic/readme/CONTRIBUTORS.rst
  l10n_br_coa_generic/readme/DESCRIPTION.rst
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review

#1333 [NEW] Context to easy disable cnpj and ie validation on data import
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳

#1341 [ADD] Campo de Imposto dedutível no Account Tax e Template
  l10n_br_coa/__manifest__.py
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa/views/account_tax_template.xml
Labels: approved, bot is merging ⏳

#1342 [FIX] DRE deduções da receita
  l10n_br_mis_report/data/mis_report_dre.xml
Labels: approved, bot is merging ⏳, needs review

#1343 [FIX] Compensation Account Type
  l10n_br_coa_generic/data/account.account.template.csv
Labels: approved, bot is merging ⏳, needs review

#1332 [FIX] Parceiros com CPF duplicado
  l10n_br_base/models/res_partner.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1344 [ADD] Disable allow cnpj multi ie via context for importing data
  l10n_br_base/models/res_config_settings.py
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳

#1314 [12.0][IMP] Abroad recipient
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/views/nfe_document_view.xml
Labels: approved, merged 🎉

#1305 [12.0] [IMP] Attributes for the Simples Nacional
  l10n_br_fiscal/constants/icms.py
  l10n_br_fiscal/data/l10n_br_fiscal.tax.group.csv
  l10n_br_fiscal/data/simplified_tax_data.xml
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, bot is merging ⏳

#1346 [FIX] nfe40_NFref comodel_name attribute
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#1306 [12.0][ADD] Invoice reference to context
  l10n_br_account/__manifest__.py
  l10n_br_account/models/__init__.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_account/views/document_line_view.xml
  l10n_br_account/views/document_view.xml
Labels: approved, bot is merging ⏳, ready to merge

#1336 [12.0][FIX] l10n_br_contract: permite a criação de contratos sem documento fiscal
  l10n_br_contract/models/contract_contract.py
  l10n_br_contract/views/contract_line.xml
  l10n_br_contract/views/contract_view.xml
Labels: approved, bot is merging ⏳

#1347 [12.0][FIX] Compute para nfe40.idDest
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#1312 [12.0][IMP] Automation of IPI GuideLine
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: approved, bot is merging ⏳

#1348 [12.0] Fix/invoice fiscal dashboard
  l10n_br_account/models/fiscal_operation.py
  l10n_br_fiscal/models/operation_dashboard.py
Labels: approved, bot is merging ⏳

#1352 [12.0] avoids failure when migrating from v10
  l10n_br_fiscal/migrations/12.0.3.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#1350 [12.0] rename tables only if they exist
  l10n_br_fiscal/migrations/12.0.12.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#1351 [12.0] fix l10n_br_fiscal/migrations/12.0.2.0.0 (bad dict)
  l10n_br_fiscal/migrations/12.0.2.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#1353 [12.0][l10n_br_fiscal][OpenUpgrade] fix migration from v10
  l10n_br_fiscal/migrations/12.0.1.0/post-migration.py
  l10n_br_fiscal/migrations/12.0.1.0/pre-migration.py
Labels: approved, bot is merging ⏳

#1356 num2words is not an external dependency anymore
  l10n_br_base/__manifest__.py
  l10n_br_base/readme/INSTALL.rst
Labels: bot is merging ⏳

#1357 fix bad settings field labels
  l10n_br_base/views/res_config_settings_view.xml
Labels: bot is merging ⏳

#1358 fix wrong ondelete cascade
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_company.py
  l10n_br_base/models/state_tax_numbers.py
Labels: bot is merging ⏳

#1360 12.0 l10n br base test lint
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_valid_createid.py
Labels: bot is merging ⏳

#1361 [12.0] l10n_br_zip: lint: except: -> except Exception:
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
Labels: approved, bot is merging ⏳

#1365 [FIX] _compute_nfe40_xEnder in res.partner
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳

#1368 [12.0] l10n_br_base: flake8 B902 'cls' used for instance method
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_valid_createid.py
Labels: approved, bot is merging ⏳

#1362 [12.0] Inscrição Estadual Isento e RG em campo separado
  l10n_br_base/__manifest__.py
  l10n_br_base/migrations/12.0.3.0.0/pre-migration.py
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/views/res_partner_view.xml
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1369 12.0 l10n br fiscal lint
  l10n_br_fiscal/data/l10n_br_fiscal.product.genre.csv
  l10n_br_fiscal/models/attachment.py
  l10n_br_fiscal/models/dfe/dfe.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/models/mdfe/mdfe.py
  l10n_br_fiscal/models/subsequent_operation.py
  l10n_br_fiscal/tests/test_certificate.py
  l10n_br_fiscal/tests/test_fiscal_closing.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_ibpt_service.py
  l10n_br_fiscal/tests/test_workflow.py
  l10n_br_fiscal/views/invalidate_number_view.xml
Labels: approved, bot is merging ⏳

#1379 [FIX] remove date shadow field
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1359 [ADD] l10n_br_sale 12.0.1.0.0 script migration
  l10n_br_sale/migrations/12.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#1371 12.0 l10n br account lint
  l10n_br_account/data/account_fiscal_position.xml
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/tests/test_customer_invoice_dummy.py
Labels: approved, bot is merging ⏳

#1387 [12.0][FIX][BUG] In case of Grouping stock move Invoice lines was created with wrong quantity
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1385 [12.0] Pacote de Liberação nº 9 (Novo leiaute da NF-e, NT 2020.006 v.1.20). Válido de 05/04/2021 a 31/08/2021. Publicado em 25/03/2021
  l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
Labels: approved, bot is merging ⏳

#1373 [FIX] nfe40_cMun as related
  l10n_br_base/data/res.city.csv
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/res_city.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_portal/tests/test_load_process.py
  l10n_br_resource/wizards/workalendar_holiday_import_wizard.py
  l10n_br_website_sale/tests/test_sale_process.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1388 [12.0][FIX] Migration of the RG should be post because the field has to exist before
  l10n_br_base/migrations/12.0.3.0.0/post-migration.py
Labels: 12.0, approved, bot is merging ⏳

#1366 [12.0] l10n_br_fiscal do not use non stored field in domain
  l10n_br_fiscal/models/certificate.py
  l10n_br_fiscal/models/res_company.py
Labels: approved, bot is merging ⏳

#1389 [FIX] save m2m fiscal_tax_ids field
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#1390 [NEW] erpbrasil.edoc 2.1.0
  requirements.txt
Labels: approved, bot is merging ⏳, needs review

#1391 [12.0] more flexible xpath extension point issue #1199
  l10n_br_sale/report/sale_report_templates.xml
Labels: approved, bot is merging ⏳

#1397 [REF] l10n_br_base - lint convert tabs to spaces
  l10n_br_base/demo/res_users_demo.xml
Labels: bot is merging ⏳

#1392 [12.0] l10n_br_fiscal fixes de performance e qualidade do codigo
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/constants/icms.py
  l10n_br_fiscal/data/l10n_br_fiscal.tax.ipi.guideline.csv
  l10n_br_fiscal/models/comment.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_eletronic.py
  l10n_br_fiscal/models/document_event.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/models/subsequent_document.py
  l10n_br_fiscal/models/subsequent_operation.py
Labels: bot is merging ⏳

#1394 [REF] l10n_br_sale lint - group
  l10n_br_sale/security/l10n_br_sale_security.xml
Labels: bot is merging ⏳

#1398 [REF] l10n_br_sale_stock lint compute method name
  l10n_br_sale_stock/models/sale_order.py
Labels: approved, bot is merging ⏳

#1395 [REF] l10n_br_repair lint
  l10n_br_repair/demo/repair_order.xml
Labels: approved, bot is merging ⏳

#1403 [FIX] IE/RG UX
  l10n_br_base/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1399 [12.0] [l10n_br_base] remove useless default @api.multi
  l10n_br_base/models/res_company.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_bank.py
Labels: approved, bot is merging ⏳

#1400 [12.0] [l10n_br_fiscal] remove useless default @api.multi
  l10n_br_fiscal/models/attachment.py
  l10n_br_fiscal/models/certificate.py
  l10n_br_fiscal/models/cest.py
  l10n_br_fiscal/models/comment.py
  l10n_br_fiscal/models/data_abstract.py
  l10n_br_fiscal/models/data_ncm_nbs_abstract.py
  l10n_br_fiscal/models/data_product_abstract.py
  l10n_br_fiscal/models/dfe/dfe.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_email.py
  l10n_br_fiscal/models/document_event.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_related.py
  l10n_br_fiscal/models/document_serie.py
  l10n_br_fiscal/models/document_type.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/invalidate_number.py
  l10n_br_fiscal/models/mdfe/mdfe.py
  l10n_br_fiscal/models/nbm.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_dashboard.py
  l10n_br_fiscal/models/operation_document_type.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/partner_profile.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/subsequent_document.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/models/tax_definition_cfop.py
  l10n_br_fiscal/models/tax_definition_company.py
  l10n_br_fiscal/models/tax_definition_icms.py
  l10n_br_fiscal/models/tax_definition_operation_line.py
  l10n_br_fiscal/models/tax_definition_partner_profile.py
  l10n_br_fiscal/models/tax_pis_cofins.py
  l10n_br_fiscal/wizards/base_wizard_mixin.py
  l10n_br_fiscal/wizards/document_cancel_wizard.py
  l10n_br_fiscal/wizards/document_correction_wizard.py
  l10n_br_fiscal/wizards/document_status_wizard.py
  l10n_br_fiscal/wizards/invalidate_number_wizard.py
  l10n_br_fiscal/wizards/l10n_br_account_invoice_costs_ratio.py
Labels: approved, bot is merging ⏳

#1401 [12.0] [l10n_br_account] remove useless default @api.multi
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_tax.py
  l10n_br_account/models/account_tax_template.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_operation.py
  l10n_br_account/models/fiscal_tax.py
  l10n_br_account/models/fiscal_tax_group.py
  l10n_br_account/wizards/account_invoice_refund.py
Labels: approved, bot is merging ⏳

#1402 [12.0] [l10n_br_stock_account] remove useless default @api.multi
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
  l10n_br_stock_account/wizards/stock_return_picking.py
Labels: approved, bot is merging ⏳

#1404 [12.0] [l10n_br_sale][l10n_br_sale_stock] remove useless default @api.multi
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1405 [12.0] [l10n_br_purchase][l10n_br_purchase_stock] remove useless default @api.multi
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase_stock/models/purchase_order_line.py
  l10n_br_purchase_stock/models/stock_move.py
  l10n_br_purchase_stock/models/stock_rule.py
  l10n_br_purchase_stock/wizards/stock_invocing_onshipping.py
Labels: approved, bot is merging ⏳

#1407 [12.0][l10n_br_fiscal] pis_wh_cst_id and cofins_wh_cst_id do not exist
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳, bug

#1408 [12.0][all modules] test lint: assertEquals -> assertEqual
  l10n_br_account/tests/test_customer_invoice_dummy.py
  l10n_br_account/tests/test_supplier_invoice_dummy.py
  l10n_br_account_payment_order/tests/test_payment_order.py
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_coa_complete/tests/test_l10n_br_coa_complete.py
  l10n_br_coa_generic/tests/test_l10n_br_coa_generic.py
  l10n_br_coa_simple/tests/test_l10n_br_coa_simple.py
  l10n_br_fiscal/tests/test_certificate.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_fiscal_document_nfse.py
  l10n_br_fiscal/tests/test_ibpt_product.py
  l10n_br_fiscal/tests/test_ibpt_service.py
  l10n_br_fiscal/tests/test_subsequent_operation.py
  l10n_br_nfe/tests/test_account_customer_invoice.py
  l10n_br_nfe/tests/test_account_customer_nfe.py
  l10n_br_nfe/tests/test_account_supplier_nfe.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_repair/tests/test_l10n_br_repair.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
Labels: approved, bot is merging ⏳

#1410 [12.0][ADD] l10n_br_delivery script migration 12.0.1.0.0
  l10n_br_delivery/migrations/12.0.1.0.0/pre-migration.py
Labels: 12.0, approved, bot is merging ⏳

#926 [NEW] Nota Paulistana
  l10n_br_nfse/models/document.py
  l10n_br_nfse_paulistana/README.rst
  l10n_br_nfse_paulistana/__init__.py
  l10n_br_nfse_paulistana/__manifest__.py
  l10n_br_nfse_paulistana/constants/paulistana.py
  l10n_br_nfse_paulistana/models/__init__.py
  l10n_br_nfse_paulistana/models/document.py
  l10n_br_nfse_paulistana/models/res_company.py
  l10n_br_nfse_paulistana/readme/CONFIGURE.rst
  l10n_br_nfse_paulistana/readme/CONTRIBUTORS.rst
  l10n_br_nfse_paulistana/readme/DESCRIPTION.rst
  l10n_br_nfse_paulistana/readme/INSTALL.rst
  l10n_br_nfse_paulistana/readme/ROADMAP.rst
  l10n_br_nfse_paulistana/readme/USAGE.rst
  l10n_br_nfse_paulistana/static/description/icon.png
  l10n_br_nfse_paulistana/static/description/index.html
  l10n_br_nfse_paulistana/tests/__init__.py
  l10n_br_nfse_paulistana/tests/nfse/paulistana.xml
  l10n_br_nfse_paulistana/tests/test_fiscal_document_nfse_paulistana.py
  requirements.txt
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge

#1415 [12.0][l10n_br_fiscal] no 0.0 default for Floats and Monetary, no required for Floats
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/product_template.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/simplified_tax_range.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/models/tax_estimate.py
Labels: approved, bot is merging ⏳

#1417 [12.0][IMP] Included CFOP in Sale Report.
  l10n_br_sale/report/sale_report.py
  l10n_br_sale/report/sale_report_view.xml
Labels: approved, bot is merging ⏳

#1419 [12.0] Corrige e padroniza o website https://github.com/OCA/l10n-brazil/ em todos os módulos
  l10n_br_account/__manifest__.py
  l10n_br_account_bank_statement_import_cnab/__manifest__.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_coa/__manifest__.py
  l10n_br_coa_complete/__manifest__.py
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_simple/__manifest__.py
  l10n_br_contract/__manifest__.py
  l10n_br_crm/__manifest__.py
  l10n_br_delivery/__manifest__.py
  l10n_br_fiscal/__manifest__.py
  l10n_br_hr/__manifest__.py
  l10n_br_hr_contract/__manifest__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_portal/__manifest__.py
  l10n_br_purchase/__manifest__.py
  l10n_br_purchase_stock/__manifest__.py
  l10n_br_sale/__manifest__.py
  l10n_br_sale_stock/__manifest__.py
  l10n_br_stock/__manifest__.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_website_sale_delivery/__manifest__.py
  l10n_br_zip/__manifest__.py
  payment_cielo/__manifest__.py
Labels: bot is merging ⏳
