Repository OCA/l10n-brazil, pull requests merged in 2021-01, with the labels that each got.

#1064 [FIX] payment_cielo tests
  payment_cielo/tests/fixtures/test_10_cielo_s2s.yaml
  payment_cielo/tests/test_cielo.py
Labels: approved, bot is merging ⏳

#1061 [12.0] product fiscal fields should be fiscal user editable
  l10n_br_fiscal/views/product_template_view.xml
Labels: approved, bot is merging ⏳

#1069 [FIX] get_address_from_cep call to use Correios WS
  l10n_br_zip/README.rst
  l10n_br_zip/__manifest__.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/models/res_config_settings.py
  l10n_br_zip/readme/CONFIGURE.rst
  l10n_br_zip/readme/DESCRIPTION.rst
  l10n_br_zip/readme/HISTORY.rst
  l10n_br_zip/static/description/index.html
  l10n_br_zip/static/description/l10n_br_zip_1.png
  l10n_br_zip/views/res_config_settings_view.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#1070 [12.0][FIX] Update version of erpbrasil.edoc.pdf
  requirements.txt
Labels: approved, bot is merging ⏳

#1068 Bump lxml from 4.2.3 to 4.6.2
  requirements.txt
Labels: approved, bot is merging ⏳

#1062 [REF] document_type_id move required attribute from object to view
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/views/document_view.xml
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1065 [12.0][IMP] l10n_br_nfse: arredondamento, impostos retidos e ajuste de leiaute danfse
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#1063 [12.0] Opção de remover o valor do ICMS da base de calculo do PIS/COFINS
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal.tax.group.csv
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/models/tax_group.py
  l10n_br_fiscal/views/tax_group_view.xml
  l10n_br_fiscal/views/tax_view.xml
Labels: 12.0, approved, bot is merging ⏳, needs review

#1074 [12.0] l10n br sale line view
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#930 [12.0] [ADD] l10n_br_nfse_issnet
  l10n_br_nfse_issnet/README.rst
  l10n_br_nfse_issnet/__init__.py
  l10n_br_nfse_issnet/__manifest__.py
  l10n_br_nfse_issnet/constants/issnet.py
  l10n_br_nfse_issnet/demo/city_taxation_code_demo.xml
  l10n_br_nfse_issnet/i18n/l10n_br_nfse_issnet.pot
  l10n_br_nfse_issnet/models/__init__.py
  l10n_br_nfse_issnet/models/l10n_br_fiscal_document.py
  l10n_br_nfse_issnet/models/res_company.py
  l10n_br_nfse_issnet/readme/CONFIGURE.rst
  l10n_br_nfse_issnet/readme/CONTRIBUTORS.rst
  l10n_br_nfse_issnet/readme/CREDITS.rst
  l10n_br_nfse_issnet/readme/DESCRIPTION.rst
  l10n_br_nfse_issnet/readme/HISTORY.rst
  l10n_br_nfse_issnet/readme/INSTALL.rst
  l10n_br_nfse_issnet/readme/ROADMAP.rst
  l10n_br_nfse_issnet/readme/USAGE.rst
  l10n_br_nfse_issnet/static/description/banner.png
  l10n_br_nfse_issnet/static/description/icon.png
  l10n_br_nfse_issnet/static/description/index.html
  l10n_br_nfse_issnet/tests/__init__.py
  l10n_br_nfse_issnet/tests/nfse/001_50_nfse.xml
  l10n_br_nfse_issnet/tests/test_fiscal_document_nfse_issnet.py
  requirements.txt
Labels: bot is merging ⏳

#1067 [12.0][FIX] Invoice refund names
  l10n_br_account/wizards/account_invoice_refund.py
Labels: approved, bot is merging ⏳

#1076 [FIX] compute_all arguments
  l10n_br_account/models/account_tax.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1078 [12.0][FIX] l10n_br_fiscal: fix the NAME attribute of the FINANCE and OTHERS tag page
  l10n_br_fiscal/views/document_view.xml
Labels: 12.0, approved, bot is merging ⏳

#1077 [12.0] Update NCM data
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
Labels: 12.0, approved, bot is merging ⏳, needs review

#1082 [12.0][FIX] update erpbrasil.edoc version
  requirements.txt
Labels: approved, bot is merging ⏳

#1081 [12.0][FIX] l10n_br_contract: fix demo data on manifest
  l10n_br_contract/__manifest__.py
Labels: approved, bot is merging ⏳

#1083 [12.0][FIX] l10n_br_nfse: change amount_inss_ret_value to amount_inss_wh_value
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#1079 [12.0][FIX] stock picking return wizard
  l10n_br_stock_account/wizards/stock_return_picking.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1086 [12.0][FIX] fix install section part of readme
  l10n_br_nfse_issnet/readme/INSTALL.rst
Labels: approved, bot is merging ⏳

#1080 [12.0][IMP] l10n_br_fiscal: add delivery page tag on document fiscal form
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#1088 [FIX] l10n_br_base demo dados de demo
  l10n_br_base/demo/res_users_demo.xml
Labels: 12.0, approved, bot is merging ⏳, bug

#1090 [FIX] IPI base compute
  l10n_br_fiscal/models/tax.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1096 [12.0] Foreign Partner Address
  l10n_br_base/__init__.py
  l10n_br_base/__manifest__.py
  l10n_br_base/hooks.py
  l10n_br_base/views/res_partner_address_view.xml
  l10n_br_zip/views/res_partner_address_view.xml
Labels: 12.0, approved, bot is merging ⏳

#1098 [12.0][FIX] Fiscal Product Mixin
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/product_mixin.py
  l10n_br_fiscal/models/product_product.py
  l10n_br_fiscal/models/product_template.py
  l10n_br_fiscal/views/product_product_view.xml
  l10n_br_fiscal/views/product_template_view.xml
Labels: approved, bot is merging ⏳

#1100 [12.0][FIX] l10n_br_contract: demo data
  l10n_br_contract/demo/contract_demo.xml
Labels: 12.0, approved, bot is merging ⏳

#1084 [12.0] l10n_br_coa Account Tax and Fiscal Update
  l10n_br_account/data/account_tax_group.xml
  l10n_br_account/data/account_tax_template.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
Labels: 12.0, approved, bot is merging ⏳, needs review

#1094 [12.0] Refatorado método fiscal.tax compute_taxes
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/account_tax.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: 12.0, approved, bot is merging ⏳

#1107 [12.0][performance] no 0.0 default for Float and Monetary fields, no required for Floats
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
Labels: approved, bot is merging ⏳

#1108 [12.0] XML exports: skip non XSD spec fields like o2m foreign keys
  spec_driven_model/models/spec_export.py
Labels: approved, bot is merging ⏳, needs review

#981 [12.0][ADD] l10n_br_nfe_spec clean initial addition
  l10n_br_nfe_spec/__init__.py
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_nfe_spec/models/__init__.py
  l10n_br_nfe_spec/models/spec_models.py
  l10n_br_nfe_spec/models/v4_00/__init__.py
  l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
  l10n_br_nfe_spec/readme/CONFIGURE.rst
  l10n_br_nfe_spec/readme/CONTRIBUTORS.rst
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
  l10n_br_nfe_spec/readme/INSTALL.rst
  l10n_br_nfe_spec/readme/ROADMAP.rst
  l10n_br_nfe_spec/readme/USAGE.rst
  l10n_br_nfe_spec/tests/__init__.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
  requirements.txt
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#1073 [12.0] Correção da base do DIFAL ICMS
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#1087 [12.0][IMP] l10n_br_fiscal: amount_estimate_tax
  l10n_br_account/models/account_tax.py
  l10n_br_fiscal/models/data_ncm_nbs_abstract.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#1110 [12.0] strip fiscal profile name
  l10n_br_fiscal/data/partner_profile_data.xml
Labels: approved, bot is merging ⏳

#1111 [12.0] l10n_br_coa_simple add missing xmlid
  l10n_br_coa_simple/data/account.account.template.csv
Labels: approved, bot is merging ⏳
