Repository OCA/l10n-brazil, pull requests merged in 2021-08, with the labels that each got.

#1552 [12.0][FIX] l10n_br_sale: get document_serie_id
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#1549 [12.0][FIX] l10n_br_nfse_issnet: corrige a inscrição municipal para tomador…
  l10n_br_nfse_issnet/models/l10n_br_fiscal_document.py
Labels: approved, bot is merging ⏳

#1538 [12.0][FIX] Validate payment information
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_nfe_serialize.py
Labels: needs fixing, approved, bot is merging ⏳

#1548 [12.0][FIX] l10n_br_repair: Ajustes de cálculos e localização do relatório Ordem de Reparo.
  l10n_br_repair/__manifest__.py
  l10n_br_repair/models/fiscal_line_mixin.py
  l10n_br_repair/models/repair_fee.py
  l10n_br_repair/models/repair_line.py
  l10n_br_repair/models/repair_order.py
  l10n_br_repair/report/repair_templates_repair_order.xml
Labels: approved, bot is merging ⏳

#1484 [12.0][FIX] l10n_br_currency_rate_update: converts the value returned by the BCB.
  l10n_br_currency_rate_update/models/res_currency_rate_provider_bcb.py
Labels: approved, ready to merge, bot is merging ⏳

#1551 [12.0][IMP] l10n_br_repair: add payment_term_id on invoices
  l10n_br_repair/__manifest__.py
  l10n_br_repair/models/repair_order.py
  oca_dependencies.txt
Labels: approved, ready to merge, bot is merging ⏳

#1550 [12.0][FIX] l10n_br_repair: invoice.tax_line_ids and document amounts
  l10n_br_repair/models/repair_order.py
Labels: approved, bot is merging ⏳

#1553 [12.0][l10n_br_nfe_spec] Pacote de Liberação nº 9 (Novo leiaute da NF-e, NT 2020.005, 2020.006 e NT 2021.002). Publicado em 29/06/2021.
  .pre-commit-config.yaml
  l10n_br_nfe_spec/__init__.py
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_nfe_spec/models/spec_models.py
  l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
Labels: approved, bot is merging ⏳

#1545 [12.0][FIX] l10n_br_fiscal: Remove obrigatoriedade de preenchimento do campo issqn_fg_city na view
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1555 [12.0][l10n_br_fiscal][FIX] store=True for related _order fields
  l10n_br_fiscal/models/cst.py
  l10n_br_fiscal/models/tax.py
Labels: needs review, approved, bot is merging ⏳

#1560 [12.0] fixes #1559 - disable buggy detpag validation #1457
  l10n_br_nfe/models/document.py
Labels: needs review, approved, bot is merging ⏳

#1557 [12.0][IMP] l10n_br_fiscal: decent readme
  l10n_br_fiscal/README.rst
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/readme/DESCRIPTION.rst
  l10n_br_fiscal/static/description/index.html
  l10n_br_fiscal/static/img/fiscal_dashboard.png
  l10n_br_fiscal/static/img/fiscal_line.png
  l10n_br_fiscal/static/img/fiscal_operation.png
  l10n_br_fiscal/static/img/fiscal_total.png
Labels: needs review, approved, bot is merging ⏳

#1562 [12.0] cielo security hotfix
  payment_cielo/models/payment_token.py
  payment_cielo/models/payment_transaction.py
Labels: bug, approved, bot is merging ⏳

#1413 [12.0] Invoice refund only
  l10n_br_account/models/account_invoice.py
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_invoice_refund.py
  l10n_br_account/views/l10n_br_account_action.xml
  l10n_br_account/wizards/account_invoice_refund.py
  l10n_br_fiscal/models/document.py
Labels: bug, needs review, approved, ready to merge, 12.0, bot is merging ⏳

#1568 [13.0] mig l10n_br_base
  .travis.yml
  l10n_br_base/README.rst
  l10n_br_base/__init__.py
  l10n_br_base/__manifest__.py
  l10n_br_base/data/res.bank.csv
  l10n_br_base/data/res.city.csv
  l10n_br_base/data/res.country.state.csv
  l10n_br_base/data/res_country_data.xml
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_base/demo/res_partner_demo.xml
  l10n_br_base/demo/res_users_demo.xml
  l10n_br_base/hooks.py
  l10n_br_base/i18n/l10n_br_base.pot
  l10n_br_base/i18n/pt_BR.po
  l10n_br_base/models/__init__.py
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_bank.py
  l10n_br_base/models/res_city.py
  l10n_br_base/models/res_company.py
  l10n_br_base/models/res_config_settings.py
  l10n_br_base/models/res_country.py
  l10n_br_base/models/res_country_state.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_bank.py
  l10n_br_base/models/state_tax_numbers.py
  l10n_br_base/readme/CONFIGURE.rst
  l10n_br_base/readme/CONTRIBUTORS.rst
  l10n_br_base/readme/DESCRIPTION.rst
  l10n_br_base/readme/HISTORY.rst
  l10n_br_base/readme/INSTALL.rst
  l10n_br_base/readme/ROADMAP.rst
  l10n_br_base/readme/USAGE.rst
  l10n_br_base/security/ir.model.access.csv
  l10n_br_base/static/description/icon.png
  l10n_br_base/static/description/index.html
  l10n_br_base/static/img/res_partner_akretion-image.jpg
  l10n_br_base/static/img/res_partner_kmee.png
  l10n_br_base/static/src/less/form_view.less
  l10n_br_base/tests/__init__.py
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_valid_createid.py
  l10n_br_base/views/res_bank_view.xml
  l10n_br_base/views/res_city_view.xml
  l10n_br_base/views/res_company_view.xml
  l10n_br_base/views/res_config_settings_view.xml
  l10n_br_base/views/res_country_view.xml
  l10n_br_base/views/res_partner_address_view.xml
  l10n_br_base/views/res_partner_bank_view.xml
  l10n_br_base/views/res_partner_view.xml
  l10n_br_base/views/webclient_templates.xml
  oca_dependencies.txt
  requirements.txt
Labels: needs review, approved, bot is merging ⏳

#1573 [12.0] l10n_br_base fixes form 13.0 review that will be upstreamed
  l10n_br_base/__manifest__.py
  l10n_br_base/models/res_company.py
Labels: needs review, approved, bot is merging ⏳

#1577 [12.0][REF] l10n_br_coa maintainers, categ, desc
  l10n_br_coa/__manifest__.py
Labels: needs review, approved, bot is merging ⏳

#1576 [13.0] mig l10n_br_coa
  l10n_br_coa/README.rst
  l10n_br_coa/__init__.py
  l10n_br_coa/__manifest__.py
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/data/account_type_data.xml
  l10n_br_coa/data/l10n_br_coa_template.xml
  l10n_br_coa/i18n/l10n_br_coa.pot
  l10n_br_coa/i18n/pt_BR.po
  l10n_br_coa/models/__init__.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax.py
  l10n_br_coa/models/account_tax_group.py
  l10n_br_coa/models/account_tax_mixin.py
  l10n_br_coa/models/account_tax_template.py
  l10n_br_coa/readme/CONFIGURE.rst
  l10n_br_coa/readme/CONTRIBUTORS.rst
  l10n_br_coa/readme/DESCRIPTION.rst
  l10n_br_coa/readme/INSTALL.rst
  l10n_br_coa/readme/ROADMAP.rst
  l10n_br_coa/readme/USAGE.rst
  l10n_br_coa/static/description/icon.png
  l10n_br_coa/static/description/index.html
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa/views/account_tax_template.xml
Labels: approved, bot is merging ⏳

#1558 [12.0][IMP] Included CNAB 400 mov. codes for Banco do Brasil, Itau and update Bradesco
  l10n_br_account_payment_brcobranca/constants/br_cobranca.py
  l10n_br_account_payment_brcobranca/models/account_move_line.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_brcobranca/tests/data/boleto_teste_bb400.pdf
  l10n_br_account_payment_brcobranca/tests/data/boleto_teste_bradesco400.pdf
  l10n_br_account_payment_brcobranca/tests/data/boleto_teste_itau400.pdf
  l10n_br_account_payment_brcobranca/tests/data/boleto_teste_sicredi_cnab240.pdf
  l10n_br_account_payment_brcobranca/tests/data/teste_remessa_bb400.REM
  l10n_br_account_payment_brcobranca/tests/data/teste_remessa_bradesco400.REM
  l10n_br_account_payment_brcobranca/tests/data/teste_remessa_itau400.REM
  l10n_br_account_payment_brcobranca/tests/data/teste_remessa_sicredi240.REM
  l10n_br_account_payment_brcobranca/tests/test_payment_order.py
  l10n_br_account_payment_order/README.rst
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_bradesco_cnab_240_400.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_cef_cnab_240.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_do_brasil_cnab_400.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_itau_cnab_240_400.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_sicred_cnab_240.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_unicred_cnab_240_400.xml
  l10n_br_account_payment_order/data/l10n_br_cnab_mov_instruction_code_data.xml
  l10n_br_account_payment_order/demo/account_invoice.xml
  l10n_br_account_payment_order/demo/account_journal.xml
  l10n_br_account_payment_order/demo/account_payment_mode.xml
  l10n_br_account_payment_order/demo/ir_sequence.xml
  l10n_br_account_payment_order/models/l10n_br_cnab_mov_intruction_code.py
  l10n_br_account_payment_order/models/l10n_br_cnab_return_move_code.py
  l10n_br_account_payment_order/readme/CONFIGURE.rst
  l10n_br_account_payment_order/readme/ROADMAP.rst
  l10n_br_account_payment_order/static/description/index.html
  l10n_br_account_payment_order/tests/test_invoice_manual_workflow.py
  l10n_br_account_payment_order/tests/test_payment_order_change.py
  l10n_br_account_payment_order/views/l10n_br_cnab_mov_instruction_code_view.xml
  l10n_br_account_payment_order/views/l10n_br_cnab_return_move_code_view.xml
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1582 [13.0][MIGR] fix account.tax.repartition.line COA loading
  l10n_br_coa/models/account_chart_template.py
Labels: needs review, approved, bot is merging ⏳

#1585 [14.0] mig l10n_br_coa
  l10n_br_coa/README.rst
  l10n_br_coa/__init__.py
  l10n_br_coa/__manifest__.py
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/data/account_type_data.xml
  l10n_br_coa/data/l10n_br_coa_template.xml
  l10n_br_coa/i18n/l10n_br_coa.pot
  l10n_br_coa/i18n/pt_BR.po
  l10n_br_coa/models/__init__.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax.py
  l10n_br_coa/models/account_tax_group.py
  l10n_br_coa/models/account_tax_mixin.py
  l10n_br_coa/models/account_tax_template.py
  l10n_br_coa/readme/CONFIGURE.rst
  l10n_br_coa/readme/CONTRIBUTORS.rst
  l10n_br_coa/readme/DESCRIPTION.rst
  l10n_br_coa/readme/INSTALL.rst
  l10n_br_coa/readme/ROADMAP.rst
  l10n_br_coa/readme/USAGE.rst
  l10n_br_coa/static/description/icon.png
  l10n_br_coa/static/description/index.html
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa/views/account_tax_template.xml
Labels: needs review, approved, bot is merging ⏳

#1584 [13.0] mig l10n_br_coa_simple
  l10n_br_coa_simple/README.rst
  l10n_br_coa_simple/__init__.py
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/data/account.account.template.csv
  l10n_br_coa_simple/data/account_group.xml
  l10n_br_coa_simple/data/account_tax_group.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template_post.xml
  l10n_br_coa_simple/demo/account_journal.xml
  l10n_br_coa_simple/hooks.py
  l10n_br_coa_simple/i18n/l10n_br_coa_simple.pot
  l10n_br_coa_simple/readme/CONFIGURE.rst
  l10n_br_coa_simple/readme/CONTRIBUTORS.rst
  l10n_br_coa_simple/readme/DESCRIPTION.rst
  l10n_br_coa_simple/readme/INSTALL.rst
  l10n_br_coa_simple/readme/ROADMAP.rst
  l10n_br_coa_simple/readme/USAGE.rst
  l10n_br_coa_simple/static/description/icon.png
  l10n_br_coa_simple/static/description/index.html
  l10n_br_coa_simple/tests/__init__.py
  l10n_br_coa_simple/tests/test_l10n_br_coa_simple.py
Labels: needs review, approved, bot is merging ⏳

#1583 [13.0] mig l10n_br_coa_generic
  l10n_br_coa_generic/README.rst
  l10n_br_coa_generic/__init__.py
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/account_fiscal_position_template.xml
  l10n_br_coa_generic/data/account_group.xml
  l10n_br_coa_generic/data/account_tax_group.xml
  l10n_br_coa_generic/data/l10n_br_coa_generic_template.xml
  l10n_br_coa_generic/data/l10n_br_coa_generic_template_post.xml
  l10n_br_coa_generic/demo/account_journal.xml
  l10n_br_coa_generic/hooks.py
  l10n_br_coa_generic/i18n/l10n_br_coa_generic.pot
  l10n_br_coa_generic/i18n/pt_BR.po
  l10n_br_coa_generic/readme/CONFIGURE.rst
  l10n_br_coa_generic/readme/CONTRIBUTORS.rst
  l10n_br_coa_generic/readme/DESCRIPTION.rst
  l10n_br_coa_generic/readme/INSTALL.rst
  l10n_br_coa_generic/readme/ROADMAP.rst
  l10n_br_coa_generic/readme/USAGE.rst
  l10n_br_coa_generic/static/description/icon.png
  l10n_br_coa_generic/static/description/index.html
  l10n_br_coa_generic/static/pdf/Livro_Escrituracao_contabil.pdf
  l10n_br_coa_generic/tests/__init__.py
  l10n_br_coa_generic/tests/test_l10n_br_coa_generic.py
Labels: needs review, approved, bot is merging ⏳

#1301 [12.0][REF] Delivery Costs( Freight, Insurance and Other Value )
  l10n_br_account/models/__init__.py
  l10n_br_account/models/account_incoterms.py
  l10n_br_account/models/account_invoice.py
  l10n_br_delivery/__manifest__.py
  l10n_br_delivery/data/account_incoterms_data.xml
  l10n_br_delivery/data/res_config_settings_data.xml
  l10n_br_delivery/demo/l10n_br_delivery_demo.xml
  l10n_br_delivery/demo/sale_order_demo.xml
  l10n_br_delivery/models/__init__.py
  l10n_br_delivery/models/account_incoterms.py
  l10n_br_delivery/models/delivery_carrier.py
  l10n_br_delivery/models/document.py
  l10n_br_delivery/models/fiscal_document_mixin.py
  l10n_br_delivery/models/sale_order.py
  l10n_br_delivery/models/vehicle.py
  l10n_br_delivery/security/ir.model.access.csv
  l10n_br_delivery/tests/test_delivery_inverse_amount.py
  l10n_br_delivery/views/account_incoterms_view.xml
  l10n_br_delivery/views/delivery_carrier_views.xml
  l10n_br_delivery/views/l10n_br_delivery_view.xml
  l10n_br_delivery/views/sale_order_view.xml
  l10n_br_delivery/views/stock_picking_view.xml
  l10n_br_sale/models/res_company.py
  l10n_br_sale/models/res_config_settings.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/views/res_company_view.xml
  l10n_br_sale/views/res_config_settings_view.xml
  l10n_br_sale/views/sale_view.xml
  oca_dependencies.txt
Labels: 12.0, bot is merging ⏳

#1590 [12.0][FIX] Standard name to City field in l10n_br_delivery.
  l10n_br_delivery/demo/l10n_br_delivery_demo.xml
  l10n_br_delivery/models/vehicle.py
  l10n_br_delivery/views/l10n_br_delivery_view.xml
Labels: approved, bot is merging ⏳

#1588 [14.0] mig l10n_br_coa_simple
  l10n_br_coa_simple/README.rst
  l10n_br_coa_simple/__init__.py
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/data/account.account.template.csv
  l10n_br_coa_simple/data/account_group.xml
  l10n_br_coa_simple/data/account_tax_group.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template_post.xml
  l10n_br_coa_simple/demo/account_journal.xml
  l10n_br_coa_simple/hooks.py
  l10n_br_coa_simple/i18n/l10n_br_coa_simple.pot
  l10n_br_coa_simple/readme/CONFIGURE.rst
  l10n_br_coa_simple/readme/CONTRIBUTORS.rst
  l10n_br_coa_simple/readme/DESCRIPTION.rst
  l10n_br_coa_simple/readme/INSTALL.rst
  l10n_br_coa_simple/readme/ROADMAP.rst
  l10n_br_coa_simple/readme/USAGE.rst
  l10n_br_coa_simple/static/description/icon.png
  l10n_br_coa_simple/static/description/index.html
  l10n_br_coa_simple/tests/__init__.py
  l10n_br_coa_simple/tests/test_l10n_br_coa_simple.py
Labels: needs review, approved, bot is merging ⏳

#1567 [12.0[l10n_br_fiscal]][REM] remove unused/untested/broken l10n_br_fiscal.attachment
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/attachment.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1594 [14.0][FIX] manifest typos
  l10n_br_coa/__manifest__.py
Labels: needs review, approved, bot is merging ⏳

#1597 [12.0][BACKPORT][l10n_br_coa_simple] maintainers + dev status + desc
  l10n_br_coa_simple/__manifest__.py
Labels: approved, bot is merging ⏳

#1600 [12.0][FIX] incorterm_id in _shadowed_fields in l10n_br_delivery fixes #1596
  l10n_br_account/models/account_invoice.py
  l10n_br_delivery/models/__init__.py
  l10n_br_delivery/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1595 [12.0][BACKPORT][l10n_br_coa] manifest
  l10n_br_coa/__manifest__.py
Labels: approved, bot is merging ⏳

#1606 [12.0] revert fix ci logging
  .travis.yml
Labels: approved

#1604 [12.0][BACKPORT][l10n_br_fiscal] usability backport
  l10n_br_fiscal/models/document_eletronic.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/wizards/base_wizard_mixin.py
Labels: approved, bot is merging ⏳

#1608 [12.0][FIX] _force_stack_paths attribute in spec_driven_model
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_nfe_structure.py
  l10n_br_nfe/views/nfe_document_view.xml
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳
