Repository OCA/l10n-brazil, pull requests merged in 2021-12, with the labels that each got.

#1736 [12.0][FIX] Correção da Tag ICMSUFDest
  l10n_br_nfe/models/document_line.py
Labels: approved, 12.0, bot is merging ⏳

#1652 [12.0] l10n_br_fiscal store=True em campos de totais
  l10n_br_account/models/account_invoice.py
  l10n_br_contract/models/contract_contract.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_nfe/demo/fiscal_document_demo.xml
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_repair/models/repair_order.py
Labels: approved, 12.0, bot is merging ⏳

#1739 [12][IMP] Alterações para suportar o banco Ailos
  l10n_br_account_payment_brcobranca/constants/br_cobranca.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1741 [12.0][IMP] Suporte para o Banco AILOS no Retorno Bancário
  l10n_br_account_payment_brcobranca/demo/account_journal_demo.xml
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
  l10n_br_account_payment_brcobranca/readme/CONTRIBUTORS.rst
  l10n_br_account_payment_brcobranca/tests/data/CNAB240AILOS.RET
  l10n_br_account_payment_brcobranca/tests/data/boleto_teste_ailos_cnab240.pdf
  l10n_br_account_payment_brcobranca/tests/data/teste_remessa_ailos240.REM
  l10n_br_account_payment_brcobranca/tests/test_payment_order.py
  l10n_br_account_payment_brcobranca/tests/test_return_import.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_ailos_cnab_240.xml
  l10n_br_account_payment_order/demo/account_invoice.xml
  l10n_br_account_payment_order/demo/account_journal.xml
  l10n_br_account_payment_order/demo/account_payment_mode.xml
  l10n_br_account_payment_order/demo/ir_sequence.xml
  l10n_br_account_payment_order/demo/res_partner_bank.xml
  l10n_br_account_payment_order/readme/CONTRIBUTORS.rst
Labels: needs review, approved, ready to merge, 12.0, bot is merging ⏳

#1737 [12.0][FIX] Valor Recebido no retorno bancário para o banco Itaú.
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1743 [12.0][FIX] Avoid Comparing apples and oranges warning
  l10n_br_account/models/account_invoice.py
Labels: approved, 12.0, bot is merging ⏳

#1748 [14.0] l10n_br_currency_rate_update migration
  l10n_br_currency_rate_update/README.rst
  l10n_br_currency_rate_update/__init__.py
  l10n_br_currency_rate_update/__manifest__.py
  l10n_br_currency_rate_update/i18n/l10n_br_currency_rate_update.pot
  l10n_br_currency_rate_update/i18n/pt_BR.po
  l10n_br_currency_rate_update/models/__init__.py
  l10n_br_currency_rate_update/models/res_currency_rate_provider_bcb.py
  l10n_br_currency_rate_update/readme/CONFIGURE.rst
  l10n_br_currency_rate_update/readme/CONTRIBUTORS.rst
  l10n_br_currency_rate_update/readme/DESCRIPTION.rst
  l10n_br_currency_rate_update/readme/USAGE.rst
  l10n_br_currency_rate_update/static/description/icon.png
  l10n_br_currency_rate_update/static/description/index.html
  l10n_br_currency_rate_update/tests/__init__.py
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
Labels: approved, migration, bot is merging ⏳, 14.0

#1746 [14.0][MIG] l10n_br_crm
  l10n_br_crm/README.rst
  l10n_br_crm/__init__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/i18n/l10n_br_crm.pot
  l10n_br_crm/i18n/pt_BR.po
  l10n_br_crm/models/__init__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/readme/CONFIGURE.rst
  l10n_br_crm/readme/CONTRIBUTORS.rst
  l10n_br_crm/readme/DESCRIPTION.rst
  l10n_br_crm/readme/INSTALL.rst
  l10n_br_crm/readme/ROADMAP.rst
  l10n_br_crm/readme/USAGE.rst
  l10n_br_crm/static/description/icon.png
  l10n_br_crm/static/description/index.html
  l10n_br_crm/tests/__init__.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_crm/views/crm_lead_view.xml
  l10n_br_crm/views/crm_quick_create_opportunity_form.xml
  setup/l10n_br_crm/odoo/addons/l10n_br_crm
  setup/l10n_br_crm/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 14.0
