Repository OCA/l10n-brazil, pull requests merged in 2021-09, with the labels that each got.

#1614 [12.0][FIX] document_status_wizard.xml: fix button string
  l10n_br_fiscal/wizards/document_status_wizard.xml
Labels: approved, bot is merging ⏳

#1616 [12.0][FIX] l10n_br_stock_account: fix message error
  l10n_br_stock_account/wizards/stock_return_picking.py
Labels: approved, bot is merging ⏳

#1615 [12.0][IMP] Purchase Report with BR fields
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/reports/purchase_report.py
  l10n_br_purchase/reports/purchase_report_views.xml
Labels: approved, bot is merging ⏳

#1617 [12.0][IMP] l10n_br_fiscal: rename tax fields (ret to wh)
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/12.0.18.0.0/pre-migration.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_nfse/report/danfse.xml
Labels: bot is merging ⏳

#1619 [12.0][FIX] l10n_br_nfse: fix irpj tax (DANFSE)
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#1620 [12.0][FIX] l10n_br_nfse: Pequenas melhorias do DANFSE
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#1621 [REF] Limpar mensagem de log do spec_model
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#1602 [12.0] refactor account tax group
  l10n_br_coa/__manifest__.py
  l10n_br_coa/models/__init__.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/l10n_br_coa_account_tax_group_account_template.py
  l10n_br_coa/security/ir.model.access.csv
  l10n_br_coa_complete/__manifest__.py
  l10n_br_coa_complete/data/account_tax_group.xml
  l10n_br_coa_complete/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_generic/data/account_tax_group.xml
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/data/account_tax_group.xml
  l10n_br_coa_simple/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, ready to merge, bot is merging ⏳

#1623 [13.0][FORWARD PORT] ref group tax
  l10n_br_coa/__manifest__.py
  l10n_br_coa/models/__init__.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/l10n_br_coa_account_tax_group_account_template.py
  l10n_br_coa/security/ir.model.access.csv
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_generic/data/account_tax_group.xml
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/data/account_tax_group.xml
  l10n_br_coa_simple/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, bot is merging ⏳

#1574 [12.0] Devoluções e Retornos de Materiais
  l10n_br_account/models/account_invoice.py
  l10n_br_account/views/l10n_br_account_action.xml
  l10n_br_account/wizards/account_invoice_refund.py
  l10n_br_fiscal/models/document.py
Labels: needs review, approved, bot is merging ⏳

#1625 [12.0][FIX] l10n_br_nfse: get values from document
  l10n_br_nfse/report/danfse.xml
Labels: bot is merging ⏳

#1627 [12.0][IMP] BR fields in the Sale Report
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/report/sale_report.py
  l10n_br_sale/report/sale_report_view.xml
Labels: approved, bot is merging ⏳

#1629 [12.0][ADD] l10n_br_nfse: Law indication in DANFSe
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#1630 [12.0][FIX] l10n_br_nfse: federal withholdings
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#1628 [12.0][FIX] l10n_br_fiscal e l10n_br_nfse: regeração do PDF do documento fiscal
  l10n_br_fiscal/models/document_eletronic.py
  l10n_br_nfse/models/document.py
Labels: approved, bot is merging ⏳

#1639 [12.0][BUG] Correção do financial_move_line_ids que as vezes fica em branco.
  l10n_br_account/models/account_invoice.py
Labels: approved

#1626 [12.0] Ao Excluir uma Fatura o documento fiscal deve ser excluido
  l10n_br_account/models/account_invoice.py
  l10n_br_fiscal/models/document.py
Labels: bug, approved, 12.0, bot is merging ⏳

#1641 [12.0][FIX] Onchange method for State field must be called.
  l10n_br_base/models/party_mixin.py
  l10n_br_base/tests/test_base_onchange.py
Labels: approved, bot is merging ⏳

#1644 [12.0][IMP] financial_total_gross and financial_discount_value
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_sale_stock/tests/test_sale_stock.py
Labels: approved, bot is merging ⏳

#1643 [12.0] ADD l10n _br_account_due_list
  l10n_br_account/__manifest__.py
  l10n_br_account/models/account_invoice.py
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_account_due_list/README.rst
  l10n_br_account_due_list/__init__.py
  l10n_br_account_due_list/__manifest__.py
  l10n_br_account_due_list/models/__init__.py
  l10n_br_account_due_list/models/account_invoice.py
  l10n_br_account_due_list/readme/CONFIGURE.rst
  l10n_br_account_due_list/readme/CONTRIBUTORS.rst
  l10n_br_account_due_list/readme/DESCRIPTION.rst
  l10n_br_account_due_list/readme/HISTORY.rst
  l10n_br_account_due_list/readme/INSTALL.rst
  l10n_br_account_due_list/readme/ROADMAP.rst
  l10n_br_account_due_list/readme/USAGE.rst
  l10n_br_account_due_list/static/description/icon.png
  l10n_br_account_due_list/static/description/index.html
  l10n_br_account_due_list/static/img/l10n_br_account_due_list_payable.png
  l10n_br_account_due_list/static/img/l10n_br_account_due_list_receivable.png
  l10n_br_account_due_list/views/account_invoice_view.xml
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/models/account_invoice.py
Labels: approved, bot is merging ⏳
