Repository OCA/l10n-brazil, pull requests merged in 2021-03, with the labels that each got.

#1160 [FIX] l10n_br_zip: correção do retorno do WS dos correios
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1155 [FIX] ondelete='cascade' fiscal.document.lines, close #1055
  l10n_br_fiscal/models/document_line.py
Labels: approved, bot is merging ⏳

#1149 [REF] NFS-e company view
  l10n_br_nfse/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#1163 [NEW] Track visibility fiscal fields
  l10n_br_fiscal/models/res_partner.py
Labels: approved, bot is merging ⏳

#1103 [FIX] l10n_br_sale_stock regressions
  l10n_br_sale_stock/__manifest__.py
  l10n_br_sale_stock/demo/sale_order_demo.xml
  l10n_br_sale_stock/models/__init__.py
  l10n_br_sale_stock/models/res_company.py
  l10n_br_sale_stock/models/res_config_settings.py
  l10n_br_sale_stock/models/sale_order.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/models/stock_rule.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/views/res_company_view.xml
  l10n_br_sale_stock/views/res_config_settings_view.xml
  l10n_br_sale_stock/views/sale_order_view.xml
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: 12.0, bot is merging ⏳

#1165 Definir os tax.definition do ICMS como noupdate
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
  l10n_br_fiscal/data/l10n_br_fiscal_tax_icms_data.xml
Labels: 12.0, approved, bot is merging ⏳

#1167 [FIX] Removing comment views domain, because they already on python
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/operation_line_view.xml
Labels: approved, bot is merging ⏳

#1172 [12.0] Demo Configurar cancelar lançamentos contábeis
  l10n_br_coa_generic/demo/account_journal.xml
  l10n_br_coa_simple/demo/account_journal.xml
Labels: 12.0, approved, bot is merging ⏳

#1176 [ADD] fiscal document message alerts
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#1180 [12.0][FIX] l10n_br_fiscal: set readonly alert fields
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#1184 [FIX] Empresas de demo não são empresas
  l10n_br_base/demo/res_company_demo.xml
Labels: approved, bot is merging ⏳

#1171 [12.0][FIX] Purchase data in invoice created from Picking
  l10n_br_purchase_stock/__init__.py
  l10n_br_purchase_stock/__manifest__.py
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_purchase_stock/models/__init__.py
  l10n_br_purchase_stock/models/purchase_order.py
  l10n_br_purchase_stock/models/stock_move.py
  l10n_br_purchase_stock/readme/CONTRIBUTORS.rst
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_purchase_stock/wizards/__init__.py
  l10n_br_purchase_stock/wizards/stock_invocing_onshipping.py
Labels: 12.0, approved, bot is merging ⏳

#1182 [12.0][IMP] Test l10n_br_sale Sale Order with product and service
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: approved, bot is merging ⏳

#1177 [ADD] Restringir a exclusão dos documentos fiscais Dummy
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: approved, bot is merging ⏳

#1170 [12.0] [IMP] danfse layout
  l10n_br_nfse/report/danfse.xml
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#1162 [12.0] Remove compute_reduction validation
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#1186 [FIX] Just try to validate cnpj on related documents if filled
  l10n_br_fiscal/models/document_related.py
Labels: approved, bot is merging ⏳

#1188 [IMP] Fiscal contants
  l10n_br_fiscal/constants/fiscal.py
Labels: approved, bot is merging ⏳

#1189 [NEW] Sum ICMSST
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#1183 [12.0][FIX] Creation Invoice from Sale Order with Product and Service
  l10n_br_sale_stock/demo/sale_order_demo.xml
  l10n_br_sale_stock/models/sale_order.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/views/sale_order_view.xml
Labels: approved, bot is merging ⏳, needs review

#1191 l10n_br_currency_rate_update faster CI: 14239 queries down to 9816
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
Labels: approved, bot is merging ⏳

#1192 l10n_br_fiscal: faster CI with SavepointCase
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_ibpt_product.py
  l10n_br_fiscal/tests/test_ibpt_service.py
  l10n_br_fiscal/tests/test_workflow.py
Labels: approved, bot is merging ⏳

#1193 l10n_br_account faster CI with SavepointCase
  l10n_br_account/tests/test_customer_invoice_dummy.py
Labels: approved, bot is merging ⏳

#1196 l10n_br_stock_account: faster CI with SavepointCase
  l10n_br_stock_account/tests/test_invoicing_picking.py
Labels: approved, bot is merging ⏳

#1195 l10n_br_sale_stock: faster CI with SavepointCase
  l10n_br_sale_stock/tests/test_sale_stock.py
Labels: approved, bot is merging ⏳

#1194 l10n_br_sale faster CI with SavepointCase
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/tests/test_l10n_br_sale_lc.py
  l10n_br_sale/tests/test_l10n_br_sale_sn.py
Labels: approved, bot is merging ⏳

#1203 [12.0][FIX] Invoice line created from Stock Picking without Fiscal Operation
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳, bug, good first issue, needs review

#1146 [12.0] Edição do Documento Fiscal e Fatura
  l10n_br_account/__manifest__.py
  l10n_br_account/models/__init__.py
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/account_move.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_operation.py
  l10n_br_account/views/account_invoice_line_view.xml
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_account/views/fiscal_invoice_line_view.xml
  l10n_br_account/views/fiscal_invoice_view.xml
  l10n_br_account/views/l10n_br_account_action.xml
  l10n_br_account/views/l10n_br_account_menu.xml
  l10n_br_account/wizards/__init__.py
  l10n_br_account/wizards/wizard_document_cancel.py
  l10n_br_account/wizards/wizard_document_correction.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_invoice_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/views/purchase_view.xml
  l10n_br_repair/models/repair_order.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/views/sale_view.xml
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/views/stock_picking.xml
Labels: 12.0, bot is merging ⏳, needs review

#1206 no more lint false positive SQL injection warning
  l10n_br_base/hooks.py
Labels: approved, bot is merging ⏳

#1212 [12.0][REM] l10n_br_hr_contract: herança duplicada.. já existe em l10n_br_hr
  l10n_br_hr_contract/views/hr_contract_view.xml
Labels: approved, bot is merging ⏳

#1211 [12.0][FIX] Return Picking process and test
  l10n_br_purchase_stock/__manifest__.py
  l10n_br_purchase_stock/models/res_config_settings.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_purchase_stock/views/res_company_view.xml
  l10n_br_sale_stock/models/res_company.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/views/res_config_settings_view.xml
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/wizards/stock_return_picking.py
Labels: approved, bot is merging ⏳

#1209 [12.0][FIX] NFS-e document number
  l10n_br_nfse/models/document.py
  l10n_br_nfse_ginfes/tests/test_fiscal_document_nfse_ginfes.py
  l10n_br_nfse_issnet/tests/test_fiscal_document_nfse_issnet.py
Labels: approved, bot is merging ⏳

#1030 [12.0] Importação de Extrato Bancário CNAB 240 - Segmento E
  l10n_br_account_bank_statement_import_cnab/README.rst
  l10n_br_account_bank_statement_import_cnab/__init__.py
  l10n_br_account_bank_statement_import_cnab/__manifest__.py
  l10n_br_account_bank_statement_import_cnab/models/__init__.py
  l10n_br_account_bank_statement_import_cnab/models/account_journal.py
  l10n_br_account_bank_statement_import_cnab/readme/CONFIGURE.rst
  l10n_br_account_bank_statement_import_cnab/readme/CONTRIBUTORS.rst
  l10n_br_account_bank_statement_import_cnab/readme/CREDITS.rst
  l10n_br_account_bank_statement_import_cnab/readme/DESCRIPTION.rst
  l10n_br_account_bank_statement_import_cnab/readme/HISTORY.rst
  l10n_br_account_bank_statement_import_cnab/readme/INSTALL.rst
  l10n_br_account_bank_statement_import_cnab/readme/USAGE.rst
  l10n_br_account_bank_statement_import_cnab/static/description/icon.png
  l10n_br_account_bank_statement_import_cnab/static/description/index.html
  l10n_br_account_bank_statement_import_cnab/tests/__init__.py
  l10n_br_account_bank_statement_import_cnab/tests/test_cnab_file/cnab240segmentoE.txt
  l10n_br_account_bank_statement_import_cnab/tests/test_import_bank_statement.py
  l10n_br_account_bank_statement_import_cnab/views/view_account_bank_statement_import.xml
  l10n_br_account_bank_statement_import_cnab/wizard/__init__.py
  l10n_br_account_bank_statement_import_cnab/wizard/account_bank_statement_import.py
  requirements.txt
Labels: 12.0, approved, bot is merging ⏳, needs review, new feature, ready to merge

#1217 [12.0][FIX] There are two buttons 'Create Invoice' in Sale Order and both should has the attribute invisible changed.
  l10n_br_sale_stock/views/sale_order_view.xml
Labels: approved, bot is merging ⏳

#1222 [12.0][FIX] New Document button
  l10n_br_fiscal/models/operation_dashboard.py
Labels: approved, bot is merging ⏳

#1220 [12.0][IMP] Default quantity in new lines
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
Labels: approved, bot is merging ⏳

#1227 [12.0][FIX] Change discount in sent quotation
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#1226 [12.0][ADD] Default fiscal operation type in out invoices
  l10n_br_account/views/l10n_br_account_action.xml
Labels: approved, bot is merging ⏳

#1231 [FIX] Demo company partner number
  l10n_br_base/demo/res_company_demo.xml
Labels: approved, bot is merging ⏳

#1236 Mixin de dados e métodos comuns entre Company e Partner
  l10n_br_base/models/__init__.py
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_company.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_fiscal/models/res_company.py
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review

#1232 [12.0][IMP] Onchange Discount Rate
  l10n_br_sale/models/sale_order.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1239 [12.0][ADD] Demo Cliente 11 SP - PF Não Contribuinte
  l10n_br_base/demo/l10n_br_base_demo.xml
Labels: approved, bot is merging ⏳

#1214 [FIX] remove copy=True in invoice_state field
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1238 [12.0][FIX] Crédito de ICMS para empresas do Simples Nacional
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#1243 [ADD] Bonification Return and Inverse Operations
  l10n_br_fiscal/data/operation_data.xml
Labels: 12.0, approved, enhancement

#1242 [REF] Rename Fiscal Taxes (IPI, PIS and COFINS) with CST Others
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal.tax.pis.cofins.csv
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/migrations/12.0.4.1.0/pre-migration.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/views/res_company_view.xml
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_repair/tests/test_l10n_br_repair.py
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: 12.0, approved, bot is merging ⏳, enhancement

#1248 [12.0][REF+FIX] Code and View moved to stock_picking_invoicing, fix tests
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_stock_account/wizards/stock_return_picking.py
  l10n_br_stock_account/wizards/stock_return_picking_view.xml
Labels: approved, bot is merging ⏳

#1246 [12.0][FIX] ICMS Tax Definition NBM not existent
  l10n_br_fiscal/demo/l10n_br_fiscal.nbm-demo.csv
  l10n_br_fiscal/demo/l10n_br_fiscal.ncm-demo.csv
Labels: approved, bot is merging ⏳

#1254 [FIX] IE Demo Company Data
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_fiscal/demo/company_demo.xml
Labels: approved, bot is merging ⏳

#1175 [12.0] Using Fiscal mixins to compute amount fields
  l10n_br_account/migrations/12.0.4.0.0/pre-migration.py
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/account_tax.py
  l10n_br_account/views/account_invoice_line_view.xml
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_contract/models/contract_contract.py
  l10n_br_delivery/models/document.py
  l10n_br_delivery/models/sale_order.py
  l10n_br_delivery/tests/test_delivery_inverse_amount.py
  l10n_br_fiscal/migrations/12.0.4.2.0/pre-migration.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/report/account_invoice_report.py
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/wizards/l10n_br_account_invoice_costs_ratio.py
  l10n_br_fiscal/wizards/l10n_br_account_invoice_costs_ratio_view.xml
  l10n_br_nfe/tests/test_account_customer_nfe.py
  l10n_br_nfe/views/nfe/account_invoice_nfe_view.xml
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_purchase/migrations/12.0.2.0.0/pre-migration.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/reports/purchase_order_templates.xml
  l10n_br_purchase/views/purchase_view.xml
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_repair/demo/repair_order.xml
  l10n_br_repair/migrations/12.0.2.0.0/pre-migration.py
  l10n_br_repair/models/fiscal_line_mixin.py
  l10n_br_repair/models/repair_order.py
  l10n_br_repair/tests/test_l10n_br_repair.py
  l10n_br_repair/views/repair_fee.xml
  l10n_br_repair/views/repair_line.xml
  l10n_br_repair/views/repair_order.xml
  l10n_br_sale/migrations/12.0.4.0.0/pre-migration.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/report/sale_report_templates.xml
  l10n_br_sale/views/sale_view.xml
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/migrations/12.0.3.0.0/pre-migration.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/views/stock_account_view.xml
  l10n_br_website_sale_delivery/controllers/main.py
  l10n_br_website_sale_delivery/tests/test_website_sale_tour.py
  l10n_br_website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review, ready to merge, refactoring

#1241 [FIX] Processador edoc OCA on nfse
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/tests/test_certificate.py
  l10n_br_fiscal/tools/misc.py
  l10n_br_nfse/models/__init__.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse_ginfes/models/document.py
  l10n_br_nfse_issnet/models/l10n_br_fiscal_document.py
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs fixing

#1221 [12.0][FIX] Fiscal closing error
  l10n_br_fiscal/models/closing.py
  l10n_br_fiscal/views/closing.xml
  l10n_br_fiscal/views/document_view.xml
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1247 [WIP] New front end testing strategy
  l10n_br_website_sale/static/src/js/l10n_br_website_sale_tour.js
  l10n_br_website_sale/tests/test_sale_process.py
Labels: approved, bot is merging ⏳

#1260 typo fix, without backdoor (unlike PHP ;-)
  l10n_br_nfse/models/document.py
  l10n_br_nfse_ginfes/models/document.py
  l10n_br_nfse_issnet/models/l10n_br_fiscal_document.py
Labels: 12.0, approved, bot is merging ⏳

#1264 [FIX] Cross-Site Scripting in lxml
  requirements.txt
Labels: approved, bot is merging ⏳

#1263 [FIX] do not remove discount field from view
  l10n_br_account/views/account_invoice_line_view.xml
Labels: 12.0, approved, bot is merging ⏳, bug
