Repository OCA/l10n-brazil, pull requests merged in 2021-11, with the labels that each got.

#1690 [12.0] fix erro causado pelo fiscal dummy
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#1691 [12.0][FIX] Pagamento de faturas com CNAB registrado.
  l10n_br_account_payment_order/models/l10n_br_cnab_change_methods.py
Labels: approved, bot is merging ⏳

#1694 [14.0][FIX] postprocess_and_fields args
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#1696 [14.0][ADD] format.address.mixin
  l10n_br_base/models/__init__.py
  l10n_br_base/models/format_address_mixin.py
Labels: approved, bot is merging ⏳, 14.0

#1695 [12.0][FIX] Data na chave do documento fiscal
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳

#1700 [12.0][l10n_br_account][FIX] fix typo: stored=True -> store=True
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1702 [12.0][l10n_br_nfe][BACKPORT] l10n br nfe backport
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/invalidate_number.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/wizards/l10n_br_account_nfe_export.py
  l10n_br_nfe/wizards/l10n_br_account_nfe_export_invoice.py
Labels: approved, bot is merging ⏳

#1698 [13.0][MIGR] l10n_br_currency_rate_update migration
  l10n_br_currency_rate_update/README.rst
  l10n_br_currency_rate_update/__init__.py
  l10n_br_currency_rate_update/__manifest__.py
  l10n_br_currency_rate_update/i18n/l10n_br_currency_rate_update.pot
  l10n_br_currency_rate_update/i18n/pt_BR.po
  l10n_br_currency_rate_update/models/__init__.py
  l10n_br_currency_rate_update/models/res_currency_rate_provider_bcb.py
  l10n_br_currency_rate_update/readme/CONFIGURE.rst
  l10n_br_currency_rate_update/readme/CONTRIBUTORS.rst
  l10n_br_currency_rate_update/readme/DESCRIPTION.rst
  l10n_br_currency_rate_update/readme/USAGE.rst
  l10n_br_currency_rate_update/static/description/icon.png
  l10n_br_currency_rate_update/static/description/index.html
  l10n_br_currency_rate_update/tests/__init__.py
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
Labels: approved, migration, ready to merge, 13.0, bot is merging ⏳

#1705 [12.0][FIX] nosso_numero no retorno Itaú (CNAB/Boleto)
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#1706 [12.0][FIX] Limit payment_line search (brcobrança)
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, 12.0, bot is merging ⏳

#1707 [12.0[FIX] Número do documento no arquivo de remessa
  l10n_br_account_payment_order/models/bank_payment_line.py
Labels: approved, 12.0, bot is merging ⏳

#1713 [12.0][FIX] Inutilização do número (módulo fiscal)
  l10n_br_nfe/models/invalidate_number.py
Labels: approved, bot is merging ⏳

#1714 [12.0][FIX] Zeros no número do documento (CNAB)
  l10n_br_account_payment_order/models/account_invoice.py
Labels: approved, 12.0, bot is merging ⏳

#1718 [12.0][FIX] generate_payment_file wrong method return
  l10n_br_account_payment_order/models/account_payment_order.py
Labels: approved, 12.0, bot is merging ⏳

#1717 [12.0][l10n_br_account_payment_order][IMP] use document_number when l10n_br_fiscal is installed
  l10n_br_account_payment_order/models/account_invoice.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1661 [12.0][FIX][BUG] Changed xml_ids of CNAB Codes missing migration script.
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_bradesco_cnab_240_400.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_cef_cnab_240.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_do_brasil_cnab_400.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_itau_cnab_240_400.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_sicred_cnab_240.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_unicred_cnab_240_400.xml
  l10n_br_account_payment_order/demo/account_payment_mode.xml
  l10n_br_account_payment_order/demo/res_partner_bank.xml
  l10n_br_account_payment_order/migrations/12.0.6.0.0/pre-migration.py
Labels: needs review, approved, ready to merge, 12.0, bot is merging ⏳

#1720 [14.0] Atualização da TIPI e Acordo com a Resolução Gecex nº 165, de 22 de fevereiro de 2021
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
Labels: approved, bot is merging ⏳, 14.0

#1719 [12.0] Atualização da TIPI e Acordo com a Resolução Gecex nº 165, de 22 de fevereiro de 2021
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
Labels: approved, 12.0, bot is merging ⏳

#1724 [12.0][FIX] correção municipio_prestacao_servico (issqn_fg_city_id)
  l10n_br_nfse_issnet/models/l10n_br_fiscal_document.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1727 [12.0][FIX] Verificação do número do documento fiscal no Boleto.
  l10n_br_account_payment_order/models/account_invoice.py
Labels: approved, bot is merging ⏳

#1728 [12.0][FIX] fiscal document mixin street related fields
  l10n_br_fiscal/models/document_fiscal_invoice_mixin.py
Labels: approved, 12.0, bot is merging ⏳

#1730 [12.0][BACKPORT] l10n_br_nfe: ir.config.parameter for nfe VerProc tag
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/data/ir_config_parameter.xml
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/res_config_settings.py
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200681583054000129550010000000012760018057-nf-e.xml
Labels: approved, 12.0, bot is merging ⏳

#1731 [12.0][FIX] nfe_version (max 20 characters)
  l10n_br_nfe/data/ir_config_parameter.xml
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200681583054000129550010000000012760018057-nf-e.xml
Labels: approved, 12.0, bot is merging ⏳

#1732 [12.0] Melhorias no módulo l10n_br_fiscal
  l10n_br_fiscal/demo/l10n_br_fiscal.cest-demo.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/operation_line.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1735 [12.0][FIX] Carregamento dos impostos
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/views/account_invoice_line_view.xml
  l10n_br_sale/models/sale_order_line.py
Labels: needs review, approved, 12.0, bot is merging ⏳
