Repository OCA/l10n-brazil, pull requests merged in 2021-06, with the labels that each got.

#1409 [12.0] [l10n_br_nfe_spec] spec currency_field is brl_currency_id
  l10n_br_nfe_spec/models/spec_models.py
Labels: approved, bot is merging ⏳, bug, needs review

#1421 [12.0][spec_driven_model] importação mais rápida das NFe's
  spec_driven_model/models/spec_import.py
Labels: approved, bot is merging ⏳, needs review

#1422 [REF] Standard OCA website spec_driven_model
  spec_driven_model/__manifest__.py
Labels: approved, bot is merging ⏳, needs review

#1427 [FIX] _compute_nfe40_xEnder method
  l10n_br_nfe/models/res_partner.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1418 [12.0][MIG] BR fiscal fields in Invoice Report
  l10n_br_account/__init__.py
  l10n_br_account/__manifest__.py
  l10n_br_account/report/__init__.py
  l10n_br_account/report/account_invoice_report.py
  l10n_br_account/report/account_invoice_report_view.xml
  l10n_br_fiscal/report/account_invoice_report.py
  l10n_br_fiscal/report/account_invoice_report_view.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1137 [NEW] l10n_br_product_contract
  l10n_br_product_contract/README.rst
  l10n_br_product_contract/__init__.py
  l10n_br_product_contract/__manifest__.py
  l10n_br_product_contract/demo/contract_template.xml
  l10n_br_product_contract/demo/product.xml
  l10n_br_product_contract/demo/sale_order.xml
  l10n_br_product_contract/models/__init__.py
  l10n_br_product_contract/models/sale_order.py
  l10n_br_product_contract/models/sale_order_line.py
  l10n_br_product_contract/readme/CONFIGURE.rst
  l10n_br_product_contract/readme/CONTRIBUTORS.rst
  l10n_br_product_contract/readme/CREDITS.rst
  l10n_br_product_contract/readme/DESCRIPTION.rst
  l10n_br_product_contract/readme/HISTORY.rst
  l10n_br_product_contract/readme/INSTALL.rst
  l10n_br_product_contract/readme/USAGE.rst
  l10n_br_product_contract/static/description/icon.png
  l10n_br_product_contract/static/description/index.html
  l10n_br_product_contract/tests/__init__.py
  l10n_br_product_contract/tests/test_l10n_br_product_contract.py
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review

#1416 [12.0] Fiscal Document UOM and UOT fields
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/uom.py
  l10n_br_nfe/models/uom_uom.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1424 [12.0][l10n_br_fiscal] m2m column typo fix with migration script
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/12.0.15.0.0/pre-migration.py
  l10n_br_fiscal/models/cest.py
  l10n_br_fiscal/models/nbm.py
  l10n_br_fiscal/models/ncm_cest.py
  l10n_br_fiscal/models/ncm_nbm.py
  l10n_br_fiscal/models/ncm_tax_pis_cofins.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/simplified_tax.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/models/tax_pis_cofins.py
Labels: bot is merging ⏳, needs review

#1428 [12.0][l10n_br_account] m2m column typo fix with migration script
  l10n_br_account/__manifest__.py
  l10n_br_account/migrations/12.0.7.0.0/pre-migration.py
  l10n_br_account/models/account_tax.py
  l10n_br_account/models/account_tax_template.py
Labels: approved, bot is merging ⏳

#1423 [12.0] [l10n_br_fiscal] lint
  l10n_br_fiscal/models/attachment.py
  l10n_br_fiscal/models/closing.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/operation_dashboard.py
  l10n_br_fiscal/tests/test_ibpt_product.py
Labels: approved, bot is merging ⏳, needs review

#1430 [12.0][l10n_br_coa] removed incorrect @api.multi
  l10n_br_coa/models/account_chart_template.py
Labels: approved, bot is merging ⏳, needs review

#1420 [12.0][l10n_br_fiscal] line amount_financial assigned in _compute_amounts as advertised
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1425 [12.0][FIX] Add the nfe40_choice7 field and depends to the compute
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳

#1432 [12.0][l10n_br_fiscal] fix ncm ir_model_data name
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
Labels: approved, bot is merging ⏳

#1433 [12.0][l10n_br_base] 12.0 pre commit l10n br base
  .codeclimate.yml
  .editorconfig
  .flake8
  .gitignore
  .isort.cfg
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  l10n_br_base/__init__.py
  l10n_br_base/__manifest__.py
  l10n_br_base/data/res_country_data.xml
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_base/demo/res_partner_demo.xml
  l10n_br_base/demo/res_users_demo.xml
  l10n_br_base/hooks.py
  l10n_br_base/migrations/12.0.1.0.0/post-migration.py
  l10n_br_base/migrations/12.0.1.0.0/pre-migration.py
  l10n_br_base/migrations/12.0.1.0.1/pre-migration.py
  l10n_br_base/migrations/12.0.3.0.0/post-migration.py
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_bank.py
  l10n_br_base/models/res_city.py
  l10n_br_base/models/res_company.py
  l10n_br_base/models/res_config_settings.py
  l10n_br_base/models/res_country.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_bank.py
  l10n_br_base/static/src/less/form_view.less
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_valid_createid.py
  l10n_br_base/views/res_bank_view.xml
  l10n_br_base/views/res_city_view.xml
  l10n_br_base/views/res_company_view.xml
  l10n_br_base/views/res_config_settings_view.xml
  l10n_br_base/views/res_country_view.xml
  l10n_br_base/views/res_partner_address_view.xml
  l10n_br_base/views/res_partner_bank_view.xml
  l10n_br_base/views/res_partner_view.xml
  l10n_br_base/views/webclient_templates.xml
Labels: approved, bot is merging ⏳, needs review

#1435 [12.0][l10n_br_coa] 12.0 pre commit l10n br coa
  .pre-commit-config.yaml
  l10n_br_coa/__manifest__.py
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/data/account_type_data.xml
  l10n_br_coa/data/l10n_br_coa_template.xml
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax.py
  l10n_br_coa/models/account_tax_group.py
  l10n_br_coa/models/account_tax_mixin.py
  l10n_br_coa/models/account_tax_template.py
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa/views/account_tax_template.xml
Labels: approved, bot is merging ⏳

#1439 [12.0][l10n_br_sale] 12.0 pre commit l10n br sale
  .pre-commit-config.yaml
  l10n_br_sale/__manifest__.py
  l10n_br_sale/data/company.xml
  l10n_br_sale/demo/company.xml
  l10n_br_sale/demo/fiscal_operation_generic.xml
  l10n_br_sale/demo/fiscal_operation_simple.xml
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/demo/product.xml
  l10n_br_sale/hooks.py
  l10n_br_sale/migrations/12.0.1.0.0/pre-migration.py
  l10n_br_sale/migrations/12.0.4.0.0/pre-migration.py
  l10n_br_sale/migrations/12.0.4.1.0/pre-migration.py
  l10n_br_sale/models/res_company.py
  l10n_br_sale/models/res_config_settings.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/report/sale_report.py
  l10n_br_sale/report/sale_report_templates.xml
  l10n_br_sale/report/sale_report_view.xml
  l10n_br_sale/security/l10n_br_sale_security.xml
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/tests/test_l10n_br_sale_lc.py
  l10n_br_sale/tests/test_l10n_br_sale_sn.py
  l10n_br_sale/views/res_company_view.xml
  l10n_br_sale/views/res_config_settings_view.xml
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#1438 [12.0][l10n_br_stock] 12.0 pre commit l10n br stock
  .pre-commit-config.yaml
  l10n_br_stock/demo/res_users_demo.xml
  l10n_br_stock/demo/stock_inventory_demo.xml
  l10n_br_stock/demo/stock_location_demo.xml
  l10n_br_stock/hooks.py
  l10n_br_stock/views/stock_view.xml
Labels: approved, bot is merging ⏳

#1440 [12.0][l10n_br_sale_stock] 12.0 pre commit l10n_br_sale_stock
  .pre-commit-config.yaml
  l10n_br_sale_stock/__manifest__.py
  l10n_br_sale_stock/demo/l10n_br_sale_stock_demo.xml
  l10n_br_sale_stock/demo/sale_order_demo.xml
  l10n_br_sale_stock/models/res_company.py
  l10n_br_sale_stock/models/res_config_settings.py
  l10n_br_sale_stock/models/sale_order.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/tests/__init__.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/views/res_company_view.xml
  l10n_br_sale_stock/views/res_config_settings_view.xml
  l10n_br_sale_stock/views/sale_order_view.xml
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1436 [12.0][l10n_br_currency_rate_update] 12.0 pre commit l10n_br_currency_rate_update
  .pre-commit-config.yaml
  l10n_br_currency_rate_update/models/res_currency_rate_provider_bcb.py
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
Labels: approved, bot is merging ⏳

#1442 [12.0][l10n_br_zip] 12.0 pre commit l10n_br_zip
  .pre-commit-config.yaml
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/models/res_config_settings.py
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
  l10n_br_zip/views/l10n_br_zip_view.xml
  l10n_br_zip/views/res_config_settings_view.xml
  l10n_br_zip/views/res_partner_address_view.xml
  l10n_br_zip/wizard/l10n_br_zip_search_view.xml
Labels: approved, bot is merging ⏳

#1454 [12.0][ADD] Remove blank spaces
  spec_driven_model/models/spec_export.py
Labels: approved, bot is merging ⏳

#1453 [12.0][FIX] Size of description
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#1448 [12.0] Data Abstract filter_domain and _name_search
  l10n_br_fiscal/models/data_abstract.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1441 [12.0][l10n_br_purchase_stock] 12.0 pre commit l10n_br_purchase_stock
  .pre-commit-config.yaml
  l10n_br_purchase_stock/__manifest__.py
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_purchase_stock/models/purchase_order.py
  l10n_br_purchase_stock/models/purchase_order_line.py
  l10n_br_purchase_stock/models/res_company.py
  l10n_br_purchase_stock/models/res_config_settings.py
  l10n_br_purchase_stock/models/stock_move.py
  l10n_br_purchase_stock/models/stock_rule.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock_lp.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock_sn.py
  l10n_br_purchase_stock/views/purchase_order.xml
  l10n_br_purchase_stock/views/res_company_view.xml
  l10n_br_purchase_stock/views/res_config_settings.xml
  l10n_br_purchase_stock/wizards/stock_invocing_onshipping.py
Labels: bot is merging ⏳

#1240 [12.0][IMP] Dado de demonstração de produtos parametrizados
  l10n_br_account_payment_order/tests/test_base_class.py
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/demo/icms_tax_definition_demo.xml
  l10n_br_fiscal/demo/product_demo.xml
  l10n_br_fiscal/hooks.py
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#1459 [12.0][l10n_br_purchase] 12.0 pre commit l10n_br_purchase
  .pre-commit-config.yaml
  l10n_br_purchase/__manifest__.py
  l10n_br_purchase/data/company.xml
  l10n_br_purchase/demo/company.xml
  l10n_br_purchase/demo/fiscal_operation_generic.xml
  l10n_br_purchase/demo/fiscal_operation_simple.xml
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/demo/product.xml
  l10n_br_purchase/hooks.py
  l10n_br_purchase/migrations/12.0.2.0.0/pre-migration.py
  l10n_br_purchase/models/account_invoice.py
  l10n_br_purchase/models/account_invoice_line.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/models/res_company.py
  l10n_br_purchase/reports/purchase_order_templates.xml
  l10n_br_purchase/reports/purchase_report.py
  l10n_br_purchase/reports/purchase_report_views.xml
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase/tests/test_l10n_br_purchase_lp.py
  l10n_br_purchase/tests/test_l10n_br_purchase_sn.py
  l10n_br_purchase/views/purchase_view.xml
  l10n_br_purchase/views/res_company_view.xml
  l10n_br_purchase_stock/views/purchase_order.xml
Labels: approved, bot is merging ⏳, needs review

#1460 [12.0][l10n_br_nfse] 12.0 pre commit l10n_br_nfse
  .pre-commit-config.yaml
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/constants/nfse.py
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/demo/product_demo.xml
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/product_template.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/report/danfse.xml
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/document_view.xml
  l10n_br_nfse/views/product_product_view.xml
  l10n_br_nfse/views/product_template_view.xml
  l10n_br_nfse/views/res_company_view.xml
Labels: approved, bot is merging ⏳, needs review

#1461 [12.0][l10n_br_contract] 12.0 pre commit l10n_br_contract
  .pre-commit-config.yaml
  l10n_br_contract/__manifest__.py
  l10n_br_contract/data/company.xml
  l10n_br_contract/demo/company.xml
  l10n_br_contract/demo/contract_demo.xml
  l10n_br_contract/models/contract_contract.py
  l10n_br_contract/models/contract_line.py
  l10n_br_contract/models/res_company.py
  l10n_br_contract/readme/HISTORY.rst
  l10n_br_contract/tests/test_l10n_br_contract.py
  l10n_br_contract/views/contract_line.xml
  l10n_br_contract/views/contract_view.xml
  l10n_br_contract/views/res_company.xml
Labels: approved, bot is merging ⏳, needs review

#1469 [12.0][l10n_br_mis_report] DRE: bale->balp everywhere
  l10n_br_mis_report/data/mis_report_dre.xml
Labels: approved, bot is merging ⏳, bug, needs review

#1464 [12.0][l10n_br_hr_contract] 12.0 pre commit l10n_br_hr_contract
  .pre-commit-config.yaml
  l10n_br_hr_contract/__manifest__.py
  l10n_br_hr_contract/data/hr_contract_admission_type_data.xml
  l10n_br_hr_contract/data/hr_contract_labor_bond_type_data.xml
  l10n_br_hr_contract/data/hr_contract_labor_regime_data.xml
  l10n_br_hr_contract/data/hr_contract_notice_termination_data.xml
  l10n_br_hr_contract/data/hr_contract_resignation_cause_data.xml
  l10n_br_hr_contract/data/hr_contract_salary_unit_data.xml
  l10n_br_hr_contract/models/hr_contract.py
  l10n_br_hr_contract/models/hr_contract_admission_type.py
  l10n_br_hr_contract/models/hr_contract_labor_bond_type.py
  l10n_br_hr_contract/models/hr_contract_labor_regime.py
  l10n_br_hr_contract/models/hr_contract_labor_resignation_cause.py
  l10n_br_hr_contract/models/hr_contract_labor_salary_unit.py
  l10n_br_hr_contract/readme/HISTORY.rst
  l10n_br_hr_contract/tests/test_l10n_br_hr_contract.py
  l10n_br_hr_contract/views/hr_contract_view.xml
Labels: approved, bot is merging ⏳, needs review

#1275 [12.0][IMP] Fields for NF-e of SN
  l10n_br_nfe/models/document_line.py
Labels: bot is merging ⏳

#1458 [12.0][l10n_br_account] 12.0 pre commit l10n_br_account
  .pre-commit-config.yaml
  l10n_br_account/__manifest__.py
  l10n_br_account/data/account_tax_group.xml
  l10n_br_account/data/account_tax_template.xml
  l10n_br_account/demo/res_users_demo.xml
  l10n_br_account/hooks.py
  l10n_br_account/migrations/12.0.4.0.0/pre-migration.py
  l10n_br_account/migrations/12.0.7.0.0/pre-migration.py
  l10n_br_account/models/account_document_line_mixin.py
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/account_journal.py
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/account_tax.py
  l10n_br_account/models/account_tax_group.py
  l10n_br_account/models/account_tax_template.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_account/models/fiscal_operation.py
  l10n_br_account/models/fiscal_operation_line.py
  l10n_br_account/models/fiscal_tax.py
  l10n_br_account/models/fiscal_tax_group.py
  l10n_br_account/readme/ROADMAP.rst
  l10n_br_account/report/account_invoice_report.py
  l10n_br_account/report/account_invoice_report_view.xml
  l10n_br_account/tests/test_account_taxes.py
  l10n_br_account/tests/test_customer_invoice_dummy.py
  l10n_br_account/tests/test_supplier_invoice_dummy.py
  l10n_br_account/views/account_invoice_line_view.xml
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_account/views/account_tax_template_view.xml
  l10n_br_account/views/account_tax_view.xml
  l10n_br_account/views/document_line_view.xml
  l10n_br_account/views/document_view.xml
  l10n_br_account/views/fiscal_invoice_line_view.xml
  l10n_br_account/views/fiscal_invoice_view.xml
  l10n_br_account/views/fiscal_operation_line_view.xml
  l10n_br_account/views/fiscal_operation_view.xml
  l10n_br_account/views/l10n_br_account_action.xml
  l10n_br_account/views/l10n_br_account_menu.xml
  l10n_br_account/wizards/account_invoice_refund.py
  l10n_br_account/wizards/account_invoice_refund_view.xml
  l10n_br_account/wizards/base_wizard_mixin.py
  l10n_br_account/wizards/wizard_document_cancel.py
  l10n_br_account/wizards/wizard_document_invalidate.py
  l10n_br_account/wizards/wizard_document_status.xml
Labels: bot is merging ⏳, help wanted

#1462 [12.0][l10n_br_resource] 12.0 pre commit l10n_br_resource
  .pre-commit-config.yaml
  l10n_br_resource/models/resource_calendar.py
  l10n_br_resource/models/resource_calendar_leaves.py
  l10n_br_resource/readme/HISTORY.rst
  l10n_br_resource/tests/test_resource_calendar.py
  l10n_br_resource/tools/__init__.py
  l10n_br_resource/tools/brazil_all_holidays_set.py
  l10n_br_resource/views/resource_calendar_leaves_view.xml
  l10n_br_resource/views/resource_calendar_menu.xml
  l10n_br_resource/views/resource_calendar_view.xml
  l10n_br_resource/wizards/workalendar_holiday_import_views.xml
  l10n_br_resource/wizards/workalendar_holiday_import_wizard.py
Labels: approved, bot is merging ⏳, needs review

#1463 [12.0][l10n_br_hr] 12.0 pre commit l10n_br_hr
  .pre-commit-config.yaml
  l10n_br_hr/data/dependent_type_data.xml
  l10n_br_hr/data/hr_deficiency_data.xml
  l10n_br_hr/data/hr_educational_attainment_data.xml
  l10n_br_hr/data/hr_ethnicity_data.xml
  l10n_br_hr/demo/hr_employee_dependent_demo.xml
  l10n_br_hr/models/data_abstract.py
  l10n_br_hr/models/hr_employee.py
  l10n_br_hr/models/hr_employee_dependent.py
  l10n_br_hr/models/res_partner.py
  l10n_br_hr/tests/test_hr_employee_dependent.py
  l10n_br_hr/views/hr_employee_dependent_view.xml
  l10n_br_hr/views/hr_employee_view.xml
  l10n_br_hr/views/hr_job_view.xml
  l10n_br_hr/views/inherited_hr_contract.xml
  l10n_br_hr/views/l10n_br_hr_cbo_view.xml
  l10n_br_hr/views/res_company_view.xml
Labels: bot is merging ⏳, needs review

#1465 [12.0][l10n_br_portal] 12.0 pre commit l10n_br_portal
  .eslintrc.yml
  .pre-commit-config.yaml
  l10n_br_portal/__manifest__.py
  l10n_br_portal/controllers/portal.py
  l10n_br_portal/demo/res_users_demo.xml
  l10n_br_portal/readme/CONTRIBUTORS.rst
  l10n_br_portal/readme/ROADMAP.rst
  l10n_br_portal/static/src/js/l10n_br_portal.js
  l10n_br_portal/static/src/js/l10n_br_portal_tour.js
  l10n_br_portal/tests/test_load_process.py
  l10n_br_portal/views/assets.xml
  l10n_br_portal/views/portal_templates.xml
Labels: approved, bot is merging ⏳, needs review

#1482 [12.0][FIX] Fields and functions names (l10n_br_nfse_paulistana)
  l10n_br_base/tests/test_other_ie.py
  l10n_br_nfse_paulistana/models/document.py
Labels: approved, bot is merging ⏳

#1477 [12.0][FIX][BUG] Method _name_search for fiscal data abstract.
  l10n_br_fiscal/models/data_abstract.py
Labels: approved, bot is merging ⏳

#1481 [12.0][FIX] Compute field own_number_without_zfill should keep right zeros.
  l10n_br_account_payment_order/models/account_move_line.py
Labels: approved, bot is merging ⏳, needs review

#1485 [12.0][l10n_br_product_contract] 12.0 pre commit l10n_br_product_cont…
  .pre-commit-config.yaml
  l10n_br_product_contract/__manifest__.py
  l10n_br_product_contract/demo/contract_template.xml
  l10n_br_product_contract/demo/product.xml
  l10n_br_product_contract/demo/sale_order.xml
  l10n_br_product_contract/models/sale_order.py
  l10n_br_product_contract/models/sale_order_line.py
  l10n_br_product_contract/readme/CONTRIBUTORS.rst
  l10n_br_product_contract/readme/USAGE.rst
  l10n_br_product_contract/tests/test_l10n_br_product_contract.py
Labels: approved, bot is merging ⏳

#1487 [12.0][FIX] account.payment.post() method being called recursively
  l10n_br_account_payment_order/models/account_payment.py
Labels: approved, bot is merging ⏳
