Repository OCA/l10n-brazil, pull requests merged in 2021-04, with the labels that each got.

#1261 [FIX] Sale Order create invoice button attr
  l10n_br_sale_stock/models/sale_order.py
Labels: 12.0, approved, bot is merging ⏳, bug

#1223 [12.0][ADD] Calculation of MVA
  l10n_br_fiscal/models/tax.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1109 [12.0] l10n_br_sale partial deliveries
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_sale/models/sale_order_line.py
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#1266 [FIX] l10n_br_fiscal migration scripts
  l10n_br_fiscal/migrations/12.0.4.1.0/pre-migration.py
  l10n_br_fiscal/migrations/12.0.4.2.0/pre-migration.py
Labels: approved, bot is merging ⏳

#1262 Use float_is_zero method in compute_taxes
  l10n_br_fiscal/models/tax.py
Labels: 12.0, approved, bot is merging ⏳

#1230 [12.0][FIX] Sale line discount
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/security/l10n_br_sale_security.xml
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review, ready to merge

#1235 [12.0][FIX] Function _amount_by_group
  l10n_br_sale/models/sale_order.py
Labels: 12.0, approved, bot is merging ⏳

#1268 [12.0] Refactoring module l10n_br_contract
  l10n_br_contract/demo/contract_demo.xml
  l10n_br_contract/models/__init__.py
  l10n_br_contract/models/account_invoice_line.py
  l10n_br_contract/models/contract_contract.py
  l10n_br_contract/models/contract_line.py
  l10n_br_contract/models/document_line.py
  l10n_br_contract/tests/test_l10n_br_contract.py
  l10n_br_contract/views/contract_view.xml
Labels: approved, bot is merging ⏳, needs review, ready to merge

#1228 [12.0][FIX] Specific module order installation to run the tests for l10n_br_sale_stock.
  l10n_br_sale_stock/tests/test_sale_stock.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review, ready to merge

#1255 Fix/generated key oca
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_nfse/models/document.py
  requirements.txt
Labels: 12.0, approved, bot is merging ⏳, bug, needs review, ready to merge

#1201 [12.0][ADD] Fiscal Operations
  l10n_br_fiscal/data/operation_data.xml
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review

#1219 [12.0][IMP] Tax Definitions
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: 12.0, approved, bot is merging ⏳, enhancement, needs review

#1274 Valor de mercadoria sem desconto
  l10n_br_delivery/tests/test_delivery_inverse_amount.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/wizards/l10n_br_account_invoice_costs_ratio.py
  l10n_br_repair/migrations/12.0.2.1.0/pre-migration.py
  l10n_br_repair/models/repair_order.py
  l10n_br_repair/views/repair_order.xml
  l10n_br_sale/migrations/12.0.4.1.0/pre-migration.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/report/sale_report_templates.xml
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#1269 [12.0] Account Invoice new and purchase document type
  l10n_br_account/models/account_invoice.py
  l10n_br_purchase/models/__init__.py
  l10n_br_purchase/models/account_invoice.py
  l10n_br_purchase/models/account_invoice_line.py
Labels: approved, bot is merging ⏳

#1284 [REF] Remove "error" word to test method names
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
Labels: approved, bot is merging ⏳

#1258 Linha de operação fiscal para não contribuinte
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_repair/tests/test_l10n_br_repair.py
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#1285 [FIX] Inutilização em produção
  l10n_br_nfe/models/document_invalidate_number.py
Labels: 12.0, approved, bot is merging ⏳, bug, needs review

#1270 [12.0][IMP] Variables for ICMSSN
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: 12.0, approved, bot is merging ⏳, needs review, ready to merge

#1304 force unique NFe schema stacked field labels
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#1277 [IMP] Mock zip tests
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
Labels: approved, bot is merging ⏳, ready to merge

#1294 [12.0][FIX] l10n_br_base and l10n_br_zip Contact Form
  l10n_br_base/views/res_partner_address_view.xml
  l10n_br_base/views/res_partner_view.xml
Labels: 12.0, approved, bot is merging ⏳, bug, ready to merge

#1307 [12.0][ADD] Base and value ICMSST export
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#1309 Corrige o valor do vProd nas linhas da NFe
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#1308 Remove invisible attr in IE fields
  l10n_br_fiscal/views/res_partner_view.xml
Labels: 12.0, approved, bot is merging ⏳, needs review

#1316 [12.0] [FIX] Danfse layout
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳
