Repository OCA/l10n-brazil, pull requests merged in 2022-08, with the labels that each got.

#2051 [REF] brcobranca: state abbreviation in address
  l10n_br_account_payment_brcobranca/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2054 [12.0][IMP] l10n_br_account_payment_brcobranca: adding other ways to set brcobranca url
  l10n_br_account_payment_brcobranca/constants/br_cobranca.py
  l10n_br_account_payment_brcobranca/models/account_invoice.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, 12.0, bot is merging ⏳

#2055 [12.0][ADD] Invoice details button in fiscal document
  l10n_br_account/models/account_invoice.py
  l10n_br_account/views/fiscal_invoice_view.xml
Labels: approved, 12.0, bot is merging ⏳

#2060 [14.0][FIX] added ind_final in purchase order form
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, bot is merging ⏳, 14.0

#2058 [12.0][FIX] Missing 1 required positional argument in get_brcobranca_api_url
  l10n_br_account_payment_brcobranca/models/account_move_line.py
Labels: bug, approved, 12.0, bot is merging ⏳

#2059 [12.0][FIX] added ind_final in purchase order form
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, 12.0, bot is merging ⏳

#2065 [12.0] l10n_br_fiscal: Arruma condição para aplicação do Difal
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#2066 [14.0] l10n_br_fiscal: Arruma condição para aplicação do Difal
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳, 14.0

#2063 [14.0][l10n_br_nfe_spec][FIX] nfe Float fixes using latest generateds-odoo
  l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
Labels: approved, bot is merging ⏳, 14.0

#2064 [12.0][l10n_br_nfe_spec][FIX] nfe Float fixes using latest generateds-odoo
  l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
Labels: approved, 12.0, bot is merging ⏳

#2069 [12.0][l10n_br_nfe]: Now imports nfe40_transporta as a partner
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2070 [14.0][l10n_br_nfe]: Now imports nfe40_transporta as a partner
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/readme/CONTRIBUTORS.rst
Labels: bot is merging ⏳

#2067 [12.0][FIX] Correção da definição do add_to_base no fiscal.tax
  l10n_br_fiscal/models/tax.py
Labels: bug, approved, 12.0, bot is merging ⏳

#2062 [14.0][FIX] payment_pagseguro: add sudo to get pagseguro_token
  payment_pagseguro/models/payment_acquirer.py
Labels: approved, bot is merging ⏳

#2068 [14.0][FIX] Correção da definição do add_to_base no fiscal.tax
  l10n_br_fiscal/models/tax.py
Labels: bug, approved, bot is merging ⏳, 14.0

#2050 [14.0][FIX] fiscal dummy in new companies
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: approved, bot is merging ⏳, 14.0

#2074 [14.0][ADD] Read permission for partner.profile
  l10n_br_sale/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2076 [14.0][l10n_br_account][FIX] ensure dummy fisc doc is used for entry moves
  l10n_br_account/models/account_invoice.py
Labels: bug, approved, bot is merging ⏳, 14.0

#2077 [12.0][IMP] l10n_br_fiscal move cnae_id from l10n_br_nfse
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/views/document_line_view.xml
Labels: approved, bot is merging ⏳

#2081 [14.0][FIX] payment_order: campos obrigatórios apenas quando for cobrança.
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳

#2079 [12.0] Adiciona campos do ICMS DIFAL nos totais do documento fiscal
  l10n_br_fiscal/views/document_view.xml
Labels: approved, 12.0, bot is merging ⏳

#2080 [14.0] Adiciona campos do ICMS DIFAL nos totais do documento fiscal
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳, 14.0

#2078 [12.0][IMP] l10n_br_contract: add brazilian fiscal data on contract line form
  l10n_br_contract/models/contract_contract.py
  l10n_br_contract/models/contract_line.py
  l10n_br_contract/models/res_company.py
  l10n_br_contract/views/contract_line.xml
  l10n_br_contract/views/contract_view.xml
  l10n_br_contract/views/res_company.xml
Labels: approved, bot is merging ⏳

#2086 [12.0][FIX] l10n_br_contract: fix contract form view
  l10n_br_contract/views/contract_line.xml
Labels: approved, bot is merging ⏳

#2090 [FIX][14.0] payment_order: Ignorar métodos do CNAB Cobrança, quando for Pagamentos.
  l10n_br_account_payment_order/models/account_move.py
  l10n_br_account_payment_order/models/account_payment_mode.py
Labels: approved, bot is merging ⏳

#2089 [14.0][FIX] l10n_br_account: remove invoice post call
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2087 [12.0][IMP] l10n_br_account: add company filter in _account_taxes
  l10n_br_account/models/account_tax.py
  l10n_br_account/models/fiscal_tax.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
Labels: approved, 12.0, bot is merging ⏳

#2093 [14.0][IMP] l10n_br_account: add company filter in _account_taxes - port 2087
  l10n_br_account/models/account_tax.py
  l10n_br_account/models/fiscal_tax.py
Labels: approved, bot is merging ⏳, 14.0

#2099 [14.0][NEW] COA POS Accounts
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa_generic_template_post.xml
  l10n_br_coa_simple/data/account.account.template.csv
  l10n_br_coa_simple/data/l10n_br_coa_simple_template_post.xml
Labels: needs review, enhancement, approved, bot is merging ⏳, 14.0

#2094 [14.0][MIG] l10n_br_purchase_request
  l10n_br_purchase_request/README.rst
  l10n_br_purchase_request/__init__.py
  l10n_br_purchase_request/__manifest__.py
  l10n_br_purchase_request/readme/CONFIGURE.rst
  l10n_br_purchase_request/readme/CONTRIBUTORS.rst
  l10n_br_purchase_request/readme/CREDITS.rst
  l10n_br_purchase_request/readme/DESCRIPTION.rst
  l10n_br_purchase_request/readme/INSTALL.rst
  l10n_br_purchase_request/readme/USAGE.rst
  l10n_br_purchase_request/static/description/icon.png
  l10n_br_purchase_request/static/description/index.html
  l10n_br_purchase_request/tests/__init__.py
  l10n_br_purchase_request/tests/test_l10n_br_purchase_request.py
  l10n_br_purchase_request/wizards/__init__.py
  l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.py
  setup/l10n_br_purchase_request/odoo/addons/l10n_br_purchase_request
  setup/l10n_br_purchase_request/setup.py
Labels: bot is merging ⏳

#2091 [12.0][ADD] l10n_br_purchase_request
  l10n_br_purchase_request/README.rst
  l10n_br_purchase_request/__init__.py
  l10n_br_purchase_request/__manifest__.py
  l10n_br_purchase_request/readme/CONFIGURE.rst
  l10n_br_purchase_request/readme/CONTRIBUTORS.rst
  l10n_br_purchase_request/readme/CREDITS.rst
  l10n_br_purchase_request/readme/DESCRIPTION.rst
  l10n_br_purchase_request/readme/INSTALL.rst
  l10n_br_purchase_request/readme/USAGE.rst
  l10n_br_purchase_request/static/description/icon.png
  l10n_br_purchase_request/static/description/index.html
  l10n_br_purchase_request/tests/__init__.py
  l10n_br_purchase_request/tests/test_l10n_br_purchase_request.py
  l10n_br_purchase_request/wizards/__init__.py
  l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.py
  oca_dependencies.txt
  setup/l10n_br_purchase_request/odoo/addons/l10n_br_purchase_request
  setup/l10n_br_purchase_request/setup.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#2100 [ADD] NFC-e constant [MOV] FISCAL_PAYMENT_MODE
  l10n_br_account_nfe/models/account_payment_mode.py
  l10n_br_fiscal/constants/fiscal.py
Labels: approved, bot is merging ⏳, 14.0

#2073 [14.0][spec_driven_model] refactor importante, fixes e testes antes do xsdata
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_related.py
  l10n_br_nfe/tests/test_nfe_structure.py
  spec_driven_model/hooks.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/readme/CONFIGURE.rst
  spec_driven_model/readme/DESCRIPTION.rst
  spec_driven_model/readme/HISTORY.rst
  spec_driven_model/readme/INSTALL.rst
  spec_driven_model/readme/ROADMAP.rst
  spec_driven_model/readme/USAGE.rst
Labels: approved, bot is merging ⏳, 14.0

#2082 [12.0][spec_driven_model] refactor importante, fixes e testes antes do xsdata
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_related.py
  l10n_br_nfe/tests/test_nfe_structure.py
  spec_driven_model/hooks.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/readme/CONFIGURE.rst
  spec_driven_model/readme/DESCRIPTION.rst
  spec_driven_model/readme/HISTORY.rst
  spec_driven_model/readme/INSTALL.rst
  spec_driven_model/readme/ROADMAP.rst
  spec_driven_model/readme/USAGE.rst
Labels: approved, ready to merge, bot is merging ⏳
