Repository OCA/l10n-brazil, pull requests merged in 2022-11, with the labels that each got.

#2219 [14.0][FIX] l10n_br_fiscal: add migration script to install l10n_br_fiscal_closing
  l10n_br_fiscal/migrations/14.0.9.0.0/pre-migration.py
Labels: bot is merging ⏳

#2221 [14.0][FIX] Update dotfiles to fix pre-commit issue
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .t2d.yml
  README.md
Labels: bot is merging ⏳

#2218 [14.0][REF] l10n_br_account_payment_brcobranca: Model Check
  l10n_br_account_payment_brcobranca/models/account_journal.py
  l10n_br_account_payment_brcobranca/wizard/import_statement.py
Labels: approved, bot is merging ⏳

#2224 [FIX] expiration date field invalid date
  l10n_br_fiscal/models/certificate.py
Labels: approved, bot is merging ⏳

#2227 [14.0][FIX] link para o flake8 quebrado
  .pre-commit-config.yaml
Labels: approved, bot is merging ⏳

#2228 [14.0][FIX] l10n_br_account: not show document_number for non-fiscal invoices
  l10n_br_account/models/account_invoice.py
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#1889 [12.0] Informar o nfe40_CNPJ/nfe40_CPF do parent_id caso esses campos estejam em branco
  l10n_br_nfe/models/res_partner.py
Labels: approved, 12.0, bot is merging ⏳

#2233 [12.0] Correções para corrigir campos na NF-e
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/models/spec_mixin.py
  l10n_br_nfe/tests/test_nfe_import.py
Labels: approved, 12.0, bot is merging ⏳

#1812 [12.0] Adicionado mapeamento para o local de entrega na NF-e
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_nfe_import_wizard.py
Labels: approved, 12.0, bot is merging ⏳

#2238 [12.0][payment_pagseguro] desativa os testes que estão blocando o repo...
  .github/workflows/test.yml
  requirements.txt
  spec_driven_model/__manifest__.py
  test-requirements.txt
Labels: approved, bot is merging ⏳
