Repository OCA/l10n-brazil, pull requests merged in 2022-01, with the labels that each got.

#1751 [14.0][MIG] l10n_br_stock
  l10n_br_stock/README.rst
  l10n_br_stock/__init__.py
  l10n_br_stock/__manifest__.py
  l10n_br_stock/demo/res_users_demo.xml
  l10n_br_stock/demo/stock_inventory_demo.xml
  l10n_br_stock/demo/stock_location_demo.xml
  l10n_br_stock/hooks.py
  l10n_br_stock/i18n/l10n_br_stock.pot
  l10n_br_stock/i18n/pt_BR.po
  l10n_br_stock/models/__init__.py
  l10n_br_stock/models/stock.py
  l10n_br_stock/readme/CONFIGURE.rst
  l10n_br_stock/readme/CONTRIBUTORS.rst
  l10n_br_stock/readme/DESCRIPTION.rst
  l10n_br_stock/readme/INSTALL.rst
  l10n_br_stock/readme/ROADMAP.rst
  l10n_br_stock/readme/USAGE.rst
  l10n_br_stock/static/description/icon.png
  l10n_br_stock/static/description/index.html
  l10n_br_stock/views/stock_view.xml
  setup/l10n_br_stock/odoo/addons/l10n_br_stock
  setup/l10n_br_stock/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 14.0

#1752 [14.0][MIG] l10n_br_resource
  l10n_br_resource/README.rst
  l10n_br_resource/__init__.py
  l10n_br_resource/__manifest__.py
  l10n_br_resource/i18n/l10n_br_resource.pot
  l10n_br_resource/i18n/pt_BR.po
  l10n_br_resource/models/__init__.py
  l10n_br_resource/models/resource_calendar.py
  l10n_br_resource/models/resource_calendar_leaves.py
  l10n_br_resource/readme/CONFIGURE.rst
  l10n_br_resource/readme/CONTRIBUTORS.rst
  l10n_br_resource/readme/CREDITS.rst
  l10n_br_resource/readme/DESCRIPTION.rst
  l10n_br_resource/readme/HISTORY.rst
  l10n_br_resource/readme/INSTALL.rst
  l10n_br_resource/readme/ROADMAP.rst
  l10n_br_resource/readme/USAGE.rst
  l10n_br_resource/security/ir.model.access.csv
  l10n_br_resource/static/description/icon.png
  l10n_br_resource/static/description/icon.svg.oca
  l10n_br_resource/static/description/index.html
  l10n_br_resource/tests/__init__.py
  l10n_br_resource/tests/test_resource_calendar.py
  l10n_br_resource/tools/__init__.py
  l10n_br_resource/tools/brazil_all_holidays_set.py
  l10n_br_resource/views/resource_calendar_leaves_view.xml
  l10n_br_resource/views/resource_calendar_menu.xml
  l10n_br_resource/views/resource_calendar_view.xml
  l10n_br_resource/wizards/__init__.py
  l10n_br_resource/wizards/workalendar_holiday_import_views.xml
  l10n_br_resource/wizards/workalendar_holiday_import_wizard.py
  requirements.txt
  setup/l10n_br_resource/odoo/addons/l10n_br_resource
  setup/l10n_br_resource/setup.py
Labels: approved, migration, bot is merging ⏳, 14.0

#1755 [12.0][IMP] l10n_br_delivery: pre-commit
  .pre-commit-config.yaml
  l10n_br_delivery/__manifest__.py
  l10n_br_delivery/data/account_incoterms_data.xml
  l10n_br_delivery/data/res_config_settings_data.xml
  l10n_br_delivery/demo/l10n_br_delivery_demo.xml
  l10n_br_delivery/demo/sale_order_demo.xml
  l10n_br_delivery/migrations/12.0.1.0.0/pre-migration.py
  l10n_br_delivery/models/account_incoterms.py
  l10n_br_delivery/models/delivery_carrier.py
  l10n_br_delivery/models/fiscal_document_mixin.py
  l10n_br_delivery/models/sale_order.py
  l10n_br_delivery/models/stock_picking.py
  l10n_br_delivery/models/vehicle.py
  l10n_br_delivery/readme/HISTORY.rst
  l10n_br_delivery/tests/test_delivery_inverse_amount.py
  l10n_br_delivery/views/account_incoterms_view.xml
  l10n_br_delivery/views/delivery_carrier_views.xml
  l10n_br_delivery/views/l10n_br_delivery_view.xml
  l10n_br_delivery/views/sale_order_view.xml
  l10n_br_delivery/views/stock_picking_view.xml
  l10n_br_hr/__manifest__.py
  l10n_br_hr_contract/__manifest__.py
  l10n_br_nfse_paulistana/__manifest__.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1759 [14.0][l10n_br_fiscal][FORWARD PORT] port pr 1652
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: needs review, approved, bot is merging ⏳, 14.0

#1467 [12.0][l10n_br_website_sale_delivery] 12.0 pre commit l10n_br_website_sale_delivery
  .pre-commit-config.yaml
  l10n_br_website_sale_delivery/__manifest__.py
  l10n_br_website_sale_delivery/controllers/main.py
  l10n_br_website_sale_delivery/readme/HISTORY.rst
  l10n_br_website_sale_delivery/static/src/js/l10n_br_website_sale_delivery_tour.js
  l10n_br_website_sale_delivery/tests/test_website_sale_tour.py
  l10n_br_website_sale_delivery/views/assets.xml
  l10n_br_website_sale_delivery/views/website_sale_delivery_templates.xml
Labels: needs review, help wanted, approved, ready to merge, 12.0, bot is merging ⏳

#1760 [12.0][l10n_br_fiscal][BACKPORT] backport pr 1759
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1754 [12.0][IMP] l10n_br_nfse_paulistana: pre commit
  .pre-commit-config.yaml
  l10n_br_nfse_paulistana/__manifest__.py
  l10n_br_nfse_paulistana/constants/paulistana.py
  l10n_br_nfse_paulistana/models/document.py
  l10n_br_nfse_paulistana/models/res_company.py
  l10n_br_nfse_paulistana/tests/test_fiscal_document_nfse_paulistana.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1749 [14.0][MIG] l10n br zip
  l10n_br_zip/README.rst
  l10n_br_zip/__init__.py
  l10n_br_zip/__manifest__.py
  l10n_br_zip/i18n/l10n_br_zip.pot
  l10n_br_zip/i18n/pt_BR.po
  l10n_br_zip/migrations/14.0.1.0.0/pre-migration.py
  l10n_br_zip/models/__init__.py
  l10n_br_zip/models/format_address_mixin.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/models/res_config_settings.py
  l10n_br_zip/readme/CONFIGURE.rst
  l10n_br_zip/readme/CONTRIBUTORS.rst
  l10n_br_zip/readme/DESCRIPTION.rst
  l10n_br_zip/readme/HISTORY.rst
  l10n_br_zip/readme/INSTALL.rst
  l10n_br_zip/readme/ROADMAP.rst
  l10n_br_zip/readme/USAGE.rst
  l10n_br_zip/security/ir.model.access.csv
  l10n_br_zip/static/description/icon.png
  l10n_br_zip/static/description/index.html
  l10n_br_zip/static/description/l10n_br_zip_1.png
  l10n_br_zip/tests/__init__.py
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
  l10n_br_zip/views/l10n_br_zip_view.xml
  l10n_br_zip/views/res_config_settings_view.xml
  l10n_br_zip/views/res_partner_address_view.xml
  l10n_br_zip/wizard/__init__.py
  l10n_br_zip/wizard/l10n_br_zip_search.py
  l10n_br_zip/wizard/l10n_br_zip_search_view.xml
  requirements.txt
  setup/l10n_br_zip/odoo/addons/l10n_br_zip
  setup/l10n_br_zip/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 14.0

#1753 [12.0][IMP] l10n_br_nfse_issnet pre-commit
  .pre-commit-config.yaml
  l10n_br_nfse_issnet/__manifest__.py
  l10n_br_nfse_issnet/constants/issnet.py
  l10n_br_nfse_issnet/demo/city_taxation_code_demo.xml
  l10n_br_nfse_issnet/models/l10n_br_fiscal_document.py
  l10n_br_nfse_issnet/models/res_company.py
  l10n_br_nfse_issnet/readme/CONTRIBUTORS.rst
  l10n_br_nfse_issnet/tests/test_fiscal_document_nfse_issnet.py
Labels: needs review, approved, 12.0, bot is merging ⏳

#1766 [14.0][FIX] _search_name method in data.abstract
  l10n_br_fiscal/models/data_abstract.py
Labels: needs review, approved, bot is merging ⏳, 14.0

#1768 [14.0][FIX] ICMS Origin wrong attrs
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: needs review, approved, bot is merging ⏳, 14.0

#1772 [14.0][MIG][l10n_br_mis_report]
  l10n_br_mis_report/README.rst
  l10n_br_mis_report/__init__.py
  l10n_br_mis_report/__manifest__.py
  l10n_br_mis_report/data/mis_report_bp.xml
  l10n_br_mis_report/data/mis_report_dre.xml
  l10n_br_mis_report/data/mis_report_styles.xml
  l10n_br_mis_report/i18n/l10n_br_mis_report.pot
  l10n_br_mis_report/i18n/pt_BR.po
  l10n_br_mis_report/readme/CONFIGURE.rst
  l10n_br_mis_report/readme/CONTRIBUTORS.rst
  l10n_br_mis_report/readme/DESCRIPTION.rst
  l10n_br_mis_report/readme/HISTORY.rst
  l10n_br_mis_report/readme/INSTALL.rst
  l10n_br_mis_report/readme/ROADMAP.rst
  l10n_br_mis_report/readme/USAGE.rst
  l10n_br_mis_report/static/description/bp.png
  l10n_br_mis_report/static/description/dre.png
  l10n_br_mis_report/static/description/icon.png
  l10n_br_mis_report/static/description/index.html
  oca_dependencies.txt
Labels: needs review, approved, migration, bot is merging ⏳, 14.0

#1466 [12.0][l10n_br_website_sale] 12.0 pre commit l10n_br_website_sale
  .pre-commit-config.yaml
  l10n_br_fiscal/i18n/l10n_br_fiscal.pot
  l10n_br_website_sale/__manifest__.py
  l10n_br_website_sale/controllers/main.py
  l10n_br_website_sale/static/src/js/l10n_br_address.js
  l10n_br_website_sale/static/src/js/l10n_br_website_sale_tour.js
  l10n_br_website_sale/templates/portal_templates.xml
  l10n_br_website_sale/tests/test_sale_process.py
  l10n_br_website_sale/views/assets.xml
  requirements.txt
Labels: needs review, help wanted, approved, bot is merging ⏳

#1779 [12.0][FIX] Exibição do nome do arquivo do certificado digital.
  l10n_br_fiscal/models/certificate.py
  l10n_br_fiscal/views/certificate_view.xml
Labels: approved, bot is merging ⏳

#1780 [FIX] typo in NFe Document Related
  l10n_br_nfe/models/document_related.py
Labels: approved, bot is merging ⏳

#1774 [14.0][FIX] Company street_number
  l10n_br_base/__manifest__.py
  l10n_br_base/data/res_country_data.xml
  l10n_br_base/migrations/14.0.2.0.0/post-migration.py 
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
Labels: approved, bot is merging ⏳

#1781 [12.0][FIX] broken logic when using 'cpf' -> always raises
  l10n_br_base/models/res_partner.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_fiscal/models/document_related.py
Labels: approved, 12.0, bot is merging ⏳

#1787 [12.0][FIX] Teste com o contexto/fusohorario da data errado
  l10n_br_account_payment_order/tests/test_base_class.py
Labels: approved, bot is merging ⏳

#1790 [14.0] Rename line_ids to fiscal_line_ids in fiscal document
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/subsequent_document.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_fiscal_document_nfse.py
  l10n_br_fiscal/tests/test_subsequent_operation.py
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳, 14.0

#1791 [14.0][l10n_br_fiscal][REM] remove dead code from before the v12 migration
  l10n_br_fiscal/wizards/l10n_br_account_invoice_costs_ratio.py
Labels: approved, bot is merging ⏳, 14.0
