Repository OCA/l10n-brazil, pull requests merged in 2022-03, with the labels that each got.

#1819 [12.0][IMP] Check document number in use
  l10n_br_fiscal/models/document_serie.py
Labels: approved, 12.0, bot is merging ⏳

#1816 [12.0][l10n_br_account] fixes #1813 skip bad recomputes
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1822 [14.0] Convertido o campo Tipo fiscal no Product Template em um campo property
  l10n_br_fiscal/models/product_template.py
Labels: approved, bot is merging ⏳, 14.0

#1799 [12.0][FIX] Conflito visão do sale_commission com o l10n_br_account
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, 12.0, bot is merging ⏳

#1825 [14.0] Alterações relacionadas ao campo ind_final
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/res_partner.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/operation_view.xml
  l10n_br_fiscal/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#1543 [12.0][NEW] Module l10n_br _stock_account_report - Legal Report Model P7
  l10n_br_fiscal/models/res_config_settings.py
  l10n_br_fiscal/views/res_config_settings_view.xml
  l10n_br_stock_account_report/README.rst
  l10n_br_stock_account_report/__init__.py
  l10n_br_stock_account_report/__manifest__.py
  l10n_br_stock_account_report/i18n/pt_BR.po
  l10n_br_stock_account_report/readme/CONFIGURE.rst
  l10n_br_stock_account_report/readme/CONTRIBUTORS.rst
  l10n_br_stock_account_report/readme/CREDITS.rst
  l10n_br_stock_account_report/readme/DESCRIPTION.rst
  l10n_br_stock_account_report/readme/HISTORY.rst
  l10n_br_stock_account_report/readme/INSTALL.rst
  l10n_br_stock_account_report/readme/USAGE.rst
  l10n_br_stock_account_report/report/l10n_br_p7_model_inventory_report.xml
  l10n_br_stock_account_report/report/l10n_br_p7_model_inventory_report_view.xml
  l10n_br_stock_account_report/static/description/index.html
  l10n_br_stock_account_report/tests/__init__.py
  l10n_br_stock_account_report/tests/test_l10n_br_p7_model_inventory_report.py
  l10n_br_stock_account_report/wizards/__init__.py
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard.py
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard_view.xml
  setup/l10n_br_stock_account_report/odoo/addons/l10n_br_stock_account_report
  setup/l10n_br_stock_account_report/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1823 [12.0] Definida as opções no_create e no_create_edit em alguns campos nas visões
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/document_fiscal_mixin_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/operation_line_view.xml
  l10n_br_fiscal/views/operation_view.xml
  l10n_br_fiscal/views/product_template_view.xml
  l10n_br_fiscal/views/res_company_view.xml
  l10n_br_fiscal/views/res_partner_view.xml
  l10n_br_fiscal/views/tax_definition_view.xml
  l10n_br_fiscal/views/tax_view.xml
Labels: approved, 12.0, bot is merging ⏳

#1828 [12.0][REF+FIX] The account.move.line should be order by Date maturity
  l10n_br_account/models/account_invoice.py
  l10n_br_account_due_list/models/__init__.py
  l10n_br_account_due_list/models/account_move_line.py
  l10n_br_account_payment_order/models/account_move_line.py
Labels: approved, bot is merging ⏳

#1765 [14.0][FORWARD PORT] #1764 Adicionado índices em alguns campos chaves
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
Labels: approved, bot is merging ⏳, 14.0

#1764 [12.0] Adicionado índices em alguns campos chaves
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
Labels: 12.0, bot is merging ⏳

#1827 [12.0][FIX] Concatenate the NFe prefix and key
  l10n_br_nfe/models/document.py
Labels: approved, 12.0, bot is merging ⏳

#1610 [12.0][l10n_br_fiscal] fiscal usability
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/models/cest.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/nbm.py
  l10n_br_fiscal/models/ncm.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/product_template.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/views/operation_line_view.xml
  l10n_br_fiscal/views/operation_view.xml
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: needs review, approved, 12.0, bot is merging ⏳

#1811 [14.0] Convertido o campo origem do ICMS no Product Template em um campo property
  l10n_br_fiscal/models/product_template.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#1804 [12.0][FIX] Cada empresa deve ter o seu próprio fiscal dummy
  l10n_br_account/__init__.py
  l10n_br_account/__manifest__.py
  l10n_br_account/hooks.py
  l10n_br_account/models/__init__.py
  l10n_br_account/models/res_company.py
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_company_fiscal_dummy.py
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/res_company.py
Labels: approved, bot is merging ⏳

#1836 [14.0][FIX] wrong tracking parameter in res.partner ind_final field
  l10n_br_fiscal/models/res_partner.py
Labels: approved, bot is merging ⏳, 14.0

#1837 [14.0[l10n_br_fiscal][FORWARD PORT PR 1814][FIX] document confirmation when the issuer is the partner
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳

#1838 [14.0][l10n_br_fiscal][FORWARD PORT 1804]
  l10n_br_coa_generic/demo/account_journal.xml
  l10n_br_coa_simple/demo/account_journal.xml
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
Labels: approved, bot is merging ⏳

#1840 [14.0][FIX] l10n_br_fiscal: fix view access permission
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#1842 [12.0][FIX] l10n_br_base: dados das cidades brasileiras
  l10n_br_base/data/res.city.csv
Labels: approved, 12.0, bot is merging ⏳

#1843 [14.0][REF] Porte da geração do certificado fake para o erpbrasil.assinatura
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/certificate.py
  l10n_br_fiscal/tests/test_certificate.py
  l10n_br_fiscal/tools/misc.py
  l10n_br_fiscal/views/certificate_view.xml
  l10n_br_nfse/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#1834 [14.0][FIX] Dados demo para os campos fiscal_type e icms_origin
  l10n_br_fiscal/demo/product_demo.xml
Labels: bot is merging ⏳

#1845 [12.0] l10n_br_nfe_spec digits backport
  l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
Labels: approved, bot is merging ⏳

#1846 [12.0][REF] Synchronize Sale Partner Shipping in Stock Picking.
  l10n_br_sale_stock/models/sale_order.py
  l10n_br_sale_stock/tests/test_sale_stock.py
Labels: approved, bot is merging ⏳

#1847 [12.0][FIX] Dados demo para os campos fiscal_type e icms_origin
  l10n_br_fiscal/demo/product_demo.xml
Labels: approved, 12.0, bot is merging ⏳

#1810 [12.0] Convertido o campo origem do ICMS no Product Template em um campo property
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/12.0.24.0.0/pre-migration.py
  l10n_br_fiscal/models/product_template.py
Labels: approved, ready to merge, 12.0, bot is merging ⏳

#1821 [12.0] Convertido o campo Tipo fiscal no Product Template em um campo property
  l10n_br_account/report/account_invoice_report.py
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/12.0.25.0.0/pre-migration.py
  l10n_br_fiscal/models/product_template.py
Labels: approved, ready to merge, 12.0, bot is merging ⏳

#1815 [12.0][IMP] Validação do XML na NF-e
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/test_nfe_xml_validation.py
Labels: approved, ready to merge, bot is merging ⏳

#1849 [12.0][REF] Movido o método de Criação dos Comentários do modulo l10n_br_account para o l10n_br_fiscal
  l10n_br_account/models/account_invoice.py
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳

#1851 [12.0][FIX] fiscal_type property field in Account Invoice Report
  l10n_br_account/report/account_invoice_report.py
Labels: approved, 12.0, bot is merging ⏳

#1852 [12.0][FIX] l10n_br_nfe: Demo data, ID inexistente causava erro no testes/Travis
  l10n_br_nfe/demo/fiscal_document_demo.xml
Labels: approved, bot is merging ⏳

#1844 [13.0][REF] Porte da geração do certificado fake para o erpbrasil.assinatura
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/certificate.py
  l10n_br_fiscal/tests/test_certificate.py
  l10n_br_fiscal/tools/misc.py
  l10n_br_fiscal/views/certificate_view.xml
  requirements.txt
Labels: approved, bot is merging ⏳
