Repository OCA/l10n-brazil, pull requests merged in 2022-09, with the labels that each got.

#2102 [12.0][ADD] Novo módulo l10n_br_sale_commission_stock
  l10n_br_sale_commission_stock/README.rst
  l10n_br_sale_commission_stock/__init__.py
  l10n_br_sale_commission_stock/__manifest__.py
  l10n_br_sale_commission_stock/demo/sale_order.xml
  l10n_br_sale_commission_stock/i18n/l10n_br_sale_commission_stock.pot
  l10n_br_sale_commission_stock/readme/CONFIGURE.rst
  l10n_br_sale_commission_stock/readme/CONTRIBUTORS.rst
  l10n_br_sale_commission_stock/readme/CREDITS.rst
  l10n_br_sale_commission_stock/readme/DESCRIPTION.rst
  l10n_br_sale_commission_stock/readme/HISTORY.rst
  l10n_br_sale_commission_stock/readme/INSTALL.rst
  l10n_br_sale_commission_stock/readme/ROADMAP.rst
  l10n_br_sale_commission_stock/readme/USAGE.rst
  l10n_br_sale_commission_stock/readme/static/description/icon.png
  l10n_br_sale_commission_stock/readme/static/description/index.html
  l10n_br_sale_commission_stock/static/description/index.html
  l10n_br_sale_commission_stock/tests/__init__.py
  l10n_br_sale_commission_stock/tests/test_sale_commission_stock.py
  l10n_br_sale_commission_stock/wizards/__init__.py
  l10n_br_sale_commission_stock/wizards/stock_invoice_onshipping.py
Labels: approved, 12.0, bot is merging ⏳

#1712 [12.0][ADD] l10n_br_sale_invoice_plan module
  l10n_br_sale_invoice_plan/README.rst
  l10n_br_sale_invoice_plan/__init__.py
  l10n_br_sale_invoice_plan/__manifest__.py
  l10n_br_sale_invoice_plan/demo/sale_order_demo.xml
  l10n_br_sale_invoice_plan/models/__init__.py
  l10n_br_sale_invoice_plan/models/sale_invoice_plan.py
  l10n_br_sale_invoice_plan/readme/CONFIGURE.rst
  l10n_br_sale_invoice_plan/readme/CONTRIBUTORS.rst
  l10n_br_sale_invoice_plan/readme/CREDITS.rst
  l10n_br_sale_invoice_plan/readme/DESCRIPTION.rst
  l10n_br_sale_invoice_plan/readme/INSTALL.rst
  l10n_br_sale_invoice_plan/static/description/icon.png
  l10n_br_sale_invoice_plan/static/description/index.html
  l10n_br_sale_invoice_plan/tests/__init__.py
  l10n_br_sale_invoice_plan/tests/test_l10n_br_sale_invoice_plan.py
  oca_dependencies.txt
  setup/l10n_br_sale_invoice_plan/odoo/addons/l10n_br_sale_invoice_plan
  setup/l10n_br_sale_invoice_plan/setup.py
Labels: needs review, 12.0, bot is merging ⏳

#2109 [14.0][FIX] l10n_br_sale: fix _create_invoices method
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
  l10n_br_sale/models/sale_order.py
Labels: bot is merging ⏳

#2106 [14.0][FIX] l10n_br_purchase_request: Dependencia do repo purchase-workflow OCA.
  oca_dependencies.txt
Labels: needs fixing, bot is merging ⏳, 14.0

#2112 [FIX+IMP] l10n_br_account_nfe: Demo Data e incluído teste para o caso sem Modo de Pagto
  l10n_br_account_nfe/demo/account_invoice_sn_demo.xml
  l10n_br_account_nfe/hooks.py
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
Labels: approved, bot is merging ⏳

#2105 [14.0][MIG] Modulo l10n_br_stock_account
  l10n_br_stock_account/README.rst
  l10n_br_stock_account/__init__.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_stock_account/data/l10n_br_stock_account_data.xml
  l10n_br_stock_account/demo/account_journal_demo.xml
  l10n_br_stock_account/demo/company_demo.xml
  l10n_br_stock_account/demo/fiscal_operation_generic.xml
  l10n_br_stock_account/demo/fiscal_operation_simple.xml
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/hooks.py
  l10n_br_stock_account/i18n/l10n_br_stock_account.pot
  l10n_br_stock_account/i18n/pt_BR.po
  l10n_br_stock_account/models/__init__.py
  l10n_br_stock_account/models/procurement_group.py
  l10n_br_stock_account/models/res_company.py
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/models/stock_picking_type.py
  l10n_br_stock_account/models/stock_rule.py
  l10n_br_stock_account/readme/CONFIGURE.rst
  l10n_br_stock_account/readme/CONTRIBUTORS.rst
  l10n_br_stock_account/readme/CREDITS.rst
  l10n_br_stock_account/readme/DESCRIPTION.rst
  l10n_br_stock_account/readme/HISTORY.rst
  l10n_br_stock_account/readme/INSTALL.rst
  l10n_br_stock_account/readme/ROADMAP.rst
  l10n_br_stock_account/readme/USAGE.rst
  l10n_br_stock_account/security/ir.model.access.csv
  l10n_br_stock_account/static/description/icon.png
  l10n_br_stock_account/static/description/index.html
  l10n_br_stock_account/tests/__init__.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/tests/test_stock_rule.py
  l10n_br_stock_account/views/res_company_view.xml
  l10n_br_stock_account/views/stock_account_view.xml
  l10n_br_stock_account/views/stock_picking.xml
  l10n_br_stock_account/views/stock_picking_type_view.xml
  l10n_br_stock_account/views/stock_rule_view.xml
  l10n_br_stock_account/wizards/__init__.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping_view.xml
  l10n_br_stock_account/wizards/stock_return_picking.py
  setup/l10n_br_stock_account/odoo/addons/l10n_br_stock_account
  setup/l10n_br_stock_account/setup.py
Labels: approved, migration, bot is merging ⏳, 14.0

#2115 [14.0][FIX] Fiscal: restrição de acesso na criação do fiscal dummy
  l10n_br_fiscal/models/res_company.py
Labels: approved, bot is merging ⏳, 14.0

#2118 [14.0][REF] l10n_br_contract: O paramentro Selection é desnecessario quando existe o Related
  l10n_br_contract/models/contract_line.py
Labels: approved, bot is merging ⏳

#2117 [12.0][REF] l10n_br_fiscal: move a geração do certificado fake para a lib erpbrasil.assinatura.
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/tests/test_certificate.py
  l10n_br_fiscal/tools/misc.py
  requirements.txt
Labels: approved, bot is merging ⏳

#2120 [14.0][FIX] l10n_br_coa: fix account template load
  l10n_br_coa/models/account_chart_template.py
Labels: approved, bot is merging ⏳, 14.0

#2113 [12.0] Cancelar uma NF-e que não foi emitida pela empresa
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_nfe/models/document.py
Labels: approved, 12.0, bot is merging ⏳

#2124 [14.0][REF][FIX] l10n_br_base: remove código desnecessário envolvendo o endereço.
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳

#2126 [14.0][FIX] brcobrança: Tratamento para o retorno do Banco do Brasil.
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#2127 [12.0][FIX] brcobrança: Tratamento para o retorno do Banco do Brasil.
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#1961 [14.0][MIG] l10n_br_sale_stock
  l10n_br_sale_stock/README.rst
  l10n_br_sale_stock/__init__.py
  l10n_br_sale_stock/__manifest__.py
  l10n_br_sale_stock/demo/l10n_br_sale_stock_demo.xml
  l10n_br_sale_stock/demo/sale_order_demo.xml
  l10n_br_sale_stock/i18n/l10n_br_sale_stock.pot
  l10n_br_sale_stock/i18n/pt_BR.po
  l10n_br_sale_stock/models/__init__.py
  l10n_br_sale_stock/models/res_company.py
  l10n_br_sale_stock/models/res_config_settings.py
  l10n_br_sale_stock/models/sale_order.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/readme/CONFIGURE.rst
  l10n_br_sale_stock/readme/CONTRIBUTORS.rst
  l10n_br_sale_stock/readme/CREDITS.rst
  l10n_br_sale_stock/readme/DESCRIPTION.rst
  l10n_br_sale_stock/readme/HISTORY.rst
  l10n_br_sale_stock/readme/INSTALL.rst
  l10n_br_sale_stock/readme/ROADMAP.rst
  l10n_br_sale_stock/readme/USAGE.rst
  l10n_br_sale_stock/static/description/icon.png
  l10n_br_sale_stock/static/description/index.html
  l10n_br_sale_stock/tests/__init__.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/views/res_company_view.xml
  l10n_br_sale_stock/views/res_config_settings_view.xml
  l10n_br_sale_stock/views/sale_order_view.xml
  l10n_br_sale_stock/wizards/__init__.py
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
  l10n_br_stock_account/demo/account_journal_demo.xml
  l10n_br_stock_account/hooks.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
  setup/l10n_br_sale_stock/odoo/addons/l10n_br_sale_stock
  setup/l10n_br_sale_stock/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 14.0

#1960 [14.0][MIG] l10n_br_purchase_stock
  l10n_br_purchase_stock/README.rst
  l10n_br_purchase_stock/__init__.py
  l10n_br_purchase_stock/__manifest__.py
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_purchase_stock/i18n/l10n_br_purchase_stock.pot
  l10n_br_purchase_stock/i18n/pt_BR.po
  l10n_br_purchase_stock/models/__init__.py
  l10n_br_purchase_stock/models/purchase_order.py
  l10n_br_purchase_stock/models/purchase_order_line.py
  l10n_br_purchase_stock/models/res_company.py
  l10n_br_purchase_stock/models/res_config_settings.py
  l10n_br_purchase_stock/models/stock_move.py
  l10n_br_purchase_stock/models/stock_rule.py
  l10n_br_purchase_stock/readme/CONFIGURE.rst
  l10n_br_purchase_stock/readme/CONTRIBUTORS.rst
  l10n_br_purchase_stock/readme/CREDITS.rst
  l10n_br_purchase_stock/readme/DESCRIPTION.rst
  l10n_br_purchase_stock/readme/HISTORY.rst
  l10n_br_purchase_stock/readme/INSTALL.rst
  l10n_br_purchase_stock/readme/ROADMAP.rst
  l10n_br_purchase_stock/readme/USAGE.rst
  l10n_br_purchase_stock/static/description/icon.png
  l10n_br_purchase_stock/static/description/index.html
  l10n_br_purchase_stock/tests/__init__.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock_lp.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock_sn.py
  l10n_br_purchase_stock/views/purchase_order.xml
  l10n_br_purchase_stock/views/res_company_view.xml
  l10n_br_purchase_stock/views/res_config_settings.xml
  l10n_br_purchase_stock/wizards/__init__.py
  l10n_br_purchase_stock/wizards/stock_invocing_onshipping.py
  l10n_br_stock_account/demo/account_journal_demo.xml
  l10n_br_stock_account/hooks.py
  setup/l10n_br_purchase_stock/odoo/addons/l10n_br_purchase_stock
  setup/l10n_br_purchase_stock/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, 14.0

#1953 [14.0][FIX] l10n_br_account_payment_order: tracking parameter
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/models/l10n_br_cnab_mov_intruction_code.py
  l10n_br_account_payment_order/models/l10n_br_cnab_payment_fields.py
  l10n_br_account_payment_order/models/l10n_br_cnab_return_move_code.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#2133 [12.0][FIX] l10n_br_fiscal: load certificate data
  l10n_br_fiscal/models/certificate.py
Labels: bot is merging ⏳

#2134 [12.0][FIX] l10n_br_sale_invoice_plan: fix price_unit on invoice.line
  l10n_br_sale_invoice_plan/models/sale_invoice_plan.py
Labels: approved, bot is merging ⏳

#2138 [14.0][FIX] Warnings with unknown parameters
  l10n_br_account_payment_order/models/account_move.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
Labels: approved, bot is merging ⏳

#2135 [14.0][FIX] l10n_br_account: fix fiscal operation type
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2137 [12.0][IMP] l10n_br_contract: remove dead code
  l10n_br_contract/models/contract_contract.py
Labels: approved, bot is merging ⏳

#2139 [14.0][REF] pay_order: hide fields for outbound payments
  l10n_br_account_payment_order/views/account_payment_order.xml
Labels: approved, bot is merging ⏳

#2123 [14.0] l10n_br_base, l10n_br_account: Cadastro de chaves PIX no Parceiro.
  l10n_br_account/__manifest__.py
  l10n_br_account/views/res_partner_view.xml
  l10n_br_base/__manifest__.py
  l10n_br_base/demo/res_partner_pix_demo.xml
  l10n_br_base/models/__init__.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_bank.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_base/readme/CONTRIBUTORS.rst
  l10n_br_base/readme/DESCRIPTION.rst
  l10n_br_base/security/ir.model.access.csv
  l10n_br_base/tests/__init__.py
  l10n_br_base/tests/test_partner_bank.py
  l10n_br_base/tests/test_valid_pix.py
  l10n_br_base/views/res_partner_bank_view.xml
  requirements.txt
Labels: approved, bot is merging ⏳

#2145 [14.0][FIX] l10n_br_account: compute fiscal operation type for entry moves
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2146 [12.0][FIX] l10n_br_purchase_request: keep the product description
  l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.py
Labels: bug, approved, 12.0, bot is merging ⏳
