Repository OCA/l10n-brazil, pull requests merged in 2022-04, with the labels that each got.

#1776 [13.0][MIG] Module l10n_br_stock
  l10n_br_stock/README.rst
  l10n_br_stock/__init__.py
  l10n_br_stock/__manifest__.py
  l10n_br_stock/demo/res_users_demo.xml
  l10n_br_stock/demo/stock_inventory_demo.xml
  l10n_br_stock/demo/stock_location_demo.xml
  l10n_br_stock/hooks.py
  l10n_br_stock/i18n/l10n_br_stock.pot
  l10n_br_stock/i18n/pt_BR.po
  l10n_br_stock/models/__init__.py
  l10n_br_stock/models/stock.py
  l10n_br_stock/readme/CONFIGURE.rst
  l10n_br_stock/readme/CONTRIBUTORS.rst
  l10n_br_stock/readme/DESCRIPTION.rst
  l10n_br_stock/readme/HISTORY.rst
  l10n_br_stock/readme/INSTALL.rst
  l10n_br_stock/readme/USAGE.rst
  l10n_br_stock/static/description/icon.png
  l10n_br_stock/static/description/index.html
  l10n_br_stock/views/stock_view.xml
  setup/l10n_br_stock/odoo/addons/l10n_br_stock
  setup/l10n_br_stock/setup.py
Labels: approved, migration, ready to merge, 13.0, bot is merging ⏳

#1855 [14.0][l10n_br_base][IMP] atualiza e adiciona cidades brasileiras
  l10n_br_base/data/res.city.csv
Labels: approved, bot is merging ⏳, 14.0

#1856 [14.0][l10n_br_fiscal] forward port #1610
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/models/cest.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/nbm.py
  l10n_br_fiscal/models/ncm.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/product_template.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/views/operation_line_view.xml
  l10n_br_fiscal/views/operation_view.xml
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: approved, bot is merging ⏳, 14.0

#1853 [12.0][ADD] Module l10n_br_account_nfe, inclusão das Tags Fat, Dup e Pag
  l10n_br_account_nfe/__init__.py
  l10n_br_account_nfe/__manifest__.py
  l10n_br_account_nfe/demo/account_invoice_demo.xml
  l10n_br_account_nfe/models/__init__.py
  l10n_br_account_nfe/models/account_payment_mode.py
  l10n_br_account_nfe/models/document_workflow.py
  l10n_br_account_nfe/readme/CONFIGURE.rst
  l10n_br_account_nfe/readme/CONTRIBUTORS.rst
  l10n_br_account_nfe/readme/DESCRIPTION.rst
  l10n_br_account_nfe/readme/HISTORY.rst
  l10n_br_account_nfe/readme/ROADMAP.rst
  l10n_br_account_nfe/readme/USAGE.rst
  l10n_br_account_nfe/tests/__init__.py
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
  l10n_br_account_nfe/views/account_payment_mode.xml
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/payment.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_nfe_structure.py
  l10n_br_nfe/views/nfe_document_view.xml
  setup/l10n_br_account_nfe/odoo/addons/l10n_br_account_nfe
  setup/l10n_br_account_nfe/setup.py
Labels: approved, bot is merging ⏳

#1857 [14.0][l10n_br_fiscal][FORWARD PORT][IMP] Minimal structure for XML validation
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳, 14.0

#1858 [14.0][l10n_br_fiscal][FORWARD PORT][REF] l10n_br_fiscal: Moved Comments creation method to be also used …
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳, 14.0

#1860 [12.0][l10n_br_account_payment_order][REF] Payment mode sequence constraitnts
  l10n_br_account_payment_order/models/account_payment_mode.py
Labels: approved, 12.0, bot is merging ⏳

#917 [NEW] PagSeguro
  payment_pagseguro/README.rst
  payment_pagseguro/__init__.py
  payment_pagseguro/__manifest__.py
  payment_pagseguro/controllers/__init__.py
  payment_pagseguro/controllers/main.py
  payment_pagseguro/data/payment_acquirer_data.xml
  payment_pagseguro/models/__init__.py
  payment_pagseguro/models/payment_acquirer.py
  payment_pagseguro/models/payment_token.py
  payment_pagseguro/models/payment_transaction.py
  payment_pagseguro/readme/CONFIGURE.rst
  payment_pagseguro/readme/CONTRIBUTORS.rst
  payment_pagseguro/readme/CREDITS.rst
  payment_pagseguro/readme/DESCRIPTION.rst
  payment_pagseguro/readme/HISTORY.rst
  payment_pagseguro/readme/INSTALL.rst
  payment_pagseguro/readme/ROADMAP.rst
  payment_pagseguro/readme/USAGE.rst
  payment_pagseguro/static/description/icon.png
  payment_pagseguro/static/description/index.html
  payment_pagseguro/static/description/pagseguro_buy.png
  payment_pagseguro/static/description/pagseguro_website.png
  payment_pagseguro/static/description/payment_acquirer_01.png
  payment_pagseguro/static/description/payment_acquirer_02.png
  payment_pagseguro/static/src/img/pag_seguro_icon.jpg
  payment_pagseguro/static/src/js/pagseguro_tokenize_card.js
  payment_pagseguro/static/src/js/pagseguro_tour.js
  payment_pagseguro/tests/__init__.py
  payment_pagseguro/tests/test_pagseguro.py
  payment_pagseguro/views/payment_acquirer.xml
  payment_pagseguro/views/payment_pagseguro_templates.xml
  setup/payment_pagseguro/odoo/addons/payment_pagseguro
  setup/payment_pagseguro/setup.py
Labels: needs review, 12.0, bot is merging ⏳

#1863 [14.0][FIX] l10n_br_nfse: make_pdf
  l10n_br_nfse/models/document.py
Labels: approved, bot is merging ⏳, 14.0

#1868 [14.0][FIX] l10n_br_fiscal: fix tracking parameter
  l10n_br_fiscal/models/operation.py
Labels: approved, bot is merging ⏳, 14.0

#1869 [14.0][FIX] l10n_br_fiscal: force pdf regeneration
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳, 14.0

#1873 [14.0][IMP] l10n_br_coa: add issqn, csll, irpj deductible tax
  l10n_br_coa/data/account_tax_template.xml
Labels: approved, bot is merging ⏳, 14.0

#1870 [14.0][IMP] l10n_br_nfse: add additional data section
  l10n_br_nfse/report/danfse.xml
Labels: enhancement, approved, bot is merging ⏳, 14.0

#1864 [14.0][IMP] l10n_br_nfse: enables the use of more than one item on the NFSE…
  l10n_br_nfse/models/document.py
  l10n_br_nfse/report/danfse.xml
Labels: enhancement, approved, ready to merge, bot is merging ⏳, 14.0

#1875 [14.0][FIX] l10n_br_nfse: fix street_name
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳, 14.0

#1867 [14.0][IMP] l10n_br_nfse: remove cnae_id
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/views/document_line_view.xml
Labels: approved, bot is merging ⏳, 14.0

#1885 [12][FIX][payment_pagseguro] includindo campo soft_descriptor
  payment_pagseguro/models/payment_transaction.py
Labels: approved, bot is merging ⏳

#1886 [12.0][FIX] payment_pagseguro: Timeout for pagseguro step tour
  payment_pagseguro/static/src/js/pagseguro_tour.js
  payment_pagseguro/tests/test_pagseguro.py
Labels: approved, bot is merging ⏳
