Repository OCA/l10n-brazil, pull requests merged in 2022-10, with the labels that each got.

#2148 [14.0][FIX] l10n_br_base: licença nos arquivos
  l10n_br_base/models/res_partner_pix.py
  l10n_br_base/tests/test_partner_bank.py
  l10n_br_base/tests/test_valid_pix.py
Labels: bot is merging ⏳

#2125 [12.0][FIX] l10n_br_contract: fix _prepare_recurring_invoices_values
  l10n_br_contract/models/contract_contract.py
Labels: needs fixing, approved, bot is merging ⏳

#2150 [14.0][FIX] l10n_br_purchase_request: keep description line if is set on wizard
  l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳, 14.0

#2149 [14.0][IMP] l10n_br_contract: remove dead code
  l10n_br_contract/models/contract_contract.py
Labels: approved, bot is merging ⏳, 14.0

#2161 [14.0][IMP] l10n_br_nfse: remove unnecessary file
  l10n_br_nfse/static/src/img/itajuba.png
Labels: approved, bot is merging ⏳

#2136 [14.0][IMP] l10n_br_fiscal l10n_br_sale: Movido parâmetro de "Custos de Entrega" para o modulo l10n_br_fiscal
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/res_config_settings.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/res_company_view.xml
  l10n_br_fiscal/views/res_config_settings_view.xml
  l10n_br_nfe/models/document_line.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase/views/purchase_view.xml
  l10n_br_sale/models/res_company.py
  l10n_br_sale/models/res_config_settings.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/views/res_company_view.xml
  l10n_br_sale/views/res_config_settings_view.xml
  l10n_br_sale/views/sale_view.xml
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#2097 [14.0][spec_driven_model][l10n_br_nfe] fix dry run import
  l10n_br_nfe/hooks.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/product_product.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/tests/test_nfe_import.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/tests/test_spec_model.py
Labels: bot is merging ⏳, 14.0

#2162 [12.0][l10n_br_payment_order][backport] payment order cleanup
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/models/l10n_br_cnab_payment_fields.py
  l10n_br_account_payment_order/views/account_payment_order.xml
Labels: approved, bot is merging ⏳

#2098 [12.0][spec_driven_model][l10n_br_nfe] fix dry run import
  l10n_br_nfe/hooks.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/product_product.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/tests/test_nfe_import.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, 12.0, bot is merging ⏳

#2163 [12.0][FIX] l10n_br_purchase_request: keep the original unit price of the purchase order
  l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#2142 [14.0][MIG] Modulo l10n_br_delivery
  l10n_br_delivery/README.rst
  l10n_br_delivery/__init__.py
  l10n_br_delivery/__manifest__.py
  l10n_br_delivery/data/account_incoterms_data.xml
  l10n_br_delivery/data/res_config_settings_data.xml
  l10n_br_delivery/demo/l10n_br_delivery_demo.xml
  l10n_br_delivery/demo/sale_order_demo.xml
  l10n_br_delivery/i18n/l10n_br_delivery.pot
  l10n_br_delivery/i18n/pt_BR.po
  l10n_br_delivery/models/__init__.py
  l10n_br_delivery/models/account_incoterms.py
  l10n_br_delivery/models/account_move.py
  l10n_br_delivery/models/delivery_carrier.py
  l10n_br_delivery/models/fiscal_document_mixin.py
  l10n_br_delivery/models/sale_order.py
  l10n_br_delivery/models/stock_picking.py
  l10n_br_delivery/models/vehicle.py
  l10n_br_delivery/readme/CONFIGURE.rst
  l10n_br_delivery/readme/CONTRIBUTORS.rst
  l10n_br_delivery/readme/DESCRIPTION.rst
  l10n_br_delivery/readme/HISTORY.rst
  l10n_br_delivery/readme/INSTALL.rst
  l10n_br_delivery/readme/ROADMAP.rst
  l10n_br_delivery/readme/USAGE.rst
  l10n_br_delivery/security/ir.model.access.csv
  l10n_br_delivery/static/description/icon.png
  l10n_br_delivery/static/description/index.html
  l10n_br_delivery/tests/__init__.py
  l10n_br_delivery/tests/test_delivery_inverse_amount.py
  l10n_br_delivery/views/account_incoterms_view.xml
  l10n_br_delivery/views/delivery_carrier_views.xml
  l10n_br_delivery/views/l10n_br_delivery_view.xml
  l10n_br_delivery/views/sale_order_view.xml
  l10n_br_delivery/views/stock_picking_view.xml
  oca_dependencies.txt
  setup/l10n_br_delivery/odoo/addons/l10n_br_delivery
  setup/l10n_br_delivery/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 14.0

#1942 [14.0][MIG] l10n_br_delivery_nfe
  l10n_br_delivery_nfe/README.rst
  l10n_br_delivery_nfe/__init__.py
  l10n_br_delivery_nfe/__manifest__.py
  l10n_br_delivery_nfe/i18n/l10n_br_delivery_nfe.pot
  l10n_br_delivery_nfe/models/__init__.py
  l10n_br_delivery_nfe/models/document.py
  l10n_br_delivery_nfe/readme/CONFIGURE.rst
  l10n_br_delivery_nfe/readme/CONTRIBUTORS.rst
  l10n_br_delivery_nfe/readme/DESCRIPTION.rst
  l10n_br_delivery_nfe/readme/HISTORY.rst
  l10n_br_delivery_nfe/readme/INSTALL.rst
  l10n_br_delivery_nfe/readme/ROADMAP.rst
  l10n_br_delivery_nfe/readme/USAGE.rst
  l10n_br_delivery_nfe/static/description/icon.png
  l10n_br_delivery_nfe/static/description/index.html
  l10n_br_delivery_nfe/views/nfe_document_view.xml
  setup/l10n_br_delivery_nfe/odoo/addons/l10n_br_delivery_nfe
  setup/l10n_br_delivery_nfe/setup.py
Labels: approved, migration, bot is merging ⏳, 14.0

#2160 [14.0][FIX] l10n_br_nfse: check provider before serializing
  l10n_br_nfse/models/document.py
Labels: approved, bot is merging ⏳

#2169 [14.0][MIG] l10n_br_repair: Migration to 14.0
  l10n_br_repair/README.rst
  l10n_br_repair/__init__.py
  l10n_br_repair/__manifest__.py
  l10n_br_repair/data/res_company.xml
  l10n_br_repair/demo/repair_order.xml
  l10n_br_repair/demo/res_company.xml
  l10n_br_repair/i18n/l10n_br_repair.pot
  l10n_br_repair/i18n/pt_BR.po
  l10n_br_repair/models/__init__.py
  l10n_br_repair/models/fiscal_line_mixin.py
  l10n_br_repair/models/repair_fee.py
  l10n_br_repair/models/repair_line.py
  l10n_br_repair/models/repair_order.py
  l10n_br_repair/models/res_company.py
  l10n_br_repair/models/res_config_settings.py
  l10n_br_repair/readme/CONFIGURE.rst
  l10n_br_repair/readme/CONTRIBUTORS.rst
  l10n_br_repair/readme/CREDITS.rst
  l10n_br_repair/readme/DESCRIPTION.rst
  l10n_br_repair/readme/HISTORY.rst
  l10n_br_repair/readme/INSTALL.rst
  l10n_br_repair/readme/ROADMAP.rst
  l10n_br_repair/readme/USAGE.rst
  l10n_br_repair/report/repair_templates_repair_order.xml
  l10n_br_repair/static/description/banner.png
  l10n_br_repair/static/description/icon.png
  l10n_br_repair/static/description/index.html
  l10n_br_repair/tests/__init__.py
  l10n_br_repair/tests/test_l10n_br_repair.py
  l10n_br_repair/tests/test_l10n_br_repair_lc.py
  l10n_br_repair/tests/test_l10n_br_repair_sn.py
  l10n_br_repair/views/repair_fee.xml
  l10n_br_repair/views/repair_line.xml
  l10n_br_repair/views/repair_order.xml
  l10n_br_repair/views/res_company.xml
  setup/l10n_br_repair/odoo/addons/l10n_br_repair
  setup/l10n_br_repair/setup.py
Labels: approved, migration, bot is merging ⏳, 14.0

#2175 [14.0][FIX] l10n_br_stock: wrong table name for stock_picking
  l10n_br_fiscal/demo/product_demo.xml
  l10n_br_nfe/tests/test_nfe_xml_validation.py
  l10n_br_stock/migrations/14.0.2.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#2183 [FIX] Pagseguro Sandbox Token
  payment_pagseguro/static/src/js/pagseguro_tour.js
  payment_pagseguro/tests/test_pagseguro.py
Labels: approved, bot is merging ⏳

#1988 [14.0][MIG] l10n_br_website_sale_delivery
  l10n_br_delivery/models/delivery_carrier.py
  l10n_br_delivery/models/sale_order.py
  l10n_br_delivery/views/sale_order_view.xml
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/views/sale_view.xml
  l10n_br_website_sale_delivery/README.rst
  l10n_br_website_sale_delivery/__init__.py
  l10n_br_website_sale_delivery/__manifest__.py
  l10n_br_website_sale_delivery/i18n/l10n_br_website_sale_delivery.pot
  l10n_br_website_sale_delivery/i18n/pt_BR.po
  l10n_br_website_sale_delivery/models/__init__.py
  l10n_br_website_sale_delivery/models/sale_order.py
  l10n_br_website_sale_delivery/readme/CONFIGURE.rst
  l10n_br_website_sale_delivery/readme/CONTRIBUTORS.rst
  l10n_br_website_sale_delivery/readme/DESCRIPTION.rst
  l10n_br_website_sale_delivery/readme/HISTORY.rst
  l10n_br_website_sale_delivery/readme/INSTALL.rst
  l10n_br_website_sale_delivery/readme/ROADMAP.rst
  l10n_br_website_sale_delivery/readme/USAGE.rst
  l10n_br_website_sale_delivery/static/description/icon.png
  l10n_br_website_sale_delivery/static/description/index.html
  l10n_br_website_sale_delivery/static/src/js/l10n_br_website_sale_delivery_tour.js
  l10n_br_website_sale_delivery/tests/__init__.py
  l10n_br_website_sale_delivery/tests/test_website_sale_tour.py
  l10n_br_website_sale_delivery/views/assets.xml
  setup/l10n_br_website_sale_delivery/odoo/addons/l10n_br_website_sale_delivery
  setup/l10n_br_website_sale_delivery/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, 14.0

#2184 Pylint missing return
  .pylintrc-mandatory
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/wizards/wizard_document_cancel.py
  l10n_br_account/wizards/wizard_document_correction.py
  l10n_br_account/wizards/wizard_document_invalidate.py
  l10n_br_account_nfe/models/document_workflow.py
  l10n_br_account_payment_brcobranca/models/account_move.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_contract/models/contract_contract.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_fiscal/models/document.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/invalidate_number.py
  l10n_br_nfse/models/document_line.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase_stock/models/stock_rule.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_repair/models/fiscal_line_mixin.py
  l10n_br_repair/models/repair_fee.py
  l10n_br_repair/models/repair_line.py
  l10n_br_repair/models/repair_order.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale_invoice_plan/models/sale_invoice_plan.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_website_sale_delivery/models/sale_order.py
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#2185 Pylint qweb replace
  .pylintrc-mandatory
  l10n_br_portal/views/portal_templates.xml
  l10n_br_repair/report/repair_templates_repair_order.xml
  l10n_br_sale/report/sale_report_templates.xml
  payment_pagseguro/views/payment_pagseguro_templates.xml
Labels: approved, bot is merging ⏳

#2187 Pylint raise missing
  .pylintrc-mandatory
  l10n_br_account_payment_brcobranca/models/account_journal.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_fiscal/models/certificate.py
  l10n_br_fiscal/models/closing.py
  l10n_br_fiscal/models/document_event.py
  l10n_br_fiscal/models/ibpt/taxes.py
  l10n_br_nfe/models/document.py
  l10n_br_zip/models/l10n_br_zip.py
Labels: approved, bot is merging ⏳

#2165 [14.0][REF][l10n_br_fiscal] extract the l10n_br_fiscal_closing module
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal_closing/README.rst
  l10n_br_fiscal_closing/__init__.py
  l10n_br_fiscal_closing/__manifest__.py
  l10n_br_fiscal_closing/models/__init__.py
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/models/document.py
  l10n_br_fiscal_closing/readme/CONFIGURE.rst
  l10n_br_fiscal_closing/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_closing/readme/CREDITS.rst
  l10n_br_fiscal_closing/readme/DESCRIPTION.rst
  l10n_br_fiscal_closing/readme/HISTORY.rst
  l10n_br_fiscal_closing/readme/INSTALL.rst
  l10n_br_fiscal_closing/readme/ROADMAP.rst
  l10n_br_fiscal_closing/readme/USAGE.rst
  l10n_br_fiscal_closing/security/ir.model.access.csv
  l10n_br_fiscal_closing/static/description/icon.png
  l10n_br_fiscal_closing/static/description/index.html
  l10n_br_fiscal_closing/tests/__init__.py
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_fiscal_closing/views/closing.xml
  setup/l10n_br_fiscal_closing/odoo/addons/l10n_br_fiscal_closing
  setup/l10n_br_fiscal_closing/setup.py
Labels: approved, bot is merging ⏳, 14.0

#2192 [14.0][l10n_br_fiscal][REF] fold back ibpt in a single file
  l10n_br_fiscal/models/data_ncm_nbs_abstract.py
  l10n_br_fiscal/models/ibpt.py
  l10n_br_fiscal/models/ibpt/__init__.py
  l10n_br_fiscal/models/nbs.py
  l10n_br_fiscal/models/ncm.py
  l10n_br_fiscal/tests/test_ibpt.py
Labels: approved, bot is merging ⏳

#2194 [15.0][MIG] l10n_br_base
  l10n_br_base/README.rst
  l10n_br_base/__init__.py
  l10n_br_base/__manifest__.py
  l10n_br_base/data/res.bank.csv
  l10n_br_base/data/res.city.csv
  l10n_br_base/data/res.country.state.csv
  l10n_br_base/data/res_country_data.xml
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_base/demo/res_partner_demo.xml
  l10n_br_base/demo/res_partner_pix_demo.xml
  l10n_br_base/demo/res_users_demo.xml
  l10n_br_base/hooks.py
  l10n_br_base/i18n/l10n_br_base.pot
  l10n_br_base/i18n/pt_BR.po
  l10n_br_base/migrations/14.0.2.0.0/post-migration.py 
  l10n_br_base/models/__init__.py
  l10n_br_base/models/format_address_mixin.py
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_bank.py
  l10n_br_base/models/res_city.py
  l10n_br_base/models/res_company.py
  l10n_br_base/models/res_config_settings.py
  l10n_br_base/models/res_country.py
  l10n_br_base/models/res_country_state.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_bank.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_base/models/state_tax_numbers.py
  l10n_br_base/readme/CONFIGURE.rst
  l10n_br_base/readme/CONTRIBUTORS.rst
  l10n_br_base/readme/DESCRIPTION.rst
  l10n_br_base/readme/HISTORY.rst
  l10n_br_base/readme/INSTALL.rst
  l10n_br_base/readme/ROADMAP.rst
  l10n_br_base/readme/USAGE.rst
  l10n_br_base/security/ir.model.access.csv
  l10n_br_base/static/description/icon.png
  l10n_br_base/static/description/index.html
  l10n_br_base/static/img/res_partner_akretion-image.jpg
  l10n_br_base/static/img/res_partner_kmee.png
  l10n_br_base/static/src/less/form_view.less
  l10n_br_base/tests/__init__.py
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_partner_bank.py
  l10n_br_base/tests/test_valid_createid.py
  l10n_br_base/tests/test_valid_pix.py
  l10n_br_base/views/res_bank_view.xml
  l10n_br_base/views/res_city_view.xml
  l10n_br_base/views/res_company_view.xml
  l10n_br_base/views/res_config_settings_view.xml
  l10n_br_base/views/res_country_view.xml
  l10n_br_base/views/res_partner_address_view.xml
  l10n_br_base/views/res_partner_bank_view.xml
  l10n_br_base/views/res_partner_view.xml
  requirements.txt
  setup/l10n_br_base/odoo/addons/l10n_br_base
  setup/l10n_br_base/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2164 [16.0][MIG] l10n_br_base
  l10n_br_base/README.rst
  l10n_br_base/__init__.py
  l10n_br_base/__manifest__.py
  l10n_br_base/data/res.bank.csv
  l10n_br_base/data/res.city.csv
  l10n_br_base/data/res.country.state.csv
  l10n_br_base/data/res_country_data.xml
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_base/demo/res_partner_demo.xml
  l10n_br_base/demo/res_partner_pix_demo.xml
  l10n_br_base/demo/res_users_demo.xml
  l10n_br_base/hooks.py
  l10n_br_base/i18n/l10n_br_base.pot
  l10n_br_base/i18n/pt_BR.po
  l10n_br_base/migrations/14.0.2.0.0/post-migration.py 
  l10n_br_base/models/__init__.py
  l10n_br_base/models/format_address_mixin.py
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_bank.py
  l10n_br_base/models/res_city.py
  l10n_br_base/models/res_company.py
  l10n_br_base/models/res_config_settings.py
  l10n_br_base/models/res_country.py
  l10n_br_base/models/res_country_state.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_bank.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_base/models/state_tax_numbers.py
  l10n_br_base/readme/CONFIGURE.rst
  l10n_br_base/readme/CONTRIBUTORS.rst
  l10n_br_base/readme/DESCRIPTION.rst
  l10n_br_base/readme/HISTORY.rst
  l10n_br_base/readme/INSTALL.rst
  l10n_br_base/readme/ROADMAP.rst
  l10n_br_base/readme/USAGE.rst
  l10n_br_base/security/ir.model.access.csv
  l10n_br_base/static/description/icon.png
  l10n_br_base/static/description/index.html
  l10n_br_base/static/img/res_partner_akretion-image.jpg
  l10n_br_base/static/img/res_partner_kmee.png
  l10n_br_base/static/src/less/form_view.less
  l10n_br_base/tests/__init__.py
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_partner_bank.py
  l10n_br_base/tests/test_valid_createid.py
  l10n_br_base/tests/test_valid_pix.py
  l10n_br_base/views/res_bank_view.xml
  l10n_br_base/views/res_city_view.xml
  l10n_br_base/views/res_company_view.xml
  l10n_br_base/views/res_config_settings_view.xml
  l10n_br_base/views/res_country_view.xml
  l10n_br_base/views/res_partner_address_view.xml
  l10n_br_base/views/res_partner_bank_view.xml
  l10n_br_base/views/res_partner_view.xml
  requirements.txt
  setup/l10n_br_base/odoo/addons/l10n_br_base
  setup/l10n_br_base/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 16.0

#2198 [FIX] test_fiscal_closing
  l10n_br_fiscal/tests/__init__.py
Labels: bot is merging ⏳

#2201 [FIX] certificate datetime test error
  l10n_br_fiscal/models/certificate.py
Labels: bot is merging ⏳

#2191 [14.0] Corrige a formatação do modulo l10n_br_fiscal
  l10n_br_fiscal/models/comment.py
Labels: bot is merging ⏳

#2195 [15.0][MIG] l10n_br_crm
  l10n_br_crm/README.rst
  l10n_br_crm/__init__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/i18n/l10n_br_crm.pot
  l10n_br_crm/i18n/pt_BR.po
  l10n_br_crm/models/__init__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/readme/CONFIGURE.rst
  l10n_br_crm/readme/CONTRIBUTORS.rst
  l10n_br_crm/readme/DESCRIPTION.rst
  l10n_br_crm/readme/INSTALL.rst
  l10n_br_crm/readme/ROADMAP.rst
  l10n_br_crm/readme/USAGE.rst
  l10n_br_crm/static/description/icon.png
  l10n_br_crm/static/description/index.html
  l10n_br_crm/tests/__init__.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_crm/views/crm_lead_view.xml
  l10n_br_crm/views/crm_quick_create_opportunity_form.xml
  setup/l10n_br_crm/odoo/addons/l10n_br_crm
  setup/l10n_br_crm/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2196 [15.0][MIG] l10n_br_zip
  l10n_br_zip/README.rst
  l10n_br_zip/__init__.py
  l10n_br_zip/__manifest__.py
  l10n_br_zip/i18n/l10n_br_zip.pot
  l10n_br_zip/i18n/pt_BR.po
  l10n_br_zip/migrations/14.0.1.0.0/pre-migration.py
  l10n_br_zip/models/__init__.py
  l10n_br_zip/models/format_address_mixin.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/models/res_config_settings.py
  l10n_br_zip/readme/CONFIGURE.rst
  l10n_br_zip/readme/CONTRIBUTORS.rst
  l10n_br_zip/readme/DESCRIPTION.rst
  l10n_br_zip/readme/HISTORY.rst
  l10n_br_zip/readme/INSTALL.rst
  l10n_br_zip/readme/ROADMAP.rst
  l10n_br_zip/readme/USAGE.rst
  l10n_br_zip/security/ir.model.access.csv
  l10n_br_zip/static/description/icon.png
  l10n_br_zip/static/description/index.html
  l10n_br_zip/static/description/l10n_br_zip_1.png
  l10n_br_zip/tests/__init__.py
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
  l10n_br_zip/views/l10n_br_zip_view.xml
  l10n_br_zip/views/res_config_settings_view.xml
  l10n_br_zip/views/res_partner_address_view.xml
  l10n_br_zip/wizard/__init__.py
  l10n_br_zip/wizard/l10n_br_zip_search.py
  l10n_br_zip/wizard/l10n_br_zip_search_view.xml
  requirements.txt
  setup/l10n_br_zip/odoo/addons/l10n_br_zip
  setup/l10n_br_zip/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2202 [15.0][MIG] l10n_br_account_due_list
  l10n_br_account_due_list/README.rst
  l10n_br_account_due_list/__init__.py
  l10n_br_account_due_list/__manifest__.py
  l10n_br_account_due_list/i18n/l10n_br_account_due_list.pot
  l10n_br_account_due_list/i18n/pt_BR.po
  l10n_br_account_due_list/models/__init__.py
  l10n_br_account_due_list/models/account_invoice.py
  l10n_br_account_due_list/readme/CONFIGURE.rst
  l10n_br_account_due_list/readme/CONTRIBUTORS.rst
  l10n_br_account_due_list/readme/DESCRIPTION.rst
  l10n_br_account_due_list/readme/HISTORY.rst
  l10n_br_account_due_list/readme/INSTALL.rst
  l10n_br_account_due_list/readme/ROADMAP.rst
  l10n_br_account_due_list/readme/USAGE.rst
  l10n_br_account_due_list/static/description/icon.png
  l10n_br_account_due_list/static/description/index.html
  l10n_br_account_due_list/static/img/l10n_br_account_due_list_payable.png
  l10n_br_account_due_list/static/img/l10n_br_account_due_list_receivable.png
  l10n_br_account_due_list/views/account_invoice_view.xml
  oca_dependencies.txt
  setup/l10n_br_account_due_list/odoo/addons/l10n_br_account_due_list
  setup/l10n_br_account_due_list/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2203 [15.0][MIG] l10n_br_coa
  l10n_br_coa/README.rst
  l10n_br_coa/__init__.py
  l10n_br_coa/__manifest__.py
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/data/account_type_data.xml
  l10n_br_coa/data/l10n_br_coa_template.xml
  l10n_br_coa/i18n/l10n_br_coa.pot
  l10n_br_coa/i18n/pt_BR.po
  l10n_br_coa/models/__init__.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax.py
  l10n_br_coa/models/account_tax_mixin.py
  l10n_br_coa/models/account_tax_template.py
  l10n_br_coa/models/l10n_br_coa_account_tax_group_account_template.py
  l10n_br_coa/readme/CONFIGURE.rst
  l10n_br_coa/readme/CONTRIBUTORS.rst
  l10n_br_coa/readme/DESCRIPTION.rst
  l10n_br_coa/readme/INSTALL.rst
  l10n_br_coa/readme/ROADMAP.rst
  l10n_br_coa/readme/USAGE.rst
  l10n_br_coa/security/ir.model.access.csv
  l10n_br_coa/static/description/icon.png
  l10n_br_coa/static/description/index.html
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa/views/account_tax_template.xml
  setup/l10n_br_coa/odoo/addons/l10n_br_coa
  setup/l10n_br_coa/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2204 [15.0][MIG] l10n_br_stock
  l10n_br_stock/README.rst
  l10n_br_stock/__init__.py
  l10n_br_stock/__manifest__.py
  l10n_br_stock/demo/res_users_demo.xml
  l10n_br_stock/demo/stock_inventory_demo.xml
  l10n_br_stock/demo/stock_location_demo.xml
  l10n_br_stock/hooks.py
  l10n_br_stock/i18n/l10n_br_stock.pot
  l10n_br_stock/i18n/pt_BR.po
  l10n_br_stock/migrations/14.0.2.0.0/pre-migration.py
  l10n_br_stock/models/__init__.py
  l10n_br_stock/models/stock_picking.py
  l10n_br_stock/readme/CONFIGURE.rst
  l10n_br_stock/readme/CONTRIBUTORS.rst
  l10n_br_stock/readme/DESCRIPTION.rst
  l10n_br_stock/readme/HISTORY.rst
  l10n_br_stock/readme/INSTALL.rst
  l10n_br_stock/readme/USAGE.rst
  l10n_br_stock/static/description/icon.png
  l10n_br_stock/static/description/index.html
  l10n_br_stock/views/stock_picking_view.xml
  setup/l10n_br_stock/odoo/addons/l10n_br_stock
  setup/l10n_br_stock/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2208 [16.0][mig] l10n_br_stock
  l10n_br_stock/README.rst
  l10n_br_stock/__init__.py
  l10n_br_stock/__manifest__.py
  l10n_br_stock/demo/res_users_demo.xml
  l10n_br_stock/demo/stock_inventory_demo.xml
  l10n_br_stock/demo/stock_location_demo.xml
  l10n_br_stock/hooks.py
  l10n_br_stock/i18n/l10n_br_stock.pot
  l10n_br_stock/i18n/pt_BR.po
  l10n_br_stock/migrations/14.0.2.0.0/pre-migration.py
  l10n_br_stock/models/__init__.py
  l10n_br_stock/models/stock_picking.py
  l10n_br_stock/readme/CONFIGURE.rst
  l10n_br_stock/readme/CONTRIBUTORS.rst
  l10n_br_stock/readme/DESCRIPTION.rst
  l10n_br_stock/readme/HISTORY.rst
  l10n_br_stock/readme/INSTALL.rst
  l10n_br_stock/readme/USAGE.rst
  l10n_br_stock/static/description/icon.png
  l10n_br_stock/static/description/index.html
  l10n_br_stock/views/stock_picking_view.xml
  setup/l10n_br_stock/odoo/addons/l10n_br_stock
  setup/l10n_br_stock/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 16.0

#2178 [16.0][MIG] l10n_br_zip
  l10n_br_zip/README.rst
  l10n_br_zip/__init__.py
  l10n_br_zip/__manifest__.py
  l10n_br_zip/i18n/l10n_br_zip.pot
  l10n_br_zip/i18n/pt_BR.po
  l10n_br_zip/migrations/14.0.1.0.0/pre-migration.py
  l10n_br_zip/models/__init__.py
  l10n_br_zip/models/format_address_mixin.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/models/res_config_settings.py
  l10n_br_zip/readme/CONFIGURE.rst
  l10n_br_zip/readme/CONTRIBUTORS.rst
  l10n_br_zip/readme/DESCRIPTION.rst
  l10n_br_zip/readme/HISTORY.rst
  l10n_br_zip/readme/INSTALL.rst
  l10n_br_zip/readme/ROADMAP.rst
  l10n_br_zip/readme/USAGE.rst
  l10n_br_zip/security/ir.model.access.csv
  l10n_br_zip/static/description/icon.png
  l10n_br_zip/static/description/index.html
  l10n_br_zip/static/description/l10n_br_zip_1.png
  l10n_br_zip/tests/__init__.py
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
  l10n_br_zip/views/l10n_br_zip_view.xml
  l10n_br_zip/views/res_config_settings_view.xml
  l10n_br_zip/views/res_partner_address_view.xml
  l10n_br_zip/wizard/__init__.py
  l10n_br_zip/wizard/l10n_br_zip_search.py
  l10n_br_zip/wizard/l10n_br_zip_search_view.xml
  requirements.txt
  setup/l10n_br_zip/odoo/addons/l10n_br_zip
  setup/l10n_br_zip/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 16.0

#2210 [FIX] VCRpy pagseguro tests
  payment_pagseguro/static/src/js/pagseguro_tokenize_card.js
  payment_pagseguro/static/src/js/pagseguro_tour.js
  payment_pagseguro/tests/fixtures/test_buy_pagseguro.yaml
  payment_pagseguro/tests/fixtures/test_buy_pagseguro_fail.yaml
  payment_pagseguro/tests/test_pagseguro.py
Labels: bug, approved, bot is merging ⏳, 14.0

#2130 [12.0] switch to gh actions
  .copier-answers.yml
  .github/workflows/test.yml
  .travis.yml
  l10n_br_account/__manifest__.py
  l10n_br_coa_complete/__manifest__.py
  l10n_br_currency_rate_update/__manifest__.py
  l10n_br_sale/__manifest__.py
  l10n_br_sale_invoice_plan/__manifest__.py
  l10n_br_stock_account_report/__manifest__.py
  requirements.txt
  spec_driven_model/__manifest__.py
Labels: approved, bot is merging ⏳

#2190 [12.0] Corrige a formatação do modulo l10n_br_fiscal
  l10n_br_fiscal/models/comment.py
Labels: 12.0, bot is merging ⏳, backport

#2200 [FIX] certificate datetime test error
  l10n_br_fiscal/models/certificate.py
Labels: 12.0, bot is merging ⏳, backport

#2213 [FIX] VCR test dependencies
  payment_pagseguro/__manifest__.py
  requirements.txt
Labels: bug, good first issue, bot is merging ⏳, 14.0

#2180 [14.0][IMP] l10n_br_account_payment_order: Suporte para o CNAB Pagamentos (sem o payment way)
  l10n_br_account/security/ir.model.access.csv
  l10n_br_account_payment_brcobranca/models/account_payment_mode.py
  l10n_br_account_payment_order/demo/account_payment_mode.xml
  l10n_br_account_payment_order/models/account_move_line.py
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/models/bank_payment_line.py
  l10n_br_account_payment_order/tests/__init__.py
  l10n_br_account_payment_order/tests/test_payment_order_outbound_pix.py
  l10n_br_account_payment_order/views/account_move_view.xml
  l10n_br_account_payment_order/views/account_payment_line.xml
  l10n_br_account_payment_order/views/account_payment_mode.xml
  l10n_br_account_payment_order/views/account_payment_order.xml
  l10n_br_account_payment_order/views/bank_payment_line.xml
Labels: approved, bot is merging ⏳
