Repository OCA/l10n-brazil, pull requests merged in 2022-06, with the labels that each got.

#1924 [12.0][REF] l10n_br_nfe: fiscal document module integration standard
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/cest.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_type.py
  l10n_br_nfe/models/nbm.py
  l10n_br_nfe/models/ncm.py
  l10n_br_nfe/models/tax_ipi_guideline.py
Labels: enhancement, approved, ready to merge, 12.0, bot is merging ⏳

#1916 [12.0][IMP] payment_pagseguro: Parcelamento de cartão de crédito
  payment_pagseguro/README.rst
  payment_pagseguro/data/payment_acquirer_data.xml
  payment_pagseguro/models/payment_acquirer.py
  payment_pagseguro/models/payment_token.py
  payment_pagseguro/models/payment_transaction.py
  payment_pagseguro/readme/CONFIGURE.rst
  payment_pagseguro/readme/ROADMAP.rst
  payment_pagseguro/readme/USAGE.rst
  payment_pagseguro/static/description/index.html
  payment_pagseguro/static/description/pagseguro_payment_form.png
  payment_pagseguro/static/description/payment_acquirer_03.png
  payment_pagseguro/static/lib/pagseguro_templates.js
  payment_pagseguro/static/src/js/pagseguro_tokenize_card.js
  payment_pagseguro/tests/test_pagseguro.py
  payment_pagseguro/views/payment_acquirer.xml
  payment_pagseguro/views/payment_pagseguro_templates.xml
Labels: approved, ready to merge, bot is merging ⏳

#1947 [FIX] Upgrade black version in pre-commit config
  .pre-commit-config.yaml
Labels: approved

#1950 [12.0] pre-commit after pre-commit version upgrade
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
  l10n_br_account_payment_brcobranca/tests/test_payment_order.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/tests/test_base_class.py
  l10n_br_account_payment_order/tests/test_invoice_manual_workflow.py
  l10n_br_account_payment_order/tests/test_invoice_normal_workflow.py
  l10n_br_account_payment_order/tests/test_payment_order.py
  l10n_br_account_payment_order/tests/test_payment_order_change.py
  l10n_br_account_payment_order/tests/test_payment_order_inbound.py
  l10n_br_base/models/res_company.py
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_fiscal/models/comment.py
  l10n_br_fiscal/models/partner_profile.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/tests/test_certificate.py
  l10n_br_fiscal/tests/test_cnae.py
  l10n_br_fiscal/tests/test_fiscal_closing.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_fiscal_document_nfse.py
  l10n_br_fiscal/tests/test_fiscal_tax.py
  l10n_br_fiscal/tests/test_service_type.py
  l10n_br_fiscal/tests/test_subsequent_operation.py
  l10n_br_hr_contract/models/hr_contract.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_account_customer_nfe.py
  l10n_br_nfe/tests/test_account_nfe_refund.py
  l10n_br_nfe/wizards/l10n_br_account_nfe_export.py
  l10n_br_nfe/wizards/l10n_br_account_nfe_export_invoice.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse_issnet/tests/test_fiscal_document_nfse_issnet.py
  l10n_br_nfse_paulistana/tests/test_fiscal_document_nfse_paulistana.py
  l10n_br_resource/models/resource_calendar.py
  l10n_br_resource/models/resource_calendar_leaves.py
  l10n_br_resource/tests/test_resource_calendar.py
  l10n_br_resource/wizards/workalendar_holiday_import_wizard.py
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account_report/tests/test_l10n_br_p7_model_inventory_report.py
  payment_pagseguro/models/payment_acquirer.py
  payment_pagseguro/models/payment_transaction.py
Labels: approved, 12.0

#1954 [FIX] Remove web modules tests from travis
  .travis.yml
Labels: approved

#1952 [14.0][FIX] spec_driven_model: change and remove parameters unknown
  spec_driven_model/tests/fake_odoo_purchase.py
Labels: approved, bot is merging ⏳, 14.0

#1956 [14.0][MIG] add company in res.partner.bank
  l10n_br_account_payment_order/demo/res_partner_bank.xml
Labels: approved, bot is merging ⏳

#1955 [FIX] Add EXCLUDE env variable to travis matrix
  .travis.yml
Labels: approved

#1841 [14.0][MIG] l10n_br_purchase
  l10n_br_purchase/README.rst
  l10n_br_purchase/__init__.py
  l10n_br_purchase/__manifest__.py
  l10n_br_purchase/data/company.xml
  l10n_br_purchase/demo/company.xml
  l10n_br_purchase/demo/fiscal_operation_generic.xml
  l10n_br_purchase/demo/fiscal_operation_simple.xml
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/demo/product.xml
  l10n_br_purchase/hooks.py
  l10n_br_purchase/i18n/l10n_br_purchase.pot
  l10n_br_purchase/i18n/pt_BR.po
  l10n_br_purchase/models/__init__.py
  l10n_br_purchase/models/account_move.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/models/res_company.py
  l10n_br_purchase/readme/CONFIGURE.rst
  l10n_br_purchase/readme/CONTRIBUTORS.rst
  l10n_br_purchase/readme/CREDITS.rst
  l10n_br_purchase/readme/DESCRIPTION.rst
  l10n_br_purchase/readme/HISTORY.rst
  l10n_br_purchase/readme/INSTALL.rst
  l10n_br_purchase/readme/ROADMAP.rst
  l10n_br_purchase/readme/USAGE.rst
  l10n_br_purchase/reports/__init__.py
  l10n_br_purchase/reports/purchase_order_templates.xml
  l10n_br_purchase/reports/purchase_report.py
  l10n_br_purchase/reports/purchase_report_views.xml
  l10n_br_purchase/security/ir.model.access.csv
  l10n_br_purchase/static/description/icon.png
  l10n_br_purchase/static/description/index.html
  l10n_br_purchase/tests/__init__.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase/tests/test_l10n_br_purchase_lp.py
  l10n_br_purchase/tests/test_l10n_br_purchase_sn.py
  l10n_br_purchase/views/purchase_view.xml
  l10n_br_purchase/views/res_company_view.xml
  setup/l10n_br_purchase/odoo/addons/l10n_br_purchase
  setup/l10n_br_purchase/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 14.0

#1957 [12.0] l10n_br_nfe: Adiciona res_country ao init
  l10n_br_nfe/models/__init__.py
Labels: approved, bot is merging ⏳

#1945 [12.0] l10n_br_nfe: Arruma importação do campo xFant
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/tests/test_nfe_import.py
Labels: approved, bot is merging ⏳

#1943 [12.0]l10n_br_nfe: Check who is document issuer during import process
  l10n_br_nfe/models/document.py
Labels: approved, 12.0, bot is merging ⏳

#1958 [14.0][FIX] l10n_br_fiscal: onchange ind_final
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
Labels: approved, bot is merging ⏳

#1948 [12.0] spec_driven_model: Troca operador de match para strings
  spec_driven_model/models/spec_import.py
Labels: approved, 12.0, bot is merging ⏳

#1951 [14.0] import commits from 12.0
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/account_tax.py
  l10n_br_account/models/fiscal_operation.py
  l10n_br_account/models/fiscal_tax.py
  l10n_br_account/report/account_invoice_report.py
Labels: approved, bot is merging ⏳, 14.0

#1962 [12.0][FIX] l10n_br_fiscal: onchange partner update ind_final
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
Labels: approved, bot is merging ⏳

#1854 [14.0][MIG] l10n_br_sale
  l10n_br_sale/README.rst
  l10n_br_sale/__init__.py
  l10n_br_sale/__manifest__.py
  l10n_br_sale/data/company.xml
  l10n_br_sale/demo/company.xml
  l10n_br_sale/demo/fiscal_operation_generic.xml
  l10n_br_sale/demo/fiscal_operation_simple.xml
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/demo/product.xml
  l10n_br_sale/hooks.py
  l10n_br_sale/i18n/l10n_br_sale.pot
  l10n_br_sale/i18n/pt_BR.po
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/res_company.py
  l10n_br_sale/models/res_config_settings.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/readme/CONFIGURE.rst
  l10n_br_sale/readme/CONTRIBUTORS.rst
  l10n_br_sale/readme/CREDITS.rst
  l10n_br_sale/readme/DESCRIPTION.rst
  l10n_br_sale/readme/HISTORY.rst
  l10n_br_sale/readme/INSTALL.rst
  l10n_br_sale/readme/ROADMAP.rst
  l10n_br_sale/readme/USAGE.rst
  l10n_br_sale/report/__init__.py
  l10n_br_sale/report/sale_report.py
  l10n_br_sale/report/sale_report_templates.xml
  l10n_br_sale/report/sale_report_view.xml
  l10n_br_sale/security/ir.model.access.csv
  l10n_br_sale/security/l10n_br_sale_security.xml
  l10n_br_sale/static/description/icon.png
  l10n_br_sale/static/description/index.html
  l10n_br_sale/static/description/sale_order_1.png
  l10n_br_sale/static/description/sale_order_2.png
  l10n_br_sale/tests/__init__.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/tests/test_l10n_br_sale_lc.py
  l10n_br_sale/tests/test_l10n_br_sale_sn.py
  l10n_br_sale/views/res_company_view.xml
  l10n_br_sale/views/res_config_settings_view.xml
  l10n_br_sale/views/sale_view.xml
  setup/l10n_br_sale/odoo/addons/l10n_br_sale
  setup/l10n_br_sale/setup.py
Labels: help wanted, approved, migration, bot is merging ⏳, 14.0

#1944 [12.0] l10n_br_nfe: Fixed various if clauses on document.line build_many2one method
  l10n_br_nfe/models/document_line.py
Labels: approved, 12.0, bot is merging ⏳

#1965 [14.0][REF] l10n_br_stock: Renomeado campo da Inscrição Estadual no stock.picking
  l10n_br_stock/__manifest__.py
  l10n_br_stock/migrations/14.0.2.0.0/pre-migration.py
  l10n_br_stock/models/__init__.py
  l10n_br_stock/models/stock_picking.py
  l10n_br_stock/readme/CONFIGURE.rst
  l10n_br_stock/readme/DESCRIPTION.rst
  l10n_br_stock/readme/HISTORY.rst
  l10n_br_stock/readme/INSTALL.rst
  l10n_br_stock/readme/ROADMAP.rst
  l10n_br_stock/readme/USAGE.rst
  l10n_br_stock/views/stock_picking_view.xml
Labels: approved, bot is merging ⏳

#1967 [14.0][IMP] l10n_br_sale: Exibe a indicação do Consumidor Final no Pedido de Venda.
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳, 14.0

#1833 [14.0][MIG] l10n_br_contract
  l10n_br_contract/README.rst
  l10n_br_contract/__init__.py
  l10n_br_contract/__manifest__.py
  l10n_br_contract/data/company.xml
  l10n_br_contract/demo/company.xml
  l10n_br_contract/demo/contract_demo.xml
  l10n_br_contract/i18n/l10n_br_contract.pot
  l10n_br_contract/i18n/pt_BR.po
  l10n_br_contract/models/__init__.py
  l10n_br_contract/models/contract_contract.py
  l10n_br_contract/models/contract_line.py
  l10n_br_contract/models/res_company.py
  l10n_br_contract/readme/CONFIGURE.rst
  l10n_br_contract/readme/CONTRIBUTORS.rst
  l10n_br_contract/readme/DESCRIPTION.rst
  l10n_br_contract/readme/HISTORY.rst
  l10n_br_contract/readme/INSTALL.rst
  l10n_br_contract/readme/USAGE.rst
  l10n_br_contract/static/description/icon.png
  l10n_br_contract/static/description/index.html
  l10n_br_contract/tests/__init__.py
  l10n_br_contract/tests/test_l10n_br_contract.py
  l10n_br_contract/views/contract_line.xml
  l10n_br_contract/views/contract_view.xml
  l10n_br_contract/views/res_company.xml
  setup/l10n_br_contract/odoo/addons/l10n_br_contract
  setup/l10n_br_contract/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 14.0

#1963 [12.0][FIX] Valor base dos impostos
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/models/tax_group.py
  l10n_br_fiscal/views/tax_group_view.xml
Labels: approved, bot is merging ⏳

#1964 [14.0][FIX] Valor base dos impostos
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/models/tax_group.py
  l10n_br_fiscal/readme/CONFIGURE.rst
  l10n_br_fiscal/readme/CONTRIBUTORS.rst
  l10n_br_fiscal/readme/DESCRIPTION.rst
  l10n_br_fiscal/readme/INSTALL.rst
  l10n_br_fiscal/readme/ROADMAP.rst
  l10n_br_fiscal/readme/USAGE.rst
  l10n_br_fiscal/views/tax_group_view.xml
Labels: approved, bot is merging ⏳, 14.0

#1966 [14.0][IMP][l10n_br_fiscal] Opção de mapear o ICMS pela operação Consumidor Final
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
  l10n_br_fiscal/demo/l10n_br_fiscal.ncm-demo.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_icms_regulation.py
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: approved, bot is merging ⏳, 14.0

#1971 [14.0][FIX] map_tax_icms_difal must get icms tax defs from destination
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳, 14.0

#1970 [12.0][FIX] map_tax_icms_difal must get icms tax defs from destination
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#1973 [14.0] [l10n_br_fiscal] forward port #1732
  l10n_br_fiscal/demo/l10n_br_fiscal.cest-demo.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/readme/CONTRIBUTORS.rst
Labels: approved, bot is merging ⏳

#1981 [14.0][FIX] l10n_br_fiscal: load certificate data
  l10n_br_fiscal/models/certificate.py
Labels: approved, bot is merging ⏳

#1982 [14.0][FIX] l10n_br_fiscal: next fiscal number
  l10n_br_fiscal/models/document_serie.py
Labels: approved, bot is merging ⏳

#1975 [14.0][FIX] Geração dos boletos sem a criação automática do arquivo de remessa.
  l10n_br_account_payment_order/models/account_move.py
Labels: approved, bot is merging ⏳

#1938 [12.0] l10n_br_nfe: build_many2one now builds a 'delivery' type contact for nfe40_entrega
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#1983 [14.0] l10n_br_nfe: build_many2one now builds a 'delivery' type contact for nfe40_entrega
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳, 14.0

#1984 [12.0][REF] Adicionado método _prepare_result_line para extender o relatório modelo P7
  l10n_br_stock_account_report/report/l10n_br_p7_model_inventory_report_view.xml
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard.py
Labels: approved, 12.0, bot is merging ⏳

#1976 [14.0][MIG] l10n_br_website_sale
  l10n_br_website_sale/README.rst
  l10n_br_website_sale/__init__.py
  l10n_br_website_sale/__manifest__.py
  l10n_br_website_sale/controllers/__init__.py
  l10n_br_website_sale/controllers/main.py
  l10n_br_website_sale/i18n/l10n_br_website_sale.pot
  l10n_br_website_sale/i18n/pt_BR.po
  l10n_br_website_sale/readme/CONFIGURE.rst
  l10n_br_website_sale/readme/CONTRIBUTORS.rst
  l10n_br_website_sale/readme/CREDITS.rst
  l10n_br_website_sale/readme/DESCRIPTION.rst
  l10n_br_website_sale/readme/HISTORY.rst
  l10n_br_website_sale/readme/INSTALL.rst
  l10n_br_website_sale/readme/ROADMAP.rst
  l10n_br_website_sale/readme/USAGE.rst
  l10n_br_website_sale/static/description/icon.png
  l10n_br_website_sale/static/description/index.html
  l10n_br_website_sale/static/src/js/l10n_br_address.js
  l10n_br_website_sale/static/src/js/l10n_br_website_sale_tour.js
  l10n_br_website_sale/templates/portal_templates.xml
  l10n_br_website_sale/tests/__init__.py
  l10n_br_website_sale/tests/test_sale_process.py
  l10n_br_website_sale/views/assets.xml
  setup/l10n_br_website_sale/odoo/addons/l10n_br_website_sale
  setup/l10n_br_website_sale/setup.py
Labels: approved, migration, bot is merging ⏳, 14.0

#1990 [14.][FIX] default_fiscal_operation_type in _change_action_view method context
  l10n_br_account/models/fiscal_operation.py
Labels: bug, approved, bot is merging ⏳, 14.0

#1989 [12.0][FIX] default_fiscal_operation_type in _change_action_view method context
  l10n_br_account/models/fiscal_operation.py
Labels: bug, approved, 12.0, bot is merging ⏳

#1994 [12.0][FIX] Get document key from right fiscal document
  l10n_br_nfe/models/document_related.py
Labels: bug, approved, 12.0, bot is merging ⏳

#1995 [14.0][FIX] Get document key from right fiscal document
  l10n_br_nfe/models/document_related.py
Labels: bug, approved, bot is merging ⏳, 14.0

#1992 [14.0][FIX] Allows create line_section and line_note
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, bot is merging ⏳, 14.0

#1996 [12.0] Criar campos relacionais para faturas de retenções de impostos
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_move.py
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, 12.0, bot is merging ⏳

#1991 [12.0][FIX] Allows create line_section and line_note
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, 12.0, bot is merging ⏳

#1999 [14.0][FIX] l10n_br_account: fix view_account_invoice_filter
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#1907 [14.0][MIG] payment_pagseguro
  payment_pagseguro/README.rst
  payment_pagseguro/__init__.py
  payment_pagseguro/__manifest__.py
  payment_pagseguro/controllers/__init__.py
  payment_pagseguro/controllers/main.py
  payment_pagseguro/data/payment_acquirer_data.xml
  payment_pagseguro/i18n/payment_pagseguro.pot
  payment_pagseguro/models/__init__.py
  payment_pagseguro/models/payment_acquirer.py
  payment_pagseguro/models/payment_token.py
  payment_pagseguro/models/payment_transaction.py
  payment_pagseguro/readme/CONFIGURE.rst
  payment_pagseguro/readme/CONTRIBUTORS.rst
  payment_pagseguro/readme/CREDITS.rst
  payment_pagseguro/readme/DESCRIPTION.rst
  payment_pagseguro/readme/HISTORY.rst
  payment_pagseguro/readme/INSTALL.rst
  payment_pagseguro/readme/ROADMAP.rst
  payment_pagseguro/readme/USAGE.rst
  payment_pagseguro/static/description/icon.png
  payment_pagseguro/static/description/index.html
  payment_pagseguro/static/description/pagseguro_buy.png
  payment_pagseguro/static/description/pagseguro_website.png
  payment_pagseguro/static/description/payment_acquirer_01.png
  payment_pagseguro/static/description/payment_acquirer_02.png
  payment_pagseguro/static/src/img/pag_seguro_icon.jpg
  payment_pagseguro/static/src/js/pagseguro_tokenize_card.js
  payment_pagseguro/static/src/js/pagseguro_tour.js
  payment_pagseguro/tests/__init__.py
  payment_pagseguro/tests/test_pagseguro.py
  payment_pagseguro/views/payment_acquirer.xml
  payment_pagseguro/views/payment_pagseguro_templates.xml
  setup/payment_pagseguro/odoo/addons/payment_pagseguro
  setup/payment_pagseguro/setup.py
Labels: migration, bot is merging ⏳, 14.0
