Repository OCA/l10n-brazil, pull requests merged in 2022-12, with the labels that each got.

#2235 [14.0] Correções para corrigir campos na NF-e
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/models/spec_mixin.py
  l10n_br_nfe/tests/test_nfe_import.py
Labels: approved, bot is merging ⏳, 14.0

#2240 [14.0] Calculo dos impostos na entrada de importação
  l10n_br_fiscal/data/l10n_br_fiscal.tax.group.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_fiscal_tax.py
Labels: approved, bot is merging ⏳, 14.0

#2241 [16.0][FIX] PyCQA no longer has a gitlab mirror of repos
  .pre-commit-config.yaml
Labels: approved, bot is merging ⏳

#2177 [16.0][MIG] l10n_br_crm
  l10n_br_crm/README.rst
  l10n_br_crm/__init__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/i18n/l10n_br_crm.pot
  l10n_br_crm/i18n/pt_BR.po
  l10n_br_crm/models/__init__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/readme/CONFIGURE.rst
  l10n_br_crm/readme/CONTRIBUTORS.rst
  l10n_br_crm/readme/DESCRIPTION.rst
  l10n_br_crm/readme/INSTALL.rst
  l10n_br_crm/readme/ROADMAP.rst
  l10n_br_crm/readme/USAGE.rst
  l10n_br_crm/static/description/icon.png
  l10n_br_crm/static/description/index.html
  l10n_br_crm/tests/__init__.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_crm/views/crm_lead_view.xml
  l10n_br_crm/views/crm_quick_create_opportunity_form.xml
  setup/l10n_br_crm/odoo/addons/l10n_br_crm
  setup/l10n_br_crm/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, 16.0

#2231 [14.0][FIX] l10n_br_sale: required attribute for operation line
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#2239 [14.0][IMP] l10n_br_account_payment_order: add barcode field on account.payment.line
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_account_payment_order/models/bank_payment_line.py
  l10n_br_account_payment_order/views/account_move_line.xml
  l10n_br_account_payment_order/views/account_payment_line.xml
  l10n_br_account_payment_order/views/bank_payment_line.xml
Labels: approved, bot is merging ⏳

#2236 [14.0] spec_driven_model _export_fields dynamic dispatch
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/res_partner.py
  spec_driven_model/models/spec_export.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#2256 [12.0][FIX] pylint url on .pre-commit-config.yaml
  .pre-commit-config.yaml
Labels: approved, bot is merging ⏳

#2232 [14.0][FIX] l10n_br_sale: Amarrar lógica de descontos
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/readme/CONTRIBUTORS.rst
  l10n_br_sale/tests/__init__.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/tests/test_l10n_br_sale_discount.py
  l10n_br_sale/views/sale_view.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#2259 [14.0][IMP] l10n_br_fiscal: add event print feature
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/document_event.py
  l10n_br_fiscal/views/document_event_report.xml
  l10n_br_fiscal/views/document_event_template.xml
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#2264 [14.0][l10n_br_account_due_list][ADD] receivable and payable tests
  l10n_br_account_due_list/__manifest__.py
  l10n_br_account_due_list/tests/__init__.py
  l10n_br_account_due_list/tests/test_payments.py
Labels: approved, bot is merging ⏳

#2269 [14.0][l10n_br_account_due_list][REF] test cleanup
  l10n_br_account_due_list/tests/test_payments.py
Labels: approved, bot is merging ⏳

#2273 [14.0][spec_driven_model] fix export float monetary method
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200681583054000129550010000000012760018057-nf-e.xml
  spec_driven_model/models/spec_export.py
Labels: needs review, approved, bot is merging ⏳

#2271 [14.0][ADD] test-requirements.txt
  payment_pagseguro/__manifest__.py
  requirements.txt
  spec_driven_model/__manifest__.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#2246 [14.0][REF] l10n_br_account_nfe: create tags in compute methods
  l10n_br_account/views/fiscal_invoice_view.xml
  l10n_br_account_nfe/__manifest__.py
  l10n_br_account_nfe/demo/account_invoice_sn_demo.xml
  l10n_br_account_nfe/models/__init__.py
  l10n_br_account_nfe/models/document.py
  l10n_br_account_nfe/models/document_workflow.py
  l10n_br_account_nfe/models/leiauteNFe.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/views/nfe_document_view.xml
  l10n_br_nfe_spec/models/spec_models.py
Labels: approved, bot is merging ⏳

#2265 [14.0][IMP] Ajustes na criação de documento fiscal.
  l10n_br_account/models/fiscal_document.py
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳

#2276 [14.0][IMP] l10n_br_fiscal: ajustando estado do edoc quando o emissor é o parceiro e não a empresa
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: approved, bot is merging ⏳

#2274 [14.0][FIX] l10n_br_fiscal: UndefinedFunction: operator does not exist
  l10n_br_fiscal/models/comment.py
Labels: approved, bot is merging ⏳
