Repository OCA/l10n-brazil, pull requests merged in 2022-07, with the labels that each got.

#1986 [12.0] l10n_br_nfe: adiciona método match_or_create_m2o para product.product
  l10n_br_nfe/models/product_product.py
Labels: approved, bot is merging ⏳

#1997 [12.0][FIX] invoice_line_tax_ids field view widget
  l10n_br_account/views/account_invoice_line_view.xml
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, 12.0, bot is merging ⏳

#1830 [12.0][NEW] l10n_br_sale_commission
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_sale_commission/README.rst
  l10n_br_sale_commission/__init__.py
  l10n_br_sale_commission/__manifest__.py
  l10n_br_sale_commission/demo/res_config_settings_demo.xml
  l10n_br_sale_commission/demo/sale_order_demo.xml
  l10n_br_sale_commission/i18n/l10n_br_commission.pot
  l10n_br_sale_commission/models/__init__.py
  l10n_br_sale_commission/models/account_invoice_line.py
  l10n_br_sale_commission/models/res_config_settings.py
  l10n_br_sale_commission/models/sale_order_line.py
  l10n_br_sale_commission/models/settlement.py
  l10n_br_sale_commission/readme/CONFIGURE.rst
  l10n_br_sale_commission/readme/CONTRIBUTORS.rst
  l10n_br_sale_commission/readme/DESCRIPTION.rst
  l10n_br_sale_commission/readme/HISTORY.rst
  l10n_br_sale_commission/readme/INSTALL.rst
  l10n_br_sale_commission/readme/ROADMAP.rst
  l10n_br_sale_commission/readme/USAGE.rst
  l10n_br_sale_commission/static/description/icon.png
  l10n_br_sale_commission/static/description/index.html
  l10n_br_sale_commission/tests/__init__.py
  l10n_br_sale_commission/tests/test_l10n_br_sale_commission.py
  l10n_br_sale_commission/views/res_config_settings_views.xml
  l10n_br_sale_commission/views/sale_order.xml
  l10n_br_sale_commission/wizards/__init__.py
  l10n_br_sale_commission/wizards/wizard_invoice.py
  l10n_br_sale_commission/wizards/wizard_invoice.xml
  l10n_br_sale_stock/tests/test_sale_stock.py
  oca_dependencies.txt
  setup/l10n_br_sale_commission/odoo/addons/l10n_br_sale_commission
  setup/l10n_br_sale_commission/setup.py
Labels: approved, 12.0, bot is merging ⏳

#2001 [12.0][IMP] l10n_br_account_payment_brcobranca: update library BRcobranca to version 10.0.0
  l10n_br_account_payment_brcobranca/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2006 [12.0][FIX] payment_order / brcobranca: adiciona o código do convênio líder.
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_order/demo/account_payment_mode.xml
  l10n_br_account_payment_order/models/account_payment_order.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/views/account_payment_mode.xml
  l10n_br_account_payment_order/views/account_payment_order.xml
Labels: approved, bot is merging ⏳

#2004 [14.0][IMP] l10n_br_account_payment_brcobranca: update to BRcobranca v10.0.0
  l10n_br_account_payment_brcobranca/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2007 [12.0][l10n_br_contract][REF] cleaning: _id(s) -> _val(s)
  l10n_br_contract/models/contract_contract.py
Labels: approved, bot is merging ⏳

#2011 [14.0][FIX] payment_order / brcobranca: adiciona o código do convênio líder.
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_order/demo/account_payment_mode.xml
  l10n_br_account_payment_order/models/account_payment_order.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/views/account_payment_mode.xml
  l10n_br_account_payment_order/views/account_payment_order.xml
Labels: approved, bot is merging ⏳

#2010 [14.0][l10n_br_contract][REF] cleaning: _id(s) -> _val(s)
  l10n_br_contract/models/contract_contract.py
Labels: approved, bot is merging ⏳

#2016 [14.0][ADD] Read permission for fiscal document and document line
  l10n_br_account/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, 14.0

#2018 [12.0][ADD] read permission for fiscal document and document line
  l10n_br_account/security/ir.model.access.csv
Labels: approved, 12.0, bot is merging ⏳

#2017 [12.0] l10n_br_account: Considera ind_final no calculo dos impostos do account.invoice
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2015 [12.0][l10n_br_account][spec_model_driven] several hook fixes
  l10n_br_account/__init__.py
  l10n_br_account/__manifest__.py
  l10n_br_account/hooks.py
  spec_driven_model/hooks.py
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#1985 [12.0] l10n_br_nfe: Adição do wizard de importação de nf-e por xml
  l10n_br_nfe/__init__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/product_product.py
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200181583054000129550010000000052062777166.xml
  l10n_br_nfe/tests/test_nfe_import_wizard.py
  l10n_br_nfe/views/nfe_action.xml
  l10n_br_nfe/views/nfe_document_view.xml
  l10n_br_nfe/views/nfe_menu.xml
  l10n_br_nfe/wizards/__init__.py
  l10n_br_nfe/wizards/import_document.py
  l10n_br_nfe/wizards/import_document.xml
Labels: approved, ready to merge, bot is merging ⏳

#2022 [14.0][IMP] l10n_br_account: change city_taxation_code_id and service_type mandatory only fiscal document type equal out
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#2012 [12.0][FIX] Correções para o Boleto Santander.
  l10n_br_account_payment_brcobranca/models/account_move_line.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_brcobranca/tests/test_payment_order.py
  l10n_br_account_payment_brcobranca/tests/test_return_import.py
  l10n_br_account_payment_order/models/account_invoice.py
  l10n_br_account_payment_order/models/account_move_line.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/tests/test_base_class.py
  l10n_br_account_payment_order/tests/test_invoice_manual_workflow.py
  l10n_br_account_payment_order/tests/test_invoice_normal_workflow.py
  l10n_br_account_payment_order/tests/test_payment_order.py
  l10n_br_account_payment_order/tests/test_payment_order_change.py
  l10n_br_account_payment_order/tests/test_payment_order_inbound.py
  l10n_br_account_payment_order/views/account_move_line.xml
  l10n_br_account_payment_order/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳

#2025 [14.0][l10n_br_nfe][FIX] xFant same label warning
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳

#2026 [14.0][spec_model_driven][FIX] mute spurious selection warnings
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#2028 [14.0][IMP] l10n_br_account_payment_brcobranca: adding other ways to set brcobranca_api_url value
  l10n_br_account_payment_brcobranca/constants/br_cobranca.py
  l10n_br_account_payment_brcobranca/models/account_move.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#2037 [14.0][l10n_br_nfe][FIX] fix #2035 inconsistent/spurious translations
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2036 [14.0][FIX] exibição do campo "document_type_id" no acocunt.move
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#2034 [14.0][IMP] l10n_br_fiscal: add brazilian commercial fields on partner _commercial_fields
  l10n_br_fiscal/models/res_partner.py
Labels: approved, bot is merging ⏳

#2038 [12.0][l10n_br_nfe][FIX] fix #2035 inconsistent/spurious translations
  l10n_br_nfe/models/document.py
Labels: bot is merging ⏳

#2005 [14.0][MIG] l10n_br_account_nfe
  l10n_br_account/hooks.py
  l10n_br_account_nfe/README.rst
  l10n_br_account_nfe/__init__.py
  l10n_br_account_nfe/__manifest__.py
  l10n_br_account_nfe/demo/account_invoice_sn_demo.xml
  l10n_br_account_nfe/hooks.py
  l10n_br_account_nfe/i18n/l10n_br_account_nfe.pot
  l10n_br_account_nfe/models/__init__.py
  l10n_br_account_nfe/models/account_move_line.py
  l10n_br_account_nfe/models/account_payment_mode.py
  l10n_br_account_nfe/models/document_workflow.py
  l10n_br_account_nfe/readme/CONFIGURE.rst
  l10n_br_account_nfe/readme/CONTRIBUTORS.rst
  l10n_br_account_nfe/readme/DESCRIPTION.rst
  l10n_br_account_nfe/readme/HISTORY.rst
  l10n_br_account_nfe/readme/ROADMAP.rst
  l10n_br_account_nfe/readme/USAGE.rst
  l10n_br_account_nfe/static/description/icon.png
  l10n_br_account_nfe/static/description/index.html
  l10n_br_account_nfe/tests/__init__.py
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
  l10n_br_account_nfe/views/account_payment_mode.xml
  l10n_br_account_payment_order/demo/account_journal.xml
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_nfe/models/document.py
  setup/l10n_br_account_nfe/odoo/addons/l10n_br_account_nfe
  setup/l10n_br_account_nfe/setup.py
  spec_driven_model/hooks.py
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#2041 [12.0][l10n_br_nfe][FIX] xFant same label warning
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳

#2042 [14.0][FIX] l10n_br_nfe: fix make_pdf method
  l10n_br_nfe/models/document.py
Labels: bug, approved, bot is merging ⏳, 14.0

#2046 [FIX] brcobranca: add cep in sacado_endereco
  l10n_br_account_payment_brcobranca/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2045 [12.0][FIX] If you create NF-e without payment_mode_id
  l10n_br_account_nfe/models/document_workflow.py
Labels: approved, 12.0, bot is merging ⏳

#2040 [14.0][IMP] l10n_br_nfe: add accountant cnpj_cpf on autXML tag
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_config_settings.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/views/nfe_document_view.xml
  l10n_br_nfe/views/res_company_view.xml
Labels: approved, bot is merging ⏳, 14.0

#2048 [12.0][IMP] l10n_br_nfe: get nfe40_autXML default value
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_config_settings.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/views/nfe_document_view.xml
  l10n_br_nfe/views/res_company_view.xml
Labels: enhancement, approved, 12.0, bot is merging ⏳

#2049 [14.0] [FIX] If you create NF-e without payment_mode_id
  l10n_br_account_nfe/models/document_workflow.py
Labels: approved, bot is merging ⏳, 14.0

#2047 [14.0][RFC] l10n_br_contract: add brazilian fiscal data on contract line form
  l10n_br_contract/models/contract_contract.py
  l10n_br_contract/models/contract_line.py
  l10n_br_contract/models/res_company.py
  l10n_br_contract/views/contract_line.xml
  l10n_br_contract/views/contract_view.xml
  l10n_br_contract/views/res_company.xml
Labels: enhancement, approved, bot is merging ⏳, 14.0

#2031 [14.0][FIX] CNAB - Banco do Brasil - Código para protesto.
  l10n_br_account_payment_brcobranca/models/bank_payment_line.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0
