Repository OCA/l10n-brazil, pull requests merged in 2022-02, with the labels that each got.

#1797 14.0 account tax amount factor
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax_mixin.py
Labels: approved, bot is merging ⏳, 14.0

#1798 [12.0][REM] Removed the possibility to associate additional fee in Payment Mode Boleto
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/account_analytic_tag_data.xml
  l10n_br_account_payment_order/demo/account_payment_mode.xml
  l10n_br_account_payment_order/models/account_invoice.py
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/tests/test_payment_order.py
  l10n_br_account_payment_order/views/account_payment_mode.xml
Labels: approved, 12.0, bot is merging ⏳

#1750 [14.0][MIG] l10n_br_nfse
  l10n_br_nfse/README.rst
  l10n_br_nfse/__init__.py
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/constants/nfse.py
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/demo/product_demo.xml
  l10n_br_nfse/i18n/l10n_br_nfse.pot
  l10n_br_nfse/i18n/pt_BR.po
  l10n_br_nfse/models/__init__.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/product_template.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/readme/CONFIGURE.rst
  l10n_br_nfse/readme/CONTRIBUTORS.rst
  l10n_br_nfse/readme/DESCRIPTION.rst
  l10n_br_nfse/readme/INSTALL.rst
  l10n_br_nfse/readme/ROADMAP.rst
  l10n_br_nfse/readme/USAGE.rst
  l10n_br_nfse/report/danfse.xml
  l10n_br_nfse/security/ir.model.access.csv
  l10n_br_nfse/static/description/icon.png
  l10n_br_nfse/static/description/index.html
  l10n_br_nfse/static/src/img/itajuba.png
  l10n_br_nfse/tests/__init__.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/document_view.xml
  l10n_br_nfse/views/product_product_view.xml
  l10n_br_nfse/views/product_template_view.xml
  l10n_br_nfse/views/res_company_view.xml
  requirements.txt
  setup/l10n_br_nfse/odoo/addons/l10n_br_nfse
  setup/l10n_br_nfse/setup.py
Labels: approved, migration, bot is merging ⏳, 14.0

#1802 [12.0][FIX] Erro ao criar um imposto no fiscal quando o l10n_br_account esta intalado
  l10n_br_account/models/fiscal_tax.py
Labels: bug, approved, 12.0, bot is merging ⏳

#1770 [14.0][MIG] l10n_br_portal
  l10n_br_portal/README.rst
  l10n_br_portal/__init__.py
  l10n_br_portal/__manifest__.py
  l10n_br_portal/controllers/__init__.py
  l10n_br_portal/controllers/portal.py
  l10n_br_portal/demo/res_users_demo.xml
  l10n_br_portal/i18n/l10n_br_portal.pot
  l10n_br_portal/i18n/pt_BR.po
  l10n_br_portal/readme/CONFIGURE.rst
  l10n_br_portal/readme/CONTRIBUTORS.rst
  l10n_br_portal/readme/DESCRIPTION.rst
  l10n_br_portal/readme/INSTALL.rst
  l10n_br_portal/readme/ROADMAP.rst
  l10n_br_portal/readme/USAGE.rst
  l10n_br_portal/static/description/icon.png
  l10n_br_portal/static/description/index.html
  l10n_br_portal/static/description/screenshot1.png
  l10n_br_portal/static/lib/cleave/cleave.min.js
  l10n_br_portal/static/src/js/l10n_br_portal.js
  l10n_br_portal/static/src/js/l10n_br_portal_tour.js
  l10n_br_portal/tests/__init__.py
  l10n_br_portal/tests/test_load_process.py
  l10n_br_portal/views/assets.xml
  l10n_br_portal/views/portal_templates.xml
  setup/l10n_br_portal/odoo/addons/l10n_br_portal
  setup/l10n_br_portal/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 14.0

#1771 [14.0][MIG] l10n_br_hr
  l10n_br_hr/README.rst
  l10n_br_hr/__init__.py
  l10n_br_hr/__manifest__.py
  l10n_br_hr/data/dependent_type_data.xml
  l10n_br_hr/data/hr_deficiency_data.xml
  l10n_br_hr/data/hr_educational_attainment_data.xml
  l10n_br_hr/data/hr_ethnicity_data.xml
  l10n_br_hr/data/l10n_br_hr.cbo.csv
  l10n_br_hr/demo/hr_employee_dependent_demo.xml
  l10n_br_hr/i18n/l10n_br_hr.pot
  l10n_br_hr/i18n/pt_BR.po
  l10n_br_hr/models/__init__.py
  l10n_br_hr/models/data_abstract.py
  l10n_br_hr/models/hr_civil_certificate_type.py
  l10n_br_hr/models/hr_deficiency.py
  l10n_br_hr/models/hr_dependent_type.py
  l10n_br_hr/models/hr_educational_attainment.py
  l10n_br_hr/models/hr_employee.py
  l10n_br_hr/models/hr_employee_dependent.py
  l10n_br_hr/models/hr_ethnicity.py
  l10n_br_hr/models/hr_identity_type.py
  l10n_br_hr/models/hr_job.py
  l10n_br_hr/models/l10n_br_hr_cbo.py
  l10n_br_hr/models/res_company.py
  l10n_br_hr/models/res_partner.py
  l10n_br_hr/readme/CONFIGURE.rst
  l10n_br_hr/readme/CONTRIBUTORS.rst
  l10n_br_hr/readme/DESCRIPTION.rst
  l10n_br_hr/readme/INSTALL.rst
  l10n_br_hr/readme/ROADMAP.rst
  l10n_br_hr/readme/USAGE.rst
  l10n_br_hr/security/ir.model.access.csv
  l10n_br_hr/static/description/icon.png
  l10n_br_hr/static/description/index.html
  l10n_br_hr/tests/__init__.py
  l10n_br_hr/tests/test_hr_employee_dependent.py
  l10n_br_hr/tests/test_l10n_br_hr.py
  l10n_br_hr/views/hr_employee_dependent_view.xml
  l10n_br_hr/views/hr_employee_view.xml
  l10n_br_hr/views/hr_job_view.xml
  l10n_br_hr/views/inherited_hr_contract.xml
  l10n_br_hr/views/l10n_br_hr_cbo_view.xml
  l10n_br_hr/views/res_company_view.xml
  setup/l10n_br_hr/odoo/addons/l10n_br_hr
  setup/l10n_br_hr/setup.py
Labels: needs review, migration, bot is merging ⏳, 14.0

#1807 [12.0] Atualização da tabela de CFOPs
  l10n_br_fiscal/data/l10n_br_fiscal.cfop.csv
Labels: approved, 12.0, bot is merging ⏳

#1814 [12.0][FIX] Confirmação do documento quando o emitente é o parceiro
  l10n_br_fiscal/models/document_workflow.py
Labels: bug, approved, 12.0, bot is merging ⏳

#1808 [14.0] Atualização da tabela de CFOPs
  l10n_br_fiscal/data/l10n_br_fiscal.cfop.csv
Labels: approved, bot is merging ⏳

#1809 [12.0] Alterações relacionadas ao campo ind_final
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/account_tax.py
  l10n_br_contract/models/contract_line.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/res_partner.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/operation_view.xml
  l10n_br_fiscal/views/res_partner_view.xml
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_repair/models/repair_fee.py
  l10n_br_repair/models/repair_line.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/views/sale_view.xml
  l10n_br_stock_account/models/stock_move.py
Labels: approved, 12.0, bot is merging ⏳

#1817 [12.0][FIX] l10n_br_sale_stock: Concatenation of Sale Note and Customer Additional Data.
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#1805 [12.0][FIX] l10n_br_account: dummy fiscal document line correction
  l10n_br_account/models/account_invoice.py
Labels: bot is merging ⏳

#1818 [12.0][FIX] Wrong inverse for field nfe40_tpImp
  l10n_br_nfe/models/document.py
Labels: approved, 12.0, bot is merging ⏳
