Repository OCA/l10n-brazil, pull requests merged in 2023-09, with the labels that each got.

#2672 [14.0][FIX] Delete modules on DFe migration
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/14.0.19.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#2675 [14.0][FIX+IMP] l10n_br_nfe: Endereço da Transportadora na NFe duplicando o Número
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳

#2676 [14.0][FIX] l10n_br_sale_stock: Na criação da Fatura a partir do Picking buscar o Modo de Pagto e Inconterm do Pedido de Vendas relacionado
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#2674 [14.0][IMP] l10n_br_nfe: Verificar campos necessários para Gerar Chave EDOC
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2679 [14.0][REF] l10n_br_stock_account_report: Substituição da precisão decimal "Account" pelo método da Moeda/res.currency
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard.py
Labels: approved, bot is merging ⏳

#2677 [14.0][REF] l10n_br_account_payment_order: Substituição da precisão decimal "Account" pelo método da Moeda/res.currency
  l10n_br_account_payment_order/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2678 [14.0][REF] l10n_br_account_payment_brcobranca: Substituição da precisão decimal "Account" pelo método da Moeda/res.currency
  l10n_br_account_payment_brcobranca/models/account_move_line.py
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
Labels: approved, bot is merging ⏳

#2628 [14.0][FIX] l10n_br_nfse_paulistana: fix ValorCargaTributaria and FonteCarg…
  l10n_br_nfse_paulistana/models/document.py
  l10n_br_nfse_paulistana/tests/nfse/paulistana.xml
Labels: approved, ready to merge, bot is merging ⏳

#2684 [14.0][REF] l10n_br_purchase, l10n_br_purchase_stock, l10n_br_sale_stock, l10n_br_stock_account: Dados de Demonstração para evitar erro no modulo MRP
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/demo/product.xml
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_sale_stock/demo/sale_order_demo.xml
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
Labels: approved, bot is merging ⏳

#2662 [14.0][FIX] sales, stock: Pedido de venda com produtos KITs.
  l10n_br_setup_tests/README.rst
  l10n_br_setup_tests/__init__.py
  l10n_br_setup_tests/__manifest__.py
  l10n_br_setup_tests/readme/CONTRIBUTORS.rst
  l10n_br_setup_tests/readme/DESCRIPTION.rst
  l10n_br_setup_tests/readme/HISTORY.rst
  l10n_br_setup_tests/tests/__init__.py
  l10n_br_setup_tests/tests/test_sale_picking.py
  l10n_br_stock_account/models/stock_rule.py
  l10n_br_stock_account/readme/HISTORY.rst
  oca_dependencies.txt
  setup/l10n_br_setup_tests/odoo/addons/l10n_br_setup_tests
  setup/l10n_br_setup_tests/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2692 [14.0][FIX] l10n_br_sale: returns a list of moves instead of record set
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#2689 [14.0][FIX] Quando parceiro estrangeiro com algum valor no CNPJ/Vat dá erro: Compute method... nfe40_choice2
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳

#2626 [14.0][ADD] l10n_br_sale_blanket_order: new module
  l10n_br_sale_blanket_order/README.rst
  l10n_br_sale_blanket_order/__init__.py
  l10n_br_sale_blanket_order/__manifest__.py
  l10n_br_sale_blanket_order/demo/l10n_br_sale_blanket_order.xml
  l10n_br_sale_blanket_order/models/__init__.py
  l10n_br_sale_blanket_order/models/sale_blanket_order.py
  l10n_br_sale_blanket_order/models/sale_blanket_order_line.py
  l10n_br_sale_blanket_order/readme/CONTRIBUTORS.rst
  l10n_br_sale_blanket_order/readme/DESCRIPTION.rst
  l10n_br_sale_blanket_order/readme/USAGE.rst
  l10n_br_sale_blanket_order/static/description/icon.png
  l10n_br_sale_blanket_order/static/description/index.html
  l10n_br_sale_blanket_order/tests/__init__.py
  l10n_br_sale_blanket_order/tests/test_l10n_br_sale_blanket_order.py
  l10n_br_sale_blanket_order/views/sale_blanket_order.xml
  l10n_br_sale_blanket_order/wizards/__init__.py
  l10n_br_sale_blanket_order/wizards/sale_blanket_order_wizard.py
  setup/l10n_br_sale_blanket_order/odoo/addons/l10n_br_sale_blanket_order
  setup/l10n_br_sale_blanket_order/setup.py
Labels: approved, bot is merging ⏳

#2694 [14.0][FIX] l10n_br_nfe: Resolvendo Warnings do modulo
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_supplement.py
  l10n_br_nfe/models/invalidate_number.py
  l10n_br_nfe/models/mde.py
  l10n_br_nfe/tests/test_account_customer_invoice.py
  l10n_br_nfe/tests/test_account_nfe_refund.py
  l10n_br_nfe/tests/test_account_supplier_nfe.py
  l10n_br_nfe/tests/test_nfe_export.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_structure.py
Labels: approved, bot is merging ⏳

#2693 [14.0][FIX] l10n_br_fiscal_dfe: Dependência do modulo l10n_br_fiscal_certificate e Warnings no LOG
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_fiscal_dfe/models/attachment.py
  l10n_br_fiscal_dfe/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2686 [14.0][ADD] UOM alternative data
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/uom_alternative_data.xml
  l10n_br_fiscal/data/uom_data.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200681583054000129550010000000012760018057-nf-e.xml
Labels: approved, bot is merging ⏳, 14.0

#2699 [14.0][FIX] erpbrasil.transmissão dependency
  l10n_br_ie_search/__manifest__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse_ginfes/__manifest__.py
  l10n_br_nfse_paulistana/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#2695 [14.0][l10n_br_fiscal_certificate][FIX] robust demo mode detection
  l10n_br_fiscal_certificate/hooks.py
Labels: approved, blocked, bot is merging ⏳

#2700 [14.0][FIX] l10n_br_fiscal: CSLL tax percent
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
Labels: approved, bot is merging ⏳

#2687 [12.0][ADD] UOM alternative data
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/uom_alternative_data.xml
  l10n_br_fiscal/data/uom_data.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200181583054000129550010000000052062777166.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200681583054000129550010000000012760018057-nf-e.xml
  l10n_br_nfe/tests/test_nfe_import_wizard.py
Labels: approved, 12.0, bot is merging ⏳

#2704 [14.0][FIX] l10n_br_account_payment_brcobranca: due_date referenced before
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#2703 [14.0][FIX] l10n_br_contract: fix contract line report view
  l10n_br_contract/models/contract_line.py
  l10n_br_contract/views/contract_line.xml
Labels: approved, bot is merging ⏳

#2596 [14.0][l10n_br_cte_spec] leiautes abstratos para Conhecimento de Transporte electrónico (CT-e) versão 4.00
  .pre-commit-config.yaml
  l10n_br_cte_spec/__init__.py
  l10n_br_cte_spec/__manifest__.py
  l10n_br_cte_spec/models/__init__.py
  l10n_br_cte_spec/models/spec_models.py
  l10n_br_cte_spec/models/v4_0/__init__.py
  l10n_br_cte_spec/models/v4_0/cte_modal_aereo_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_aquaviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_dutoviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_ferroviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_rodoviario_os_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_rodoviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_multi_modal_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_tipos_basico_v4_00.py
  l10n_br_cte_spec/models/v4_0/evento_cte_tipos_basico_v4_00.py
  l10n_br_cte_spec/models/v4_0/tipos_geral_cte_v4_00.py
  l10n_br_cte_spec/readme/CONTRIBUTORS.rst
  l10n_br_cte_spec/readme/DESCRIPTION.rst
  l10n_br_cte_spec/static/description/icon.png
  l10n_br_cte_spec/static/description/index.html
  l10n_br_cte_spec/tests/__init__.py
  l10n_br_cte_spec/tests/test_cte_import.py
  setup/l10n_br_cte_spec/odoo/addons/l10n_br_cte_spec
  setup/l10n_br_cte_spec/setup.py
Labels: bot is merging ⏳

#2485 [14.0][l10n_br_mdfe_spec] leiautes abstratos do Manifesto Eletrônico de Documentos Fiscais (MDF-e)
  .pre-commit-config.yaml
  l10n_br_mdfe_spec/__init__.py
  l10n_br_mdfe_spec/__manifest__.py
  l10n_br_mdfe_spec/models/__init__.py
  l10n_br_mdfe_spec/models/spec_models.py
  l10n_br_mdfe_spec/models/v3_0/__init__.py
  l10n_br_mdfe_spec/models/v3_0/ev_pagto_oper_mdfe_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_aereo_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_aquaviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_ferroviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_rodoviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_tipos_basico_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/tipos_geral_mdfe_v3_00.py
  l10n_br_mdfe_spec/readme/CONTRIBUTORS.rst
  l10n_br_mdfe_spec/readme/DESCRIPTION.rst
  l10n_br_mdfe_spec/static/description/icon.png
  l10n_br_mdfe_spec/static/description/index.html
  l10n_br_mdfe_spec/tests/__init__.py
  l10n_br_mdfe_spec/tests/test_mdfe_import.py
  setup/l10n_br_mdfe_spec/odoo/addons/l10n_br_mdfe_spec
  setup/l10n_br_mdfe_spec/setup.py
Labels: bot is merging ⏳

#2590 [14.0][l10n_br_account] account move tests
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/common.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/tests/test_account_move_sn.py
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, bot is merging ⏳

#2716 [14.0][FIX] l10n_br_zip: change PyCEP-Correios to BrazilCEP
  l10n_br_zip/__manifest__.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/readme/HISTORY.rst
  l10n_br_zip/readme/INSTALL.rst
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
  requirements.txt
Labels: approved, bot is merging ⏳

#2717 [FIX] l10n_br_sale: Impostos errados na geração da fatura pelo pedido.
  l10n_br_sale/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#2720 [14.0][l10n_br_nfe][l10n_br_stock_account_report][l10n_br_nfse_paulistana][l10n_br_nfse_ginfes] no import tests
  l10n_br_nfe/__init__.py
  l10n_br_nfse_ginfes/__init__.py
  l10n_br_nfse_paulistana/__init__.py
  l10n_br_stock_account_report/__init__.py
Labels: approved, bot is merging ⏳

#2721 [14.0][FIX] l10n_br_base: Informar os campo de Outras Inscrições Estaduais na visão da Empresa
  l10n_br_base/models/__init__.py
  l10n_br_base/models/res_company.py
  l10n_br_base/models/state_tax_numbers.py
  l10n_br_base/tests/__init__.py
  l10n_br_base/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#2724 [14.0][REF] l10n_br_account_payment_order, l10n_br_account_payment_brcobranca: Movido o botão Imprimir Boleto para permitir herda-lo e evitar duplicação de código
  l10n_br_account_payment_brcobranca/__manifest__.py
  l10n_br_account_payment_brcobranca/models/__init__.py
  l10n_br_account_payment_brcobranca/models/account_move.py
  l10n_br_account_payment_brcobranca/parser/__init__.py
  l10n_br_account_payment_brcobranca/views/account_move_view.xml
  l10n_br_account_payment_order/models/account_move.py
  l10n_br_account_payment_order/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#2671 [14.0][FIX] fiscal,account: Atualizar os valores do DIFAL ao atualizar o indicador de "Contribuinte do ICMS"
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/tax.py
Labels: bot is merging ⏳
