Repository OCA/l10n-brazil, pull requests merged in 2023-03, with the labels that each got.

#2360 [14.0][FIX] Incoterms definido na fatura para o documento fiscal.
  l10n_br_account/models/account_invoice.py
  l10n_br_delivery_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2364 [12.0][FIX] pre-commit
  l10n_br_fiscal/models/tax.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/views/nfe_document_line_view.xml
Labels: approved, bot is merging ⏳

#2354 [14.0][FIX] l10n_br_sale: sale onchange product fiscal price with price list
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/tests/__init__.py
  l10n_br_sale/tests/test_l10n_br_sale_pricelist.py
Labels: approved, ready to merge, bot is merging ⏳

#2365 [12.0][RFC] Extract Fiscal Closing (port from 14.0)
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/12.0.31.0.0/pre-migration.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal_closing/README.rst
  l10n_br_fiscal_closing/__init__.py
  l10n_br_fiscal_closing/__manifest__.py
  l10n_br_fiscal_closing/models/__init__.py
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/models/document.py
  l10n_br_fiscal_closing/readme/CONFIGURE.rst
  l10n_br_fiscal_closing/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_closing/readme/CREDITS.rst
  l10n_br_fiscal_closing/readme/DESCRIPTION.rst
  l10n_br_fiscal_closing/readme/HISTORY.rst
  l10n_br_fiscal_closing/readme/INSTALL.rst
  l10n_br_fiscal_closing/readme/ROADMAP.rst
  l10n_br_fiscal_closing/readme/USAGE.rst
  l10n_br_fiscal_closing/security/ir.model.access.csv
  l10n_br_fiscal_closing/static/description/icon.png
  l10n_br_fiscal_closing/static/description/index.html
  l10n_br_fiscal_closing/tests/__init__.py
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_fiscal_closing/views/closing.xml
  setup/l10n_br_fiscal_closing/odoo/addons/l10n_br_fiscal_closing
  setup/l10n_br_fiscal_closing/setup.py
Labels: approved, bot is merging ⏳

#2368 [12.0][l10n_br_fiscal] amount taxes
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/tests/test_fiscal_tax.py
Labels: approved, bot is merging ⏳

#2378 [16.0][FIX] ignore case sensitive in res.city search
  l10n_br_zip/models/l10n_br_zip.py
Labels: bug, approved, bot is merging ⏳, 16.0

#2376 [14.0][FIX] ignore case sensitive in res.city search
  l10n_br_zip/models/l10n_br_zip.py
Labels: bug, approved, bot is merging ⏳, 14.0

#2375 [12.0][FIX] ignore case sensitive in res.city search
  l10n_br_zip/models/l10n_br_zip.py
Labels: bug, approved, 12.0, bot is merging ⏳

#2372 [14.0][FIX] l10n_br_hr: add group hr.group_hr_user on private brazilian fields
  l10n_br_hr/models/hr_employee.py
Labels: approved, bot is merging ⏳

#2369 [14.0][FIX] Busca a descrição correta para a linha da nota fiscal (Tag xProd)
  l10n_br_nfe/models/document_line.py
Labels: approved, ready to merge, bot is merging ⏳

#2380 [FIX] isort version
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#2381 [12.0][l10n_br_nfe][FIX] Troca campo nfe40_nFat de related para computed
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2390 [14.0][IMP] l10n_br_account_payment_order: document number of payment line in tree view
  l10n_br_account_payment_order/views/account_move_line.xml
Labels: approved, bot is merging ⏳

#2398 [FIX] l10n_br_pos: script migration
  l10n_br_pos/migration/14.0.1.1.0/pre-migration.py
Labels: approved, bot is merging ⏳

#2388 [12.0][BACKPORT] l10n_br_fiscal: backport from 14.0 #2276
  .github/workflows/test.yml
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: approved, ready to merge, bot is merging ⏳

#2391 [14.0][IMP] l10n_br_account_payment_order: document number in bank line treee
  l10n_br_account_payment_order/views/bank_payment_line.xml
Labels: approved, bot is merging ⏳

#2399 [12.0][IMP]l10n_br_fiscal: populate date in out partner issuer document BKP #2280
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_nfe/models/document.py
  l10n_br_nfse/models/document.py
Labels: approved, bot is merging ⏳

#2400 [FIX] l10n_br_account: discount on subtotal
  l10n_br_account/models/account_invoice_line.py
Labels: approved, bot is merging ⏳

#2401 [14.0][IMP] l10n_br_account: discount tests
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_invoice_general_cases.py
Labels: approved, bot is merging ⏳

#2405 [14.0][FIX] l10n_br_account: required invisible uot_id
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#2404 [14.0][FIX] l10n_br_account: uot_id context in compute_all
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/account_tax.py
Labels: approved, bot is merging ⏳

#2406 [14.0][FIX] l10n_br_purchase: ind final from order to move
  l10n_br_purchase/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2402 [FIX][14.0] l10n_br_pos: correção no nome do método e da chave de retorno
  l10n_br_pos/models/pos_order.py
  l10n_br_pos/static/src/js/models.js
  l10n_br_pos/tests/test_l10n_br_pos_order.py
Labels: needs fixing, approved, bot is merging ⏳
