Repository OCA/l10n-brazil, pull requests merged in 2023-07, with the labels that each got.

#2573 [14.0][FIX] l10n_br_account_payment_order: don't copy CNAB fields for invoice
  l10n_br_account_payment_order/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2539 [14.0][FIX] l10n_br_nfe: Rejeição: CFOP de Importação e não informado dados de II
  l10n_br_fiscal/data/l10n_br_fiscal.cfop.csv
  l10n_br_fiscal/models/cfop.py
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#2577 [14.0][FIX] l10n_br_nfse: fixes the value of the field base_calculo that goes to the xml
  l10n_br_nfse/models/document.py
Labels: approved, bot is merging ⏳

#2371 [14.0][spec_driven_model][l10n_br_nfe_spec][l10n_br_nfe] NFe com bindings xsdata
  l10n_br_nfe/hooks.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/invalidate_number.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_webservices.py
  l10n_br_nfe_spec/models/spec_models.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/tests/purchase_order_lib.py
  spec_driven_model/tests/spec_poxsd.py
  spec_driven_model/tests/spec_purchase.py
  spec_driven_model/tests/test_spec_model.py
Labels: refactoring, approved, bot is merging ⏳, 14.0

#2575 [14.0][l10n_br_fiscal] simplified typo fix
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/i18n/l10n_br_fiscal.pot
  l10n_br_fiscal/i18n/pt_BR.po
  l10n_br_fiscal/migrations/14.0.14.0.0/pre-migration.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/res_company_view.xml
Labels: bot is merging ⏳

#2579 [14.0][l10n_br_coa_simple][FIX] missing tax receivable account
  l10n_br_coa_simple/data/l10n_br_coa_simple_template_post.xml
Labels: approved, bot is merging ⏳

#2580 [12.0][l10n_br_fiscal] simplified typo fix
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/i18n/l10n_br_fiscal.pot
  l10n_br_fiscal/i18n/pt_BR.po
  l10n_br_fiscal/migrations/12.0.35.0.0/pre-migration.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/res_company_view.xml
Labels: approved, 12.0, bot is merging ⏳, backport

#2578 [12.0][FIX] l10n_br_nfe: Rejeição: CFOP de Importação e não informado dados de II
  l10n_br_fiscal/data/l10n_br_fiscal.cfop.csv
  l10n_br_fiscal/models/cfop.py
  l10n_br_nfe/models/document_line.py
Labels: approved, 12.0, bot is merging ⏳, backport

#2581 [12.0][l10n_br_fiscal] infors typo fix
  l10n_br_account/views/fiscal_invoice_line_view.xml
  l10n_br_fiscal/views/document_line_view.xml
Labels: approved, 12.0, bot is merging ⏳, backport

#2585 [FIX][l10n_br_coa] conta ICMS SN à recolher
  l10n_br_coa_simple/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_coa_simple/data/l10n_br_coa_simple_template_post.xml
Labels: approved, bot is merging ⏳

#2587 [12.0][l10n_br_base][BUG] Removido o método _set_street do res.partner
  l10n_br_base/models/res_partner.py
Labels: bug, approved, 12.0, bot is merging ⏳

#2589 [FIX][14.0] mock cancelamento NFe
  l10n_br_nfe/tests/test_nfe_webservices.py
Labels: approved, bot is merging ⏳

#2591 [14.0][FIX] l10n_br_fiscal: remove duplicate code
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳

#2593 [14.0][l10n_br_fiscal] Melhorias nas visões do documento Fiscal
  l10n_br_fiscal/models/document_eletronic.py
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#2594 [14.0][muitos modulos] fix demo mode detection
  l10n_br_account_nfe/hooks.py
  l10n_br_base/__init__.py
  l10n_br_cnab_structure/hooks.py
  l10n_br_coa_generic/hooks.py
  l10n_br_coa_simple/hooks.py
  l10n_br_fiscal/hooks.py
  l10n_br_purchase/hooks.py
  l10n_br_sale/hooks.py
  l10n_br_stock/hooks.py
  l10n_br_stock_account/hooks.py
Labels: approved, bot is merging ⏳

#2595 [14.0][l10n_br_coa][l10n_br_simple][l10n_br_generic] refactor load fiscal taxes
  l10n_br_account/hooks.py
  l10n_br_account/models/__init__.py
  l10n_br_account/models/account_chart_template.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa_generic/hooks.py
  l10n_br_coa_simple/hooks.py
Labels: bot is merging ⏳

#2499 [14.0][FIX] l10n_br_sale: Divisão do faturamento em múltiplos documentos fiscais.
  l10n_br_sale/models/sale_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2602 [14.0][FIX] l10n_br_product_contract: is_contract
  l10n_br_product_contract/demo/sale_order.xml
Labels: approved, bot is merging ⏳

#2545 [14.0] Fiscal Tax Benefit
  l10n_br_fiscal/constants/icms.py
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/models/tax_definition_benefit.py
  l10n_br_fiscal/models/tax_definition_icms.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_icms_regulation.py
  l10n_br_fiscal/tests/test_tax_benefit.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/tax_definition_view.xml
  l10n_br_nfe/models/document_line.py
Labels: new feature, approved, bot is merging ⏳, 14.0

#2607 [14.0][FIX] l10n_br_sale: fix company page xpath
  l10n_br_sale/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#2608 [14.0][FIX] l10n_br_purchase: fix company page xpath
  l10n_br_purchase/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#2609 [14.0][FIX] l10n_br_stock_account: fix company page xpath
  l10n_br_stock_account/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#2610 [14.0][FIX] l10n_br_repair: fix company page xpath
  l10n_br_repair/views/res_company.xml
Labels: approved, bot is merging ⏳

#2611 [14.0][FIX] l10n_br_contract: fix company page xpath
  l10n_br_contract/views/res_company.xml
Labels: approved, bot is merging ⏳

#2111 [14.0][MIG] l10n_br_nfse_ginfes
  l10n_br_nfse_ginfes/README.rst
  l10n_br_nfse_ginfes/__init__.py
  l10n_br_nfse_ginfes/__manifest__.py
  l10n_br_nfse_ginfes/constants/ginfes.py
  l10n_br_nfse_ginfes/i18n/l10n_br_nfse_ginfes.pot
  l10n_br_nfse_ginfes/i18n/pt_BR.po
  l10n_br_nfse_ginfes/models/__init__.py
  l10n_br_nfse_ginfes/models/document.py
  l10n_br_nfse_ginfes/models/res_company.py
  l10n_br_nfse_ginfes/readme/CONFIGURE.rst
  l10n_br_nfse_ginfes/readme/CONTRIBUTORS.rst
  l10n_br_nfse_ginfes/readme/DESCRIPTION.rst
  l10n_br_nfse_ginfes/readme/INSTALL.rst
  l10n_br_nfse_ginfes/readme/ROADMAP.rst
  l10n_br_nfse_ginfes/readme/USAGE.rst
  l10n_br_nfse_ginfes/static/description/icon.png
  l10n_br_nfse_ginfes/static/description/index.html
  l10n_br_nfse_ginfes/static/src/img/itajuba.png
  l10n_br_nfse_ginfes/tests/__init__.py
  l10n_br_nfse_ginfes/tests/nfse/001_50_nfse.xml
  l10n_br_nfse_ginfes/tests/test_fiscal_document_nfse_ginfes.py
  requirements.txt
  setup/l10n_br_nfse_ginfes/odoo/addons/l10n_br_nfse_ginfes
  setup/l10n_br_nfse_ginfes/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 14.0

#2606 [14.0][FIX] l10n_br_fiscal: fix access to contact form
  l10n_br_fiscal/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2560 [14.0][l10n_br_account] kill dummy records
  l10n_br_account/__init__.py
  l10n_br_account/__manifest__.py
  l10n_br_account/hooks.py
  l10n_br_account/migrations/14.0.9.0.0/post-migration.py
  l10n_br_account/models/__init__.py
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_account/models/ir_model_data.py
  l10n_br_account/models/res_company.py
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_company_fiscal_dummy.py
  l10n_br_account/tests/test_customer_invoice_dummy.py
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_account_nfe/models/account_move_line.py
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: approved, bot is merging ⏳

#2613 [14.0][l10n_br_account][DEL] remove l10n_br_account.document.line.mixin dead code
  l10n_br_account/models/__init__.py
  l10n_br_account/models/account_document_line_mixin.py
Labels: approved, bot is merging ⏳

#2582 [14.0][NEW] l10n_br_ie_search
  l10n_br_ie_search/README.rst
  l10n_br_ie_search/__init__.py
  l10n_br_ie_search/__manifest__.py
  l10n_br_ie_search/models/__init__.py
  l10n_br_ie_search/models/l10n_br_base_party_mixin.py
  l10n_br_ie_search/models/res_config_settings.py
  l10n_br_ie_search/models/sefaz_webservice.py
  l10n_br_ie_search/models/sintegra_webservice.py
  l10n_br_ie_search/readme/CONFIGURE.rst
  l10n_br_ie_search/readme/CONTRIBUTORS.rst
  l10n_br_ie_search/readme/DESCRIPTION.rst
  l10n_br_ie_search/readme/USAGE.rst
  l10n_br_ie_search/static/description/index.html
  l10n_br_ie_search/static/icon.png
  l10n_br_ie_search/tests/__init__.py
  l10n_br_ie_search/tests/test_sefaz.py
  l10n_br_ie_search/tests/test_sintegra.py
  l10n_br_ie_search/views/res_config_settings_view.xml
  setup/l10n_br_ie_search/odoo/addons/l10n_br_ie_search
  setup/l10n_br_ie_search/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2616 [14.0][FIX] l10n_br_account: set doc line to right move line
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/fiscal_document_line.py
Labels: approved, bot is merging ⏳

#2618 [14.0][IMP] l10n_br_fiscal: remove required for field fiscal_profile_id
  l10n_br_fiscal/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2584 [14.0][FIX] l10n_br_nfse_paulistana: emissão de NFS-e com descontos.
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse_paulistana/models/document.py
Labels: approved, ready to merge, bot is merging ⏳

#2622 [14.0][l10n_br_fiscal][REF] unnest tools dir
  l10n_br_fiscal/models/cest.py
  l10n_br_fiscal/models/document_event.py
  l10n_br_fiscal/models/nbm.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/models/tax_pis_cofins.py
  l10n_br_fiscal/tools.py
  l10n_br_fiscal/tools/__init__.py
Labels: approved, bot is merging ⏳

#2621 [14.0][FIX] l10n_br_nfse_paulistana: remove issret hard coded
  l10n_br_nfse_paulistana/models/document.py
Labels: approved, ready to merge, bot is merging ⏳

#2619 [14.0][FIX] l10n_br_nfse_paulistana: Municipal registration is EMPTY if the city of the recipient differs from the city of the provider.
  l10n_br_nfse_paulistana/models/document.py
Labels: approved, ready to merge, bot is merging ⏳
