Repository OCA/l10n-brazil, pull requests merged in 2023-04, with the labels that each got.

#2407 [14.0] [FIX] l10n_br_account: generate all move line in general test invoice
  l10n_br_account/tests/test_invoice_general_cases.py
Labels: approved, bot is merging ⏳

#2370 [14.0][l10n_br_account] fixes OCA#1813 skip bad recomputes
  l10n_br_account/__init__.py
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/tests/test_customer_invoice_dummy.py
  l10n_br_account/tests/test_supplier_invoice_dummy.py
Labels: bug, approved, ready to merge, bot is merging ⏳

#2422 [14.0][l10n_br_account] fix bad recompute final
  l10n_br_account/__init__.py
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_account/tests/test_customer_invoice_dummy.py
  l10n_br_account/tests/test_supplier_invoice_dummy.py
  l10n_br_nfe/models/document_line.py
  l10n_br_purchase_stock/wizards/stock_invocing_onshipping.py
Labels: approved, bot is merging ⏳

#2426 [14.0][DOC] proper module dependencies
  l10n_br_base/readme/INSTALL.rst
Labels: approved, bot is merging ⏳

#2423 [14.0][FIX] fix for 'NoneType' object is not iterable
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#2425 [14.0][FIX] break explicitly when demo deps are missing
  l10n_br_account/hooks.py
Labels: approved, bot is merging ⏳

#2428 [14.0][MIG] l10n_br_product_contract: Migration to 14.0
  l10n_br_product_contract/README.rst
  l10n_br_product_contract/__init__.py
  l10n_br_product_contract/__manifest__.py
  l10n_br_product_contract/demo/contract_template.xml
  l10n_br_product_contract/demo/product.xml
  l10n_br_product_contract/demo/sale_order.xml
  l10n_br_product_contract/i18n/l10n_br_product_contract.pot
  l10n_br_product_contract/models/__init__.py
  l10n_br_product_contract/models/sale_order.py
  l10n_br_product_contract/models/sale_order_line.py
  l10n_br_product_contract/readme/CONFIGURE.rst
  l10n_br_product_contract/readme/CONTRIBUTORS.rst
  l10n_br_product_contract/readme/CREDITS.rst
  l10n_br_product_contract/readme/DESCRIPTION.rst
  l10n_br_product_contract/readme/HISTORY.rst
  l10n_br_product_contract/readme/INSTALL.rst
  l10n_br_product_contract/readme/USAGE.rst
  l10n_br_product_contract/static/description/icon.png
  l10n_br_product_contract/static/description/index.html
  l10n_br_product_contract/tests/__init__.py
  l10n_br_product_contract/tests/test_l10n_br_product_contract.py
  setup/l10n_br_product_contract/odoo/addons/l10n_br_product_contract
  setup/l10n_br_product_contract/setup.py
Labels: approved, bot is merging ⏳

#2432 [14.0][BUG] Erro ao salvar certificado
  l10n_br_fiscal/models/certificate.py
Labels: bug, approved, bot is merging ⏳, 14.0

#2431 [12.0][BUG] Erro ao salvar certificado
  l10n_br_fiscal/models/certificate.py
Labels: bug, approved, 12.0, bot is merging ⏳

#2434 [12.0][FIX] nfe40_pICMSInter compute
  l10n_br_nfe/models/document_line.py
Labels: approved, 12.0, bot is merging ⏳

#2436 [14.0][FIX] nfe40_pICMSInter compute
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳, 14.0

#2440 [14.0][REF] l10n_br_nfse: Usabilidade do código de verificação (NFS-e)
  l10n_br_nfse/models/document.py
  l10n_br_nfse/views/document_view.xml
Labels: approved, bot is merging ⏳

#2438 [15.0] [MIG] l10n_br_resource: Migration to 15.0
  l10n_br_resource/README.rst
  l10n_br_resource/__init__.py
  l10n_br_resource/__manifest__.py
  l10n_br_resource/i18n/l10n_br_resource.pot
  l10n_br_resource/i18n/pt_BR.po
  l10n_br_resource/models/__init__.py
  l10n_br_resource/models/resource_calendar.py
  l10n_br_resource/models/resource_calendar_leaves.py
  l10n_br_resource/readme/CONFIGURE.rst
  l10n_br_resource/readme/CONTRIBUTORS.rst
  l10n_br_resource/readme/CREDITS.rst
  l10n_br_resource/readme/DESCRIPTION.rst
  l10n_br_resource/readme/HISTORY.rst
  l10n_br_resource/readme/INSTALL.rst
  l10n_br_resource/readme/ROADMAP.rst
  l10n_br_resource/readme/USAGE.rst
  l10n_br_resource/security/ir.model.access.csv
  l10n_br_resource/static/description/icon.png
  l10n_br_resource/static/description/icon.svg.oca
  l10n_br_resource/static/description/index.html
  l10n_br_resource/tests/__init__.py
  l10n_br_resource/tests/test_resource_calendar.py
  l10n_br_resource/tests/test_resource_calendar_2.py
  l10n_br_resource/tools/__init__.py
  l10n_br_resource/tools/brazil_all_holidays_set.py
  l10n_br_resource/views/resource_calendar_leaves_view.xml
  l10n_br_resource/views/resource_calendar_menu.xml
  l10n_br_resource/views/resource_calendar_view.xml
  l10n_br_resource/wizards/__init__.py
  l10n_br_resource/wizards/workalendar_holiday_import_views.xml
  l10n_br_resource/wizards/workalendar_holiday_import_wizard.py
  requirements.txt
  setup/l10n_br_resource/odoo/addons/l10n_br_resource
  setup/l10n_br_resource/setup.py
Labels: approved, bot is merging ⏳

#2445 [14.0][l10n_br_resource] Add tests
  l10n_br_resource/tests/__init__.py
  l10n_br_resource/tests/test_resource_calendar_2.py
Labels: approved, bot is merging ⏳

#2442 [14.0][l10n_br_account] onchange was shadowed by invoice onchange
  l10n_br_account/models/account_invoice.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
Labels: approved, bot is merging ⏳

#2443 [14.0][l10n_br_account] fix document refund
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_account_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2449 [14.0][FIX] l10n_br_fiscal: ignore canceled document key on constrains
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳

#2452 [14.0][REF] l10n_br_account_payment_order: Campo sequencial "Nosso Número" só pode ser informado no Modo de Pagamento
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/boleto_data.xml
  l10n_br_account_payment_order/demo/ir_sequence.xml
  l10n_br_account_payment_order/models/__init__.py
  l10n_br_account_payment_order/models/account_move.py
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/models/res_company.py
  l10n_br_account_payment_order/readme/ROADMAP.rst
  l10n_br_account_payment_order/views/account_payment_mode.xml
  l10n_br_account_payment_order/views/res_company.xml
Labels: approved, bot is merging ⏳
