Repository OCA/l10n-brazil, pull requests merged in 2023-05, with the labels that each got.

#2466 [14.0[l10n_br_account] fix l10n_br_account/hooks.py
  l10n_br_account/hooks.py
Labels: approved, bot is merging ⏳

#2453 [14.0][IMP] l10n_br_fiscal: check if product has a default code
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳

#2457 [14.0][l10n_br_nfe_spec] xsdata NF-e mixins
  .pre-commit-config.yaml
  l10n_br_nfe/hooks.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_related.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_structure.py
  l10n_br_nfe_spec/models/__init__.py
  l10n_br_nfe_spec/models/spec_models.py
  l10n_br_nfe_spec/models/v4_0/__init__.py
  l10n_br_nfe_spec/models/v4_0/leiaute_cons_sit_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_inut_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/tipos_basico_v4_00.py
  l10n_br_nfe_spec/models/v4_00/__init__.py
  l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/tests/fake_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#2468 [14.0][l10n_br_account][FIX] fix critical dummy doc compute chain shortcut bug
  l10n_br_account/hooks.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
Labels: approved, bot is merging ⏳

#2471 [12.0][l10n_br_nfe_spec] xsdata nfe mixins
  .pre-commit-config.yaml
  l10n_br_nfe/hooks.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_related.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_structure.py
  l10n_br_nfe_spec/models/__init__.py
  l10n_br_nfe_spec/models/spec_models.py
  l10n_br_nfe_spec/models/v4_0/__init__.py
  l10n_br_nfe_spec/models/v4_0/leiaute_cons_sit_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_inut_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/tipos_basico_v4_00.py
  l10n_br_nfe_spec/models/v4_00/__init__.py
  l10n_br_nfe_spec/models/v4_00/leiauteNFe.py
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#2476 [14.0][FIX] l10n_br_sale: Série para diferentes documentos fiscais em faturas do mesmo pedido
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#2478 [14.0][FIX] l10n_br_nfe: campo nfe40_choice4
  l10n_br_nfe/models/document_related.py
Labels: approved, bot is merging ⏳

#2479 [12.0][l10n_br_nfe][FIX] nfe40_choice4 key error
  l10n_br_nfe/models/document_related.py
Labels: approved, bot is merging ⏳

#2470 [14.0][IMP] l10n_br_fiscal: Update NCM Table
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/migrations/14.0.11.0.0/post-migration.py
  l10n_br_fiscal/models/data_abstract.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_ncm.py
  l10n_br_fiscal/views/ncm_view.xml
Labels: approved, bot is merging ⏳

#2481 [12.0] Remover as linhas de seção ou notas do documento fiscal
  l10n_br_sale/models/sale_order.py
Labels: bug, approved, 12.0, bot is merging ⏳

#2347 [14.0][FIX] l10n_br_account: remove price_total/subtotal from base to calc invoice line balance
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/readme/CONTRIBUTORS.rst
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_purchase/tests/__init__.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase/tests/test_l10n_br_purchase_lp.py
  l10n_br_sale/tests/__init__.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/tests/test_l10n_br_sale_lc.py
  l10n_br_sale/tests/test_l10n_br_sale_sn.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳, 14.0

#2459 [12.0][FIX] account.invoice.tax create
  l10n_br_account/models/account_invoice.py
Labels: approved, ready to merge, 12.0, bot is merging ⏳

#2483 [12.0] l10n_br_fiscal: Update NCM Table
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/migrations/12.0.32.0.0/post-migration.py
  l10n_br_fiscal/models/data_abstract.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_ncm.py
  l10n_br_fiscal/views/ncm_view.xml
Labels: approved, 12.0, bot is merging ⏳

#2488 [14.0][l10n_br_fiscal][l10n_br_nfe][FIX] in Odoo aml product_id should be optional
  l10n_br_fiscal/models/document.py
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2493 [14.0][IMP] l10n_br_account: allow edit invoice line account_id
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#2491 [14.0][FIX] l10n_br_account: recompute taxes after ind final
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2480 [14.0][FIX] l10n_br_account: Data do Documento e Data de Escrituração diferente da Fatura
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/tests/test_invoice_general_cases.py
Labels: approved, ready to merge, bot is merging ⏳

#2495 [14.0][l10n_br_base][FIX] fix email_validator deprecation warning
  l10n_br_base/models/res_partner_pix.py
Labels: approved, bot is merging ⏳

#2497 [14.0][FIX] l10n_br_nfse: Valor correto dos serviços quando a quantidade maior que um.
  l10n_br_nfse/models/document_line.py
Labels: approved, bot is merging ⏳

#2498 [14.0][FIX] l10n_br_fiscal: Prefixo correto para a NFC-e
  l10n_br_fiscal/data/l10n_br_fiscal.document.type.csv
Labels: approved, bot is merging ⏳

#2386 [14.0][REF] Adapted CNAB implementation after bank.payment.line was removed from account_payment_order module
  l10n_br_account/__manifest__.py
  l10n_br_account/security/ir.model.access.csv
  l10n_br_account_payment_brcobranca/__init__.py
  l10n_br_account_payment_brcobranca/__manifest__.py
  l10n_br_account_payment_brcobranca/models/__init__.py
  l10n_br_account_payment_brcobranca/models/account_journal.py
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
  l10n_br_account_payment_brcobranca/tests/test_payment_order.py
  l10n_br_account_payment_brcobranca/wizard/__init__.py
  l10n_br_account_payment_order/__init__.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/demo/account_journal.xml
  l10n_br_account_payment_order/demo/account_payment_mode.xml
  l10n_br_account_payment_order/migrations/14.0.3.0.0/post-migration.py
  l10n_br_account_payment_order/models/__init__.py
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/models/account_payment_order.py
  l10n_br_account_payment_order/models/bank_payment_line.py
  l10n_br_account_payment_order/models/l10n_br_cnab.py
  l10n_br_account_payment_order/models/l10n_br_cnab_event.py
  l10n_br_account_payment_order/readme/ROADMAP.rst
  l10n_br_account_payment_order/tests/__init__.py
  l10n_br_account_payment_order/tests/test_invoice_normal_workflow.py
  l10n_br_account_payment_order/tests/test_payment_mode.py
  l10n_br_account_payment_order/tests/test_payment_order_inbound.py
  l10n_br_account_payment_order/tests/test_payment_order_outbound_pix.py
  l10n_br_account_payment_order/views/account_move_line.xml
  l10n_br_account_payment_order/views/account_payment_order.xml
  l10n_br_account_payment_order/views/bank_payment_line.xml
  l10n_br_account_payment_order/views/l10n_br_cnab_return_log_view.xml
  l10n_br_account_payment_order/wizards/__init__.py
  l10n_br_cnab_structure/__manifest__.py
  l10n_br_cnab_structure/data/l10n_br_cnab.line.field.csv
  l10n_br_cnab_structure/models/__init__.py
  l10n_br_cnab_structure/models/account_payment_line.py
  l10n_br_cnab_structure/models/cnab_structure.py
  l10n_br_cnab_structure/models/l10n_br_cnab_event.py
  l10n_br_cnab_structure/views/l10n_br_cnab_return_event_view.xml
  l10n_br_cnab_structure/views/l10n_br_cnab_return_log_view.xml
  test-requirements.txt
Labels: refactoring, needs review, approved, bot is merging ⏳, 14.0

#2502 [14.0][l10n_br_base] erpbrasil.base>=2.3.0 e email-validator fix
  l10n_br_base/__manifest__.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_fiscal/__manifest__.py
  l10n_br_hr/__manifest__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfse/__manifest__.py
  requirements.txt
  test-requirements.txt
Labels: approved, bot is merging ⏳

#2448 [14.0][REF] Alteração do método que retorna os Impostos e ou Dedutíveis para ser chamado apenas uma vez
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/fiscal_tax.py
  l10n_br_contract/models/contract_line.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_repair/models/fiscal_line_mixin.py
  l10n_br_repair/tests/test_l10n_br_repair.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
Labels: approved, ready to merge, bot is merging ⏳
