Repository OCA/l10n-brazil, pull requests merged in 2023-08, with the labels that each got.

#2625 [FIX] Bug forcing user to be fiscal
  l10n_br_cnpj_search/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2630 [14.0][FIX] l10n_br_nfe: remove duplicate vFCPUFDest
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#2516 [14.0][FIX] l10n_br_account: lançamento contábil com retenções
  l10n_br_account/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2633 [IMP+REF] l10n_br_stock_account: Modulo compatível com o caso internacional
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/views/stock_account_view.xml
  l10n_br_stock_account/views/stock_picking.xml
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#2632 [14.0][MIG] Migração l10n_br_stock_account_report
  l10n_br_stock_account_report/README.rst
  l10n_br_stock_account_report/__init__.py
  l10n_br_stock_account_report/__manifest__.py
  l10n_br_stock_account_report/i18n/l10n_br_stock_account_report.pot
  l10n_br_stock_account_report/i18n/pt_BR.po
  l10n_br_stock_account_report/readme/CONFIGURE.rst
  l10n_br_stock_account_report/readme/CONTRIBUTORS.rst
  l10n_br_stock_account_report/readme/CREDITS.rst
  l10n_br_stock_account_report/readme/DESCRIPTION.rst
  l10n_br_stock_account_report/readme/HISTORY.rst
  l10n_br_stock_account_report/readme/INSTALL.rst
  l10n_br_stock_account_report/readme/USAGE.rst
  l10n_br_stock_account_report/report/l10n_br_p7_model_inventory_report.xml
  l10n_br_stock_account_report/report/l10n_br_p7_model_inventory_report_view.xml
  l10n_br_stock_account_report/security/ir.model.access.csv
  l10n_br_stock_account_report/static/description/icon.png
  l10n_br_stock_account_report/static/description/index.html
  l10n_br_stock_account_report/tests/__init__.py
  l10n_br_stock_account_report/tests/test_l10n_br_p7_model_inventory_report.py
  l10n_br_stock_account_report/wizards/__init__.py
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard.py
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard_view.xml
  setup/l10n_br_stock_account_report/odoo/addons/l10n_br_stock_account_report
  setup/l10n_br_stock_account_report/setup.py
Labels: approved, bot is merging ⏳

#2637 [14.0][REF] l10n_br_repair: Resolvido Warnings no LOG
  l10n_br_repair/models/fiscal_line_mixin.py
  l10n_br_repair/models/repair_fee.py
  l10n_br_repair/models/repair_line.py
Labels: approved, bot is merging ⏳

#2329 [14.0][IMP] l10n_br_nfe: Emissão da NFCe
  l10n_br_account_nfe/models/document.py
  l10n_br_account_nfe/tests/__init__.py
  l10n_br_account_nfe/tests/test_nfce_contingency.py
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_nfe/__init__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/demo/fiscal_document_demo.xml
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_supplement.py
  l10n_br_nfe/models/invalidate_number.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/readme/CONTRIBUTORS.rst
  l10n_br_nfe/readme/DESCRIPTION.rst
  l10n_br_nfe/security/ir_model_access.xml
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/test_nfce.py
  l10n_br_nfe/views/res_company_view.xml
  requirements.txt
Labels: new feature, work in progress, approved, ready to merge, bot is merging ⏳, 14.0

#2639 [14.0][REF] l10n_br_account l10n_br_fiscal: Resolvido Warnings no LOG
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳

#2642 [14.0][FIX] saving XML response instead of authorization file
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_nfce.py
  requirements.txt
Labels: approved, bot is merging ⏳

#2644 [14.0][FIX] l10n_br_nfe: Campos choice no modelo res.partner
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳

#2648 [16.0][REF] l10n_br_base: Resolvendo Warning da LIB validate_email depreciado
  l10n_br_base/models/res_partner_pix.py
Labels: approved, bot is merging ⏳

#2647 [16.0][FIX] l10n_br_zip: Botão de Pesquisa do CEP na visão da Empresa.
  l10n_br_zip/__manifest__.py
  l10n_br_zip/views/res_company_views.xml
Labels: approved, bot is merging ⏳

#2646 [14.0][FIX] l10n_br_nfse_paulistana: PIS, COFINS, INSS, IR, CSLL XML tags must only be filled in when there is tax withholding
  l10n_br_nfse_paulistana/models/document.py
Labels: approved, bot is merging ⏳

#2651 [16.0][FIX] l10n_br_currency_rate_update: Resolvido Warning Deprecated class SavepointCase
  .coveragerc
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
Labels: approved, bot is merging ⏳

#2640 [14.0][FIX] l10n_br_fiscal: DIFAL nos estados destinos que dependem do Indicador de Consumidor Final
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#2656 [12.0][BUG] Atributo ondelete errado do campo carrier_id no fiscal.document.mixin
  l10n_br_delivery/models/fiscal_document_mixin.py
Labels: bug, approved, 12.0, bot is merging ⏳

#2657 [14.0][BUG] Atributo ondelete errado do campo carrier_id no fiscal.document.mixin
  l10n_br_delivery/models/fiscal_document_mixin.py
Labels: bug, approved, bot is merging ⏳, 14.0

#2588 [14.0][WIP][NEW] l10n_br_pos_nfce
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/report/danfe_nfce.xml
  l10n_br_nfe/report/reports.xml
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/test_nfce.py
  l10n_br_nfe/tests/test_res_partner.py
  l10n_br_pos/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  l10n_br_pos/static/src/js/models.js
  l10n_br_pos_nfce/README.rst
  l10n_br_pos_nfce/__init__.py
  l10n_br_pos_nfce/__manifest__.py
  l10n_br_pos_nfce/demo/l10n_br_pos_nfce.xml
  l10n_br_pos_nfce/models/__init__.py
  l10n_br_pos_nfce/models/pos_config.py
  l10n_br_pos_nfce/models/pos_order.py
  l10n_br_pos_nfce/models/pos_payment_method.py
  l10n_br_pos_nfce/readme/CONFIGURE.rst
  l10n_br_pos_nfce/readme/CONTRIBUTORS.rst
  l10n_br_pos_nfce/readme/CREDITS.rst
  l10n_br_pos_nfce/readme/DESCRIPTION.rst
  l10n_br_pos_nfce/readme/HISTORY.rst
  l10n_br_pos_nfce/readme/INSTALL.rst
  l10n_br_pos_nfce/static/description/icon.png
  l10n_br_pos_nfce/static/description/index.html
  l10n_br_pos_nfce/static/src/css/ReceiptOrder.css
  l10n_br_pos_nfce/static/src/js/Screens/OrderManagementScreen/ControlButtons/CancelOrderButton.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/NfceFiscalInfoReceipt.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/NfceFooterReceipt.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/NfceHeaderReceipt.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/NfceItemReceipt.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/NfceOrderReceipt.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/NfcePaymentlineReceipt.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/NfceTotalsReceipt.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  l10n_br_pos_nfce/static/src/js/models.js
  l10n_br_pos_nfce/static/src/js/nfe-xml.js
  l10n_br_pos_nfce/static/src/js/utils.js
  l10n_br_pos_nfce/static/src/lib/xmlbuilder2.min.js
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/NfceFiscalInfoReceipt.xml
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/NfceFooterReceipt.xml
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/NfceHeaderReceipt.xml
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/NfceItemReceipt.xml
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/NfceOrderReceipt.xml
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/NfcePaymentlineReceipt.xml
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/NfceTotalsReceipt.xml
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/ReceiptScreen.xml
  l10n_br_pos_nfce/tests/__init__.py
  l10n_br_pos_nfce/tests/common.py
  l10n_br_pos_nfce/tests/test_pos_order.py
  l10n_br_pos_nfce/views/pos_config_view.xml
  l10n_br_pos_nfce/views/pos_payment_method.xml
  l10n_br_pos_nfce/views/pos_template.xml
  l10n_br_pos_nfce/views/res_partner.xml
  setup/l10n_br_pos_nfce/odoo/addons/l10n_br_pos_nfce
  setup/l10n_br_pos_nfce/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2660 [FIX][14.0] NFC-e: Cliente sem Identificação
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_nfce.py
Labels: approved, bot is merging ⏳

#2663 [16.0][FIX+IMP] l10n_br_resource: Resolvido Warning no LOG e incluido Testes
  l10n_br_resource/models/resource_calendar.py
  l10n_br_resource/tests/test_resource_calendar.py
  l10n_br_resource/tests/test_resource_calendar_2.py
Labels: approved, bot is merging ⏳

#2664 [14.0][FIX] l10n_br_nfe: Falha no schema XML.
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2665 [12.0][FIX][l10n_br_nfe] Removido campo duplicado vFCPUFDest
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#2474 [14.0][l10n_br_nfe_spec] atualizações dos esquemas até Pacote nº 9k (NT 2023.001 v.1.20)
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_nfe_spec/migrations/14.0.5.0.0/pre-migration.py
  l10n_br_nfe_spec/models/v4_0/leiaute_cons_sit_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_inut_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/tipos_basico_v4_00.py
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
Labels: approved, ready to merge, bot is merging ⏳

#2654 [14.0][FIX]Divergência dos valores da invoice_line_ids com a line_ids: issue #2645
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/account_tax.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#2668 [14.0][FIX] l10n_br_nfe: Possibilidade de usar o Certificado eCNPJ
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2667 [14.0][Anglo-saxon accounting]: Habilita anglo-saxon para COA templates e cria contas intermediárias para COA generic
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa_generic_template.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template.xml
Labels: approved, bot is merging ⏳

#2597 [14.0][ADD] l10n_br_fiscal_dfe
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/dfe/__init__.py
  l10n_br_fiscal/models/dfe/dfe.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/mdfe/__init__.py
  l10n_br_fiscal/models/mdfe/mdfe.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/views/dfe/dfe_views.xml
  l10n_br_fiscal_dfe/__init__.py
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_fiscal_dfe/constants/dfe.py
  l10n_br_fiscal_dfe/data/ir_cron.xml
  l10n_br_fiscal_dfe/models/__init__.py
  l10n_br_fiscal_dfe/models/attachment.py
  l10n_br_fiscal_dfe/models/dfe.py
  l10n_br_fiscal_dfe/models/document.py
  l10n_br_fiscal_dfe/models/res_company.py
  l10n_br_fiscal_dfe/security/ir.model.access.csv
  l10n_br_fiscal_dfe/static/description/icon.png
  l10n_br_fiscal_dfe/tests/__init__.py
  l10n_br_fiscal_dfe/tests/test_dfe.py
  l10n_br_fiscal_dfe/tools/__init__.py
  l10n_br_fiscal_dfe/tools/utils.py
  l10n_br_fiscal_dfe/views/dfe/dfe_views.xml
  l10n_br_fiscal_dfe/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal_dfe/views/res_company_view.xml
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/constants/mde.py
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/dfe.py
  l10n_br_nfe/models/mde.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/security/ir.model.access.csv
  l10n_br_nfe/security/ir_model_access.xml
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/test_nfe_dfe.py
  l10n_br_nfe/tests/test_nfe_mde.py
  l10n_br_nfe/views/dfe/dfe_views.xml
  l10n_br_nfe/views/mde/mde_views.xml
  requirements.txt
  setup/l10n_br_fiscal_dfe/odoo/addons/l10n_br_fiscal_dfe
  setup/l10n_br_fiscal_dfe/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2670 [14.0][l10n_br_coa_generic]: Ajustes no plano de contas - reordenação
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/account_group.xml
Labels: approved, bot is merging ⏳
