Repository OCA/l10n-brazil, pull requests merged in 2023-12, with the labels that each got.

#2813 [14.0][FIX] l10n_br_purchase: fix product_id and product_uom attributes on form view
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#2799 [14.0][REF] l10n_br_stock_account: Adaptando o modulo para ter compatibilidade com os casos internacionais
  l10n_br_purchase_stock/tests/test_stock_rule.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/demo/stock_inventory_demo.xml
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/tests/__init__.py
  l10n_br_stock_account/tests/common.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/tests/test_stock_rule.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#2821 [15.0][FIX][l10n_br_currency_rate_update]: Solve Warning Deprecated class SavepointCase
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
Labels: approved, bot is merging ⏳

#2819 [13.0][FIX] atualização do repositório
  .copier-answers.yml
  .eslintrc.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  workflows/pre-commit.yml
  workflows/stale.yml
  workflows/test.yml
Labels: approved, bot is merging ⏳

#2732 [14.0][l10n_br_account][FIX] update_xmlids for multiple records to filter
  l10n_br_account/models/ir_model_data.py
Labels: approved, bot is merging ⏳

#2823 [15.0][l10n_br_coa][MIG] ensure id keys in account_ref map
  l10n_br_coa/models/account_chart_template.py
Labels: approved, bot is merging ⏳

#2825 [14.0][IMP] l10n_br_nfse e ginfes: add civil_construction_code and art
  .pre-commit-config.yaml
  l10n_br_nfse/models/document.py
  l10n_br_nfse/views/document_view.xml
  l10n_br_nfse_ginfes/models/document.py
  l10n_br_nfse_ginfes/tests/nfse/001_50_nfse.xml
Labels: approved, bot is merging ⏳

#2828 [14.0][FIX] l10n_br_fiscal: verificação no script de migração
  l10n_br_fiscal/migrations/14.0.14.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#2815 [14.0][l10n_br_account][REM] partner_shipping_id is not a shadowed field anymore
  l10n_br_account/models/account_move.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/account_move.py
  l10n_br_sale/models/fiscal_document.py
Labels: approved, ready to merge, bot is merging ⏳

#2831 [14.0][FIX] l10n_br_account_payment_brcobranca: 14.0.2.0.0 migration
  l10n_br_account_payment_brcobranca/migrations/14.0.2.0.0/post-migration.py
Labels: approved, bot is merging ⏳

#2827 [13.0][MIG] l10n_br_account_due_list: add major migration script
  l10n_br_account_due_list/migrations/13.0.1.0.0/post-migration.py
  l10n_br_account_due_list/migrations/13.0.1.0.0/pre-migration.py
Labels: approved

#2814 [14.0][ADD] l10n_br_nfse_barueri: add new module
  l10n_br_nfse_barueri/README.rst
  l10n_br_nfse_barueri/__init__.py
  l10n_br_nfse_barueri/__manifest__.py
  l10n_br_nfse_barueri/constants/barueri.py
  l10n_br_nfse_barueri/models/__init__.py
  l10n_br_nfse_barueri/models/document.py
  l10n_br_nfse_barueri/models/res_company.py
  l10n_br_nfse_barueri/readme/CONFIGURE.rst
  l10n_br_nfse_barueri/readme/CONTRIBUTORS.rst
  l10n_br_nfse_barueri/readme/DESCRIPTION.rst
  l10n_br_nfse_barueri/readme/INSTALL.rst
  l10n_br_nfse_barueri/readme/ROADMAP.rst
  l10n_br_nfse_barueri/readme/USAGE.rst
  l10n_br_nfse_barueri/static/description/index.html
  l10n_br_nfse_barueri/tests/__init__.py
  l10n_br_nfse_barueri/tests/nfse/nfse.xml
  l10n_br_nfse_barueri/tests/test_fiscal_document_nfse_barueri.py
  requirements.txt
  setup/l10n_br_nfse_barueri/odoo/addons/l10n_br_nfse_barueri
  setup/l10n_br_nfse_barueri/setup.py
Labels: approved, bot is merging ⏳

#2830 [14.0][IMP] Scripts de migração da versão principal.
  l10n_br_account/migrations/14.0.1.0.0/post-migration.py
  l10n_br_account_payment_brcobranca/migrations/14.0.1.0.0/post-migration.py
  l10n_br_account_payment_order/migrations/14.0.1.0.0/post-migration.py
Labels: approved, bot is merging ⏳

#2795 [14.0][l10n_br_nfe] Importação do partner_id para documentos de saída
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2833 [14.0][l10n_br_account][REF] remove useless refs + docstring love
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2482 [14.0][IMP] l10n_br_nfe: check document key date
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_nfe/demo/fiscal_document_demo.xml
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_account_customer_nfe.py
  l10n_br_nfe/tests/test_nfe_serialize.py
Labels: needs review, approved, bot is merging ⏳

#2844 [14.0][FIX] l10n_br_cnpj_search: Fix the tests
  l10n_br_cnpj_search/tests/test_receitaws.py
Labels: approved, bot is merging ⏳

#2837 [14.0][FIX] l10n_br_account: fix button name to call action_move_out_refund_type
  l10n_br_account/views/fiscal_invoice_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2836 [14.0][l10n_br_pos_nfce] Arruma a criação de invoices pelo POS para empresas do SN.
  l10n_br_pos_nfce/models/pos_order.py
Labels: approved, bot is merging ⏳

#2846 [14.0][FIX] l10n_br_stock_account: fix standard_price when multicompany enable
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
Labels: approved, bot is merging ⏳
