Repository OCA/l10n-brazil, pull requests merged in 2023-06, with the labels that each got.

#2505 [14.0][FIX] l10n_br_nfe, l10n_br_base: CNPJ, CFP e IE (Produtor Rural)
  l10n_br_base/views/res_partner_view.xml
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳

#2467 [14.0] [NEW] l10n_br_cnpj_search
  l10n_br_cnpj_search/README.rst
  l10n_br_cnpj_search/__init__.py
  l10n_br_cnpj_search/__manifest__.py
  l10n_br_cnpj_search/data/serpro_qualificacao.csv
  l10n_br_cnpj_search/models/__init__.py
  l10n_br_cnpj_search/models/cnpj_webservice.py
  l10n_br_cnpj_search/models/l10n_br_base_party_mixin.py
  l10n_br_cnpj_search/models/receitaws_webservice.py
  l10n_br_cnpj_search/models/res_company.py
  l10n_br_cnpj_search/models/res_config_settings.py
  l10n_br_cnpj_search/models/res_partner.py
  l10n_br_cnpj_search/models/serpro_webservice.py
  l10n_br_cnpj_search/readme/CONFIGURE.rst
  l10n_br_cnpj_search/readme/CONTRIBUTORS.rst
  l10n_br_cnpj_search/readme/DESCRIPTION.rst
  l10n_br_cnpj_search/readme/HISTORY.rst
  l10n_br_cnpj_search/readme/INSTALL.rst
  l10n_br_cnpj_search/readme/ROADMAP.rst
  l10n_br_cnpj_search/readme/USAGE.rst
  l10n_br_cnpj_search/security/ir.model.access.csv
  l10n_br_cnpj_search/static/description/icon.png
  l10n_br_cnpj_search/static/description/receita.png
  l10n_br_cnpj_search/static/description/receita1.png
  l10n_br_cnpj_search/static/description/receita2.png
  l10n_br_cnpj_search/static/description/serpro.png
  l10n_br_cnpj_search/static/description/serpro1.png
  l10n_br_cnpj_search/tests/__init__.py
  l10n_br_cnpj_search/tests/common.py
  l10n_br_cnpj_search/tests/test_receitaws.py
  l10n_br_cnpj_search/tests/test_serpro.py
  l10n_br_cnpj_search/views/res_company_view.xml
  l10n_br_cnpj_search/views/res_config_settings_view.xml
  l10n_br_cnpj_search/views/res_partner_view.xml
  setup/l10n_br_cnpj_search/odoo/addons/l10n_br_cnpj_search
  setup/l10n_br_cnpj_search/setup.py
Labels: bot is merging ⏳

#2487 [14.0][l10n_br_acount][IMP] 30% performance improvement
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/account_invoice_line.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_delivery/models/fiscal_document_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#2512 [14.0][l10n_br_nfe][DEL] remove useless files
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/nfe/__init__.py
  l10n_br_nfe/tests/nfe/test_nfelib.py
Labels: approved, bot is merging ⏳

#2513 [14.0][REF] l10n_br_account_nfe: Verificar se o detPag foi alterado, antes de atualizar o registro.
  l10n_br_account_nfe/models/account_move_line.py
  l10n_br_account_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2427 [14.0][MIG] l10n_br_nfse_paulistana
  l10n_br_nfse_paulistana/README.rst
  l10n_br_nfse_paulistana/__init__.py
  l10n_br_nfse_paulistana/__manifest__.py
  l10n_br_nfse_paulistana/constants/paulistana.py
  l10n_br_nfse_paulistana/i18n/l10n_br_nfse_paulistana.pot
  l10n_br_nfse_paulistana/models/__init__.py
  l10n_br_nfse_paulistana/models/document.py
  l10n_br_nfse_paulistana/models/res_company.py
  l10n_br_nfse_paulistana/readme/CONFIGURE.rst
  l10n_br_nfse_paulistana/readme/CONTRIBUTORS.rst
  l10n_br_nfse_paulistana/readme/DESCRIPTION.rst
  l10n_br_nfse_paulistana/readme/INSTALL.rst
  l10n_br_nfse_paulistana/readme/ROADMAP.rst
  l10n_br_nfse_paulistana/readme/USAGE.rst
  l10n_br_nfse_paulistana/static/description/icon.png
  l10n_br_nfse_paulistana/static/description/index.html
  l10n_br_nfse_paulistana/tests/__init__.py
  l10n_br_nfse_paulistana/tests/nfse/paulistana.xml
  l10n_br_nfse_paulistana/tests/test_fiscal_document_nfse_paulistana.py
  requirements.txt
  setup/l10n_br_nfse_paulistana/odoo/addons/l10n_br_nfse_paulistana
  setup/l10n_br_nfse_paulistana/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#2519 [FIX] 14.0-l10n_br_cnpj_search Default Cnpj Provider
  l10n_br_cnpj_search/models/cnpj_webservice.py
  l10n_br_cnpj_search/views/res_config_settings_view.xml
Labels: approved, bot is merging ⏳

#2507 [14.0][l10n_br_fiscal][CI] only run IBPT tests certain days
  .coveragerc
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
  l10n_br_fiscal/tests/test_ibpt.py
  l10n_br_fiscal/tests/test_ibpt_product.py
  l10n_br_fiscal/tests/test_ibpt_service.py
Labels: approved, bot is merging ⏳

#2518 [14.0][IMP] l10n_br_nfe: more fields on nfe.40.vol view
  l10n_br_nfe/views/nfe_document_view.xml
Labels: approved, bot is merging ⏳

#2521 [FIX] tests on l10n_br_cnpj_search no delete res.partner
  l10n_br_cnpj_search/tests/test_serpro.py
Labels: approved, bot is merging ⏳

#2528 [12.0][l10n_br_fiscal][l10n_br_currency_rate_update][CI] unbkreak BCB and IBPT tests
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
  l10n_br_fiscal/tests/test_ibpt.py
  l10n_br_fiscal/tests/test_ibpt_product.py
  l10n_br_fiscal/tests/test_ibpt_service.py
Labels: approved, bot is merging ⏳

#2535 [14.0][l10n_br_cnpj_search][FIX]Test serpro once a week only
  l10n_br_cnpj_search/tests/test_serpro.py
Labels: approved, bot is merging ⏳

#2517 [14.0][FIX] l10n_br_account: Carregamento da modalidade do frete na NF-e
  l10n_br_account/models/account_move.py
  l10n_br_account/models/fiscal_document.py
Labels: approved, bot is merging ⏳

#2536 [14.0][l10n_br_nfe] mock and test NFe webservices
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_serialize_lc.py
  l10n_br_nfe/tests/test_nfe_serialize_sn.py
  l10n_br_nfe/tests/test_nfe_webservices.py
Labels: approved, bot is merging ⏳

#2531 [14.0][FIX]Adicionado um domain para que os campos "accountant_id" e "technical_support_id" busquem somente o tipo company.
  l10n_br_fiscal/i18n/pt_BR.po
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#2533 [14.0][FIX] l10n_br_account: copy invoice with fiscal dummy
  l10n_br_account/models/account_move.py
  l10n_br_account/tests/test_customer_invoice_dummy.py
Labels: approved, ready to merge, bot is merging ⏳

#2540 [12.0][l10n_br_nfe] mock and test NFe webservices
  l10n_br_nfe/models/invalidate_number.py
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_serialize_lc.py
  l10n_br_nfe/tests/test_nfe_serialize_sn.py
  l10n_br_nfe/tests/test_nfe_webservices.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#2554 [14.0] Adapted fiscal.document.move.mixin and removed duplicated fields
  l10n_br_account/models/account_move.py
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_account/views/fiscal_invoice_view.xml
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_move_mixin.py
Labels: approved, bot is merging ⏳

#2558 [14.0][l10n_br_fiscal][l10n_br_account][REF] faster tests with SavepointCase
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_account_taxes.py
  l10n_br_account/tests/test_company_fiscal_dummy.py
  l10n_br_account/tests/test_document_date.py
  l10n_br_account/tests/test_invoice_refund.py
  l10n_br_account/tests/test_move_discount.py
  l10n_br_base/tests/test_partner_bank.py
  l10n_br_base/tests/test_valid_pix.py
  l10n_br_cnpj_search/tests/common.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_certificate.py
  l10n_br_fiscal/tests/test_fiscal_tax.py
  l10n_br_fiscal/tests/test_icms_regulation.py
  l10n_br_fiscal/tests/test_ncm.py
  l10n_br_hr/tests/test_hr_employee_dependent.py
  l10n_br_hr/tests/test_l10n_br_hr.py
  l10n_br_nfe/tests/test_account_customer_nfe.py
  l10n_br_pos/tests/test_l10n_br_pos_config.py
  l10n_br_pos/tests/test_l10n_br_pos_order.py
  l10n_br_pos/tests/test_l10n_br_pos_partner.py
  l10n_br_resource/tests/test_resource_calendar.py
  l10n_br_resource/tests/test_resource_calendar_2.py
  l10n_br_zip/tests/test_l10n_br_zip_res_company.py
  l10n_br_zip/tests/test_l10n_br_zip_res_partner.py
Labels: approved, bot is merging ⏳

#2557 [FIX] Remoção Tax Id quando BR
  l10n_br_base/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#2551 [14.0][l10n_br_account] multi-localizations tests
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_multi_localizations_invoice.py
  l10n_br_account_payment_order/models/account_move_line.py
  l10n_br_account_payment_order/models/l10n_br_cnab_change_methods.py
  l10n_br_base/__init__.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_repair/tests/test_l10n_br_repair.py
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: approved, bot is merging ⏳

#2561 [14.0][FIX] l10n_br_pos, l10n_br_pos_cfe: Warnings
  l10n_br_pos/static/src/js/Screens/OrderManagementScreen/OrderRow.js
  l10n_br_pos/static/src/js/Screens/PaymentScreen/PaymentScreen.js
  l10n_br_pos/static/src/js/models.js
  l10n_br_pos/static/src/js/util.js
  l10n_br_pos_cfe/static/src/js/ChromeWidgets/ProxyStatus.js
  l10n_br_pos_cfe/static/src/js/OrderManagementScreen/ReprintReceiptScreen.js
  l10n_br_pos_cfe/static/src/js/PaymentScreen/PaymentScreen.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/ReceiptScreen.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/SatOrderReceipt.js
  l10n_br_pos_cfe/static/src/js/devices.js
  l10n_br_pos_cfe/static/src/js/fiscal_cfe.js
  l10n_br_pos_cfe/static/src/js/models.js
Labels: approved, bot is merging ⏳

#2564 [14.0][l10n_br_account][REF] cleanup dead code
  l10n_br_account/models/account_move.py
Labels: approved, bot is merging ⏳

#2566 [14][FIX] l10n_br_account: valores em branco nos campos shadowed
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2567 [14.0][FIX] l10n_br_base: Ocultação do campo Suframa.
  l10n_br_base/views/res_company_view.xml
Labels: bot is merging ⏳

#2541 [14.0][l10n_br_nfe] nfelib versão 2.0, com os bindings legacy (sem xsdata)
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/hooks.py
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
  requirements.txt
Labels: approved, merged 🎉

#2522 [14.0][FIX] QR Code não está sendo impresso em dispositivos android nas versões mais recentes
  l10n_br_pos/static/lib/JsBarcode.code128.min.js
  l10n_br_pos/static/lib/JsBarcode.js
  l10n_br_pos/static/lib/qrcode.js
  l10n_br_pos/static/lib/qrcode.min.js
  l10n_br_pos/views/pos_template.xml
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/OrderFooterReceipt.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/ReceiptScreen.js
Labels: approved, ready to merge, bot is merging ⏳

#2562 [14.0][FIX][l10n_br_cnpj_search] Correção do Mock Test Serpro
  l10n_br_cnpj_search/tests/fixtures/test_serpro_basica.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_empresa.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_not_found.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_qsa.yaml
  l10n_br_cnpj_search/tests/test_serpro.py
Labels: approved, bot is merging ⏳

#2523 [14.0][REF] l10n_br_nfse_paulistana: Minimizar erros de transação no envio da NFS-e
  l10n_br_nfse_paulistana/models/document.py
Labels: approved, bot is merging ⏳
