Repository OCA/l10n-brazil, pull requests merged in 2023-02, with the labels that each got.

#2325 [14.0][l10n_br_fiscal][FORWARD PORT] [FIX] Data na chave do documento fiscal
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳

#2326 [14.0][IMP] Colocar anexos (autorização e report) ao autorizar documento
  l10n_br_fiscal/models/document.py
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2312 [15.0][MIGR] l10n_br_coa_simple migration
  l10n_br_coa_simple/README.rst
  l10n_br_coa_simple/__init__.py
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/data/account.account.template.csv
  l10n_br_coa_simple/data/account_group.xml
  l10n_br_coa_simple/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_coa_simple/data/l10n_br_coa_simple_template.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template_post.xml
  l10n_br_coa_simple/demo/account_journal.xml
  l10n_br_coa_simple/hooks.py
  l10n_br_coa_simple/i18n/l10n_br_coa_simple.pot
  l10n_br_coa_simple/i18n/pt_BR.po
  l10n_br_coa_simple/readme/CONFIGURE.rst
  l10n_br_coa_simple/readme/CONTRIBUTORS.rst
  l10n_br_coa_simple/readme/DESCRIPTION.rst
  l10n_br_coa_simple/readme/INSTALL.rst
  l10n_br_coa_simple/readme/ROADMAP.rst
  l10n_br_coa_simple/readme/USAGE.rst
  l10n_br_coa_simple/static/description/icon.png
  l10n_br_coa_simple/static/description/index.html
  l10n_br_coa_simple/tests/__init__.py
  l10n_br_coa_simple/tests/test_l10n_br_coa_simple.py
  setup/l10n_br_coa_simple/odoo/addons/l10n_br_coa_simple
  setup/l10n_br_coa_simple/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 15.0

#2332 [15.0] mig l10n_br_coa_generic
  l10n_br_coa_generic/README.rst
  l10n_br_coa_generic/__init__.py
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/account_fiscal_position_template.xml
  l10n_br_coa_generic/data/account_group.xml
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa_generic_template.xml
  l10n_br_coa_generic/data/l10n_br_coa_generic_template_post.xml
  l10n_br_coa_generic/demo/account_journal.xml
  l10n_br_coa_generic/hooks.py
  l10n_br_coa_generic/i18n/l10n_br_coa_generic.pot
  l10n_br_coa_generic/i18n/pt_BR.po
  l10n_br_coa_generic/readme/CONFIGURE.rst
  l10n_br_coa_generic/readme/CONTRIBUTORS.rst
  l10n_br_coa_generic/readme/DESCRIPTION.rst
  l10n_br_coa_generic/readme/INSTALL.rst
  l10n_br_coa_generic/readme/ROADMAP.rst
  l10n_br_coa_generic/readme/USAGE.rst
  l10n_br_coa_generic/static/description/icon.png
  l10n_br_coa_generic/static/description/index.html
  l10n_br_coa_generic/static/pdf/Livro_Escrituracao_contabil.pdf
  l10n_br_coa_generic/tests/__init__.py
  l10n_br_coa_generic/tests/test_l10n_br_coa_generic.py
  setup/l10n_br_coa_generic/odoo/addons/l10n_br_coa_generic
  setup/l10n_br_coa_generic/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 15.0

#2333 [14.0][FIX] l10n_br_account: detalhes fiscais exigindo permissão de administrador
  l10n_br_account/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2334 [16.0] l10n_br_coa_simple migration
  l10n_br_coa_simple/README.rst
  l10n_br_coa_simple/__init__.py
  l10n_br_coa_simple/__manifest__.py
  l10n_br_coa_simple/data/account.account.template.csv
  l10n_br_coa_simple/data/account_group.xml
  l10n_br_coa_simple/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_coa_simple/data/l10n_br_coa_simple_template.xml
  l10n_br_coa_simple/data/l10n_br_coa_simple_template_post.xml
  l10n_br_coa_simple/demo/account_journal.xml
  l10n_br_coa_simple/hooks.py
  l10n_br_coa_simple/i18n/l10n_br_coa_simple.pot
  l10n_br_coa_simple/i18n/pt_BR.po
  l10n_br_coa_simple/readme/CONFIGURE.rst
  l10n_br_coa_simple/readme/CONTRIBUTORS.rst
  l10n_br_coa_simple/readme/DESCRIPTION.rst
  l10n_br_coa_simple/readme/INSTALL.rst
  l10n_br_coa_simple/readme/ROADMAP.rst
  l10n_br_coa_simple/readme/USAGE.rst
  l10n_br_coa_simple/static/description/icon.png
  l10n_br_coa_simple/static/description/index.html
  l10n_br_coa_simple/tests/__init__.py
  l10n_br_coa_simple/tests/test_l10n_br_coa_simple.py
  setup/l10n_br_coa_simple/odoo/addons/l10n_br_coa_simple
  setup/l10n_br_coa_simple/setup.py
Labels: approved, migration, bot is merging ⏳, 16.0

#2321 [14.0][FIX] l10n_br_nfe: add export fields pisnt and cofinsnt
  l10n_br_nfe/models/document_line.py
Labels: bot is merging ⏳

#2303 [14.0][FIX] l10n_br_account: impostos não inclusos no preço nos lançamentos contábeis
  l10n_br_account/models/account_invoice_line.py
Labels: approved, bot is merging ⏳

#2342 [14.0][REF] l10n_br_fiscal: issuer required only for eletronic documents
  l10n_br_fiscal/models/document_eletronic.py
Labels: approved, bot is merging ⏳

#2344 [14.0][FIX] l10n_br_fiscal: typo consumidor anonimo
  l10n_br_fiscal/data/res_partner_data.xml
Labels: approved, bot is merging ⏳

#2343 [14.0][REF] l10n_br_fiscal: remove duplicate code
  l10n_br_fiscal/models/document_line.py
Labels: approved, bot is merging ⏳

#2345 [FIX] l10n_br_fiscal: add missing depends on _compute_amounts
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#2337 [14.0][FIX] l10n_br_fiscal: compute amount taxes
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/tests/test_fiscal_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#2348 [12.0] Permitir informar o campo nfe40_cProd se o product_id não é informado
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/views/nfe_document_line_view.xml
Labels: approved, 12.0, bot is merging ⏳

#2356 [15.0][MIGR] l10n br_currency_rate_update
  l10n_br_currency_rate_update/README.rst
  l10n_br_currency_rate_update/__init__.py
  l10n_br_currency_rate_update/__manifest__.py
  l10n_br_currency_rate_update/i18n/l10n_br_currency_rate_update.pot
  l10n_br_currency_rate_update/i18n/pt_BR.po
  l10n_br_currency_rate_update/models/__init__.py
  l10n_br_currency_rate_update/models/res_currency_rate_provider_bcb.py
  l10n_br_currency_rate_update/readme/CONFIGURE.rst
  l10n_br_currency_rate_update/readme/CONTRIBUTORS.rst
  l10n_br_currency_rate_update/readme/DESCRIPTION.rst
  l10n_br_currency_rate_update/readme/USAGE.rst
  l10n_br_currency_rate_update/static/description/icon.png
  l10n_br_currency_rate_update/static/description/index.html
  l10n_br_currency_rate_update/tests/__init__.py
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
  setup/l10n_br_currency_rate_update/odoo/addons/l10n_br_currency_rate_update
  setup/l10n_br_currency_rate_update/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2357 [14.0][FIX] l10n_br_account: workaround https://github.com/oca/ocb/commit/1…
  l10n_br_account/models/account_move.py
Labels: approved, bot is merging ⏳

#2352 [14.0][IMP] l10n_br_account_nfe: Not export dup, fat in NFCe xml
  l10n_br_account_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2359 [16.0][MIGR] l10n_br_currency_rate_update
  l10n_br_currency_rate_update/README.rst
  l10n_br_currency_rate_update/__init__.py
  l10n_br_currency_rate_update/__manifest__.py
  l10n_br_currency_rate_update/i18n/l10n_br_currency_rate_update.pot
  l10n_br_currency_rate_update/i18n/pt_BR.po
  l10n_br_currency_rate_update/models/__init__.py
  l10n_br_currency_rate_update/models/res_currency_rate_provider_bcb.py
  l10n_br_currency_rate_update/readme/CONFIGURE.rst
  l10n_br_currency_rate_update/readme/CONTRIBUTORS.rst
  l10n_br_currency_rate_update/readme/DESCRIPTION.rst
  l10n_br_currency_rate_update/readme/USAGE.rst
  l10n_br_currency_rate_update/static/description/icon.png
  l10n_br_currency_rate_update/static/description/index.html
  l10n_br_currency_rate_update/tests/__init__.py
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
  setup/l10n_br_currency_rate_update/odoo/addons/l10n_br_currency_rate_update
  setup/l10n_br_currency_rate_update/setup.py
Labels: approved, migration, bot is merging ⏳, 16.0

#2351 [14.0][IMP] l10n_br_fiscal: considering inherited views in the inject_fiscal_fields method
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#2301 [14.0][NEW] l10n_br_pos_cfe
  l10n_br_pos_cfe/README.rst
  l10n_br_pos_cfe/__init__.py
  l10n_br_pos_cfe/__manifest__.py
  l10n_br_pos_cfe/demo/pos_config_demo.xml
  l10n_br_pos_cfe/demo/pos_payment_method_demo.xml
  l10n_br_pos_cfe/models/__init__.py
  l10n_br_pos_cfe/models/pos_config.py
  l10n_br_pos_cfe/models/pos_order.py
  l10n_br_pos_cfe/models/pos_payment_method.py
  l10n_br_pos_cfe/readme/CONFIGURE.rst
  l10n_br_pos_cfe/readme/CONTRIBUTORS.rst
  l10n_br_pos_cfe/readme/CREDITS.rst
  l10n_br_pos_cfe/readme/DESCRIPTION.rst
  l10n_br_pos_cfe/readme/HISTORY.rst
  l10n_br_pos_cfe/readme/INSTALL.rst
  l10n_br_pos_cfe/static/description/icon.png
  l10n_br_pos_cfe/static/description/index.html
  l10n_br_pos_cfe/static/src/css/pos.css
  l10n_br_pos_cfe/static/src/js/ChromeWidgets/ProxyStatus.js
  l10n_br_pos_cfe/static/src/js/OrderManagementScreen/ReprintReceiptScreen.js
  l10n_br_pos_cfe/static/src/js/PaymentScreen/PaymentScreen.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/OrderFooterReceipt.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/OrderHeaderReceipt.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/OrderPaymentReceipt.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/OrderRowReceipt.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/OrderSubtitleReceipt.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/OrderTotalsReceipt.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/ReceiptScreen.js
  l10n_br_pos_cfe/static/src/js/ReceiptScreen/SatOrderReceipt.js
  l10n_br_pos_cfe/static/src/js/devices.js
  l10n_br_pos_cfe/static/src/js/fiscal_cfe.js
  l10n_br_pos_cfe/static/src/js/models.js
  l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderFooterReceipt.xml
  l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderHeaderReceipt.xml
  l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderPaymentReceipt.xml
  l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderRowReceipt.xml
  l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderSubtitleReceipt.xml
  l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/OrderTotalsReceipt.xml
  l10n_br_pos_cfe/static/src/xml/Screens/ReceiptScreen/SatOrderReceipt.xml
  l10n_br_pos_cfe/tests/__init__.py
  l10n_br_pos_cfe/tests/test_l10n_br_pos_cfe.py
  l10n_br_pos_cfe/views/pos_payment_method_view.xml
  l10n_br_pos_cfe/views/pos_template.xml
  requirements.txt
  setup/l10n_br_pos_cfe/odoo/addons/l10n_br_pos_cfe
  setup/l10n_br_pos_cfe/setup.py
Labels: bot is merging ⏳

#2335 [16.0] mig l10n_br_coa_generic
  l10n_br_coa_generic/README.rst
  l10n_br_coa_generic/__init__.py
  l10n_br_coa_generic/__manifest__.py
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/account_fiscal_position_template.xml
  l10n_br_coa_generic/data/account_group.xml
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa_generic_template.xml
  l10n_br_coa_generic/data/l10n_br_coa_generic_template_post.xml
  l10n_br_coa_generic/demo/account_journal.xml
  l10n_br_coa_generic/hooks.py
  l10n_br_coa_generic/i18n/l10n_br_coa_generic.pot
  l10n_br_coa_generic/i18n/pt_BR.po
  l10n_br_coa_generic/readme/CONFIGURE.rst
  l10n_br_coa_generic/readme/CONTRIBUTORS.rst
  l10n_br_coa_generic/readme/DESCRIPTION.rst
  l10n_br_coa_generic/readme/INSTALL.rst
  l10n_br_coa_generic/readme/ROADMAP.rst
  l10n_br_coa_generic/readme/USAGE.rst
  l10n_br_coa_generic/static/description/icon.png
  l10n_br_coa_generic/static/description/index.html
  l10n_br_coa_generic/static/pdf/Livro_Escrituracao_contabil.pdf
  l10n_br_coa_generic/tests/__init__.py
  l10n_br_coa_generic/tests/test_l10n_br_coa_generic.py
  setup/l10n_br_coa_generic/odoo/addons/l10n_br_coa_generic
  setup/l10n_br_coa_generic/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, 16.0
