Repository OCA/l10n-brazil, pull requests merged in 2023-10, with the labels that each got.

#2707 [14.0][IFIX+IMP l10n_br_crm: Corrigido campos de endereço no Prospecto e deixando o modulo compatível com caso internacional
  l10n_br_crm/__init__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/models/__init__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/views/crm_lead_view.xml
Labels: approved, bot is merging ⏳

#2723 [14.0][NEW] PIS and COFINS ST
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳, sped

#2634 [14.0][IMP] l10n_br_nfe: Adicionar valores para o Grupo Retenção de Tributos.
  l10n_br_account/models/account_move_line.py
  l10n_br_fiscal/data/partner_profile_data.xml
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/partner_profile.py
  l10n_br_fiscal/models/res_partner.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/partner_profile_view.xml
  l10n_br_fiscal/views/res_partner_view.xml
  l10n_br_nfe/models/document.py
Labels: approved, ready to merge, bot is merging ⏳

#2033 [14.0][FIX] l10n_br_base: changing one of the fields resets the value of the other (state_id and inscr_est)
  l10n_br_base/models/res_company.py
  l10n_br_fiscal/tests/test_icms_regulation.py
Labels: bot is merging ⏳, 14.0

#2408 [14.0][FIX] l10n_br_fiscal: colocando outros custos para fazer base do PIS, COFINS e IPI
  l10n_br_fiscal/data/l10n_br_fiscal.tax.group.csv
  l10n_br_fiscal/tests/test_fiscal_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#2592 [14.0][FIX] account, fiscal: herança do 'onchange' e resolução de ambiguidade em mixins
  l10n_br_account/models/account_move.py
  l10n_br_delivery/models/fiscal_document_mixin.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
  l10n_br_fiscal/models/document_move_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#2733 [14.0][l10n_br_account] account remove useless tests
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_customer_invoice_dummy.py
  l10n_br_account/tests/test_non_fiscal_move.py
  l10n_br_account/tests/test_supplier_invoice_dummy.py
Labels: approved, bot is merging ⏳

#2690 [14.0][FIX] l10n_br_fiscal: remove service from line compute freight, insurance and other values
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_repair/models/repair_order.py
Labels: approved, ready to merge, bot is merging ⏳

#2739 [12.0][IMP] l10n_br_nfe: Adicionar valores para o Grupo Retenção de Tributos.
  l10n_br_account/models/account_invoice_line.py
  l10n_br_fiscal/data/partner_profile_data.xml
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/partner_profile.py
  l10n_br_fiscal/models/res_partner.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal/views/partner_profile_view.xml
  l10n_br_fiscal/views/res_partner_view.xml
  l10n_br_nfe/models/document.py
Labels: approved, 12.0, bot is merging ⏳

#2742 [14.0][FIX] l10n_br_nfse: change how the iss_retido field value is set
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
Labels: approved, bot is merging ⏳

#2737 [14.0][spec_driven_model][l10n_br_nfe] fix readonly related import
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/res_company.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/tests/spec_purchase.py
Labels: approved, bot is merging ⏳

#2552 [14.0][NEW] Importação de documentos fiscais
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/wizards/__init__.py
  l10n_br_fiscal/wizards/base_wizard_mixin.py
  l10n_br_fiscal/wizards/document_import_wizard_mixin.py
  l10n_br_fiscal/wizards/document_import_wizard_mixin.xml
  l10n_br_nfe/__init__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/hooks.py
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/dfe.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/product_product.py
  l10n_br_nfe/models/product_supplierinfo.py
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200181583054000129550010000000052062777166.xml
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_import_wizard.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/views/nfe_action.xml
  l10n_br_nfe/views/nfe_document_view.xml
  l10n_br_nfe/views/nfe_menu.xml
  l10n_br_nfe/views/supplier_info_view.xml
  l10n_br_nfe/wizards/__init__.py
  l10n_br_nfe/wizards/import_document.py
  l10n_br_nfe/wizards/import_document.xml
  l10n_br_nfe/wizards/l10n_br_account_nfe_export_invoice.py
  spec_driven_model/models/spec_import.py
Labels: needs review, enhancement, approved, bot is merging ⏳, 14.0

#2744 [14.0][REF] Inform python external dependencies make unnecessary use TRY to import a library.
  l10n_br_account_payment_brcobranca/__manifest__.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_partner.py
  l10n_br_cnpj_search/__manifest__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal_certificate/hooks.py
  l10n_br_fiscal_certificate/models/certificate.py
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_hr/__manifest__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/models/invalidate_number.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_pos/__manifest__.py
  l10n_br_pos/models/res_partner.py
  l10n_br_pos_cfe/__manifest__.py
  l10n_br_pos_cfe/models/pos_order.py
  l10n_br_website_sale/__manifest__.py
  l10n_br_website_sale/controllers/main.py
  l10n_br_zip/__manifest__.py
  l10n_br_zip/models/l10n_br_zip.py
Labels: approved, ready to merge, bot is merging ⏳

#2750 [14.0]REF] Atualização da bibliotecas do Pre-commit: Método Super sem Parâmetros
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_cnab_structure/models/cnab_batch.py
  l10n_br_cnab_structure/models/cnab_line.py
  l10n_br_cnab_structure/models/cnab_line_field.py
  l10n_br_cnab_structure/models/cnab_line_field_group.py
  l10n_br_cnab_structure/models/cnab_line_field_group_condition.py
  l10n_br_cnab_structure/models/cnab_structure.py
  l10n_br_cnpj_search/tests/test_receitaws.py
  l10n_br_cnpj_search/tests/test_serpro.py
  l10n_br_coa_simple/tests/test_l10n_br_coa_simple.py
  l10n_br_contract/tests/test_l10n_br_contract.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_hr/models/res_partner.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse_ginfes/tests/test_fiscal_document_nfse_ginfes.py
  l10n_br_nfse_paulistana/models/document.py
  l10n_br_nfse_paulistana/tests/test_fiscal_document_nfse_paulistana.py
  l10n_br_portal/controllers/portal.py
  l10n_br_pos/models/mail_thread.py
  l10n_br_pos/models/pos_order.py
  l10n_br_pos/models/res_partner.py
  l10n_br_pos/models/stock.py
  l10n_br_pos_nfce/models/pos_order.py
  l10n_br_resource/tests/test_resource_calendar.py
  l10n_br_stock_account/tests/test_stock_rule.py
  l10n_br_website_sale/controllers/main.py
  l10n_br_zip/wizard/l10n_br_zip_search.py
  payment_bacen_pix/tests/test_bacen_pix.py
  payment_pagseguro/tests/test_pagseguro.py
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#2751 [14.0][REF] Atualização da bibliotecas do Pre-commit: Flake8 E741 ambiguous variable name 'l'
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account_payment_order/tests/test_payment_order_inbound.py
  l10n_br_cnab_structure/models/cnab_batch.py
  l10n_br_cnab_structure/models/cnab_line.py
  l10n_br_cnab_structure/models/cnab_line_field.py
  l10n_br_cnab_structure/models/cnab_structure.py
  l10n_br_cnab_structure/models/l10n_br_cnab_event.py
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale_stock/models/sale_order.py
Labels: approved, bot is merging ⏳

#2752 [14.0][REF] Atualização da bibliotecas do Pre-commit: Flake8 E721 do not compare types
  l10n_br_contract/models/contract_contract.py
  l10n_br_nfe/models/document.py
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard.py
  l10n_br_website_sale/controllers/main.py
  payment_pagseguro/models/payment_transaction.py
  spec_driven_model/models/spec_export.py
Labels: approved, bot is merging ⏳

#2756 [14.0][FIX] l10n_br_fiscal: division by zero
  l10n_br_fiscal/models/document_fiscal_mixin_methods.py
Labels: approved, bot is merging ⏳

#2730 [14.0][REF] l10n_br_base, l10n_br_crm, l10n_br_fiscal, l10n_br_hr: Unificando as validações do IE, CNPJ e CPF
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_base/tools.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_fiscal/models/document_related.py
  l10n_br_hr/models/hr_employee.py
Labels: approved, bot is merging ⏳
