Repository OCA/l10n-brazil, pull requests merged in 2023-01, with the labels that each got.

#2000 [12.0][REF] l10n_br_nfe: fiscal document module integration standard document line
  .copier-answers.yml
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_nfe/models/cest.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/models/tax_ipi_guideline.py
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
  l10n_br_nfe/tests/test_nfe_import_wizard.py
  l10n_br_nfe/wizards/import_document.py
Labels: needs review, approved, ready to merge, 12.0, bot is merging ⏳

#2289 [14.0] workaround tests
  l10n_br_fiscal/models/document_workflow.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#2266 [14.0][MIG] l10n_br_account: migração da localizacao dos metodos account_invoice_refund
  l10n_br_account/__manifest__.py
  l10n_br_account/models/account_invoice.py
  l10n_br_account/tests/test_invoice_refund.py
  l10n_br_account/wizards/__init__.py
  l10n_br_account/wizards/account_invoice_refund.py
  l10n_br_account/wizards/account_invoice_refund_view.xml
  l10n_br_account/wizards/account_move_reversal.py
  l10n_br_account/wizards/account_move_reversal_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2267 [14.0][l10n_br_base][l10n_br_fiscal][l10n_br_account] create multi support
  l10n_br_account/models/account_invoice.py
  l10n_br_account/models/fiscal_tax.py
  l10n_br_account/tests/test_account_taxes.py
  l10n_br_account/tests/test_company_fiscal_dummy.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_fiscal/models/certificate.py
  l10n_br_fiscal/models/cest.py
  l10n_br_fiscal/models/data_ncm_nbs_abstract.py
  l10n_br_fiscal/models/document_eletronic.py
  l10n_br_fiscal/models/document_serie.py
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/nbm.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/subsequent_document.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/models/uom_uom.py
  l10n_br_fiscal/tests/test_subsequent_operation.py
Labels: needs review, approved, bot is merging ⏳

#2280 [14.0][IMP] l10n_br_fiscal: define field date_in_out when the document is issued by the partner
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_nfe/models/document.py
  l10n_br_nfse/models/document.py
Labels: approved, ready to merge, bot is merging ⏳

#2287 [14.0][MIG] CONTRIBUTING.md: Migration to 14.0
  CONTRIBUTING.md
Labels: approved, bot is merging ⏳

#2290 [14.0][l10n_br_nfe] fiscal document line rfc
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/models/cest.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/models/tax_ipi_guideline.py
  l10n_br_nfe/readme/DESCRIPTION.rst
  l10n_br_nfe/readme/USAGE.rst
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
Labels: approved, bot is merging ⏳

#2282 [14.0][FIX] l10n_br_contract: fix invisible attribute of br fields
  l10n_br_contract/views/contract_line.xml
Labels: approved, bot is merging ⏳

#2278 [14.0][IMP] l10n_br_fiscal_closing: include files when issuer is a partner
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#2286 [12.0][FIX] reconcile invoice and refund
  l10n_br_account/models/account_invoice.py
Labels: approved, 12.0, bot is merging ⏳

#2291 [14.0][FIX] l10n_br_fiscal_closing: change strings to english, fix typo and others
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/views/closing.xml
Labels: approved, bot is merging ⏳

#2292 [14.0][FIX] l10n_br_fiscal: fix string typo
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
Labels: approved, bot is merging ⏳

#2293 [14.0][FIX] l10n_br_fiscal_closing: change string on closing form
  l10n_br_fiscal_closing/views/closing.xml
Labels: approved, bot is merging ⏳

#2297 [14.0][l10n_br_purchase][FIX] fix purchase report
  l10n_br_purchase/__manifest__.py
  l10n_br_purchase/readme/CONTRIBUTORS.rst
  l10n_br_purchase/readme/DESCRIPTION.rst
  l10n_br_purchase/reports/purchase_report.py
Labels: approved, bot is merging ⏳

#2305 [14.0] l10n_br_nfe: Remove conversão do campo modBCST para float na importação
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#2304 [12.0] l10n_br_nfe: Remove conversão do campo modBCST para float na importação
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#2307 [12.0][l10n_br_nfse_paulistana]: Gera o pdf da nota fiscal novamente após sua autorização
  l10n_br_nfse_paulistana/models/document.py
Labels: approved, bot is merging ⏳

#2310 [14.0][FIX] l10n_br_cnab_structure: summary and maintainers in manifest
  l10n_br_cnab_structure/__manifest__.py
Labels: bot is merging ⏳

#2314 [14.0][FIX] l10n_br_account_payment_brcobranca: Texto da instrução de desconto
  l10n_br_account_payment_brcobranca/models/account_move_line.py
Labels: approved, bot is merging ⏳

#2316 [14.0][REF] l10n_br_account_payment_order/brcobranca: Valor do Desconto
  l10n_br_account_payment_brcobranca/models/account_move_line.py
  l10n_br_account_payment_brcobranca/models/bank_payment_line.py
  l10n_br_account_payment_order/models/account_move_line.py
  l10n_br_account_payment_order/views/account_move_line.xml
Labels: approved

#2315 [14.][FIX] l10n_br_account_payment_brcobranca: Tipo do desconto para o Banco AILOS
  l10n_br_account_payment_brcobranca/models/bank_payment_line.py
Labels: approved, bot is merging ⏳

#2317 [14.0][FIX] l10n_br_account_payment_brcobranca: Flag de desconto BRCobrança
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#2318 [16.0][FIX] l10n_br_base and l10n_br_stock remove warnings
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  l10n_br_base/demo/res_users_demo.xml
  l10n_br_base/models/res_partner_pix.py
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_valid_createid.py
  l10n_br_stock/demo/stock_inventory_demo.xml
  l10n_br_stock/hooks.py
Labels: approved, bot is merging ⏳, 16.0

#2320 [15.0][FIX] l10n_br_base and l10n_br_stock remove warnings
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  README.md
  l10n_br_base/demo/res_users_demo.xml
  l10n_br_base/models/res_partner_pix.py
  l10n_br_base/tests/test_amount_to_text.py
  l10n_br_base/tests/test_base_onchange.py
  l10n_br_base/tests/test_other_ie.py
  l10n_br_base/tests/test_valid_createid.py
  l10n_br_stock/demo/stock_inventory_demo.xml
  l10n_br_stock/hooks.py
Labels: bot is merging ⏳, 15.0

#2319 [15.0] l10n_br_coa Backport
  l10n_br_coa/data/l10n_br_coa_template.xml
  l10n_br_coa/models/account_chart_template.py
Labels: approved, bot is merging ⏳, 15.0

#2311 [16.0][MIGR] l10n_br_coa migration
  l10n_br_coa/README.rst
  l10n_br_coa/__init__.py
  l10n_br_coa/__manifest__.py
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/data/l10n_br_coa_template.xml
  l10n_br_coa/i18n/l10n_br_coa.pot
  l10n_br_coa/i18n/pt_BR.po
  l10n_br_coa/models/__init__.py
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax.py
  l10n_br_coa/models/account_tax_mixin.py
  l10n_br_coa/models/account_tax_template.py
  l10n_br_coa/models/l10n_br_coa_account_tax_group_account_template.py
  l10n_br_coa/readme/CONFIGURE.rst
  l10n_br_coa/readme/CONTRIBUTORS.rst
  l10n_br_coa/readme/DESCRIPTION.rst
  l10n_br_coa/readme/INSTALL.rst
  l10n_br_coa/readme/ROADMAP.rst
  l10n_br_coa/readme/USAGE.rst
  l10n_br_coa/security/ir.model.access.csv
  l10n_br_coa/static/description/icon.png
  l10n_br_coa/static/description/index.html
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa/views/account_tax_template.xml
  setup/l10n_br_coa/odoo/addons/l10n_br_coa
  setup/l10n_br_coa/setup.py
Labels: approved, migration, bot is merging ⏳, 16.0

#2268 [16.0] mig l10n_br_account_due_list
  l10n_br_account_due_list/README.rst
  l10n_br_account_due_list/__init__.py
  l10n_br_account_due_list/__manifest__.py
  l10n_br_account_due_list/i18n/l10n_br_account_due_list.pot
  l10n_br_account_due_list/i18n/pt_BR.po
  l10n_br_account_due_list/models/__init__.py
  l10n_br_account_due_list/models/account_invoice.py
  l10n_br_account_due_list/readme/CONFIGURE.rst
  l10n_br_account_due_list/readme/CONTRIBUTORS.rst
  l10n_br_account_due_list/readme/DESCRIPTION.rst
  l10n_br_account_due_list/readme/HISTORY.rst
  l10n_br_account_due_list/readme/INSTALL.rst
  l10n_br_account_due_list/readme/ROADMAP.rst
  l10n_br_account_due_list/readme/USAGE.rst
  l10n_br_account_due_list/static/description/icon.png
  l10n_br_account_due_list/static/description/index.html
  l10n_br_account_due_list/static/img/l10n_br_account_due_list_payable.png
  l10n_br_account_due_list/static/img/l10n_br_account_due_list_receivable.png
  l10n_br_account_due_list/tests/__init__.py
  l10n_br_account_due_list/tests/test_payments.py
  l10n_br_account_due_list/views/account_invoice_view.xml
  oca_dependencies.txt
  setup/l10n_br_account_due_list/odoo/addons/l10n_br_account_due_list
  setup/l10n_br_account_due_list/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 16.0
