Repository OCA/l10n-brazil, pull requests merged in 2024-09, with the labels that each got.

#3333 [12.0][FIX][l10n_br_account_payment_order] harden migr script
  l10n_br_account_payment_order/migrations/12.0.3.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#3338 [16.0][FIX] l10n_br_account: post by action - FWP-2888
  l10n_br_account/models/account_move.py
Labels: approved, bot is merging ⏳

#3342 [16.0][IMP] l10n_br_account: rename proxy fields (port from 3307 and 2815)
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/account_move.py
  l10n_br_sale/models/fiscal_document.py
  test-requirements.txt
Labels: bot is merging ⏳, 16.0

#2912 [16.0][MIG][l10n_br_purchase]
  l10n_br_purchase/README.rst
  l10n_br_purchase/__init__.py
  l10n_br_purchase/__manifest__.py
  l10n_br_purchase/data/company.xml
  l10n_br_purchase/demo/company.xml
  l10n_br_purchase/demo/fiscal_operation_generic.xml
  l10n_br_purchase/demo/fiscal_operation_simple.xml
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/demo/product.xml
  l10n_br_purchase/hooks.py
  l10n_br_purchase/i18n/l10n_br_purchase.pot
  l10n_br_purchase/i18n/pt_BR.po
  l10n_br_purchase/models/__init__.py
  l10n_br_purchase/models/account_move.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/models/res_company.py
  l10n_br_purchase/pyproject.toml
  l10n_br_purchase/readme/CONFIGURE.md
  l10n_br_purchase/readme/CONTRIBUTORS.md
  l10n_br_purchase/readme/CREDITS.md
  l10n_br_purchase/readme/DESCRIPTION.md
  l10n_br_purchase/readme/HISTORY.md
  l10n_br_purchase/readme/INSTALL.md
  l10n_br_purchase/readme/ROADMAP.md
  l10n_br_purchase/readme/USAGE.md
  l10n_br_purchase/reports/__init__.py
  l10n_br_purchase/reports/purchase_order_templates.xml
  l10n_br_purchase/reports/purchase_report.py
  l10n_br_purchase/reports/purchase_report_views.xml
  l10n_br_purchase/security/ir.model.access.csv
  l10n_br_purchase/static/description/icon.png
  l10n_br_purchase/static/description/index.html
  l10n_br_purchase/tests/__init__.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase/tests/test_l10n_br_purchase_sn.py
  l10n_br_purchase/views/purchase_view.xml
  l10n_br_purchase/views/res_company_view.xml
  setup/l10n_br_purchase/odoo/addons/l10n_br_purchase
  setup/l10n_br_purchase/setup.py
Labels: migration, bot is merging ⏳, 16.0

#3340 [16.0][FIX] l10n_br_account: unidade de medida e valor da fatura
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/fiscal_document_line.py
Labels: bot is merging ⏳, 16.0

#3341 [14.0][IMP] l10n_br_nfe: set nfe40_IEST
  l10n_br_fiscal/models/document_move_mixin.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3273 [16.0][MIG][l10n_br_account_nfe]
  l10n_br_account_nfe/README.rst
  l10n_br_account_nfe/__init__.py
  l10n_br_account_nfe/__manifest__.py
  l10n_br_account_nfe/demo/account_invoice_sn_demo.xml
  l10n_br_account_nfe/hooks.py
  l10n_br_account_nfe/i18n/l10n_br_account_nfe.pot
  l10n_br_account_nfe/i18n/pt_BR.po
  l10n_br_account_nfe/models/__init__.py
  l10n_br_account_nfe/models/account_payment_mode.py
  l10n_br_account_nfe/models/document.py
  l10n_br_account_nfe/models/leiauteNFe.py
  l10n_br_account_nfe/pyproject.toml
  l10n_br_account_nfe/readme/CONFIGURE.md
  l10n_br_account_nfe/readme/CONTRIBUTORS.md
  l10n_br_account_nfe/readme/DESCRIPTION.md
  l10n_br_account_nfe/readme/HISTORY.md
  l10n_br_account_nfe/readme/ROADMAP.md
  l10n_br_account_nfe/readme/USAGE.md
  l10n_br_account_nfe/report/__init__.py
  l10n_br_account_nfe/report/danfe_report.xml
  l10n_br_account_nfe/report/ir_actions_report.py
  l10n_br_account_nfe/static/description/icon.png
  l10n_br_account_nfe/static/description/index.html
  l10n_br_account_nfe/tests/__init__.py
  l10n_br_account_nfe/tests/test_nfce_contingency.py
  l10n_br_account_nfe/tests/test_nfe_danfe_account.py
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
  l10n_br_account_nfe/tests/test_nfe_with_ipi.py
  l10n_br_account_nfe/views/account_payment_mode.xml
  setup/l10n_br_account_nfe/odoo/addons/l10n_br_account_nfe
  setup/l10n_br_account_nfe/setup.py
Labels: approved, bot is merging ⏳

#3346 [14.0][l10n_br_fiscal_edi][l10n_br_nfe][l10n_br_nfse][l10n_br_account] increment version avec l10n_br_fiscal_edi extraction
  l10n_br_account/__manifest__.py
  l10n_br_fiscal_closing/__manifest__.py
  l10n_br_fiscal_edi/__manifest__.py
  l10n_br_fiscal_edi/readme/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_edi/readme/readme/DESCRIPTION.rst
  l10n_br_fiscal_edi/readme/readme/ROADMAP.rst
  l10n_br_fiscal_edi/readme/readme/USAGE.rst
  l10n_br_nfe/__manifest__.py
  l10n_br_nfse/__manifest__.py
Labels: approved, bot is merging ⏳

#3348 [14.0] l10n_br_fiscal_dfe: Descrição dos módulos e contribuidores (backport)
  l10n_br_fiscal_dfe/README.rst
  l10n_br_fiscal_dfe/models/attachment.py
  l10n_br_fiscal_dfe/models/dfe.py
  l10n_br_fiscal_dfe/readme/CONTRIBUTORS.md
  l10n_br_fiscal_dfe/readme/DESCRIPTION.md
  l10n_br_fiscal_dfe/static/description/index.html
Labels: bot is merging ⏳, 14.0

#3353 [14.0][FIX] NFC-e
  l10n_br_nfe/models/document.py
  l10n_br_pos_nfce/models/pos_config.py
  l10n_br_pos_nfce/models/pos_order.py
Labels: approved, bot is merging ⏳

#3332 [14.0][l10n_br_fiscal][l10n_br_account][l10n_br_sale][l10n_br_delivery] document rename
  l10n_br_account/models/__init__.py
  l10n_br_account/models/document.py
  l10n_br_account/models/document_line.py
  l10n_br_delivery/models/__init__.py
  l10n_br_delivery/models/document_mixin.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin.py
  l10n_br_fiscal/models/document_mixin_fields.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/document.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3356 [16.0][l10n_br_fiscal][l10n_br_account][l10n_br_sale] document rename#3332 - FWP 3332
  l10n_br_account/models/__init__.py
  l10n_br_account/models/document.py
  l10n_br_account/models/document_line.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin.py
  l10n_br_fiscal/models/document_mixin_fields.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/document.py
Labels: approved, bot is merging ⏳

#3355 [15.0][l10n_br_fiscal][l10n_br_account][l10n_br_sale] document rename#3332 - FWP 3332
  l10n_br_account/models/__init__.py
  l10n_br_account/models/document.py
  l10n_br_account/models/document_line.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin.py
  l10n_br_fiscal/models/document_mixin_fields.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/document.py
Labels: approved, bot is merging ⏳

#3357 [15.0][FIX] l10n_br_purchase: fix purchase order line form button 'save and new'
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#3361 [14.0][CI] l10n_br_account_payment_brcobranca: Github CI with live API
  .github/workflows/test.yml
  l10n_br_account_payment_brcobranca/tests/test_payment_order.py
Labels: approved, bot is merging ⏳

#3335 [14.0][spec_driven_model] db wise mapping + simpler registration hook
  l10n_br_account_nfe/tests/test_nfce_contingency.py
  l10n_br_nfe/hooks.py
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_structure.py
  spec_driven_model/hooks.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, ready to merge, bot is merging ⏳

#3364 [14.0][FIX] l10n_br_account: fix account.move post when there is no fiscal document
  l10n_br_account/models/account_move.py
Labels: approved, bot is merging ⏳

#3343 [16.0][MIG] l10n_br_mis_report (continuação)
  l10n_br_mis_report/README.rst
  l10n_br_mis_report/__init__.py
  l10n_br_mis_report/__manifest__.py
  l10n_br_mis_report/data/mis_report_bp_generic.xml
  l10n_br_mis_report/data/mis_report_bp_simple.xml
  l10n_br_mis_report/data/mis_report_dre_generic.xml
  l10n_br_mis_report/data/mis_report_dre_simple.xml
  l10n_br_mis_report/data/mis_report_styles.xml
  l10n_br_mis_report/i18n/l10n_br_mis_report.pot
  l10n_br_mis_report/i18n/pt_BR.po
  l10n_br_mis_report/pyproject.toml
  l10n_br_mis_report/readme/CONFIGURE.md
  l10n_br_mis_report/readme/CONTRIBUTORS.md
  l10n_br_mis_report/readme/DESCRIPTION.md
  l10n_br_mis_report/readme/HISTORY.md
  l10n_br_mis_report/readme/INSTALL.md
  l10n_br_mis_report/readme/ROADMAP.md
  l10n_br_mis_report/readme/USAGE.md
  l10n_br_mis_report/static/description/bp.png
  l10n_br_mis_report/static/description/dre.png
  l10n_br_mis_report/static/description/icon.png
  l10n_br_mis_report/static/description/index.html
  setup/l10n_br_mis_report/odoo/addons/l10n_br_mis_report
  setup/l10n_br_mis_report/setup.py
Labels: approved, ready to merge, bot is merging ⏳, 16.0

#3334 [14.0][IMP][l10n_br_fiscal] safer NCM upgrade
  l10n_br_fiscal/migrations/14.0.11.0.0/post-migration.py
Labels: approved, ready to merge, bot is merging ⏳

#3354 [14.0][IMP] l10n_br_fiscal: tax.definition states usability / CBENEF
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3372 [16.0][REF] l10n_br_account: remove dead code
  l10n_br_account/models/account_move_line.py
Labels: approved, bot is merging ⏳

#3360 [14.0][FIX+IMP] l10n_br_account_payment_order, l10n_br_account_payment_brcobranca: Código de Desconto no caso UNICRED 400 e possibilidade de informar códigos além do 0 e 1
  l10n_br_account_payment_brcobranca/__manifest__.py
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_ailos_240_boleto_discount_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_bradesco_240_boleto_discount_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_cef_240_boleto_discount_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_santander_240_boleto_discount_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_sicredi_240_boleto_discount_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_unicred_240_400_boleto_discount_code.xml
  l10n_br_account_payment_order/demo/l10n_br_cnab_config_demo.xml
  l10n_br_account_payment_order/migrations/14.0.8.0.0/post-migration.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/views/l10n_br_cnab_config_view.xml
Labels: approved, bot is merging ⏳

#3308 [16.0][MIG][l10n_br_sale]: fix _nothing_to_invoice_error
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#3374 [14.0] l10n_br_fiscal: icms fcp and difal destination comments
  l10n_br_fiscal/data/l10n_br_fiscal_comment_data.xml
Labels: approved, bot is merging ⏳, 14.0

#3365 [14.0][REM] l10n_br_account_payment_order, l10n_br_account_payment_brcobranca: Removendo Campos, Objetos e Visões obsoletos
  l10n_br_account_payment_brcobranca/models/__init__.py
  l10n_br_account_payment_brcobranca/models/account_payment_mode.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/migrations/14.0.9.0.0/pre-migration.py
  l10n_br_account_payment_order/models/__init__.py
  l10n_br_account_payment_order/models/account_move_line.py
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_wallet_code.py
  l10n_br_account_payment_order/models/l10n_br_cnab_mov_intruction_code.py
  l10n_br_account_payment_order/models/l10n_br_cnab_return_move_code.py
  l10n_br_account_payment_order/security/ir.model.access.csv
  l10n_br_account_payment_order/views/account_move_line.xml
  l10n_br_account_payment_order/views/account_payment_line.xml
  l10n_br_account_payment_order/views/l10n_br_cnab_boleto_wallet_code_view.xml
  l10n_br_account_payment_order/views/l10n_br_cnab_mov_instruction_code_view.xml
  l10n_br_account_payment_order/views/l10n_br_cnab_return_move_code_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3272 [14.0][IMP] l10n_br_account: cancel invoice on fiscal document denial
  l10n_br_account/models/document.py
  l10n_br_account/tests/test_account_move_lc.py
Labels: approved, bot is merging ⏳

#3378 [16.0][FIX] l10n_br_account: fix _compute_fiscal_document_ids
  l10n_br_account/models/account_move.py
Labels: approved, bot is merging ⏳

#3377 [15.0][FIX] l10n_br_account: fix _compute_fiscal_document_ids
  l10n_br_account/models/account_move.py
Labels: approved, bot is merging ⏳

#3359 [14.0][FIX] l10n_br_nfe: export nfe40_iest to XML and PDF
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3382 [14.0][FIX] l10n_br_fiscal_edi: rename refactored reports
  l10n_br_fiscal_edi/models/document_event.py
  l10n_br_fiscal_edi/views/document_event_report.xml
  l10n_br_fiscal_edi/views/document_event_template.xml
Labels: approved, bot is merging ⏳

#2849 [14.0][FIX] Ao mapear a Linha de Operação Fiscal o método precisa considerar os casos onde o Partner do objeto não é o Partner para Faturar/Partner to Invoice
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: bug, approved, ready to merge, bot is merging ⏳, 14.0

#3384 [FIX] l10n_br_account_payment_brcobranca: discount value
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
Labels: approved, bot is merging ⏳

#3399 [16.0][FIX] l10n_br_fiscal_edi: rename refactored reports - fwp #3382
  l10n_br_fiscal_edi/models/document_event.py
  l10n_br_fiscal_edi/views/document_event_report.xml
  l10n_br_fiscal_edi/views/document_event_template.xml
Labels: approved, bot is merging ⏳

#3398 [15.0][FIX] l10n_br_fiscal_edi: rename refactored reports - fwp #3382
  l10n_br_fiscal_edi/models/document_event.py
  l10n_br_fiscal_edi/views/document_event_report.xml
  l10n_br_fiscal_edi/views/document_event_template.xml
Labels: approved, bot is merging ⏳

#3392 [15.0][IMP] l10n_br_fiscal: tax.definition states usability - fwp #3354
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: approved, bot is merging ⏳

#3393 [16.0][IMP] l10n_br_fiscal: tax.definition states usability - fpw 3354
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: approved, bot is merging ⏳

#3395 [16.0][IMP] l10n_br_fiscal: icms fcp and difal destination comments - fwp #3374
  l10n_br_fiscal/data/l10n_br_fiscal_comment_data.xml
Labels: approved, merged 🎉

#3394 [15.0][IMP] l10n_br_fiscal: icms fcp and difal destination comments - fwp #3374
  l10n_br_fiscal/data/l10n_br_fiscal_comment_data.xml
Labels: approved, bot is merging ⏳
