Repository OCA/l10n-brazil, pull requests merged in 2024-06, with the labels that each got.

#3108 [14.0][FIX] l10n_br_base: Add missing district to demo companies
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
Labels: approved, bot is merging ⏳

#3111 [14.0][FIX] l10n_br_fiscal: Alterar o valor do tempo limite do serviço ibpt
  l10n_br_fiscal/data/ir_cron.xml
  l10n_br_fiscal/models/ibpt.py
Labels: approved, bot is merging ⏳, 14.0

#3114 [14.0][CI] avoid suprious coverage changes
  .coveragerc
Labels: approved, bot is merging ⏳

#3110 [16.0] [FIX] l10n_br_base partner view
  l10n_br_base/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#3112 [15.0][MIG] l10n_br_cnpj_search: Migration to 15.0
  l10n_br_cnpj_search/README.rst
  l10n_br_cnpj_search/__init__.py
  l10n_br_cnpj_search/__manifest__.py
  l10n_br_cnpj_search/data/serpro_qualificacao.csv
  l10n_br_cnpj_search/i18n/l10n_br_cnpj_search.pot
  l10n_br_cnpj_search/i18n/pt_BR.po
  l10n_br_cnpj_search/models/__init__.py
  l10n_br_cnpj_search/models/cnpj_webservice.py
  l10n_br_cnpj_search/models/l10n_br_base_party_mixin.py
  l10n_br_cnpj_search/models/receitaws_webservice.py
  l10n_br_cnpj_search/models/res_company.py
  l10n_br_cnpj_search/models/res_config_settings.py
  l10n_br_cnpj_search/models/res_partner.py
  l10n_br_cnpj_search/models/serpro_webservice.py
  l10n_br_cnpj_search/readme/CONFIGURE.rst
  l10n_br_cnpj_search/readme/CONTRIBUTORS.rst
  l10n_br_cnpj_search/readme/DESCRIPTION.rst
  l10n_br_cnpj_search/readme/HISTORY.rst
  l10n_br_cnpj_search/readme/INSTALL.rst
  l10n_br_cnpj_search/readme/ROADMAP.rst
  l10n_br_cnpj_search/readme/USAGE.rst
  l10n_br_cnpj_search/security/ir.model.access.csv
  l10n_br_cnpj_search/static/description/icon.png
  l10n_br_cnpj_search/static/description/index.html
  l10n_br_cnpj_search/static/description/receita.png
  l10n_br_cnpj_search/static/description/receita1.png
  l10n_br_cnpj_search/static/description/receita2.png
  l10n_br_cnpj_search/static/description/serpro.png
  l10n_br_cnpj_search/static/description/serpro1.png
  l10n_br_cnpj_search/tests/__init__.py
  l10n_br_cnpj_search/tests/common.py
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_empresa.yaml
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_multiplos_telefones.yaml
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_not_found.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_basica.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_empresa.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_not_found.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_qsa.yaml
  l10n_br_cnpj_search/tests/test_receitaws.py
  l10n_br_cnpj_search/tests/test_serpro.py
  l10n_br_cnpj_search/views/res_company_view.xml
  l10n_br_cnpj_search/views/res_config_settings_view.xml
  l10n_br_cnpj_search/views/res_partner_view.xml
  l10n_br_cnpj_search/wizard/__init__.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.xml
  setup/l10n_br_cnpj_search/odoo/addons/l10n_br_cnpj_search
  setup/l10n_br_cnpj_search/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#3116 [12.0] l10n_br_base: Update res.city.csv data
  l10n_br_base/data/res.city.csv
Labels: approved, 12.0, bot is merging ⏳, backport

#3117 [14.0] l10n_br_base: Update res.city.csv data
  l10n_br_base/data/res.city.csv
Labels: approved, bot is merging ⏳, 14.0

#3119 [16.0] l10n_br_base: Update res.city.csv data
  l10n_br_base/data/res.city.csv
Labels: bot is merging ⏳, 16.0

#3118 [15.0] l10n_br_base: Update res.city.csv data
  l10n_br_base/data/res.city.csv
Labels: bot is merging ⏳, 15.0

#3115 [14.0][FIX] l10n_br_fiscal: Criado parâmetro para configurar o valor do tempo limite do serviço ibpt
  l10n_br_fiscal/models/data_ncm_nbs_abstract.py
  l10n_br_fiscal/models/ibpt.py
  l10n_br_fiscal/tests/test_ibpt.py
Labels: approved, bot is merging ⏳, 14.0

#3084 [14.0][FIX] l10n_br_nfse_focus: SSL verify disabled
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/views/res_company_view.xml
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/views/res_company.xml
Labels: approved, ready to merge, bot is merging ⏳

#3093 [14.0][FIX] l10n_br_account: validate move on document
  l10n_br_account/models/account_move.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/tests/common.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/tests/test_account_move_sn.py
  l10n_br_account_withholding/tests/test_account_wh_invoice.py
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳

#3124 [16.0][FIX] l10n_br_fiscal: Criado parâmetro para configurar o valor do tempo limite do serviço ibpt
  l10n_br_fiscal/models/data_ncm_nbs_abstract.py
  l10n_br_fiscal/models/ibpt.py
  l10n_br_fiscal/tests/test_ibpt.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3123 [15.0][FIX] l10n_br_fiscal: Criado parâmetro para configurar o valor do tempo limite do serviço ibpt
  l10n_br_fiscal/models/data_ncm_nbs_abstract.py
  l10n_br_fiscal/models/ibpt.py
  l10n_br_fiscal/tests/test_ibpt.py
Labels: approved, bot is merging ⏳, 15.0, backport

#3122 [14.0][FIX] l10n_br_fiscal: exclude ex from some ncm
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
Labels: approved, bot is merging ⏳, 14.0

#3099 [14.0] Reserva o nº do documento fiscal no picking
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/models/stock_picking_type.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/views/stock_picking.xml
  l10n_br_stock_account/views/stock_picking_type_view.xml
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3125 [REF] additional_data Char to Text to allow \n
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
Labels: approved, bot is merging ⏳, 14.0

#3121 [14.0][IMP] l10n_br_account_payment_brcobranca: add Santander cod_desconto
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
Labels: approved, ready to merge, bot is merging ⏳

#3120 [14.0][IMP] envia instrução de protesto na primeira instrução do Itau.
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
Labels: approved, bot is merging ⏳, 14.0

#3134 [14.0][REF] l10n_br_purchase: Usando o campo related para o País da Empresa ao invés de um campo função
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#3132 [14.0][IMP][l10n_br_nfe_spec] Pacote 9o - NT-2024-001
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#3136 [FIX][l10n_br_nfse] DANFSE report update after doc authorized
  l10n_br_nfse/models/document.py
Labels: approved, bot is merging ⏳

#3143 [16.0][FIX] l10n_br_fiscal: exclude ex from some ncm - PORT 3122
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
Labels: approved, bot is merging ⏳

#3142 [15.0][FIX] l10n_br_fiscal: exclude ex from some ncm - PORT 3122
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
Labels: approved, bot is merging ⏳

#3144 [14.0][REF] l10n_br_stock_account: Adaptando o código para os casos Sem Operação Fiscal ou Multi-Localizações
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/tests/common.py
Labels: approved, bot is merging ⏳
