Repository OCA/l10n-brazil, pull requests merged in 2024-03, with the labels that each got.

#2930 [14.0][IMP] l10n_br_fiscal: add support for using icms_imported_tax on incoming documents of return type
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#2933 [14.0][FIX] l10n_br_fiscal: update icms_base_type when icms_tax_id is set
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳, 14.0

#2927 [14.0][l10n_br_nfe][REF] refator dos campos nfe40_choice*
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/migrations/14.0.14.0.0/pre-migration.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_related.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/models/res_partner.py
Labels: refactoring, approved, bot is merging ⏳, 14.0

#2926 [14.0][l10n_br_nfe_spec] Pacote 9m (NT 2023.004 v.1.01 e NT 2019.001 v.1.60)
  l10n_br_nfe_spec/models/v4_0/leiaute_cons_sit_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_inut_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#2931 [14.0][REF] l10n_br_nfe: aprimoramento nos testes
  l10n_br_nfe/README.rst
  l10n_br_nfe/readme/CONTRIBUTORS.rst
  l10n_br_nfe/static/description/index.html
  l10n_br_nfe/tests/mock_utils.py
  l10n_br_nfe/tests/mocks/retConsReciNFe/autorizada.xml
  l10n_br_nfe/tests/mocks/retConsSitNFe/nao_consta_na_base.xml
  l10n_br_nfe/tests/mocks/retConsStatServ/em_operacao.xml
  l10n_br_nfe/tests/mocks/retEnvEvento/nfce_cancelamento.xml
  l10n_br_nfe/tests/mocks/retEnvEvento/nfe_cancelamento.xml
  l10n_br_nfe/tests/mocks/retEnviNFe/autorizada.xml
  l10n_br_nfe/tests/mocks/retEnviNFe/denegada.xml
  l10n_br_nfe/tests/mocks/retEnviNFe/lote_recebido.xml
  l10n_br_nfe/tests/mocks/retEnviNFe/rejeitada.xml
  l10n_br_nfe/tests/mocks/retEnviNFe/servico_paralizado.xml
  l10n_br_nfe/tests/mocks/retInutNFe/nfce_inutilizacao.xml
  l10n_br_nfe/tests/mocks/retInutNFe/nfe_inutilizacao.xml
  l10n_br_nfe/tests/test_nfce.py
  l10n_br_nfe/tests/test_nfe_webservices.py
Labels: approved, bot is merging ⏳

#2936 [15.0][IMP] l10n_br_fiscal: add support for using icms_imported_tax on incoming documents of return type
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#2935 [16.0][FIX] l10n_br_fiscal: update icms_base_type when icms_tax_id is set
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#2937 [16.0][IMP] l10n_br_fiscal: add support for using icms_imported_tax on incoming documents of return type
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#2934 [15.0][FIX] l10n_br_fiscal: update icms_base_type when icms_tax_id is set
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#2938 [14.0][FIX][l10n_br_account_payment_brcobranca]: sequencial na geração de arquivo REM
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
Labels: approved, bot is merging ⏳

#2939 [14.0][l10n_br_fiscal][l10n_br_nfe][REF] made edoc/NFe import wizard more generic
  l10n_br_fiscal/wizards/document_import_wizard_mixin.py
  l10n_br_fiscal/wizards/document_import_wizard_mixin.xml
  l10n_br_nfe/i18n/l10n_br_nfe.pot
  l10n_br_nfe/models/dfe.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/tests/test_nfe_import_wizard.py
  l10n_br_nfe/wizards/import_document.py
  l10n_br_nfe/wizards/import_document.xml
Labels: approved, bot is merging ⏳

#2940 [14.0][l10n_br_nfe][IMP] almost complete NFe tax importation
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#2835 [14.0][IMP] l10n_br_fiscal: Make the 'Back to Draft' button invisible if the electronic document is sent and awaiting processing.
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#2942 [14.0][REF] l10n_br_account_payment_order, l10n_br_account_payment_brcobranca, l10n_br_cnab_structure: Movido o método get_file_name para evitar ter código duplicado
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_order/models/account_payment_order.py
  l10n_br_cnab_structure/models/account_payment_oder.py
Labels: approved, bot is merging ⏳

#2868 [14.0][IMP] l10n_br_base, l10n_br_fiscal: Inclusão de um contato de Cobrança e outro de Entrega nos Dados de Demonstração
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_fiscal/demo/partner_demo.xml
Labels: approved, bot is merging ⏳

#2947 [14.0][FIX] l10n_br_stock_account: Campo parent.state causa erro no Relatório de Movimentações de Estoque
  l10n_br_stock_account/views/stock_account_view.xml
Labels: approved, bot is merging ⏳

#2951 [16.0][IMP]]l10n_br_base][l10n_br_fiscal] port: Inclusão de um contato de Cobrança e outro de Entrega nos Dados de Demonstração
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_fiscal/demo/partner_demo.xml
Labels: approved, bot is merging ⏳

#2949 [16.0][l10n_br_fiscal][REF] port: made edoc/NFe import wizard more generic
  l10n_br_fiscal/wizards/document_import_wizard_mixin.py
  l10n_br_fiscal/wizards/document_import_wizard_mixin.xml
Labels: approved, bot is merging ⏳

#2953 [15.0][l10n_br_account][MIG] update account test framework to v15
  l10n_br_account/tests/common.py
  l10n_br_account_due_list/models/account_invoice.py
Labels: approved, bot is merging ⏳

#2943 [15.0][IMP] l10n_br_fiscal: change back2draft button to invisible if edoc is sent and awaiting processing
  l10n_br_fiscal/views/document_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2954 [14.0][FIX] l10n_br_website_sale: fix checkout_autoformat_selector
  l10n_br_website_sale/controllers/main.py
  l10n_br_website_sale/static/src/js/l10n_br_address.js
Labels: approved, bot is merging ⏳

#2950 [15.0][IMP][l10n_br_base][l10n_br_fiscal] port: Inclusão de um contato de Cobrança e outro de Entrega nos Dados de Demonstração
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_fiscal/demo/partner_demo.xml
Labels: approved, ready to merge, bot is merging ⏳

#2948 [15.0][l10n_br_fiscal][REF] port: made edoc/NFe import wizard more generic
  l10n_br_fiscal/wizards/document_import_wizard_mixin.py
  l10n_br_fiscal/wizards/document_import_wizard_mixin.xml
Labels: approved, bot is merging ⏳

#2773 [14.0][ADD] l10n_br_nfse_focus: add new module
  l10n_br_nfse_focus/README.rst
  l10n_br_nfse_focus/__init__.py
  l10n_br_nfse_focus/__manifest__.py
  l10n_br_nfse_focus/data/l10n_br_nfse_focus_cron.xml
  l10n_br_nfse_focus/models/__init__.py
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/models/res_company.py
  l10n_br_nfse_focus/readme/CONFIGURE.rst
  l10n_br_nfse_focus/readme/CONTRIBUTORS.rst
  l10n_br_nfse_focus/readme/DESCRIPTION.rst
  l10n_br_nfse_focus/readme/INSTALL.rst
  l10n_br_nfse_focus/readme/USAGE.rst
  l10n_br_nfse_focus/static/description/index.html
  l10n_br_nfse_focus/tests/__init__.py
  l10n_br_nfse_focus/tests/nfse/pdf_example.pdf
  l10n_br_nfse_focus/tests/test_l10n_br_nfse_focus.py
  l10n_br_nfse_focus/views/res_company.xml
  setup/l10n_br_nfse_focus/odoo/addons/l10n_br_nfse_focus
  setup/l10n_br_nfse_focus/setup.py
Labels: approved, bot is merging ⏳

#2032 [14.0][RFC] l10n_br_website_sale: refactor /shop/address view
  l10n_br_website_sale/controllers/main.py
  l10n_br_website_sale/static/src/js/l10n_br_address.js
  l10n_br_website_sale/templates/portal_templates.xml
Labels: enhancement, approved, bot is merging ⏳, 14.0

#2957 [14.0][FIX] l10n_br_nfe: missing tag in icms choice
  l10n_br_nfe/models/document_line.py
Labels: approved, bot is merging ⏳

#2958 [14.0][FIX] l10n_br_stock_account: local variable tax_ids referenced before assignment
  l10n_br_stock_account/models/stock_move.py
Labels: approved, bot is merging ⏳

#2959 [14.0][FIX] l10n_br_nfse_focus: fix docstring to imperative mood
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/models/res_company.py
Labels: approved, bot is merging ⏳

#2960 [14.0][l10n_br_portal][l10n_br_website_sale][REF] promote to Beta status
  l10n_br_portal/__manifest__.py
  l10n_br_website_sale/__manifest__.py
Labels: approved, bot is merging ⏳

#2812 [14.0][FIX] l10n_br_pos_nfce: desabilita a emissão da fatura por padrão
  l10n_br_pos_nfce/static/src/js/Screens/OrderManagementScreen/ControlButtons/CancelOrderButton.js
  l10n_br_pos_nfce/static/src/js/Screens/ReceiptScreen/ReceiptScreen.js
  l10n_br_pos_nfce/static/src/js/models.js
  l10n_br_pos_nfce/static/src/js/nfe-xml.js
  l10n_br_pos_nfce/static/src/js/utils.js
  l10n_br_pos_nfce/static/src/xml/Screens/ReceiptScreen/ReceiptScreen.xml
Labels: approved, bot is merging ⏳

#2972 [FIX][15.0][l10n_br_fiscal_dfe] SavepointCase ->TransactionCase
  l10n_br_fiscal_dfe/tests/test_dfe.py
Labels: approved, bot is merging ⏳

#2484 [14.0][IMP] l10n_br_fiscal: adds field to define anonymous consumer
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/res_partner.py
  l10n_br_fiscal/views/res_company_view.xml
  l10n_br_fiscal/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2968 [15.0][l10n_br_nfse] mig l10n_br_nfse
  l10n_br_nfse/README.rst
  l10n_br_nfse/__init__.py
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/constants/nfse.py
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/demo/product_demo.xml
  l10n_br_nfse/i18n/l10n_br_nfse.pot
  l10n_br_nfse/i18n/pt_BR.po
  l10n_br_nfse/models/__init__.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/product_template.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/readme/CONFIGURE.rst
  l10n_br_nfse/readme/CONTRIBUTORS.rst
  l10n_br_nfse/readme/DESCRIPTION.rst
  l10n_br_nfse/readme/INSTALL.rst
  l10n_br_nfse/readme/ROADMAP.rst
  l10n_br_nfse/readme/USAGE.rst
  l10n_br_nfse/report/danfse.xml
  l10n_br_nfse/security/ir.model.access.csv
  l10n_br_nfse/static/description/icon.png
  l10n_br_nfse/static/description/index.html
  l10n_br_nfse/tests/__init__.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/document_view.xml
  l10n_br_nfse/views/product_product_view.xml
  l10n_br_nfse/views/product_template_view.xml
  l10n_br_nfse/views/res_company_view.xml
  setup/l10n_br_nfse/odoo/addons/l10n_br_nfse
  setup/l10n_br_nfse/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2977 [16.0][l10n_br_base][l10n_br_fiscal] performance: unaccent=False for code fields
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_bank.py
  l10n_br_base/models/res_city.py
  l10n_br_base/models/res_country.py
  l10n_br_base/models/res_country_state.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_bank.py
  l10n_br_base/models/res_partner_pix.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_serie.py
  l10n_br_fiscal/models/document_type.py
  l10n_br_fiscal/models/nbm.py
  l10n_br_fiscal/models/nbs.py
  l10n_br_fiscal/models/ncm.py
Labels: approved, bot is merging ⏳

#2969 [16.0][l10n_br_nfse] mig l10n_br_nfse
  l10n_br_nfse/README.rst
  l10n_br_nfse/__init__.py
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/constants/nfse.py
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/demo/product_demo.xml
  l10n_br_nfse/i18n/l10n_br_nfse.pot
  l10n_br_nfse/i18n/pt_BR.po
  l10n_br_nfse/models/__init__.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/product_template.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/readme/CONFIGURE.rst
  l10n_br_nfse/readme/CONTRIBUTORS.rst
  l10n_br_nfse/readme/DESCRIPTION.rst
  l10n_br_nfse/readme/INSTALL.rst
  l10n_br_nfse/readme/ROADMAP.rst
  l10n_br_nfse/readme/USAGE.rst
  l10n_br_nfse/report/danfse.xml
  l10n_br_nfse/security/ir.model.access.csv
  l10n_br_nfse/static/description/icon.png
  l10n_br_nfse/static/description/index.html
  l10n_br_nfse/tests/__init__.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/document_view.xml
  l10n_br_nfse/views/product_product_view.xml
  l10n_br_nfse/views/product_template_view.xml
  l10n_br_nfse/views/res_company_view.xml
  setup/l10n_br_nfse/odoo/addons/l10n_br_nfse
  setup/l10n_br_nfse/setup.py
Labels: approved, migration, bot is merging ⏳, 16.0

#2974 [16.0][FIX][l10n_br_fiscal] selection_add 'product'
  l10n_br_fiscal/models/product_template.py
Labels: approved, bot is merging ⏳

#2973 [15.0][FIX][l10n_br_fiscal] selection_add 'product'
  l10n_br_fiscal/models/product_template.py
Labels: approved, bot is merging ⏳

#2975 [14.0][l10n_br_nfse_focus][REF] backport lint fixes
  l10n_br_nfse_focus/models/document.py
Labels: approved, bot is merging ⏳

#2970 [15.0][l10n_br_nfse_focus] mig l10n_br_nfse_focus
  l10n_br_nfse_focus/README.rst
  l10n_br_nfse_focus/__init__.py
  l10n_br_nfse_focus/__manifest__.py
  l10n_br_nfse_focus/data/l10n_br_nfse_focus_cron.xml
  l10n_br_nfse_focus/i18n/l10n_br_nfse_focus.pot
  l10n_br_nfse_focus/models/__init__.py
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/models/res_company.py
  l10n_br_nfse_focus/readme/CONFIGURE.rst
  l10n_br_nfse_focus/readme/CONTRIBUTORS.rst
  l10n_br_nfse_focus/readme/DESCRIPTION.rst
  l10n_br_nfse_focus/readme/INSTALL.rst
  l10n_br_nfse_focus/readme/USAGE.rst
  l10n_br_nfse_focus/static/description/icon.png
  l10n_br_nfse_focus/static/description/index.html
  l10n_br_nfse_focus/tests/__init__.py
  l10n_br_nfse_focus/tests/nfse/pdf_example.pdf
  l10n_br_nfse_focus/tests/test_l10n_br_nfse_focus.py
  l10n_br_nfse_focus/views/res_company.xml
  setup/l10n_br_nfse_focus/odoo/addons/l10n_br_nfse_focus
  setup/l10n_br_nfse_focus/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#2966 [14.0][FIX] l10n_br_account_payment_brcobranca: espécie da moeda e documento impresso no boleto
  l10n_br_account_payment_brcobranca/models/account_move_line.py
  l10n_br_account_payment_order/constants.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
Labels: approved, bot is merging ⏳

#2979 [16.0[l10n_br_fiscal][MIG] dup restricted view fields as invisible
  l10n_br_fiscal/views/document_serie_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#2983 [14.0][l10n_br_account][REF] clean up inherited fields
  l10n_br_account/views/account_invoice_view.xml
Labels: approved, bot is merging ⏳

#2984 [FIX] ICMS ST state_to_ids domain
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#2981 [14.0][FIX] l10n_br_sale: Erro no caso 'Down Payments' Adiantamento/Entrada de Pagtos e o metodo _get_invoiceable_lines espera objetos e não uma Lista
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#2990 [14.0][FIX] l10n_br_stock_account: Campo tax_ids indo errado na criação da Fatura a partir da Ordem de Separação/stock.picking
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#2989 [FIX] ICMS FCP state_to_ids domain
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#2991 [14.0][FIX] l10n_br_fiscal: read rights for base user
  l10n_br_fiscal/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2986 [15.0][l10n_br_account][REF] clean up inherited fields
  l10n_br_account/views/account_invoice_view.xml
Labels: bot is merging ⏳
