Repository OCA/l10n-brazil, pull requests merged in 2024-07, with the labels that each got.

#3154 [14.0] nfelib<=2.0.7
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_nfe/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#3147 [14.0][FIX] ICMS Regulation default for Pernambuco state
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
Labels: bug, approved, bot is merging ⏳, 14.0

#3159 [14.0][FIX] stock_account hasattr
  l10n_br_stock_account/models/stock_picking.py
Labels: approved, bot is merging ⏳

#3148 [15.0][FIX] ICMS Regulation default for Pernambuco state
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
Labels: bug, approved, bot is merging ⏳, 15.0

#3146 [12.0][FIX] ICMS Regulation default for Pernambuco state
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
Labels: bug, approved, 12.0, bot is merging ⏳

#3162 [14.0][IMP] l10n_br_nfse: add ISSQN city validation in report
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#3156 [14.0][FIX] FCPUFDest
  l10n_br_nfe/models/document_line.py
Labels: bug, approved, bot is merging ⏳, 14.0

#3161 [14.0][ADD] comments_ids in sale.order
  l10n_br_sale/views/sale_view.xml
Labels: bug, approved, bot is merging ⏳, 14.0

#3168 [16.0][FIX] nfelib version
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_fiscal_dfe/static/description/index.html
  requirements.txt
  test-requirements.txt
Labels: approved, bot is merging ⏳

#3165 [14.0][REF] l10n_br_fiscal: split methods to facilitate inheritance
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#3167 [16.0][IMP] l10n_br_nfse: add ISSQN city validation in report - PORT 3162
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#3164 16.0 mig l10n br cnpj search
  .pre-commit-config.yaml
  l10n_br_cnpj_search/README.rst
  l10n_br_cnpj_search/__init__.py
  l10n_br_cnpj_search/__manifest__.py
  l10n_br_cnpj_search/data/serpro_qualificacao.csv
  l10n_br_cnpj_search/i18n/l10n_br_cnpj_search.pot
  l10n_br_cnpj_search/i18n/pt_BR.po
  l10n_br_cnpj_search/models/__init__.py
  l10n_br_cnpj_search/models/cnpj_webservice.py
  l10n_br_cnpj_search/models/l10n_br_base_party_mixin.py
  l10n_br_cnpj_search/models/receitaws_webservice.py
  l10n_br_cnpj_search/models/res_company.py
  l10n_br_cnpj_search/models/res_config_settings.py
  l10n_br_cnpj_search/models/res_partner.py
  l10n_br_cnpj_search/models/serpro_webservice.py
  l10n_br_cnpj_search/readme/CONFIGURE.rst
  l10n_br_cnpj_search/readme/CONTRIBUTORS.rst
  l10n_br_cnpj_search/readme/DESCRIPTION.rst
  l10n_br_cnpj_search/readme/HISTORY.rst
  l10n_br_cnpj_search/readme/INSTALL.rst
  l10n_br_cnpj_search/readme/ROADMAP.rst
  l10n_br_cnpj_search/readme/USAGE.rst
  l10n_br_cnpj_search/security/ir.model.access.csv
  l10n_br_cnpj_search/static/description/icon.png
  l10n_br_cnpj_search/static/description/index.html
  l10n_br_cnpj_search/static/description/receita.png
  l10n_br_cnpj_search/static/description/receita1.png
  l10n_br_cnpj_search/static/description/receita2.png
  l10n_br_cnpj_search/static/description/serpro.png
  l10n_br_cnpj_search/static/description/serpro1.png
  l10n_br_cnpj_search/tests/__init__.py
  l10n_br_cnpj_search/tests/common.py
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_empresa.yaml
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_multiplos_telefones.yaml
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_not_found.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_basica.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_empresa.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_not_found.yaml
  l10n_br_cnpj_search/tests/fixtures/test_serpro_qsa.yaml
  l10n_br_cnpj_search/tests/test_receitaws.py
  l10n_br_cnpj_search/tests/test_serpro.py
  l10n_br_cnpj_search/views/res_company_view.xml
  l10n_br_cnpj_search/views/res_config_settings_view.xml
  l10n_br_cnpj_search/views/res_partner_view.xml
  l10n_br_cnpj_search/wizard/__init__.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.xml
  setup/l10n_br_cnpj_search/odoo/addons/l10n_br_cnpj_search
  setup/l10n_br_cnpj_search/setup.py
  test-requirements.txt
Labels: approved, bot is merging ⏳

#3166 [15.0][IMP] l10n_br_nfse: add ISSQN city validation in report - PORT 3162
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#3172 [14.0][FIX] l10n_br_cnpj_search: carregamento do nome da cidade
  l10n_br_cnpj_search/tests/test_receitaws.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
Labels: approved, bot is merging ⏳

#3169 [16.0][UPD] l10n_br_zip: cep_ws_provide default
  l10n_br_zip/__manifest__.py
  l10n_br_zip/migrations/16.0.2.2.0/pre-migration.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/models/res_config_settings.py
  l10n_br_zip/static/description/index.html
Labels: bot is merging ⏳

#3171 [15.0][UPD] l10n_br_zip: cep_ws_provide default
  l10n_br_zip/__manifest__.py
  l10n_br_zip/migrations/15.0.1.1.0/pre-migration.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/models/res_config_settings.py
  l10n_br_zip/static/description/index.html
Labels: approved, bot is merging ⏳

#3170 [14.0][UPD] l10n_br_zip: cep_ws_provide default
  l10n_br_zip/__manifest__.py
  l10n_br_zip/migrations/14.0.2.2.0/pre-migration.py
  l10n_br_zip/models/l10n_br_zip.py
  l10n_br_zip/models/res_config_settings.py
  l10n_br_zip/static/description/index.html
Labels: approved, bot is merging ⏳

#3174 [16.0][PORT] 3172 from 14.0
  l10n_br_cnpj_search/tests/test_receitaws.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
Labels: approved, bot is merging ⏳

#3149 [16.0][FIX] ICMS Regulation default for Pernambuco state
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
Labels: bug, needs fixing, approved, bot is merging ⏳, 16.0

#3176 [12.0][l10n_br_nfe][REF] l10n_br_nfe: nfelib<=2.0.7
  requirements.txt
Labels: approved, bot is merging ⏳

#3177 [12.0][spec_driven_model][FIX] spec_driven_model: disable automatic views
  spec_driven_model/models/__init__.py
Labels: approved, bot is merging ⏳

#3173 [15.0][PORT] 3172 from 14.0
  l10n_br_cnpj_search/tests/test_receitaws.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
Labels: approved, bot is merging ⏳

#3178 [12.0] Adicionado campo de valores do DIFAL no relatório de faturas
  l10n_br_account/report/account_invoice_report.py
Labels: approved, 12.0, bot is merging ⏳

#3179 [14.0] Adicionado campo de valores do DIFAL no relatório de faturas
  l10n_br_account/report/account_invoice_report.py
Labels: approved, bot is merging ⏳, 14.0

#3180 [15.0] Adicionado campo de valores do DIFAL no relatório de faturas
  l10n_br_account/report/account_invoice_report.py
Labels: bot is merging ⏳, 15.0

#3109 [14.0][FIX] Valor dos produtos na NF-e
  l10n_br_account/tests/common.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account_nfe/tests/__init__.py
  l10n_br_account_nfe/tests/test_nfe_with_ipi.py
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: bug, approved, ready to merge, bot is merging ⏳, 14.0

#3135 [14.0][FIX][l10n_br_nfse] price_gross
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/report/danfse.xml
Labels: bug, approved, ready to merge, bot is merging ⏳, 14.0

#3068 [14.0][REF] Impressão da DANFE a partir da lib BrazilFiscalReport
  l10n_br_account_nfe/__init__.py
  l10n_br_account_nfe/__manifest__.py
  l10n_br_account_nfe/report/__init__.py
  l10n_br_account_nfe/report/danfe_report.xml
  l10n_br_account_nfe/report/ir_actions_report.py
  l10n_br_account_nfe/tests/__init__.py
  l10n_br_account_nfe/tests/test_nfe_danfe_account.py
  l10n_br_nfe/__init__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/constants/nfe.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/report/__init__.py
  l10n_br_nfe/report/danfe_report.xml
  l10n_br_nfe/report/ir_actions_report.py
  l10n_br_nfe/tests/__init__.py
  l10n_br_nfe/tests/test_nfe_danfe.py
  l10n_br_nfe/views/res_company_view.xml
  requirements.txt
Labels: approved, ready to merge, bot is merging ⏳, 14.0

#3189 [15.0][IMP] l10n_br_fiscal: add city update on city_taxation_code_id onchange
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#3196 [16.0][l10n_br_fiscal][IMP] l10n_br_fiscal: add city update on city_taxation_code_id onchange
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#3187 [15.0][FIX] l10n_br_base: Add missing district to demo companies
  l10n_br_base/demo/res_company_demo.xml
Labels: approved, bot is merging ⏳, 15.0, backport

#3188 [16.0][FIX] l10n_br_base: Add missing district to demo companies
  l10n_br_base/demo/res_company_demo.xml
Labels: approved, bot is merging ⏳, 16.0, backport

#3205 [l16.0][IMP] l10n_br_nfe_spec: Pacote 9o - NT-2024-001
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳, 16.0, backport

#3204 [15.0][IMP] l10n_br_nfe_spec: Pacote 9o - NT-2024-001
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳, 15.0, backport

#3184 [14.0][FIX] l10n_br_fiscal: fix validation error message
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳, 14.0

#3200 [16.0][l10n_br_fiscal] Oca port from 14.0 to 16.0 pr 3081
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/models/document_event.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/views/document_event_view.xml
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳, 16.0, backport

#3192 [15.0][l10n_br_fiscal] Oca port from 14.0 to 15.0 pr 3081
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/models/document_event.py
  l10n_br_fiscal/models/document_workflow.py
  l10n_br_fiscal/views/document_event_view.xml
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳, 15.0, backport

#3210 [15.0][FIX] l10n_br_base: check ie only partner is company (port from 3206)
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳

#2876 [15.0][MIG][spec_driven_model]
  .pre-commit-config.yaml
  setup/spec_driven_model/odoo/addons/spec_driven_model
  setup/spec_driven_model/setup.py
  spec_driven_model/README.rst
  spec_driven_model/__init__.py
  spec_driven_model/__manifest__.py
  spec_driven_model/hooks.py
  spec_driven_model/i18n/pt_BR.po
  spec_driven_model/i18n/spec_driven_model.pot
  spec_driven_model/models/__init__.py
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/models/spec_view.py
  spec_driven_model/readme/CONFIGURE.rst
  spec_driven_model/readme/CONTRIBUTORS.rst
  spec_driven_model/readme/DESCRIPTION.rst
  spec_driven_model/readme/HISTORY.rst
  spec_driven_model/readme/INSTALL.rst
  spec_driven_model/readme/ROADMAP.rst
  spec_driven_model/readme/USAGE.rst
  spec_driven_model/static/description/icon.png
  spec_driven_model/static/description/index.html
  spec_driven_model/tests/PurchaseOrderSchema.xsd
  spec_driven_model/tests/__init__.py
  spec_driven_model/tests/fake_mixin.py
  spec_driven_model/tests/fake_odoo_purchase.py
  spec_driven_model/tests/purchase_order_lib.py
  spec_driven_model/tests/spec_poxsd.py
  spec_driven_model/tests/spec_purchase.py
  spec_driven_model/tests/test_spec_model.py
  test-requirements.txt
Labels: approved, migration, bot is merging ⏳, 15.0

#3203 [14.0][spec_driven_model][REF] spec_driven_model: clean inherit+import
  spec_driven_model/models/__init__.py
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/models/spec_view.py
Labels: approved, bot is merging ⏳

#3199 [16.0][l10n_br_fiscal][REF] additional_data Char to Text to allow \n
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3191 [15.0][l10n_br_fiscal][REF] additional_data Char to Text to allow \n
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
Labels: approved, bot is merging ⏳, 15.0, backport

#2882 [16.0][MIG][spec_driven_model]
  .pre-commit-config.yaml
  oca_dependencies.txt
  setup/spec_driven_model/odoo/addons/spec_driven_model
  setup/spec_driven_model/setup.py
  spec_driven_model/README.rst
  spec_driven_model/__init__.py
  spec_driven_model/__manifest__.py
  spec_driven_model/hooks.py
  spec_driven_model/i18n/pt_BR.po
  spec_driven_model/i18n/spec_driven_model.pot
  spec_driven_model/models/__init__.py
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/models/spec_view.py
  spec_driven_model/readme/CONFIGURE.rst
  spec_driven_model/readme/CONTRIBUTORS.rst
  spec_driven_model/readme/DESCRIPTION.rst
  spec_driven_model/readme/HISTORY.rst
  spec_driven_model/readme/INSTALL.rst
  spec_driven_model/readme/ROADMAP.rst
  spec_driven_model/readme/USAGE.rst
  spec_driven_model/static/description/icon.png
  spec_driven_model/static/description/index.html
  spec_driven_model/tests/PurchaseOrderSchema.xsd
  spec_driven_model/tests/__init__.py
  spec_driven_model/tests/fake_mixin.py
  spec_driven_model/tests/fake_odoo_purchase.py
  spec_driven_model/tests/purchase_order_lib.py
  spec_driven_model/tests/spec_poxsd.py
  spec_driven_model/tests/spec_purchase.py
  spec_driven_model/tests/test_spec_model.py
  test-requirements.txt
Labels: approved, migration, bot is merging ⏳, 16.0

#3190 [15.0[l10n_br_fiscal][REF] document number fields in fiscal mixin
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
Labels: approved, bot is merging ⏳, 15.0, backport

#3209 [16.0][FIX] l10n_br_fiscal: fix validation error message (port from #3184)
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3212 [14.0][IMP] l10n_br_fiscal: change page name Recipient to Partners
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳, 14.0

#3211 [16.0][FIX] l10n_br_base: check ie only partner is company (port from 3206)
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3195 [16.0][l10n_br_fiscal] Oca port from 14.0 to 16.0 pr 3016
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax_definition.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3197 [16.0][l10n_br_fiscal] Oca port from 14.0 to 16.0 pr 3093
  l10n_br_fiscal/models/document_workflow.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3206 [14.0][FIX] l10n_br_base: check ie only partner is_company
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳, 14.0

#3186 [14.0][FIX] l10n_br_nfe: don't read stacking point id
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3214 [14.0][l10n_br_nfe][REF] l10n_br_nfe: lint fixes
  l10n_br_nfe/__init__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/mde.py
  l10n_br_nfe/models/res_partner.py
  l10n_br_nfe/wizards/import_document.py
Labels: approved, bot is merging ⏳

#3215 [14.0][spec_driven_model][FIX] fix MRO + auto access
  l10n_br_nfe/hooks.py
  spec_driven_model/hooks.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#3218 [14.0][FIX] l10n_br_account_payment_brcobranca: Santander parser
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#3220 [14.0][REF] l10n_br_account_payment_order: lint fixes
  l10n_br_account_payment_order/models/account_payment_line.py
  l10n_br_account_payment_order/models/account_payment_mode.py
  l10n_br_account_payment_order/models/account_payment_order.py
  l10n_br_account_payment_order/models/l10n_br_cnab_change_methods.py
  l10n_br_account_payment_order/models/l10n_br_cnab_data_abstract.py
  l10n_br_account_payment_order/views/account_move_view.xml
Labels: approved, bot is merging ⏳, 14.0

#3234 [16.0][FIX] l10n_br_base: Cidade nos dados de demostração
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/demo/res_company_demo.xml
Labels: approved, bot is merging ⏳, 16.0

#3225 [14.0][REF] l10n_br_account_payment_brcobranca: backport do lint
  l10n_br_account_payment_brcobranca/constants/br_cobranca.py
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
Labels: approved, bot is merging ⏳, 14.0

#3223 [16.0][MIG] l10n_br_ie_search
  l10n_br_cnpj_search/models/receitaws_webservice.py
  l10n_br_ie_search/README.rst
  l10n_br_ie_search/__init__.py
  l10n_br_ie_search/__manifest__.py
  l10n_br_ie_search/i18n/l10n_br_ie_search.pot
  l10n_br_ie_search/i18n/pt_BR.po
  l10n_br_ie_search/models/__init__.py
  l10n_br_ie_search/models/res_config_settings.py
  l10n_br_ie_search/models/sefaz_webservice.py
  l10n_br_ie_search/models/sintegra_webservice.py
  l10n_br_ie_search/readme/CONFIGURE.rst
  l10n_br_ie_search/readme/CONTRIBUTORS.rst
  l10n_br_ie_search/readme/DESCRIPTION.rst
  l10n_br_ie_search/readme/USAGE.rst
  l10n_br_ie_search/static/description/icon.png
  l10n_br_ie_search/static/description/index.html
  l10n_br_ie_search/static/icon.png
  l10n_br_ie_search/tests/__init__.py
  l10n_br_ie_search/tests/fixtures/test_sefaz.yaml
  l10n_br_ie_search/tests/test_sefaz.py
  l10n_br_ie_search/tests/test_sintegra.py
  l10n_br_ie_search/views/res_config_settings_view.xml
  l10n_br_ie_search/wizard/__init__.py
  l10n_br_ie_search/wizard/extend_partner_cnpj_search_wizard.py
  setup/l10n_br_ie_search/odoo/addons/l10n_br_ie_search
  setup/l10n_br_ie_search/setup.py
Labels: migration, bot is merging ⏳, 16.0

#3113 [15.0][MIG] l10n_br_ie_search: Migration to 15.0
  l10n_br_cnpj_search/models/receitaws_webservice.py
  l10n_br_ie_search/README.rst
  l10n_br_ie_search/__init__.py
  l10n_br_ie_search/__manifest__.py
  l10n_br_ie_search/i18n/l10n_br_ie_search.pot
  l10n_br_ie_search/i18n/pt_BR.po
  l10n_br_ie_search/models/__init__.py
  l10n_br_ie_search/models/res_config_settings.py
  l10n_br_ie_search/models/sefaz_webservice.py
  l10n_br_ie_search/models/sintegra_webservice.py
  l10n_br_ie_search/readme/CONFIGURE.rst
  l10n_br_ie_search/readme/CONTRIBUTORS.rst
  l10n_br_ie_search/readme/DESCRIPTION.rst
  l10n_br_ie_search/readme/USAGE.rst
  l10n_br_ie_search/static/description/icon.png
  l10n_br_ie_search/static/description/index.html
  l10n_br_ie_search/static/icon.png
  l10n_br_ie_search/tests/__init__.py
  l10n_br_ie_search/tests/fixtures/test_sefaz.yaml
  l10n_br_ie_search/tests/test_sefaz.py
  l10n_br_ie_search/tests/test_sintegra.py
  l10n_br_ie_search/views/res_config_settings_view.xml
  l10n_br_ie_search/wizard/__init__.py
  l10n_br_ie_search/wizard/extend_partner_cnpj_search_wizard.py
  setup/l10n_br_ie_search/odoo/addons/l10n_br_ie_search
  setup/l10n_br_ie_search/setup.py
Labels: migration, bot is merging ⏳, 15.0

#3193 [15.0][REF] l10n_br_fiscal: split methods to facilitate inheritance
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: work in progress, approved, bot is merging ⏳, 15.0, backport

#3236 [14.0][FIX] l10n_br_base: Cidade nos dados de demostração
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/demo/res_company_demo.xml
Labels: approved, bot is merging ⏳, 14.0, backport

#3235 [15.0][FIX] l10n_br_base: Cidade nos dados de demostração
  l10n_br_base/demo/l10n_br_base_demo.xml
  l10n_br_base/demo/res_company_demo.xml
Labels: approved, bot is merging ⏳, 15.0, backport

#3230 [14.0][l10n_br_cnpj_search][l10n_br_ie_search] resolve problemas com ausencia de valores
  l10n_br_cnpj_search/models/receitaws_webservice.py
  l10n_br_ie_search/models/sintegra_webservice.py
Labels: approved, bot is merging ⏳, 14.0

#3227 [16.0][FIX] l10n_br_stock: Remove old migration file
  l10n_br_base/migrations/14.0.2.0.0/post-migration.py
  l10n_br_hr/migrations/14.0.1.0.0/pre-migration.py
  l10n_br_nfe/migrations/14.0.14.0.0/pre-migration.py
  l10n_br_nfe_spec/migrations/14.0.5.0.0/pre-migration.py
  l10n_br_stock/migrations/14.0.2.0.0/pre-migration.py
  l10n_br_zip/migrations/14.0.1.0.0/pre-migration.py
Labels: approved, bot is merging ⏳, 16.0

#3231 [16.0][MIG] l10n_br_fiscal_closing
  l10n_br_fiscal_closing/README.rst
  l10n_br_fiscal_closing/__init__.py
  l10n_br_fiscal_closing/__manifest__.py
  l10n_br_fiscal_closing/i18n/l10n_br_fiscal_closing.pot
  l10n_br_fiscal_closing/i18n/pt_BR.po
  l10n_br_fiscal_closing/models/__init__.py
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/models/document.py
  l10n_br_fiscal_closing/readme/CONFIGURE.rst
  l10n_br_fiscal_closing/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_closing/readme/CREDITS.rst
  l10n_br_fiscal_closing/readme/DESCRIPTION.rst
  l10n_br_fiscal_closing/readme/HISTORY.rst
  l10n_br_fiscal_closing/readme/INSTALL.rst
  l10n_br_fiscal_closing/readme/ROADMAP.rst
  l10n_br_fiscal_closing/readme/USAGE.rst
  l10n_br_fiscal_closing/security/ir.model.access.csv
  l10n_br_fiscal_closing/static/description/icon.png
  l10n_br_fiscal_closing/static/description/index.html
  l10n_br_fiscal_closing/tests/__init__.py
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_fiscal_closing/views/closing.xml
  setup/l10n_br_fiscal_closing/odoo/addons/l10n_br_fiscal_closing
  setup/l10n_br_fiscal_closing/setup.py
Labels: approved, migration, bot is merging ⏳, 16.0

#3229 [15.0][MIG] l10n_br_fiscal_closing
  l10n_br_fiscal_closing/README.rst
  l10n_br_fiscal_closing/__init__.py
  l10n_br_fiscal_closing/__manifest__.py
  l10n_br_fiscal_closing/i18n/l10n_br_fiscal_closing.pot
  l10n_br_fiscal_closing/i18n/pt_BR.po
  l10n_br_fiscal_closing/models/__init__.py
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/models/document.py
  l10n_br_fiscal_closing/readme/CONFIGURE.rst
  l10n_br_fiscal_closing/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_closing/readme/CREDITS.rst
  l10n_br_fiscal_closing/readme/DESCRIPTION.rst
  l10n_br_fiscal_closing/readme/HISTORY.rst
  l10n_br_fiscal_closing/readme/INSTALL.rst
  l10n_br_fiscal_closing/readme/ROADMAP.rst
  l10n_br_fiscal_closing/readme/USAGE.rst
  l10n_br_fiscal_closing/security/ir.model.access.csv
  l10n_br_fiscal_closing/static/description/icon.png
  l10n_br_fiscal_closing/static/description/index.html
  l10n_br_fiscal_closing/tests/__init__.py
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_fiscal_closing/views/closing.xml
  setup/l10n_br_fiscal_closing/odoo/addons/l10n_br_fiscal_closing
  setup/l10n_br_fiscal_closing/setup.py
Labels: approved, migration, bot is merging ⏳, 15.0

#3238 [14.0][FIX] l10n_br_nfe: fix _nfe_cancel method
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3239 [14.0][FIX][spec_driven_model] define access_fields before loop
  spec_driven_model/hooks.py
Labels: approved, bot is merging ⏳

#3242 [16.0][FIX][spec_driven_model] avoid undef access_fields
  spec_driven_model/hooks.py
Labels: approved, 16.0

#3241 [15.0][FIX][spec_driven_model] avoid undef access_fields
  spec_driven_model/hooks.py
Labels: approved, bot is merging ⏳, 15.0

#3247 [14.0][CI] workaround vcrpy install
  .github/workflows/test.yml
  test-requirements.txt
Labels: approved

#3248 [15.0][CI] workaround vcrpy install
  .github/workflows/test.yml
  test-requirements.txt
Labels: approved

#3249 [16.0][CI] workaround vcrpy install
  .github/workflows/test.yml
  test-requirements.txt
Labels: approved

#3244 [14.0][REF] l10n_br_fiscal: Manter os preços no teste unitário.
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: approved, bot is merging ⏳

#3246 [14.0][FIX] l10n_br_cnab_structure: remove payment_line_ids in structure line field
  l10n_br_cnab_structure/data/l10n_br_cnab.line.field.csv
Labels: bot is merging ⏳, 14.0

#3250 [15.0][FIX] l10n_br_nfe: fix _nfe_cancel method (port from #3238)
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳, 15.0, backport
