Repository OCA/l10n-brazil, pull requests merged in 2024-01, with the labels that each got.

#2843 [14.0][IMP] l10n_br_nfe: Check company.partner == partner and partner.state != partner_shipping.state for idDest in _compute_nfe40_idDest
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#2847 [14.0][IMP] l10n_br_stock_account: add ncm_id and others on view form
  l10n_br_stock_account/views/stock_picking.xml
Labels: approved, ready to merge, bot is merging ⏳

#2848 [14.0][FORWARD-PORT][l10n_br_account_payment_brcobranca] - Santander CNAB 400
  l10n_br_account_payment_brcobranca/models/account_move_line.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/views/account_payment_mode.xml
Labels: approved, bot is merging ⏳

#2743 [14.0][REF] l10n_br_sale: Adaptando o modulo para manter a compatibilidade com os casos internacionais
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/views/sale_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2759 [14.0][REF] l10n_br_purchase: Adaptando o modulo para manter a compatibilidade com os casos internacionais
  l10n_br_purchase/models/account_move.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2840 [14.0][FIX] l10n_br_coa: fix wh tax factor_percent
  l10n_br_coa/data/account_tax_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#2839 [14.0][IMP] l10n_br_coa_generic: add group tax
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, ready to merge, bot is merging ⏳

#2719 [14.0][RFC] l10n_br_portal: my/account form refactor
  l10n_br_portal/__init__.py
  l10n_br_portal/controllers/portal.py
  l10n_br_portal/models/__init__.py
  l10n_br_portal/models/res_partner.py
  l10n_br_portal/static/src/js/l10n_br_portal_tour.js
  l10n_br_portal/views/portal_templates.xml
Labels: approved, bot is merging ⏳

#2857 [14.0][FIX] l10n_br_account_payment_order: tracking field warn
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
Labels: approved, bot is merging ⏳

#2711 [14.0][FIX] l10n_br_purchase_stock: Botão para acessar as Faturas a partir do Pedido de Compra
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_purchase_stock/models/purchase_order.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_purchase_stock/views/purchase_order.xml
Labels: bot is merging ⏳

#2867 [14.0][FIX] l10n_br_stock_account: Método para obter Operação Fiscal padrão deve usar a empresa do ENV não do usuário
  l10n_br_stock_account/models/stock_picking.py
Labels: approved, bot is merging ⏳

#2871 [14.0][IMP] l10n_br_account_payment_order: cnab_codes Santander [240 e 400]
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_santander_cnab_240_400.xml
Labels: approved, bot is merging ⏳

#2866 [14.0][FIX] l10n_br_sale: Possibilidade de incluir uma Seção ou Nota na Linha do Pedido de Vendas
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#2883 [14.0][REF] l10n_br_sale: Removendo onchanges desnecessários nos Dados de Demonstração
  l10n_br_sale/demo/l10n_br_sale.xml
Labels: approved, bot is merging ⏳

#2884 [14.0][REF] l10n_br_sale_stock: Removendo onchanges desnecessários nos Dados de Demonstração
  l10n_br_sale_stock/demo/sale_order_demo.xml
Labels: approved, bot is merging ⏳

#2885 [14.0][REF] l10n_br_stock_account: Removendo onchanges desnecessários nos Dados de Demonstração
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
Labels: approved, bot is merging ⏳

#2886 [14.0][REF] l10n_br_purchase: Removendo onchanges desnecessários nos Dados de Demonstração
  l10n_br_purchase/demo/l10n_br_purchase.xml
Labels: approved, bot is merging ⏳

#2887 [14.0][REF] l10n_br_purchase_stock: Removendo onchanges desnecessários nos Dados de Demonstração
  l10n_br_purchase_stock/demo/purchase_order.xml
Labels: approved, bot is merging ⏳

#2859 [16.0][FIX][l10n_br_coa_simple] conta ICMS SN à recolher
  l10n_br_coa_simple/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, ready to merge, bot is merging ⏳

#2854 [15.0][IMP] l10n_br_coa_generic: add group tax
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, ready to merge, bot is merging ⏳

#2858 [16.0][l10n_br_coa][MIG] ensure id keys in account_ref map
  l10n_br_coa/models/account_chart_template.py
Labels: approved, ready to merge, bot is merging ⏳

#2855 [16.0][IMP] l10n_br_coa_generic: add group tax
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, bot is merging ⏳

#2869 [15.0][MIG][l10n_br_fiscal_certificate]
  l10n_br_fiscal_certificate/README.rst
  l10n_br_fiscal_certificate/__init__.py
  l10n_br_fiscal_certificate/__manifest__.py
  l10n_br_fiscal_certificate/constants.py
  l10n_br_fiscal_certificate/hooks.py
  l10n_br_fiscal_certificate/i18n/l10n_br_fiscal_certificate.pot
  l10n_br_fiscal_certificate/i18n/pt_BR.po
  l10n_br_fiscal_certificate/models/__init__.py
  l10n_br_fiscal_certificate/models/certificate.py
  l10n_br_fiscal_certificate/models/res_company.py
  l10n_br_fiscal_certificate/models/res_config_settings.py
  l10n_br_fiscal_certificate/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_certificate/readme/DESCRIPTION.rst
  l10n_br_fiscal_certificate/readme/HISTORY.rst
  l10n_br_fiscal_certificate/readme/USAGE.rst
  l10n_br_fiscal_certificate/security/ir.model.access.csv
  l10n_br_fiscal_certificate/static/description/icon.png
  l10n_br_fiscal_certificate/static/description/index.html
  l10n_br_fiscal_certificate/tests/test_certificate.py
  l10n_br_fiscal_certificate/views/certificate_view.xml
  l10n_br_fiscal_certificate/views/res_company_view.xml
  l10n_br_fiscal_certificate/views/res_config_settings_view.xml
  requirements.txt
  setup/l10n_br_fiscal_certificate/odoo/addons/l10n_br_fiscal_certificate
  setup/l10n_br_fiscal_certificate/setup.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#2895 [14.0][FIX] *_cnpj_search: mock the api response
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_empresa.yaml
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_multiplos_telefones.yaml
  l10n_br_cnpj_search/tests/fixtures/test_receitaws_not_found.yaml
  l10n_br_cnpj_search/tests/test_receitaws.py
Labels: approved, bot is merging ⏳

#2861 [14.0][REF] l10n_br_sale: Adaptando o modulo para ter compatibilidade com o Caso Internacional ou sem Operação Fiscal
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: approved, ready to merge, bot is merging ⏳

#2892 [14.0][REF+FIX] l10n_br_fiscal_certificate, l10n_br_nfe: Incluído um campo compute para obter o Certificado( e-CNPJ ou e-NFe)
  l10n_br_fiscal_certificate/models/res_company.py
  l10n_br_fiscal_certificate/tests/__init__.py
  l10n_br_fiscal_certificate/tests/test_certificate.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/invalidate_number.py
Labels: approved, bot is merging ⏳
