Repository OCA/l10n-brazil, pull requests merged in 2024-10, with the labels that each got.

#3405 [16.0][l10n_br_nfe] fwp 3341 3353 3359
  l10n_br_fiscal/models/document_move_mixin.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3404 [15.0][l10n_br_nfe] fwp 3341 3353 3359
  l10n_br_fiscal/models/document_move_mixin.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3411 [15.0][FIX] l10n_br_fiscal_edi: fix warnings - bp 3400
  l10n_br_fiscal_edi/__manifest__.py
  l10n_br_fiscal_edi/security/ir.model.access.csv
  l10n_br_fiscal_edi/views/document_view.xml
Labels: approved, bot is merging ⏳

#3410 [14.0][FIX] l10n_br_fiscal_edi: fix warnings - bp 3400
  l10n_br_fiscal_edi/__manifest__.py
  l10n_br_fiscal_edi/security/ir.model.access.csv
  l10n_br_fiscal_edi/views/document_view.xml
Labels: approved, bot is merging ⏳

#3414 [14.0][FIX] l10n_br_sale_stock: _get_fiscal_partner method returning integer instead of partner object
  l10n_br_sale_stock/models/stock_picking.py
Labels: approved, bot is merging ⏳

#3412 [14.0][IMP] l10n_br_fiscal_closing: add document_cte_ids
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/views/closing.xml
Labels: approved, bot is merging ⏳

#3415 [14.0][FIX] l10n_br_pos_nfce: fiscal map must be related to product
  l10n_br_pos_nfce/models/pos_order.py
Labels: approved, bot is merging ⏳

#3327 [14.0][FIX] l10n_br_stock_account, l10n_br_purchase_stock, l10n_br_sale_stock: Método para obter a Operação Fiscal Padrão
  l10n_br_purchase_stock/models/__init__.py
  l10n_br_purchase_stock/models/stock_picking.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_stock_account/models/stock_picking.py
Labels: approved, bot is merging ⏳

#3396 [15.0][l10n_br_fiscal][l10n_br_sale][l10n_br_purchase] fix mapping line op fiscal with partner to invoice - fwp #2849
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: approved, ready to merge, bot is merging ⏳

#3409 [14.0] Refatoração dos Scripts de Migração módulos CNAB.
  l10n_br_account_payment_order/migrations/14.0.6.0.0/post-migration.py
  l10n_br_account_payment_order/migrations/14.0.6.0.0/pre-migration.py
  l10n_br_account_payment_order/migrations/14.0.7.0.0/post-migration.py
  l10n_br_account_payment_order/migrations/14.0.9.0.0/pre-migration.py
  l10n_br_account_payment_order/models/l10n_br_cnab_code.py
Labels: needs review, approved, ready to merge, bot is merging ⏳, 14.0

#3427 [14.0][spec_driven_model][l10n_br_nfe] stacking fixes
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_related.py
  l10n_br_nfe/models/document_supplement.py
  l10n_br_nfe/tests/test_nfe_structure.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#3426 [14.0][REF][spec_driven_model]: rm dead code; + XML tests
  spec_driven_model/models/spec_export.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, bot is merging ⏳

#3385 [16.0][FIX] l10n_br_fiscal: fix redundant field defaults / duplicate field labels
  l10n_br_account/models/document_line.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_mixin_fields.py
  l10n_br_fiscal/tests/test_subsequent_operation.py
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_nfe/models/document.py
  l10n_br_purchase/models/purchase_order.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#3430 [14.0][IMP] l10n_br_nfe: Configuração das margens da DANFE
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/report/ir_actions_report.py
  l10n_br_nfe/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#3429 [14.0][UPD] l10n_br_account_payment_order, l10n_br_account_payment_brcobranca: Atualizando o README
  l10n_br_account_payment_brcobranca/README.rst
  l10n_br_account_payment_brcobranca/readme/CONFIGURE.rst
  l10n_br_account_payment_brcobranca/readme/CONTRIBUTORS.rst
  l10n_br_account_payment_brcobranca/readme/DESCRIPTION.rst
  l10n_br_account_payment_brcobranca/readme/HISTORY.rst
  l10n_br_account_payment_brcobranca/readme/INSTALL.rst
  l10n_br_account_payment_brcobranca/readme/USAGE.rst
  l10n_br_account_payment_brcobranca/static/description/index.html
  l10n_br_account_payment_order/README.rst
  l10n_br_account_payment_order/readme/CONFIGURE.rst
  l10n_br_account_payment_order/readme/CONTRIBUTORS.rst
  l10n_br_account_payment_order/readme/DESCRIPTION.rst
  l10n_br_account_payment_order/readme/HISTORY.rst
  l10n_br_account_payment_order/readme/ROADMAP.rst
  l10n_br_account_payment_order/readme/USAGE.rst
  l10n_br_account_payment_order/static/description/index.html
Labels: approved, bot is merging ⏳

#3436 [16.0][l10n_br_fiscal][l10n_br_sale][l10n_br_purchase] fwp 2849
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#3091 [14.0][IMP] add delivery_nfe volumes
  l10n_br_delivery_nfe/README.rst
  l10n_br_delivery_nfe/__init__.py
  l10n_br_delivery_nfe/__manifest__.py
  l10n_br_delivery_nfe/models/__init__.py
  l10n_br_delivery_nfe/models/product_product.py
  l10n_br_delivery_nfe/models/product_template.py
  l10n_br_delivery_nfe/models/stock_picking.py
  l10n_br_delivery_nfe/models/stock_picking_lacres.py
  l10n_br_delivery_nfe/models/stock_picking_vol.py
  l10n_br_delivery_nfe/readme/CONTRIBUTORS.rst
  l10n_br_delivery_nfe/security/ir.model.access.csv
  l10n_br_delivery_nfe/static/description/index.html
  l10n_br_delivery_nfe/tests/__init__.py
  l10n_br_delivery_nfe/tests/test_delivery_nfe.py
  l10n_br_delivery_nfe/tests/test_delivery_nfe_grouped.py
  l10n_br_delivery_nfe/views/product_product_view.xml
  l10n_br_delivery_nfe/views/product_template_view.xml
  l10n_br_delivery_nfe/views/stock_picking_view.xml
  l10n_br_delivery_nfe/wizards/__init__.py
  l10n_br_delivery_nfe/wizards/stock_generate_volumes.py
  l10n_br_delivery_nfe/wizards/stock_generate_volumes_view.xml
  l10n_br_delivery_nfe/wizards/stock_invoice_onshipping.py
  l10n_br_delivery_nfe/wizards/stock_invoice_onshipping_view.xml
  l10n_br_delivery_nfe/wizards/vol_stock_invoice_onshipping.py
  oca_dependencies.txt
Labels: needs review, approved, ready to merge, bot is merging ⏳, 14.0

#3437 [16.0][FIX] l10n_br_stock_account: Get Default OP Fiscal - fwp 3327
  l10n_br_stock_account/models/stock_picking.py
Labels: approved, bot is merging ⏳

#3439 [16.0][MIG] l10n_br_account_nfe: _render_qweb_* migration
  l10n_br_account_nfe/report/ir_actions_report.py
  l10n_br_account_nfe/tests/test_nfe_danfe_account.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/report/ir_actions_report.py
  l10n_br_nfe/tests/test_nfe_danfe.py
Labels: bot is merging ⏳

#3431 [14.0][spec_driven_model][l10n_br_nfe] multi schemas support - round 2
  l10n_br_account_nfe/tests/test_nfce_contingency.py
  l10n_br_nfe/hooks.py
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_related.py
  l10n_br_nfe/models/document_supplement.py
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_structure.py
  l10n_br_nfe_spec/models/__init__.py
  l10n_br_nfe_spec/models/spec_mixin.py
  spec_driven_model/README.rst
  spec_driven_model/__manifest__.py
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/models/spec_view.py
  spec_driven_model/readme/DESCRIPTION.rst
  spec_driven_model/static/description/index.html
  spec_driven_model/tests/__init__.py
  spec_driven_model/tests/fake_mixin.py
  spec_driven_model/tests/spec_purchase.py
  spec_driven_model/tests/test_spec_model.py
Labels: needs review, approved, bot is merging ⏳

#3440 [16.0][l10n_br_account] fwp 3272
  l10n_br_account/models/document.py
  l10n_br_account/tests/test_account_move_lc.py
Labels: approved, bot is merging ⏳

#3441 [15.0][l10n_br_account] fwp 3272
  l10n_br_account/models/document.py
Labels: approved, bot is merging ⏳

#3442 [15.0][spec_driven_model] fwp 3335
  l10n_br_account_nfe/tests/test_nfce_contingency.py
  l10n_br_nfe/hooks.py
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_structure.py
  spec_driven_model/hooks.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, bot is merging ⏳

#3448 [16.0][IMP] l10n_br_ie_search: change vcr mocks for unittest mocks.
  l10n_br_ie_search/tests/fixtures/test_sefaz.yaml
  l10n_br_ie_search/tests/test_sefaz.py
Labels: approved, bot is merging ⏳

#3447 [14.0][IMP] l10n_br_account: add fiscal_operation_line and parameter add_to_amount on _get_amount_credit_debit_model method
  l10n_br_account/models/account_move_line.py
Labels: approved, bot is merging ⏳

#3450 [16.0][FIX] equal Estadual Inscription detection
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳

#3444 [16.0][spec_driven_model] fwp 3335
  l10n_br_account_nfe/tests/test_nfce_contingency.py
  l10n_br_nfe/hooks.py
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_structure.py
  spec_driven_model/hooks.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, bot is merging ⏳

#3461 [14.0][FIX][l10n_br_nfe_spec] fix file rename in test + fix
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
Labels: bot is merging ⏳

#3459 [16.0][IMP] l10n_br_nfe: DANFE margins config - fwp 3430
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/report/ir_actions_report.py
  l10n_br_nfe/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#3458 [15.0][IMP] l10n_br_nfe: DANFE margins config - fwp 3430
  l10n_br_nfe/models/res_company.py
  l10n_br_nfe/report/ir_actions_report.py
  l10n_br_nfe/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#3457 [16.0][IMP] l10n_br_fiscal_closing: add document_cte_ids - fwp 3412
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/views/closing.xml
Labels: approved, bot is merging ⏳

#3456 [15.0][IMP] l10n_br_fiscal_closing: add document_cte_ids - fwp 3412
  l10n_br_fiscal_closing/models/closing.py
  l10n_br_fiscal_closing/views/closing.xml
Labels: approved, bot is merging ⏳

#3446 [14.0][IMP] l10n_br_fiscal: imp document supplement
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document_supplement.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/migrations/14.0.19.0.0/pre-migration.py
  l10n_br_nfe/models/document_supplement.py
Labels: approved, ready to merge, bot is merging ⏳

#3454 [16.0][REF] spec_driven_model: rm dead code; + XML tests -fwp 3426
  spec_driven_model/models/spec_export.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, bot is merging ⏳

#3453 [15.0][REF] spec_driven_model: rm dead code; + XML tests - fwp 3426
  spec_driven_model/models/spec_export.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, bot is merging ⏳

#3289 [16.0][NEW] l10n_br_crm_cnpj_search: busca de CNPJ através do Lead
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
  l10n_br_crm_cnpj_search/README.rst
  l10n_br_crm_cnpj_search/__init__.py
  l10n_br_crm_cnpj_search/__manifest__.py
  l10n_br_crm_cnpj_search/models/__init__.py
  l10n_br_crm_cnpj_search/models/crm_lead.py
  l10n_br_crm_cnpj_search/models/l10n_br_base_party_mixin.py
  l10n_br_crm_cnpj_search/pyproject.toml
  l10n_br_crm_cnpj_search/readme/CONFIGURE.md
  l10n_br_crm_cnpj_search/readme/CONTRIBUTORS.md
  l10n_br_crm_cnpj_search/readme/DESCRIPTION.md
  l10n_br_crm_cnpj_search/readme/INSTALL.md
  l10n_br_crm_cnpj_search/readme/USAGE.md
  l10n_br_crm_cnpj_search/static/description/icon.png
  l10n_br_crm_cnpj_search/static/description/index.html
  l10n_br_crm_cnpj_search/tests/__init__.py
  l10n_br_crm_cnpj_search/tests/test_receitaws.py
  l10n_br_crm_cnpj_search/views/crm_lead_form.xml
  l10n_br_crm_cnpj_search/wizard/__init__.py
  l10n_br_crm_cnpj_search/wizard/partner_cnpj_search_wizard.py
  setup/l10n_br_crm_cnpj_search/odoo/addons/l10n_br_crm_cnpj_search
  setup/l10n_br_crm_cnpj_search/setup.py
Labels: enhancement, approved, bot is merging ⏳, 16.0

#3463 [14.0][FIX] l10n_br_nfe: apply context TZ to document_date
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3468 [16.0][FIX] l10n_br_fiscal: tree view field
  l10n_br_fiscal/views/res_company_view.xml
Labels: approved, bot is merging ⏳

#3469 [14.0][FIX] l10n_br_fiscal: ncm starting with 09 conflicts with service type
  l10n_br_fiscal/models/product_mixin.py
Labels: approved, bot is merging ⏳

#3471 [14.0][IMP] l10n_br_fiscal: tax_definition add Service Type
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/views/tax_definition_view.xml
Labels: bot is merging ⏳

#3473 [16.0][FIX] l10n_br_fiscal: ncm starting with 09 conflicts with service type - fwp 3469
  l10n_br_fiscal/models/product_mixin.py
Labels: approved, bot is merging ⏳

#3472 [15.0][FIX] l10n_br_fiscal: ncm starting with 09 conflicts with service type - fwp 3469
  l10n_br_fiscal/models/product_mixin.py
Labels: approved, bot is merging ⏳
