Repository OCA/l10n-brazil, pull requests merged in 2024-05, with the labels that each got.

#3056 [14.0][REM] l10n_br_account_payment_order: Removendo campo journal_entry_ref por não estar sendo usado
  l10n_br_account_payment_order/models/account_move_line.py
  l10n_br_account_payment_order/tests/test_payment_order_inbound.py
Labels: approved, bot is merging ⏳

#3060 [15.0][FIX] less to scss
  l10n_br_base/__manifest__.py
  l10n_br_base/static/src/scss/form.scss
Labels: approved, bot is merging ⏳

#3053 [16.0][l10n_br_fiscal] forward port de #3032
  l10n_br_fiscal/models/document.py
Labels: approved, ready to merge, bot is merging ⏳

#3031 [16.0][MIG] l10n_br_hr: Migration to 16.0
  l10n_br_hr/README.rst
  l10n_br_hr/__init__.py
  l10n_br_hr/__manifest__.py
  l10n_br_hr/data/hr_deficiency_data.xml
  l10n_br_hr/data/hr_ethnicity_data.xml
  l10n_br_hr/data/l10n_br_hr.cbo.csv
  l10n_br_hr/i18n/l10n_br_hr.pot
  l10n_br_hr/i18n/pt_BR.po
  l10n_br_hr/migrations/14.0.1.0.0/pre-migration.py
  l10n_br_hr/models/__init__.py
  l10n_br_hr/models/data_abstract.py
  l10n_br_hr/models/hr_civil_certificate_type.py
  l10n_br_hr/models/hr_deficiency.py
  l10n_br_hr/models/hr_employee.py
  l10n_br_hr/models/hr_ethnicity.py
  l10n_br_hr/models/hr_identity_type.py
  l10n_br_hr/models/hr_job.py
  l10n_br_hr/models/l10n_br_hr_cbo.py
  l10n_br_hr/models/res_company.py
  l10n_br_hr/readme/CONFIGURE.rst
  l10n_br_hr/readme/CONTRIBUTORS.rst
  l10n_br_hr/readme/DESCRIPTION.rst
  l10n_br_hr/readme/INSTALL.rst
  l10n_br_hr/readme/ROADMAP.rst
  l10n_br_hr/readme/USAGE.rst
  l10n_br_hr/security/ir.model.access.csv
  l10n_br_hr/static/description/icon.png
  l10n_br_hr/static/description/index.html
  l10n_br_hr/tests/__init__.py
  l10n_br_hr/tests/test_l10n_br_hr.py
  l10n_br_hr/views/hr_employee_view.xml
  l10n_br_hr/views/hr_job_view.xml
  l10n_br_hr/views/inherited_hr_contract.xml
  l10n_br_hr/views/l10n_br_hr_cbo_view.xml
  l10n_br_hr/views/res_company_view.xml
  setup/l10n_br_hr/odoo/addons/l10n_br_hr
  setup/l10n_br_hr/setup.py
Labels: approved, bot is merging ⏳

#3023 [15.0][MIG] l10n_br_account_withholding: Migration to 15.0
  l10n_br_account/__manifest__.py
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account_withholding/README.rst
  l10n_br_account_withholding/__init__.py
  l10n_br_account_withholding/__manifest__.py
  l10n_br_account_withholding/demo/ir.property.xml
  l10n_br_account_withholding/i18n/l10n_br_account_withholding.pot
  l10n_br_account_withholding/i18n/pt_BR.po
  l10n_br_account_withholding/models/__init__.py
  l10n_br_account_withholding/models/account_move.py
  l10n_br_account_withholding/models/account_move_line.py
  l10n_br_account_withholding/models/l10n_br_fiscal_tax_group.py
  l10n_br_account_withholding/readme/CONFIGURE.md
  l10n_br_account_withholding/readme/CONTEXT.md
  l10n_br_account_withholding/readme/CONTRIBUTORS.md
  l10n_br_account_withholding/readme/DESCRIPTION.md
  l10n_br_account_withholding/readme/INSTALL.md
  l10n_br_account_withholding/readme/USAGE.md
  l10n_br_account_withholding/static/description/icon.png
  l10n_br_account_withholding/static/description/index.html
  l10n_br_account_withholding/tests/__init__.py
  l10n_br_account_withholding/tests/test_account_wh_invoice.py
  l10n_br_account_withholding/views/account_move.xml
  l10n_br_account_withholding/views/l10n_br_fiscal_tax_group.xml
  setup/l10n_br_account_withholding/odoo/addons/l10n_br_account_withholding
  setup/l10n_br_account_withholding/setup.py
Labels: approved, bot is merging ⏳

#3062 [15.0] l10n_br_fiscal: port from 14.0 (pr 2801 and 3030)
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_fiscal/constants/icms.py
  l10n_br_fiscal/data/l10n_br_fiscal.icms.relief.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, bot is merging ⏳

#3063 [16.0] l10n_br_fiscal: port icms relief calculation pr2801 3030
  l10n_br_fiscal/constants/icms.py
  l10n_br_fiscal/data/l10n_br_fiscal.icms.relief.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, bot is merging ⏳

#3066 [14.0][RFC] l10n_br_stock_account: change test ind_final
  l10n_br_stock_account/tests/test_invoicing_picking.py
Labels: approved, bot is merging ⏳

#2880 [16.0][MIG][l10n_br_nfe_spec]
  .pre-commit-config.yaml
  l10n_br_nfe_spec/README.rst
  l10n_br_nfe_spec/__init__.py
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_nfe_spec/i18n/l10n_br_nfe_spec.pot
  l10n_br_nfe_spec/i18n/pt_BR.po
  l10n_br_nfe_spec/migrations/14.0.5.0.0/pre-migration.py
  l10n_br_nfe_spec/models/__init__.py
  l10n_br_nfe_spec/models/spec_models.py
  l10n_br_nfe_spec/models/v4_0/__init__.py
  l10n_br_nfe_spec/models/v4_0/leiaute_cons_sit_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_inut_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/tipos_basico_v4_00.py
  l10n_br_nfe_spec/readme/CONFIGURE.rst
  l10n_br_nfe_spec/readme/CONTRIBUTORS.rst
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
  l10n_br_nfe_spec/readme/INSTALL.rst
  l10n_br_nfe_spec/readme/ROADMAP.rst
  l10n_br_nfe_spec/readme/USAGE.rst
  l10n_br_nfe_spec/static/description/icon.png
  l10n_br_nfe_spec/static/description/index.html
  l10n_br_nfe_spec/tests/__init__.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
  setup/l10n_br_nfe_spec/odoo/addons/l10n_br_nfe_spec
  setup/l10n_br_nfe_spec/setup.py
  test-requirements.txt
Labels: approved, migration, bot is merging ⏳, 16.0

#2875 [15.0][MIG][l10n_br_nfe_spec]
  .pre-commit-config.yaml
  l10n_br_nfe_spec/README.rst
  l10n_br_nfe_spec/__init__.py
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_nfe_spec/i18n/l10n_br_nfe_spec.pot
  l10n_br_nfe_spec/i18n/pt_BR.po
  l10n_br_nfe_spec/migrations/14.0.5.0.0/pre-migration.py
  l10n_br_nfe_spec/models/__init__.py
  l10n_br_nfe_spec/models/spec_models.py
  l10n_br_nfe_spec/models/v4_0/__init__.py
  l10n_br_nfe_spec/models/v4_0/leiaute_cons_sit_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_inut_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/tipos_basico_v4_00.py
  l10n_br_nfe_spec/readme/CONFIGURE.rst
  l10n_br_nfe_spec/readme/CONTRIBUTORS.rst
  l10n_br_nfe_spec/readme/DESCRIPTION.rst
  l10n_br_nfe_spec/readme/INSTALL.rst
  l10n_br_nfe_spec/readme/ROADMAP.rst
  l10n_br_nfe_spec/readme/USAGE.rst
  l10n_br_nfe_spec/static/description/icon.png
  l10n_br_nfe_spec/static/description/index.html
  l10n_br_nfe_spec/tests/__init__.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
  setup/l10n_br_nfe_spec/odoo/addons/l10n_br_nfe_spec
  setup/l10n_br_nfe_spec/setup.py
  test-requirements.txt
Labels: approved, migration, bot is merging ⏳, 15.0

#3069 [15.0][RFC] l10n_br_account: forward port de #3064
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/fiscal_document_line.py
Labels: approved, bot is merging ⏳

#3070 [16.0][l10n_br_hr][REF] l10n_br_hr: SavepointCase->TransactionCase
  l10n_br_hr/tests/test_l10n_br_hr.py
Labels: approved, bot is merging ⏳

#3073 [ADD] stock invoicing bug - tax included value
  l10n_br_stock_account/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#3078 [15.0][MIG] l10n_br_mis_report
  l10n_br_mis_report/README.rst
  l10n_br_mis_report/__init__.py
  l10n_br_mis_report/__manifest__.py
  l10n_br_mis_report/data/mis_report_bp.xml
  l10n_br_mis_report/data/mis_report_dre.xml
  l10n_br_mis_report/data/mis_report_styles.xml
  l10n_br_mis_report/i18n/l10n_br_mis_report.pot
  l10n_br_mis_report/i18n/pt_BR.po
  l10n_br_mis_report/readme/CONFIGURE.rst
  l10n_br_mis_report/readme/CONTRIBUTORS.rst
  l10n_br_mis_report/readme/DESCRIPTION.rst
  l10n_br_mis_report/readme/HISTORY.rst
  l10n_br_mis_report/readme/INSTALL.rst
  l10n_br_mis_report/readme/ROADMAP.rst
  l10n_br_mis_report/readme/USAGE.rst
  l10n_br_mis_report/static/description/bp.png
  l10n_br_mis_report/static/description/dre.png
  l10n_br_mis_report/static/description/icon.png
  l10n_br_mis_report/static/description/index.html
  setup/l10n_br_mis_report/odoo/addons/l10n_br_mis_report
  setup/l10n_br_mis_report/setup.py
Labels: approved, bot is merging ⏳

#3080 [16.0][FIX][l10n_br_coa_generic] expense
  l10n_br_coa_generic/data/account.account.template.csv
Labels: approved, bot is merging ⏳

#3077 [14.0][FIX][l10n_br_account] reordering vals_list to correctly associate with with fiscal_document_line
  l10n_br_account/models/account_move_line.py
Labels: approved, bot is merging ⏳

#3085 [15.0][FIX][l10n_br_account] reordering vals_list to correctly associate with with fiscal_document_line - port de #3077
  l10n_br_account/models/account_move_line.py
Labels: approved, bot is merging ⏳

#3075 [15.0][FIX] l10n_br_account: price_total and price_subtotal values (port de 3037)
  l10n_br_account/models/account_move_line.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/tests/test_account_move_sn.py
  l10n_br_account_withholding/tests/test_account_wh_invoice.py
Labels: needs review, approved, bot is merging ⏳

#3086 [14.0][FIX] Obtenção incorreta do valor da empresa em alguns casos
  l10n_br_contract/models/contract_contract.py
  l10n_br_delivery/models/fiscal_document_mixin.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/wizards/l10n_br_account_nfe_export_invoice.py
  l10n_br_repair/models/fiscal_line_mixin.py
  l10n_br_repair/models/repair_order.py
Labels: approved, bot is merging ⏳

#3016 [14.0][FIX] l10n_br_account/l10n_br_fiscal: amount total,amount_price_gross when has tax withholding and IPI
  l10n_br_account/models/account_move_line.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_sale/models/sale_order_line.py
Labels: approved, ready to merge, bot is merging ⏳

#3087 [14.0][FIX] l10n_br_sale_blanket_order: delete pt.po file
  l10n_br_sale_blanket_order/i18n/pt.po
Labels: approved, bot is merging ⏳

#3090 [14.0][FIX] l10n_br_account: account move on fiscal wiz
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/wizards/__init__.py
  l10n_br_account/wizards/base_wizard_mixin.py
  l10n_br_account/wizards/wizard_document_cancel.py
  l10n_br_account/wizards/wizard_document_correction.py
  l10n_br_account/wizards/wizard_document_invalidate.py
Labels: approved, bot is merging ⏳

#3088 [14.0][FIX] l10n_br_purchase: fix purchase order line form button 'save and new'
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#3097 [15.0][FIX][l10n_br_account]: account move on fiscal wiz
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/wizards/__init__.py
  l10n_br_account/wizards/base_wizard_mixin.py
  l10n_br_account/wizards/wizard_document_cancel.py
  l10n_br_account/wizards/wizard_document_correction.py
  l10n_br_account/wizards/wizard_document_invalidate.py
Labels: approved, bot is merging ⏳

#3101 [14.0][REF] 10n_br_account_nfe: Remoção de código obsoleto.
  l10n_br_account_nfe/models/__init__.py
  l10n_br_account_nfe/models/account_move_line.py
Labels: approved, bot is merging ⏳

#3103 [14.0][l10n_br_fiscal][FIX] selection_add 'product'
  l10n_br_fiscal/models/product_template.py
Labels: approved, bot is merging ⏳

#3107 [14.0][FIX] l10n_br_nfe: remoção do warning inconsistent 'compute_sudo'
  l10n_br_nfe/models/res_partner.py
Labels: approved, bot is merging ⏳
