Repository OCA/l10n-brazil, pull requests merged in 2024-08, with the labels that each got.

#3255 [16.0][MIG][l10n_br_nfe] _render_qweb_* methods migration
  l10n_br_nfe/models/document.py
  l10n_br_nfe/report/ir_actions_report.py
  l10n_br_nfe/tests/test_nfe_danfe.py
Labels: approved, migration, bot is merging ⏳, 16.0

#3257 [16.0][l10n_br_nfse] port of 3135
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳, 16.0, backport

#3256 [15.0][l10n_br_nfse] port of 3135
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳, 15.0, backport

#3258 [16.0][MIG][spec_driven_model] fields_get_keys is deprecated
  spec_driven_model/hooks.py
Labels: approved, bot is merging ⏳, 16.0

#3264 [14.0] l10n_br_fiscal: Alteração do nome do método fiscal
  l10n_br_account/models/account_move.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_repair/models/repair_fee.py
  l10n_br_repair/models/repair_line.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale_blanket_order/models/sale_blanket_order_line.py
Labels: approved, bot is merging ⏳, 14.0, backport

#3269 [14.0][REF][l10n_br_account_nfe] lint
  l10n_br_account_nfe/models/document.py
  l10n_br_account_nfe/tests/test_nfce_contingency.py
  l10n_br_account_nfe/tests/test_nfe_danfe_account.py
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
  l10n_br_account_nfe/tests/test_nfe_with_ipi.py
Labels: approved, bot is merging ⏳

#3270 [14.0][REF][l10n_br_stock_account] lint
  l10n_br_stock_account/demo/account_journal_demo.xml
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#3268 [14.0][FIX] l10n_br_account_payment_order: ensure payment_mode_id.cnab_write_off_code_id is defined before comparison
  l10n_br_account_payment_order/models/account_move_line.py
Labels: approved, bot is merging ⏳, 14.0

#3274 [15.0][REF][l10n_br_hr] SavepointCase->TransactionCase
  l10n_br_hr/tests/test_l10n_br_hr.py
Labels: refactoring, approved, bot is merging ⏳, 15.0

#3265 [14.0][REF] l10n_br_fiscal: Melhoria de Desempenho nos Documentos Fiscais
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳, 14.0

#3277 [16.0][REF][l10n_br_fiscal] Update all taxes fields at once - FWP 3265
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3276 [15.0][REF][l10n_br_fiscal] Update all taxes fields at once - FWP 3265
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳, 15.0, backport

#3278 [14.0][FIX] Change res.company data to noupdate = 1
  l10n_br_contract/data/company.xml
  l10n_br_repair/data/res_company.xml
  l10n_br_sale/data/company.xml
  l10n_br_stock_account/data/l10n_br_stock_account_data.xml
Labels: approved, bot is merging ⏳

#3283 [15.0][FW][FIX] l10n_br_sale: change res.company data to noupdate = 1 (port from #3278)
  l10n_br_sale/data/company.xml
Labels: approved, bot is merging ⏳

#3281 [14.0][REF+IMP] l10n_br_purchase_stock: Usando os Testes Comuns/Common Tests para reduzir código duplicado e testando o caso Sem Operação Fiscal
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
Labels: approved, bot is merging ⏳

#3282 [14.0][REF] l10n_br_purchase_stock: Adaptando o modulo para deixar compatível com os casos Internacionais ou Sem Operação Fiscal
  l10n_br_purchase_stock/models/purchase_order.py
  l10n_br_purchase_stock/models/purchase_order_line.py
Labels: approved, bot is merging ⏳

#3284 [14.0][REF] l10n_br_purchase_stock: Informando o campo ind_final nos Dados de Demonstração para evitar erros
  l10n_br_purchase_stock/demo/purchase_order.xml
Labels: approved, bot is merging ⏳

#3286 [14.0][REF] l10n_br_purchase_stock: Desnecessário chamar métodos onchange que já são chamados pelo _onchange_product_id_fiscal
  l10n_br_purchase_stock/models/stock_rule.py
Labels: approved, bot is merging ⏳

#3287 [14.0][REF] l10n_br_account_payment_brcobranca: Resolvendo erros PEP8 validados em versões recentes
  l10n_br_account_payment_brcobranca/constants/br_cobranca.py
  l10n_br_account_payment_brcobranca/models/account_move.py
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#3145 [14.0][REF+IMP] l10n_br_purchase_stock: Renomeando o campo da Politica de Fatura e adaptando código para o caso Sem Operação Fiscal
  l10n_br_purchase_stock/__manifest__.py
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_purchase_stock/migrations/14.0.2.0.0/pre-migration.py
  l10n_br_purchase_stock/models/__init__.py
  l10n_br_purchase_stock/models/purchase_order.py
  l10n_br_purchase_stock/models/purchase_order_line.py
  l10n_br_purchase_stock/models/res_company.py
  l10n_br_purchase_stock/models/res_config_settings.py
  l10n_br_purchase_stock/views/res_company_view.xml
  l10n_br_purchase_stock/views/res_config_settings.xml
Labels: new feature, approved, bot is merging ⏳, 14.0

#3292 [14.0][IMP] l10n_br_fiscal: considerar ind_final em mapa impostos adicionais
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#3288 [14.0][FIX] l10n_br_stock_account: no longer reads fop from null sale/purchase
  l10n_br_purchase_stock/models/purchase_order.py
  l10n_br_stock_account/models/stock_picking.py
Labels: approved, bot is merging ⏳

#3293 [14.0][ADD] l10n_br_hr_expense_invoice: add new module
  l10n_br_hr_expense_invoice/README.rst
  l10n_br_hr_expense_invoice/__init__.py
  l10n_br_hr_expense_invoice/__manifest__.py
  l10n_br_hr_expense_invoice/models/__init__.py
  l10n_br_hr_expense_invoice/models/hr_expense.py
  l10n_br_hr_expense_invoice/models/res_company.py
  l10n_br_hr_expense_invoice/readme/CONTRIBUTORS.rst
  l10n_br_hr_expense_invoice/readme/DESCRIPTION.rst
  l10n_br_hr_expense_invoice/readme/USAGE.rst
  l10n_br_hr_expense_invoice/static/description/icon.png
  l10n_br_hr_expense_invoice/static/description/index.html
  l10n_br_hr_expense_invoice/tests/__init__.py
  l10n_br_hr_expense_invoice/tests/test_l10n_br_hr_expense_invoice.py
  l10n_br_hr_expense_invoice/views/hr_expense_sheet.xml
  l10n_br_hr_expense_invoice/views/res_company.xml
  setup/l10n_br_hr_expense_invoice/odoo/addons/l10n_br_hr_expense_invoice
  setup/l10n_br_hr_expense_invoice/setup.py
Labels: approved, bot is merging ⏳

#3298 [14.0][FIX] l10n_br_nfe: local_entrega only if not equal to partner_id
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3297 [16.0][REF][l10n_br_account_payment_order] no tracking in tests
  l10n_br_account_payment_order/tests/test_base_class.py
  l10n_br_account_payment_order/tests/test_cnab_codes.py
  l10n_br_account_payment_order/tests/test_invoice_normal_workflow.py
  l10n_br_account_payment_order/tests/test_payment_order.py
  l10n_br_account_payment_order/tests/test_payment_order_inbound.py
Labels: approved, bot is merging ⏳

#3182 [14.0][FIX][l10n_br_nfe] falha no cancelamento de nota fiscal sem retorno
  l10n_br_nfe/models/document.py
Labels: work in progress, approved, bot is merging ⏳, 14.0

#2911 [16.0][MIG][l10n_br_sale]
  l10n_br_sale/README.rst
  l10n_br_sale/__init__.py
  l10n_br_sale/__manifest__.py
  l10n_br_sale/data/company.xml
  l10n_br_sale/demo/company.xml
  l10n_br_sale/demo/fiscal_operation_generic.xml
  l10n_br_sale/demo/fiscal_operation_simple.xml
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/demo/product.xml
  l10n_br_sale/hooks.py
  l10n_br_sale/i18n/l10n_br_sale.pot
  l10n_br_sale/i18n/pt_BR.po
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/res_company.py
  l10n_br_sale/models/res_config_settings.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/readme/CONFIGURE.rst
  l10n_br_sale/readme/CONTRIBUTORS.rst
  l10n_br_sale/readme/CREDITS.rst
  l10n_br_sale/readme/DESCRIPTION.rst
  l10n_br_sale/readme/HISTORY.rst
  l10n_br_sale/readme/INSTALL.rst
  l10n_br_sale/readme/ROADMAP.rst
  l10n_br_sale/readme/USAGE.rst
  l10n_br_sale/report/__init__.py
  l10n_br_sale/report/sale_report.py
  l10n_br_sale/report/sale_report_templates.xml
  l10n_br_sale/report/sale_report_view.xml
  l10n_br_sale/security/ir.model.access.csv
  l10n_br_sale/security/l10n_br_sale_security.xml
  l10n_br_sale/static/description/icon.png
  l10n_br_sale/static/description/index.html
  l10n_br_sale/static/description/sale_order_1.png
  l10n_br_sale/static/description/sale_order_2.png
  l10n_br_sale/tests/__init__.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/tests/test_l10n_br_sale_discount.py
  l10n_br_sale/tests/test_l10n_br_sale_pricelist.py
  l10n_br_sale/tests/test_l10n_br_sale_sn.py
  l10n_br_sale/views/res_company_view.xml
  l10n_br_sale/views/res_config_settings_view.xml
  l10n_br_sale/views/sale_view.xml
  setup/l10n_br_sale/odoo/addons/l10n_br_sale
  setup/l10n_br_sale/setup.py
Labels: approved, migration, bot is merging ⏳, 16.0

#3300 [14.0][REF] l10n_br_sale_stock: Usando o Common Tests para reduzir código duplicado
  l10n_br_sale_stock/tests/test_sale_stock.py
Labels: refactoring, approved, bot is merging ⏳, 14.0

#3299 [14.0][IMP] l10n_br_purchase_stock: Tornando a Fatura criada pela Ordem de Seleção/stock.picking semelhante a do Pedido de Compra/purchase.order, evitando "glue modules"
  l10n_br_purchase_stock/__manifest__.py
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_purchase_stock/wizards/stock_invocing_onshipping.py
Labels: approved, bot is merging ⏳, 14.0

#3198 [16.0][l10n_br_fiscal][REF] document number fields in fiscal mixin
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
Labels: needs review, approved, bot is merging ⏳, 16.0, backport

#3307 [14.0][IMP] l10n_br_account: rename proxy fields
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_delivery/models/fiscal_document_mixin.py
  l10n_br_sale/models/fiscal_document.py
Labels: approved, bot is merging ⏳

#3280 [14.0][IMP] l10n_br_base: filtrar parceiro pelo cnpj, sem formatação.
  l10n_br_base/models/party_mixin.py
  l10n_br_base/views/res_partner_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3312 [16.0][FIX] l10n_br_cnpj_search: fix response assignment error in tests
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
Labels: approved, bot is merging ⏳

#3305 [16.0][MIG][l10n_br_account] code cleanup
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/account_tax.py
Labels: approved, bot is merging ⏳

#3309 [14.0][FIX] l10n_br_ delivery. l10n_br_sale and l10n_br_account: fix warnings (fields have same label)
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_delivery/models/fiscal_document_mixin.py
  l10n_br_sale/models/fiscal_document.py
Labels: approved, bot is merging ⏳

#3310 [15.0][IMP] l10n_br_account: rename proxy fields (port from 3307 and 2815)
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/fiscal_document.py
  l10n_br_account/models/fiscal_document_line.py
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/account_move.py
  l10n_br_sale/models/fiscal_document.py
Labels: approved, bot is merging ⏳

#3313 [14.0][REM][l10n_br_account] remove dummy document leftover
  l10n_br_account/models/account_move.py
Labels: approved, bot is merging ⏳

#3315 [16.0][FIX][l10n_br_account_payment_order] ensure payment_mode_id.cnab_writ… - FWP-3268
  l10n_br_account_payment_order/models/account_move_line.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3314 [15.0][FIX][l10n_br_account_payment_order] ensure payment_mode_id.cnab_writ… - FWP-3268
  l10n_br_account_payment_order/models/account_move_line.py
Labels: approved, bot is merging ⏳, 15.0, backport

#3317 [16.0][IMP][l10n_br_base] partner filter by cnpj/cpf without mask - FWP-3280
  l10n_br_base/models/party_mixin.py
  l10n_br_base/views/res_partner_view.xml
Labels: approved, bot is merging ⏳, 16.0, backport

#3324 [16.0][FIX][l10n_br_nfe] nfe doc cancel - justification field size validation - FWP-3182
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3323 [15.0][FIX][l10n_br_nfe] nfe doc cancel - justification field size validation - FWP-3182
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳, 15.0, backport

#3322 [16.0][FIX][l10n_br_nfe] local_entrega only if not equal to partner_id -FWP-3298
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳, 16.0, backport

#3318 [16.0][l10n_br_account-payment_brcobranca] port 3287
  l10n_br_account_payment_brcobranca/constants/br_cobranca.py
  l10n_br_account_payment_brcobranca/models/account_move.py
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_brcobranca/models/account_payment_order.py
  l10n_br_account_payment_brcobranca/parser/cnab_file_parser.py
Labels: approved, bot is merging ⏳

#3319 [15.0][IMP][l10n_br_fiscal] icms regulation: ST, FCT and FCPST map tax by ind_final -FWP-3292
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#3320 [16.0][IMP][l10n_br_fiscal] icms regulation: ST, FCT and FCPST map tax by ind_final -FWP-3292
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#3328 [14.0][REF][l10n_br_account] invoice_view -> move_view
  l10n_br_account/__manifest__.py
  l10n_br_account/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#3330 [16.0][FIX] l10n_br_base, l10n_br_zip: Visões dinâmicas do endereço
  l10n_br_base/models/format_address_mixin.py
  l10n_br_base/models/res_company.py
  l10n_br_base/views/res_partner_address_view.xml
  l10n_br_zip/models/format_address_mixin.py
Labels: approved, bot is merging ⏳

#3325 [14.0][FIX] l10n_br_sale_stock: Caso do Pedido de Venda Sem Operação ou Internacional não deve incluir os Dados Fiscais do Brasil
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/models/stock_move.py
Labels: approved, bot is merging ⏳
