Repository OCA/l10n-brazil, pull requests merged in 2024-12, with the labels that each got.

#3520 [16.0][FIX][l10n_br_sale] fix landed costs
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: approved, bot is merging ⏳

#3524 [14.0][FIX][l10n_br_nfse_paulistana] Status consulta
  l10n_br_nfse_paulistana/models/document.py
Labels: approved, bot is merging ⏳

#3521 [14.0][FIX] l10n_br_fiscal: Preencher document_date apenas na confirmação do documento
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳

#3508 [14.0][IMP] l10n_br_fiscal_edi: add _document_qrcode() on _exec_before_SITUACAO_EDOC_A_ENVIAR method
  l10n_br_fiscal_edi/models/document_workflow.py
Labels: approved, ready to merge, bot is merging ⏳

#3533 [16.0][REF] Remoção de alguns SavepointCase
  l10n_br_base/tests/test_partner_bank.py
  l10n_br_base/tests/test_valid_pix.py
  l10n_br_fiscal_edi/tests/test_fiscal_document_generic.py
  l10n_br_fiscal_edi/tests/test_tax_benefit.py
Labels: approved, bot is merging ⏳, 16.0

#3517 [16.0][l10n_br_account] Oca port 14.0 to 16.0 e4e419
  .oca/oca-port/blacklist/l10n_br_account.json
  l10n_br_account/__manifest__.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#3534 [16.0] remove oca_dependencies.txt
  oca_dependencies.txt
Labels: approved

#3535 [16.0][FIX] l10n_br_sale: Tratamento do UserError na criação da Fatura.
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#3519 [14.0][IMP] l10n_br_nfe: computed impostoDevol added to nfe
  l10n_br_account_nfe/tests/test_nfe_with_ipi.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_nfe/models/document_line.py
Labels: bot is merging ⏳

#3540 [16.0][FIX] Removendo warning do campo res.partner.vat
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳, 16.0

#3543 [15.0][l10n_br_base][FIX] Avoid res.partner.vat warning message - bcp 3540
  l10n_br_base/models/res_partner.py
Labels: approved, bot is merging ⏳, 15.0

#3528 [14.0][IMP] l10n_br_stock_account: displays tax document information outside of tabs
  l10n_br_stock_account/views/stock_picking.xml
Labels: bot is merging ⏳

#3545 [14.0][REF] l10n_br_base, l10n_br_stock: Company name
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_cte/tests/cte/v4_00/leiauteCTe/CTe35240759594315000157570010000057311040445890.xml
  l10n_br_mdfe/tests/mdfe/v3_00/leiauteMDFe/MDFe35230905472475000102580200000602081550195716.xml
  l10n_br_mdfe/tests/mdfe/v3_00/leiauteMDFe/MDFe35231005472475000102580200000602161434590525.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfse_barueri/tests/nfse/nfse.xml
  l10n_br_stock/__manifest__.py
  l10n_br_stock/demo/res_company_demo.xml
Labels: approved, bot is merging ⏳, 14.0

#3547 [14.0][RFC] l10n_br_nfse: danfse refactor
  l10n_br_nfse/models/document.py
  l10n_br_nfse/report/danfse.xml
Labels: approved, bot is merging ⏳

#3548 [14.0][FIX][l10n_br_nfse_focus]: pis, cofins, csll, inss, ir has value only if type is tax withholding
  l10n_br_nfse_focus/models/document.py
Labels: approved, bot is merging ⏳

#3175 [14.0][FIX] l10n_br_nfse_focus: fix make pdf and transmission
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/models/res_company.py
  l10n_br_nfse_focus/views/res_company.xml
Labels: work in progress, approved, ready to merge, bot is merging ⏳, 14.0

#3491 [14.0][FIX] l10n_br_fiscal: operation copy
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_operation.py
Labels: approved, bot is merging ⏳

#3549 [16.0] l10n_br_fiscal: Renomeação de métodos compute para evitar ambiguidades em heranças de modelos
  l10n_br_account/models/account_move.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin_fields.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_stock_account/models/stock_picking.py
Labels: approved, bot is merging ⏳

#3550 [16.0][FIX] l10n_br_sale: Sobrescrever o carregamento de impostos para pedidos em empresas brasileiras
  l10n_br_sale/models/sale_order_line.py
Labels: approved, bot is merging ⏳

#3552 [16.0][FIX+MIG+FWD] l10n_br_stock_account: Adaptando a Visão para a v16 e FWD 3528
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#3554 [14.0][RFC] l10n_br_fiscal/l10n_br_cte: fields refactor
  l10n_br_cte/models/__init__.py
  l10n_br_cte/models/document_mixin_fields.py
  l10n_br_fiscal/models/document_mixin_fields.py
Labels: approved, bot is merging ⏳

#3557 [14.0][FIX] l10n_br_cte: Hide partner fields(sendering and others) for non-CTE fiscal documents
  l10n_br_cte/views/document.xml
Labels: approved, bot is merging ⏳

#3559 [14.0][IMP] l10n_br_cte: add insurance fields on fiscal document form
  l10n_br_cte/views/document.xml
Labels: approved, bot is merging ⏳

#3558 [16.0][REF] l10n_br_account, fiscal: Aperfeiçoamento nos lançamentos contábeis
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/tests/test_invoice_refund.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
  l10n_br_purchase/models/purchase_order_line.py
Labels: approved, ready to merge, bot is merging ⏳
