Repository OCA/l10n-brazil, pull requests merged in 2024-04, with the labels that each got.

#2987 [14.0][l10n_br_focus][REF] import existing filter
  l10n_br_nfse_focus/models/document.py
Labels: approved, bot is merging ⏳

#2801 [14.0][IMP] l10n_br_fiscal: Calculo correto da desoneração do ICMS
  l10n_br_fiscal/constants/icms.py
  l10n_br_fiscal/data/l10n_br_fiscal.icms.relief.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: needs fixing, bot is merging ⏳

#2988 [15.0][FIX] l10n_br_sale: Erro no caso 'Down Payments'
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳

#2996 [14.0][FIX] l10n_br_purchase_request: onchange_partner_id_fiscal
  l10n_br_purchase_request/tests/test_l10n_br_purchase_request.py
  l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#2995 [14.0][FIX] l10n_br_purchase_request: calculation when keep_estimated_cost is present
  l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.py
Labels: approved, bot is merging ⏳

#3001 [14.0][RFC] l10n_br_coa: refactor withholding
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax_mixin.py
  l10n_br_coa/models/account_tax_template.py
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, bot is merging ⏳

#3000 [14.0][ADD] Adiciona grupo de impostos para FCP ST
  l10n_br_account/data/account_tax_group.xml
  l10n_br_account/data/account_tax_template.xml
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal.tax.group.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/tests/test_nfe_xml_validation.py
Labels: approved, bot is merging ⏳

#3003 [14.0][FIX] l10n_br_nfe: authorization date format with xsdata
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3006 [14.0][FIX] l10n_br_nfse_focus: fix unit test
  l10n_br_nfse_focus/tests/test_l10n_br_nfse_focus.py
Labels: approved, bot is merging ⏳

#3011 [14.0][FIX] l10n_br_fiscal: FCP-ST tax domain and view adjustment
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, bot is merging ⏳

#3015 [14.0][FIX] l10n_br_coa: fix account.tax confins wh out group
  l10n_br_coa/data/account_tax_template.xml
Labels: approved, bot is merging ⏳

#3007 [15.0] [RFC] l10n_br_coa: refactor withholding (port from #3001 and #3015)
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax_mixin.py
  l10n_br_coa/models/account_tax_template.py
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, ready to merge, bot is merging ⏳

#3008 [16.0] [RFC] l10n_br_coa: refactor withholding (port from #3001 and 3015)
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_coa/models/account_chart_template.py
  l10n_br_coa/models/account_tax_mixin.py
  l10n_br_coa/models/account_tax_template.py
  l10n_br_coa/views/account_tax.xml
  l10n_br_coa_generic/data/account.account.template.csv
  l10n_br_coa_generic/data/l10n_br_coa.account.tax.group.account.template.csv
Labels: approved, ready to merge, bot is merging ⏳

#2761 [14.0][l10n_br_account][IMP] composite account.move
  l10n_br_account/__manifest__.py
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_account/views/l10n_br_account_menu.xml
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
Labels: approved, ready to merge, bot is merging ⏳

#3018 [14.0][FIX] l10n_br_purchase: Possibilidade de incluir linhas de Seção ou Notas no Pedido de Compra
  l10n_br_purchase/views/purchase_view.xml
Labels: bot is merging ⏳

#3019 [14.0][RFC] l10n br fiscal: change amount tax withholding string
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
Labels: approved, bot is merging ⏳

#3024 [14.0][FIX] l10n_br_account_withholding: fix button_draft method
  l10n_br_account_withholding/models/account_move.py
Labels: approved, bot is merging ⏳

#3026 [16.0][RFC] l10n_br_fiscal: port from 3019
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
Labels: approved, bot is merging ⏳

#3025 [15.0][RFC] l10n_br_fiscal: port from 3019
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
Labels: bot is merging ⏳

#3020 [14.0][IMP] l10n_br_purchase: add amount_tax_withholding on purchase order form subtotal
  l10n_br_purchase/views/purchase_view.xml
Labels: approved, bot is merging ⏳

#3021 [14.0][IMP] l10n_br_sale: add amount_tax_withholding on sale order form subtotal
  l10n_br_sale/views/sale_view.xml
Labels: approved, bot is merging ⏳

#3022 [14.0][IMP] Improve repository description in README.md to provide more detailed information to the community.
  README.md
Labels: approved

#3036 [14.0][FIX][l10n_br_fiscal] CFOP 5124: no financial
  l10n_br_fiscal/data/l10n_br_fiscal.cfop.csv
Labels: approved, bot is merging ⏳

#3030 [14.0][FIX] l10n_br_fiscal: compute icms_relief_value only if icms_relief_id is defined in the fiscal document line
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/tax.py
Labels: approved, bot is merging ⏳

#3054 [16.0][l10n_br_fiscal][IMP] composite account.move; forward port de #2761
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
Labels: approved, bot is merging ⏳

#2962 [15.0][l10n_br_account][IMP] composite account.move; forward port de #2761
  l10n_br_account/__manifest__.py
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/views/account_invoice_view.xml
  l10n_br_account/views/l10n_br_account_menu.xml
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
Labels: approved, ready to merge, bot is merging ⏳

#3047 [16.0][l10n_br_fiscal]: read rights for base user; forward port de #2991
  l10n_br_fiscal/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#3046 [15.0[l10n_br_fiscal] read rights for base user; forward port de #2991
  l10n_br_fiscal/security/ir.model.access.csv
Labels: bot is merging ⏳

#3041 [16.0] l10n_br_focus: import existing filter; forward port de #2987 e de #3006
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/tests/test_l10n_br_nfse_focus.py
Labels: approved, bot is merging ⏳

#3040 [15.0][l10n_br_focus]: import existing filter; foward port #2987 e de #3006
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/tests/test_l10n_br_nfse_focus.py
Labels: approved, bot is merging ⏳

#3045 [16.0][l10n_br_fiscal][FIX] ICMS ST state_to_ids domain; forward port de #2984
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#3044 [15.0][l10n_br_fiscal][FIX] ICMS ST state_to_ids domain; forward port de #2984
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#3043 [16.0][10n_br_fiscal][FIX] ICMS FCP state_to_ids domain; forward port de #2989
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#3042 [15.0][l10n_br_fiscal] ICMS FCP state_to_ids domain; forward port de #2989
  l10n_br_fiscal/models/icms_regulation.py
Labels: approved, bot is merging ⏳

#3039 [16.0][ l10n_br_coa][ l10n_br_fiscal] forward port #3000 e #3011
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal.tax.group.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, bot is merging ⏳

#3038 [15.0][ l10n_br_coa][ l10n_br_fiscal][l10n_br_account] forward port #3000 e #3011
  l10n_br_account/data/account_tax_group.xml
  l10n_br_account/data/account_tax_template.xml
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal.tax.group.csv
  l10n_br_fiscal/models/document_fiscal_line_mixin.py
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
  l10n_br_fiscal/models/document_fiscal_mixin_fields.py
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/tax.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
Labels: approved, bot is merging ⏳

#3051 [16.0][l10n_br_fiscal] CFOP 5124: no financial; port de #3036
  l10n_br_fiscal/data/l10n_br_fiscal.cfop.csv
Labels: approved, bot is merging ⏳

#3050 [15.0][l10n_br_fiscal] CFOP 5124: no financial; port de #3036
  l10n_br_fiscal/data/l10n_br_fiscal.cfop.csv
Labels: approved, bot is merging ⏳

#3052 [15.0][l10n_br_fiscal][l10n_br_account] forward port de #3032
  l10n_br_account/models/fiscal_document.py
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳
