Repository OCA/l10n-brazil, pull requests merged in 2024-02, with the labels that each got.

#2853 [16.0][FIX] l10n_br_coa: fix wh tax factor_percent
  l10n_br_coa/data/account_tax_template.xml
Labels: approved, bot is merging ⏳

#2898 [16.0][l10n_br_crm] port de todos novos commits da 14.0
  l10n_br_crm/__init__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/models/__init__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_crm/views/crm_lead_view.xml
Labels: approved, bot is merging ⏳

#2897 [15.0][l10n_br_crm] port de todos novos commits da 14.0
  l10n_br_crm/__init__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/models/__init__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_crm/views/crm_lead_view.xml
Labels: approved, bot is merging ⏳, 15.0, backport

#2901 [14.0][IMP] l10n_br_fiscal: Added two new fiscal operation lines for service purchases
  l10n_br_fiscal/data/operation_data.xml
Labels: new feature, approved, bot is merging ⏳, 14.0

#2872 [15.0][MIG][l10n_br_fiscal_dfe]
  l10n_br_fiscal_dfe/README.rst
  l10n_br_fiscal_dfe/__init__.py
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_fiscal_dfe/constants/dfe.py
  l10n_br_fiscal_dfe/data/ir_cron.xml
  l10n_br_fiscal_dfe/i18n/l10n_br_fiscal_dfe.pot
  l10n_br_fiscal_dfe/i18n/pt_BR.po
  l10n_br_fiscal_dfe/models/__init__.py
  l10n_br_fiscal_dfe/models/attachment.py
  l10n_br_fiscal_dfe/models/dfe.py
  l10n_br_fiscal_dfe/models/document.py
  l10n_br_fiscal_dfe/models/res_company.py
  l10n_br_fiscal_dfe/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_dfe/readme/DESCRIPTION.rst
  l10n_br_fiscal_dfe/security/ir.model.access.csv
  l10n_br_fiscal_dfe/static/description/icon.png
  l10n_br_fiscal_dfe/tests/__init__.py
  l10n_br_fiscal_dfe/tests/test_dfe.py
  l10n_br_fiscal_dfe/tools/__init__.py
  l10n_br_fiscal_dfe/tools/utils.py
  l10n_br_fiscal_dfe/views/dfe/dfe_views.xml
  l10n_br_fiscal_dfe/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal_dfe/views/res_company_view.xml
  requirements.txt
  setup/l10n_br_fiscal_dfe/odoo/addons/l10n_br_fiscal_dfe
  setup/l10n_br_fiscal_dfe/setup.py
Labels: migration, bot is merging ⏳, 15.0

#2904 [14.0] Atualização das alíquotas internas de ICMS 2024
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
  l10n_br_fiscal/migrations/14.0.21.0.0/pre-migration.py
Labels: approved, bot is merging ⏳, 14.0

#2905 [15.0] Atualização das alíquotas internas de ICMS 2024
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
Labels: approved, bot is merging ⏳, 15.0

#2903 [12.0] Atualização das alíquotas internas de ICMS 2024
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
  l10n_br_fiscal/migrations/12.0.35.5.0/pre-migration.py
Labels: approved, 12.0, bot is merging ⏳

#2902 [14.0][FIX] l10n_br_fiscal: Grupo Usuário NFe e Fiscal deve ter acesso para ver e criar Documentos Fiscais
  l10n_br_fiscal/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#2908 [14.0][FIX] l10n_br_pos_nfce: Correção nos testes da NFCe
  l10n_br_pos_nfce/tests/test_pos_order.py
Labels: approved, bot is merging ⏳

#2910 [16.0][FIX][PORT-FOWARD] l10n_br_fiscal: Grupo Usuário NFe e Fiscal deve ter acesso para ver e criar Documentos Fiscais
  l10n_br_fiscal/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, 16.0, backport

#2915 [16.0][IMP] l10n_br_fiscal: Added two new fiscal operation lines for service purchases
  l10n_br_fiscal/data/operation_data.xml
Labels: new feature, approved, bot is merging ⏳, 14.0

#2916 [16.0][l10n_br_coa_simple] forward port de #2595
  l10n_br_coa_simple/hooks.py
Labels: approved, bot is merging ⏳, 16.0, backport

#2914 [15.0][IMP] l10n_br_fiscal: Added two new fiscal operation lines for service purchases
  l10n_br_fiscal/data/operation_data.xml
Labels: approved, bot is merging ⏳, 15.0, backport

#2917 [14.0][FIX] l10n_br_base: Retorna campo a view
  l10n_br_base/views/res_partner_address_view.xml
Labels: approved, bot is merging ⏳

#2816 [15.0][MIG][l10n_br_sale]
  l10n_br_sale/README.rst
  l10n_br_sale/__init__.py
  l10n_br_sale/__manifest__.py
  l10n_br_sale/data/company.xml
  l10n_br_sale/demo/company.xml
  l10n_br_sale/demo/fiscal_operation_generic.xml
  l10n_br_sale/demo/fiscal_operation_simple.xml
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/demo/product.xml
  l10n_br_sale/hooks.py
  l10n_br_sale/i18n/l10n_br_sale.pot
  l10n_br_sale/i18n/pt_BR.po
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/res_company.py
  l10n_br_sale/models/res_config_settings.py
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/readme/CONFIGURE.rst
  l10n_br_sale/readme/CONTRIBUTORS.rst
  l10n_br_sale/readme/CREDITS.rst
  l10n_br_sale/readme/DESCRIPTION.rst
  l10n_br_sale/readme/HISTORY.rst
  l10n_br_sale/readme/INSTALL.rst
  l10n_br_sale/readme/ROADMAP.rst
  l10n_br_sale/readme/USAGE.rst
  l10n_br_sale/report/__init__.py
  l10n_br_sale/report/sale_report.py
  l10n_br_sale/report/sale_report_templates.xml
  l10n_br_sale/report/sale_report_view.xml
  l10n_br_sale/security/ir.model.access.csv
  l10n_br_sale/security/l10n_br_sale_security.xml
  l10n_br_sale/static/description/icon.png
  l10n_br_sale/static/description/index.html
  l10n_br_sale/static/description/sale_order_1.png
  l10n_br_sale/static/description/sale_order_2.png
  l10n_br_sale/tests/__init__.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/tests/test_l10n_br_sale_discount.py
  l10n_br_sale/tests/test_l10n_br_sale_pricelist.py
  l10n_br_sale/tests/test_l10n_br_sale_sn.py
  l10n_br_sale/views/res_company_view.xml
  l10n_br_sale/views/res_config_settings_view.xml
  l10n_br_sale/views/sale_view.xml
  setup/l10n_br_sale/odoo/addons/l10n_br_sale
  setup/l10n_br_sale/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, 15.0

#2913 [14.0][IMP][l10n_br_cnpj_search]: adicionar wizard para atualizar dados do parceiro
  l10n_br_cnpj_search/__init__.py
  l10n_br_cnpj_search/__manifest__.py
  l10n_br_cnpj_search/models/l10n_br_base_party_mixin.py
  l10n_br_cnpj_search/models/res_partner.py
  l10n_br_cnpj_search/security/ir.model.access.csv
  l10n_br_cnpj_search/static/description/index.html
  l10n_br_cnpj_search/tests/test_receitaws.py
  l10n_br_cnpj_search/tests/test_serpro.py
  l10n_br_cnpj_search/views/res_company_view.xml
  l10n_br_cnpj_search/views/res_partner_view.xml
  l10n_br_cnpj_search/wizard/__init__.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.xml
  l10n_br_ie_search/__init__.py
  l10n_br_ie_search/models/__init__.py
  l10n_br_ie_search/tests/fixtures/test_sefaz.yaml
  l10n_br_ie_search/tests/test_sefaz.py
  l10n_br_ie_search/tests/test_sintegra.py
  l10n_br_ie_search/wizard/__init__.py
  l10n_br_ie_search/wizard/extend_partner_cnpj_search_wizard.py
Labels: new feature, approved, bot is merging ⏳, 14.0

#2817 [15.0][MIG][l10n_br_purchase]
  l10n_br_purchase/README.rst
  l10n_br_purchase/__init__.py
  l10n_br_purchase/__manifest__.py
  l10n_br_purchase/data/company.xml
  l10n_br_purchase/demo/company.xml
  l10n_br_purchase/demo/fiscal_operation_generic.xml
  l10n_br_purchase/demo/fiscal_operation_simple.xml
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/demo/product.xml
  l10n_br_purchase/hooks.py
  l10n_br_purchase/i18n/l10n_br_purchase.pot
  l10n_br_purchase/i18n/pt_BR.po
  l10n_br_purchase/models/__init__.py
  l10n_br_purchase/models/account_move.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_purchase/models/res_company.py
  l10n_br_purchase/readme/CONFIGURE.rst
  l10n_br_purchase/readme/CONTRIBUTORS.rst
  l10n_br_purchase/readme/CREDITS.rst
  l10n_br_purchase/readme/DESCRIPTION.rst
  l10n_br_purchase/readme/HISTORY.rst
  l10n_br_purchase/readme/INSTALL.rst
  l10n_br_purchase/readme/ROADMAP.rst
  l10n_br_purchase/readme/USAGE.rst
  l10n_br_purchase/reports/__init__.py
  l10n_br_purchase/reports/purchase_order_templates.xml
  l10n_br_purchase/reports/purchase_report.py
  l10n_br_purchase/reports/purchase_report_views.xml
  l10n_br_purchase/security/ir.model.access.csv
  l10n_br_purchase/static/description/icon.png
  l10n_br_purchase/static/description/index.html
  l10n_br_purchase/tests/__init__.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase/tests/test_l10n_br_purchase_sn.py
  l10n_br_purchase/views/purchase_view.xml
  l10n_br_purchase/views/res_company_view.xml
  setup/l10n_br_purchase/odoo/addons/l10n_br_purchase
  setup/l10n_br_purchase/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, 15.0

#2896 [15.0][FORWARD PORT][REF+FIX][l10n_br_fiscal][l10n_br_fiscal_certificate]
  l10n_br_fiscal_certificate/models/certificate.py
  l10n_br_fiscal_certificate/models/res_company.py
  l10n_br_fiscal_certificate/tests/__init__.py
  l10n_br_fiscal_certificate/tests/test_certificate.py
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_fiscal_dfe/models/dfe.py
Labels: approved, bot is merging ⏳, 15.0, backport

#2879 [16.0][MIG][l10n_br_fiscal_certificate]
  l10n_br_fiscal_certificate/README.rst
  l10n_br_fiscal_certificate/__init__.py
  l10n_br_fiscal_certificate/__manifest__.py
  l10n_br_fiscal_certificate/constants.py
  l10n_br_fiscal_certificate/hooks.py
  l10n_br_fiscal_certificate/i18n/l10n_br_fiscal_certificate.pot
  l10n_br_fiscal_certificate/i18n/pt_BR.po
  l10n_br_fiscal_certificate/models/__init__.py
  l10n_br_fiscal_certificate/models/certificate.py
  l10n_br_fiscal_certificate/models/res_company.py
  l10n_br_fiscal_certificate/models/res_config_settings.py
  l10n_br_fiscal_certificate/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_certificate/readme/DESCRIPTION.rst
  l10n_br_fiscal_certificate/readme/HISTORY.rst
  l10n_br_fiscal_certificate/readme/USAGE.rst
  l10n_br_fiscal_certificate/security/ir.model.access.csv
  l10n_br_fiscal_certificate/static/description/icon.png
  l10n_br_fiscal_certificate/static/description/index.html
  l10n_br_fiscal_certificate/tests/__init__.py
  l10n_br_fiscal_certificate/tests/test_certificate.py
  l10n_br_fiscal_certificate/views/certificate_view.xml
  l10n_br_fiscal_certificate/views/res_company_view.xml
  l10n_br_fiscal_certificate/views/res_config_settings_view.xml
  requirements.txt
  setup/l10n_br_fiscal_certificate/odoo/addons/l10n_br_fiscal_certificate
  setup/l10n_br_fiscal_certificate/setup.py
  test-requirements.txt
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳, 16.0

#2881 [16.0][MIG][l10n_br_fiscal_dfe]
  l10n_br_fiscal_dfe/README.rst
  l10n_br_fiscal_dfe/__init__.py
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_fiscal_dfe/constants/dfe.py
  l10n_br_fiscal_dfe/data/ir_cron.xml
  l10n_br_fiscal_dfe/i18n/l10n_br_fiscal_dfe.pot
  l10n_br_fiscal_dfe/i18n/pt_BR.po
  l10n_br_fiscal_dfe/models/__init__.py
  l10n_br_fiscal_dfe/models/attachment.py
  l10n_br_fiscal_dfe/models/dfe.py
  l10n_br_fiscal_dfe/models/document.py
  l10n_br_fiscal_dfe/models/res_company.py
  l10n_br_fiscal_dfe/readme/CONTRIBUTORS.rst
  l10n_br_fiscal_dfe/readme/DESCRIPTION.rst
  l10n_br_fiscal_dfe/security/ir.model.access.csv
  l10n_br_fiscal_dfe/static/description/icon.png
  l10n_br_fiscal_dfe/tests/__init__.py
  l10n_br_fiscal_dfe/tests/test_dfe.py
  l10n_br_fiscal_dfe/tools/__init__.py
  l10n_br_fiscal_dfe/tools/utils.py
  l10n_br_fiscal_dfe/views/dfe/dfe_views.xml
  l10n_br_fiscal_dfe/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal_dfe/views/res_company_view.xml
  requirements.txt
  setup/l10n_br_fiscal_dfe/odoo/addons/l10n_br_fiscal_dfe
  setup/l10n_br_fiscal_dfe/setup.py
Labels: needs review, approved, migration, bot is merging ⏳, 16.0

#2921 [14.0][FIX] l10n_br_cnpj_search: Perda do vínculo com os contatos do parceiro
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
Labels: approved, bot is merging ⏳

#2922 [14.0] [IMP] l10n_br_fiscal: fill issqn_fg_city_id when city_taxation_code_id changes value
  l10n_br_fiscal/models/document_fiscal_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#2860 [14.0][REF] l10n_br_stock_account: Adaptando o modulo para ter compatibilidade com o Caso Internacional
  l10n_br_stock_account/wizards/stock_invoice_onshipping.py
  l10n_br_stock_account/wizards/stock_invoice_onshipping_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2928 [15.0][FIX] l10n_br_base: Retorna campo a view
  l10n_br_base/views/res_partner_address_view.xml
Labels: bot is merging ⏳

#2929 [16.0][FIX] l10n_br_base: Retorna campo a view
  l10n_br_base/views/res_partner_address_view.xml
Labels: approved, bot is merging ⏳, 16.0, backport

#2932 [14.0][FIX][l10n_br_cnpj_search]: adicionar descrição no wizard
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
Labels: approved, bot is merging ⏳
