Repository OCA/l10n-brazil, pull requests merged in 2025-06, with the labels that each got.

#3821 [16.0][REF] spec_driven_model: fix demo PO mixins
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/tests/spec_poxsd.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, bot is merging ⏳

#3824 [14.0][IMP] l10n_br_nfse/l10n_br_nfse_focus: informações adicionais do Contribuinte e Fiscal
  l10n_br_nfse/models/document.py
  l10n_br_nfse_focus/models/document.py
Labels: approved, bot is merging ⏳

#3816 [14.0][IMP] l10n_br_fiscal: fiscal doc VAT specification
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/views/document_view.xml
Labels: approved, bot is merging ⏳

#3823 [14.0]FIX] l10n_br_account: _add_inherited_fields fix - backport de #3808
  l10n_br_account/models/account_move.py
  l10n_br_account/models/document_line.py
  l10n_br_account/models/fiscal_decorator_mixin.py
  l10n_br_cte/models/document_line.py
  l10n_br_fiscal/models/document_line.py
Labels: approved, bot is merging ⏳

#3809 [16.0][IMP] spec_driven_model: faster/cleaner update
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
Labels: approved, bot is merging ⏳

#3788 [16.0] l10n_br_base fixes
  l10n_br_base/models/party_mixin.py
  l10n_br_base/models/res_partner.py
  l10n_br_base/models/res_partner_bank.py
  l10n_br_base/views/res_partner_view.xml
Labels: approved, ready to merge, merged 🎉, 16.0

#3825 [16.0] l10n_br_account, l10n_br_stock_account: _get_view improvements
  l10n_br_account/models/account_move.py
  l10n_br_stock_account/models/stock_picking.py
Labels: approved, bot is merging ⏳

#3827 [14.0][FIX] l10n_br_mdfe: fix mdfe view attrs
  l10n_br_mdfe/views/document.xml
Labels: approved, bot is merging ⏳

#3526 [14.0][IMP] l10n_br_mdfe: add transmission, cancelling and closure
  l10n_br_account/models/account_move.py
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal_edi/models/document_event.py
  l10n_br_mdfe/__init__.py
  l10n_br_mdfe/__manifest__.py
  l10n_br_mdfe/models/document.py
  l10n_br_mdfe/models/modal_rodoviario.py
  l10n_br_mdfe/models/res_partner.py
  l10n_br_mdfe/security/ir.model.access.csv
  l10n_br_mdfe/tests/__init__.py
  l10n_br_mdfe/tests/mdfe/v3_00/leiauteMDFe/MDFe35230905472475000102580200000602011208018449.xml
  l10n_br_mdfe/tests/mdfe/v3_00/leiauteMDFe/MDFe35230905472475000102580200000602071611554500.xml
  l10n_br_mdfe/tests/mdfe/v3_00/leiauteMDFe/MDFe35230905472475000102580200000602081550195716.xml
  l10n_br_mdfe/tests/mdfe/v3_00/leiauteMDFe/MDFe35231005472475000102580200000602161434590525.xml
  l10n_br_mdfe/tests/test_mdfe_document.py
  l10n_br_mdfe/tests/test_mdfe_serialize.py
  l10n_br_mdfe/views/document.xml
  l10n_br_mdfe/wizards/__init__.py
  l10n_br_mdfe/wizards/document_closure_wizard.py
  l10n_br_mdfe/wizards/document_closure_wizard.xml
Labels: bot is merging ⏳, 14.0

#3100 [14.0][ADD][l10n_br_sped_base] SPED BASE MODULE
  l10n_br_sped_base/README.rst
  l10n_br_sped_base/__init__.py
  l10n_br_sped_base/__manifest__.py
  l10n_br_sped_base/models/__init__.py
  l10n_br_sped_base/models/sped_declaration.py
  l10n_br_sped_base/models/sped_mixin.py
  l10n_br_sped_base/readme/CONTRIBUTORS.rst
  l10n_br_sped_base/readme/DESCRIPTION.rst
  l10n_br_sped_base/static/description/icon.png
  l10n_br_sped_base/static/description/index.html
  l10n_br_sped_base/tests/__init__.py
  l10n_br_sped_base/tests/demo_fake.txt
  l10n_br_sped_base/tests/sped_fake.py
  l10n_br_sped_base/tests/sped_fake_spec_9.py
  l10n_br_sped_base/tests/sped_mixin_fake.py
  l10n_br_sped_base/tests/test_sped_base.py
  l10n_br_sped_base/views/sped_base.xml
  setup/l10n_br_sped_base/odoo/addons/l10n_br_sped_base
  setup/l10n_br_sped_base/setup.py
Labels: new feature, work in progress, approved, bot is merging ⏳, 14.0

#3841 [16.0][FIX] l10n_br_mdfe: fix mdfe view attrs - fwp #3827
  l10n_br_mdfe/views/document.xml
Labels: approved, bot is merging ⏳

#3840 [16.0][FWP] l10n_br_nfse_focus - fwp #3084, #3137, #3175, #3548, #3824
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/views/res_company_view.xml
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/models/res_company.py
  l10n_br_nfse_focus/views/res_company.xml
Labels: approved, bot is merging ⏳, 16.0, backport

#3844 [16.0][REF] l10n_br_coa: use csv for flat data
  l10n_br_coa/__manifest__.py
  l10n_br_coa/data/account.account.tag.csv
  l10n_br_coa/data/account.tax.group.csv
  l10n_br_coa/data/account.tax.template.csv
  l10n_br_coa/data/account_tax_group.xml
  l10n_br_coa/data/account_tax_tag.xml
  l10n_br_coa/data/account_tax_template.xml
Labels: approved, bot is merging ⏳, 16.0

#3843 [16.0][REF] l10n_br_account_due_list refactor
  l10n_br_account_due_list/__manifest__.py
  l10n_br_account_due_list/models/__init__.py
  l10n_br_account_due_list/models/account_invoice.py
  l10n_br_account_due_list/models/account_move.py
  l10n_br_account_due_list/readme/DESCRIPTION.md
  l10n_br_account_due_list/tests/test_payments.py
  l10n_br_account_due_list/views/account_move_view.xml
  l10n_br_account_nfe/models/document.py
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
  l10n_br_account_payment_brcobranca/models/account_move.py
  l10n_br_account_payment_brcobranca/tests/test_payment_order.py
  l10n_br_account_payment_brcobranca/tests/test_return_import.py
  l10n_br_account_payment_order/models/account_move.py
  l10n_br_account_payment_order/tests/test_payment_order_change.py
Labels: refactoring, approved, bot is merging ⏳, 16.0

#3850 [16.0] l10n_br_nfe: remove old v7/v8 OpenERP wizards
  l10n_br_nfe/security/ir.model.access.csv
  l10n_br_nfe/tests/test_account_customer_invoice.py
  l10n_br_nfe/tests/test_account_customer_nfe.py
  l10n_br_nfe/tests/test_account_nfe_refund.py
  l10n_br_nfe/tests/test_account_supplier_nfe.py
  l10n_br_nfe/tests/test_nfe_export.py
  l10n_br_nfe/wizards/__init__.py
  l10n_br_nfe/wizards/l10n_br_account_nfe_export.py
  l10n_br_nfe/wizards/l10n_br_account_nfe_export_invoice.py
Labels: approved, bot is merging ⏳
