Repository OCA/l10n-brazil, pull requests merged in 2025-01, with the labels that each got.

#3565 [16.0][spec_driven_model][MIG] spec_driven_model: no more deprecated method
  spec_driven_model/models/spec_mixin.py
Labels: approved, ready to merge, bot is merging ⏳

#3564 [16.0][l10n_br_base][l10n_br_nfe][l10n_br_stock] fwp 3545
  l10n_br_base/demo/res_company_demo.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000012062777161.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200181583054000129550010000000052062777166.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200681583054000129550010000000012760018057-nf-e.xml
  l10n_br_stock/__manifest__.py
  l10n_br_stock/demo/res_company_demo.xml
Labels: approved, ready to merge, bot is merging ⏳

#3574 [16.0][FIX] l10n_br_account: fix undef tax_ids
  l10n_br_account/models/account_move_line.py
Labels: approved, bot is merging ⏳

#3578 [16.0][REM] l10n_br_nfe: remove dead nbm code
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/nbm.py
Labels: bot is merging ⏳

#2955 [14.0][REF] l10n_br_sale_stock: Extraction referent the creation of the module sale_stock_picking_invoicing
  l10n_br_sale_stock/README.rst
  l10n_br_sale_stock/__manifest__.py
  l10n_br_sale_stock/demo/sale_order_demo.xml
  l10n_br_sale_stock/migrations/14.0.2.0.0/pre-migration.py
  l10n_br_sale_stock/models/__init__.py
  l10n_br_sale_stock/models/res_company.py
  l10n_br_sale_stock/models/res_config_settings.py
  l10n_br_sale_stock/models/sale_order.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/readme/HISTORY.rst
  l10n_br_sale_stock/static/description/index.html
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/views/res_company_view.xml
  l10n_br_sale_stock/views/res_config_settings_view.xml
  l10n_br_sale_stock/views/sale_order_view.xml
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: approved, ready to merge, bot is merging ⏳

#3181 [14.0][IMP] l10n_br_account_withholding: handling of partner_id assignment
  l10n_br_account_withholding/README.rst
  l10n_br_account_withholding/__manifest__.py
  l10n_br_account_withholding/models/__init__.py
  l10n_br_account_withholding/models/account_move.py
  l10n_br_account_withholding/models/res_partner.py
  l10n_br_account_withholding/readme/CONFIGURE.md
  l10n_br_account_withholding/readme/USAGE.md
  l10n_br_account_withholding/static/description/index.html
  l10n_br_account_withholding/tests/test_account_wh_invoice.py
  l10n_br_account_withholding/views/res_partner.xml
Labels: approved, ready to merge, bot is merging ⏳, 14.0, stale

#3510 [15.0][spec_driven_model][l10n_br_nfe][l10n_br_nfe_spec][l10n_br_account_nfe] Oca port spec driven model 14.0 to 15.0 51e0f3 (fwp 3431)
  l10n_br_account_nfe/tests/test_nfce_contingency.py
  l10n_br_nfe/hooks.py
  l10n_br_nfe/models/__init__.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_related.py
  l10n_br_nfe/models/document_supplement.py
  l10n_br_nfe/tests/test_nfe_import.py
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_structure.py
  l10n_br_nfe_spec/models/__init__.py
  l10n_br_nfe_spec/models/spec_mixin.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
  spec_driven_model/__manifest__.py
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/models/spec_view.py
  spec_driven_model/readme/DESCRIPTION.rst
  spec_driven_model/tests/__init__.py
  spec_driven_model/tests/fake_mixin.py
  spec_driven_model/tests/spec_purchase.py
  spec_driven_model/tests/test_spec_model.py
Labels: approved, ready to merge, bot is merging ⏳

#3581 [16.0][l10n_br_base] oca-port: blacklist PR(s) 2868, 3545 for l10n_br_base
  .oca/oca-port/blacklist/l10n_br_base.json
Labels: approved

#3583 [15.0][MIG][l10n_br_mdfe_spec]
  .pre-commit-config.yaml
  l10n_br_mdfe_spec/README.rst
  l10n_br_mdfe_spec/__init__.py
  l10n_br_mdfe_spec/__manifest__.py
  l10n_br_mdfe_spec/i18n/l10n_br_mdfe_spec.pot
  l10n_br_mdfe_spec/i18n/pt_BR.po
  l10n_br_mdfe_spec/models/__init__.py
  l10n_br_mdfe_spec/models/spec_mixin.py
  l10n_br_mdfe_spec/models/v3_0/__init__.py
  l10n_br_mdfe_spec/models/v3_0/ev_pagto_oper_mdfe_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_aereo_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_aquaviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_ferroviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_rodoviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_tipos_basico_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/tipos_geral_mdfe_v3_00.py
  l10n_br_mdfe_spec/readme/CONTRIBUTORS.rst
  l10n_br_mdfe_spec/readme/DESCRIPTION.rst
  l10n_br_mdfe_spec/static/description/icon.png
  l10n_br_mdfe_spec/static/description/index.html
  l10n_br_mdfe_spec/tests/__init__.py
  l10n_br_mdfe_spec/tests/test_mdfe_import.py
  setup/l10n_br_mdfe_spec/odoo/addons/l10n_br_mdfe_spec
  setup/l10n_br_mdfe_spec/setup.py
Labels: approved, bot is merging ⏳

#3589 [15.0][l10n_br_fiscal][l10n_br_nfe] Oca port 14.0 to 16.0 7ffa39
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_supplement.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/views/document_view.xml
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/document_supplement.py
  l10n_br_nfe/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#3580 [14.0][IMP] l10n_br_purchase: improving the search by fiscal document type
  l10n_br_purchase/models/purchase_order.py
Labels: approved, bot is merging ⏳

#3591 [16.0][IMP] l10n_br_purchase: improving the search by fiscal document type (port from 14.0
  l10n_br_purchase/models/purchase_order.py
Labels: approved, bot is merging ⏳

#3590 [15.0][IMP] l10n_br_purchase: improving the search by fiscal document type (port from 14.0)
  l10n_br_purchase/models/purchase_order.py
Labels: approved, bot is merging ⏳

#3588 [14.0][FIX] l10n_br_contract: fix contracts with section or notes lines
  l10n_br_contract/models/contract_contract.py
Labels: approved, bot is merging ⏳

#3593 [16.0][FIX] l10n_br_account_payment_order: make migration script more fault-tolerant
  l10n_br_account_payment_order/migrations/16.0.2.0.0/post-migration.py
Labels: approved, bot is merging ⏳, 16.0

#3592 [16.0][REF] l10n_br_stock_account: Usando o Common Test do stock_picking_invoicing e removendo campo já informado
  l10n_br_stock_account/models/stock_rule.py
  l10n_br_stock_account/tests/common.py
  l10n_br_stock_account/tests/test_invoicing_picking.py
Labels: approved, bot is merging ⏳

#3594 [16.0][REF] l10n_br_account_payment_order: Na v16 é possível usar campos tipo Many2Many no Agrupar Por/Group By
  l10n_br_account_payment_order/README.rst
  l10n_br_account_payment_order/models/l10n_br_cnab_code.py
  l10n_br_account_payment_order/readme/ROADMAP.md
  l10n_br_account_payment_order/static/description/index.html
  l10n_br_account_payment_order/views/l10n_br_cnab_code_view.xml
Labels: approved, bot is merging ⏳

#3595 [16.0][MIG] l10n_br_purchase_stock: Migração para a v16
  l10n_br_purchase_stock/README.rst
  l10n_br_purchase_stock/__init__.py
  l10n_br_purchase_stock/__manifest__.py
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_purchase_stock/i18n/l10n_br_purchase_stock.pot
  l10n_br_purchase_stock/i18n/pt_BR.po
  l10n_br_purchase_stock/models/__init__.py
  l10n_br_purchase_stock/models/purchase_order.py
  l10n_br_purchase_stock/models/purchase_order_line.py
  l10n_br_purchase_stock/models/res_company.py
  l10n_br_purchase_stock/models/res_config_settings.py
  l10n_br_purchase_stock/models/stock_move.py
  l10n_br_purchase_stock/models/stock_picking.py
  l10n_br_purchase_stock/models/stock_rule.py
  l10n_br_purchase_stock/pyproject.toml
  l10n_br_purchase_stock/readme/CONFIGURE.md
  l10n_br_purchase_stock/readme/CONTRIBUTORS.md
  l10n_br_purchase_stock/readme/CREDITS.md
  l10n_br_purchase_stock/readme/DESCRIPTION.md
  l10n_br_purchase_stock/readme/HISTORY.md
  l10n_br_purchase_stock/readme/INSTALL.md
  l10n_br_purchase_stock/readme/ROADMAP.md
  l10n_br_purchase_stock/readme/USAGE.md
  l10n_br_purchase_stock/static/description/icon.png
  l10n_br_purchase_stock/static/description/index.html
  l10n_br_purchase_stock/tests/__init__.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock_lp.py
  l10n_br_purchase_stock/tests/test_l10n_br_purchase_stock_sn.py
  l10n_br_purchase_stock/tests/test_stock_rule.py
  l10n_br_purchase_stock/views/purchase_order.xml
  l10n_br_purchase_stock/views/res_company_view.xml
  l10n_br_purchase_stock/views/res_config_settings.xml
  l10n_br_purchase_stock/wizards/__init__.py
  l10n_br_purchase_stock/wizards/stock_invocing_onshipping.py
Labels: approved, bot is merging ⏳

#3527 [14.0][IMP] Paulistana Status Consulta
  l10n_br_nfse_paulistana/constants/paulistana.py
  l10n_br_nfse_paulistana/models/document.py
Labels: bug, approved, bot is merging ⏳

#3600 [16.0][FIX] l10n_br_account_payment_order: Teste de Alteração da Data de Vencimento, erro no CI
  l10n_br_account_payment_order/tests/test_base_class.py
  l10n_br_account_payment_order/tests/test_payment_order_change.py
Labels: bot is merging ⏳

#3602 [16.0][FIX] l10n_br_fiscal, l10n_br_fiscal_edi: Tree view
  l10n_br_fiscal/views/cfop_view.xml
  l10n_br_fiscal_edi/views/document_view.xml
Labels: approved, bot is merging ⏳
