Repository OCA/l10n-brazil, pull requests merged in 2025-05, with the labels that each got.

#3764 [14.0][FIX] l10n_br_account_withholding: chamada errada do super
  l10n_br_account_withholding/models/account_move_line.py
Labels: bot is merging ⏳

#3766 [16.0][REF] l10n_br_fiscal: partner profile -> csv
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/l10n_br_fiscal.partner.profile.csv
  l10n_br_fiscal/data/partner_profile_data.xml
Labels: approved, bot is merging ⏳

#3767 [16.0][IMP] l10n_br_fiscal: Update NBS file data
  l10n_br_fiscal/data/l10n_br_fiscal.nbs.csv
  l10n_br_fiscal/demo/__init__.py
Labels: approved, bot is merging ⏳, 16.0

#3728 [16.0][REF] l10n_br_account: set shadowed fields with inverse
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/document.py
  l10n_br_account/models/document_line.py
  l10n_br_account/models/fiscal_decorator_mixin.py
  l10n_br_account/tests/__init__.py
  l10n_br_account/tests/test_move_edition.py
  l10n_br_account/tests/test_non_fiscal_move.py
  l10n_br_cte/models/document_line.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_sale/models/__init__.py
  l10n_br_sale/models/account_move.py
  l10n_br_sale/models/document.py
Labels: refactoring, approved, ready to merge, bot is merging ⏳, 16.0

#3762 [16.0][REF] l10n_br_fiscal: Substituição dos objetos uom.uom e uom.uom.alternative pelo módulo uom_alias
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/uom.alias.csv
  l10n_br_fiscal/data/uom_alternative_data.xml
  l10n_br_fiscal/data/uom_data.xml
  l10n_br_fiscal/migrations/16.0.5.0.0/pre-migration.py
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/uom_uom.py
  l10n_br_fiscal/models/uom_uom_alternative.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_uom_uom.py
  l10n_br_fiscal/views/uom_uom.xml
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/uom.py
  l10n_br_nfe/wizards/import_document.py
Labels: refactoring, approved, bot is merging ⏳, 16.0

#3709 [16.0][l10n_br_fiscal] document_serie(_id): onchange -> compute
  l10n_br_account/tests/test_document_date.py
  l10n_br_account/tests/test_move_edition.py
  l10n_br_account_nfe/tests/test_nfe_generate_tags_cobr_dup_pag.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_mixin.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_fiscal_document_nfse.py
  l10n_br_fiscal/tests/test_subsequent_operation.py
  l10n_br_fiscal/tests/test_tax_benefit.py
  l10n_br_fiscal_edi/tests/test_fiscal_document_generic.py
  l10n_br_fiscal_edi/tests/test_tax_benefit.py
  l10n_br_nfe/tests/test_nfce.py
  l10n_br_nfe/tests/test_nfe_xml_validation.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
Labels: approved, bot is merging ⏳

#3768 [16.0][IMP] l10n_br_fiscal: Update FCP file data
  l10n_br_fiscal/data/l10n_br_fiscal.tax.csv
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
Labels: approved, bot is merging ⏳, 16.0

#3773 [16.0][REF] l10n_br_account: create_from_account context
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/document.py
  l10n_br_account/models/document_line.py
  l10n_br_account/models/fiscal_decorator_mixin.py
Labels: approved, bot is merging ⏳

#3771 [16.0][FIX] l10n_br_nfe: Check document date
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3782 [16.0][FIX] spec_driven_model: valid field parameter warning
  spec_driven_model/models/spec_mixin.py
Labels: bot is merging ⏳, 16.0

#3784 [16.0][IMP] l10n_br_sale: Melhorias na visão do pedido de venda
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/views/sale_view.xml
Labels: bot is merging ⏳, 16.0

#3769 [14.0][IMP] l10n_br_fiscal: Update NBS file data
  l10n_br_fiscal/data/l10n_br_fiscal.nbs.csv
Labels: approved, bot is merging ⏳, 14.0, backport

#3791 [16.0][REF] l10n_br_fiscal: simplifica alguns campos name de cadastros.
  l10n_br_fiscal/models/cest.py
  l10n_br_fiscal/models/icms_regulation.py
  l10n_br_fiscal/models/nbm.py
Labels: approved, bot is merging ⏳

#3786 [16.0][IMP] Adicionado cadastro de Natureza Jurídica
  l10n_br_cnpj_search/models/__init__.py
  l10n_br_cnpj_search/models/cnpj_webservice.py
  l10n_br_cnpj_search/models/l10n_br_base_party_mixin.py
  l10n_br_cnpj_search/models/res_company.py
  l10n_br_cnpj_search/models/res_partner.py
  l10n_br_cnpj_search/views/res_company_view.xml
  l10n_br_cnpj_search/views/res_partner_view.xml
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.py
  l10n_br_cnpj_search/wizard/partner_cnpj_search_wizard.xml
  l10n_br_crm_cnpj_search/models/crm_lead.py
  l10n_br_crm_cnpj_search/views/crm_lead_form.xml
  l10n_br_crm_cnpj_search/wizard/partner_cnpj_search_wizard.py
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/l10n_br_fiscal.legal.nature.csv
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/models/__init__.py
  l10n_br_fiscal/models/legal_nature.py
  l10n_br_fiscal/models/res_company.py
  l10n_br_fiscal/models/res_partner.py
  l10n_br_fiscal/security/ir.model.access.csv
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal/views/legal_nature_view.xml
  l10n_br_fiscal/views/res_company_view.xml
  l10n_br_fiscal/views/res_partner_view.xml
Labels: approved, bot is merging ⏳, 16.0

#3792 [16.0][IMP] l10n_br_account_payment_brcobranca: reconciled msg
  l10n_br_account_payment_brcobranca/models/account_move.py
Labels: approved, bot is merging ⏳

#3799 [16.0][FIX] spec_driven_model: proper export if field is False
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/tests/fake_odoo_purchase.py
  spec_driven_model/tests/spec_purchase.py
Labels: approved, bot is merging ⏳, 16.0

#3780 [15.0][MIG] l10n br nfse paulistana
  l10n_br_nfse_paulistana/README.rst
  l10n_br_nfse_paulistana/__init__.py
  l10n_br_nfse_paulistana/__manifest__.py
  l10n_br_nfse_paulistana/constants/paulistana.py
  l10n_br_nfse_paulistana/i18n/l10n_br_nfse_paulistana.pot
  l10n_br_nfse_paulistana/i18n/pt_BR.po
  l10n_br_nfse_paulistana/models/__init__.py
  l10n_br_nfse_paulistana/models/document.py
  l10n_br_nfse_paulistana/models/res_company.py
  l10n_br_nfse_paulistana/readme/CONFIGURE.rst
  l10n_br_nfse_paulistana/readme/CONTRIBUTORS.rst
  l10n_br_nfse_paulistana/readme/DESCRIPTION.rst
  l10n_br_nfse_paulistana/readme/INSTALL.rst
  l10n_br_nfse_paulistana/readme/ROADMAP.rst
  l10n_br_nfse_paulistana/readme/USAGE.rst
  l10n_br_nfse_paulistana/static/description/icon.png
  l10n_br_nfse_paulistana/static/description/index.html
  l10n_br_nfse_paulistana/tests/__init__.py
  l10n_br_nfse_paulistana/tests/nfse/paulistana.xml
  l10n_br_nfse_paulistana/tests/test_fiscal_document_nfse_paulistana.py
  requirements.txt
  setup/l10n_br_nfse_paulistana/odoo/addons/l10n_br_nfse_paulistana
  setup/l10n_br_nfse_paulistana/setup.py
Labels: approved, bot is merging ⏳, 15.0

#3801 [16.0][FIX] l10n_br_account: tax_totals widget invisible
  l10n_br_account/models/account_move.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_sale/models/sale_order.py
Labels: approved, bot is merging ⏳
