Repository OCA/l10n-brazil, pull requests merged in 2025-10, with the labels that each got.

#4119 [17.0][REF] l10n_br_nfse: hide meths from RPC
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
Labels: approved, bot is merging ⏳

#4118 [18.0] oca port l10n_br_fiscal 16.0 to 18.0 6d1ab7
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/demo/fiscal_document_nfse_demo.xml
  l10n_br_fiscal/demo/fiscal_operation_demo.xml
  l10n_br_fiscal/migrations/18.0.3.0.0/pre-migration.py
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_fiscal/models/document_related.py
  l10n_br_fiscal/tests/test_document_edition.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_fiscal_document_nfse.py
  l10n_br_fiscal/tests/test_tax_benefit.py
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
Labels: approved, bot is merging ⏳

#4013 [16.0][IMP] l10n_br_account_nfe: payment_mode_id - fwp #3861
  l10n_br_account_nfe/README.rst
  l10n_br_account_nfe/__init__.py
  l10n_br_account_nfe/__manifest__.py
  l10n_br_account_nfe/models/account_move.py
  l10n_br_account_nfe/readme/CONTRIBUTORS.md
  l10n_br_account_nfe/static/description/index.html
  l10n_br_account_nfe/tests/__init__.py
  l10n_br_account_nfe/tests/test_invoice_refund.py
  l10n_br_account_nfe/wizard/__init__.py
  l10n_br_account_nfe/wizard/account_move_reversal.py
  l10n_br_account_nfe/wizard/account_move_reversal_view.xml
Labels: approved, bot is merging ⏳

#4121 [16.0][FIX+IMP] l10n_br_account_payment_order, l10n_br_account_payment_brcobranca: Corrigido processo de apagar um account.move e melhoria na cobertura de testes
  l10n_br_account_payment_brcobranca/tests/common.py
  l10n_br_account_payment_brcobranca/tests/test_brcobranca.py
  l10n_br_account_payment_order/models/account_move.py
  l10n_br_account_payment_order/tests/common.py
  l10n_br_account_payment_order/tests/test_payment_order_inbound.py
  l10n_br_account_payment_order/tests/tools.py
Labels: approved, bot is merging ⏳

#4127 [17.0] l10n_br_fiscal: Novo Tipo de Documento Fiscal 75
  l10n_br_fiscal/data/l10n_br_fiscal.document.type.csv
Labels: approved, bot is merging ⏳, 17.0

#4128 [18.0] l10n_br_fiscal: Novo Tipo de Documento Fiscal 75
  l10n_br_fiscal/data/l10n_br_fiscal.document.type.csv
Labels: approved, bot is merging ⏳, 18.0

#4126 [16.0] l10n_br_fiscal: Novo Tipo de Documento Fiscal 75
  l10n_br_fiscal/data/l10n_br_fiscal.document.type.csv
Labels: approved, bot is merging ⏳, 16.0

#4125 [16.0][REF] Mover constante FISCAL_PAYMENT_MODE do módulo l10n_br_fiscal para o módulo l10n_br_nfe
  l10n_br_account_nfe/models/account_payment_mode.py
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_nfe/constants/nfe.py
  l10n_br_nfe/models/document.py
Labels: refactoring, approved, bot is merging ⏳, 16.0

#4130 [16.0] l10n_br_fiscal, l10n_br_cte: clean cte view
  l10n_br_cte/views/document.xml
  l10n_br_fiscal/views/document_view.xml
Labels: approved, merged 🎉
