Repository OCA/l10n-brazil, pull requests merged in 2025-03, with the labels that each got.

#3640 [16.0][MIG] l10n_br_stock_account_report: Migração para a v16
  l10n_br_stock_account_report/README.rst
  l10n_br_stock_account_report/__init__.py
  l10n_br_stock_account_report/__manifest__.py
  l10n_br_stock_account_report/i18n/l10n_br_stock_account_report.pot
  l10n_br_stock_account_report/i18n/pt_BR.po
  l10n_br_stock_account_report/pyproject.toml
  l10n_br_stock_account_report/readme/CONFIGURE.md
  l10n_br_stock_account_report/readme/CONTRIBUTORS.md
  l10n_br_stock_account_report/readme/CREDITS.md
  l10n_br_stock_account_report/readme/DESCRIPTION.md
  l10n_br_stock_account_report/readme/HISTORY.md
  l10n_br_stock_account_report/readme/INSTALL.md
  l10n_br_stock_account_report/readme/ROADMAP.md
  l10n_br_stock_account_report/readme/USAGE.md
  l10n_br_stock_account_report/report/l10n_br_p7_model_inventory_report.xml
  l10n_br_stock_account_report/report/l10n_br_p7_model_inventory_report_view.xml
  l10n_br_stock_account_report/security/ir.model.access.csv
  l10n_br_stock_account_report/static/description/icon.png
  l10n_br_stock_account_report/static/description/index.html
  l10n_br_stock_account_report/tests/__init__.py
  l10n_br_stock_account_report/tests/test_l10n_br_p7_model_inventory_report.py
  l10n_br_stock_account_report/wizards/__init__.py
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard.py
  l10n_br_stock_account_report/wizards/l10n_br_p7_model_inventory_report_wizard_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#3648 [16.0][MIG] l10n_br_delivery_nfe
  l10n_br_delivery_nfe/README.rst
  l10n_br_delivery_nfe/__init__.py
  l10n_br_delivery_nfe/__manifest__.py
  l10n_br_delivery_nfe/i18n/l10n_br_delivery_nfe.pot
  l10n_br_delivery_nfe/i18n/pt_BR.po
  l10n_br_delivery_nfe/models/__init__.py
  l10n_br_delivery_nfe/models/document.py
  l10n_br_delivery_nfe/models/product_product.py
  l10n_br_delivery_nfe/models/product_template.py
  l10n_br_delivery_nfe/models/stock_picking.py
  l10n_br_delivery_nfe/models/stock_picking_lacres.py
  l10n_br_delivery_nfe/models/stock_picking_vol.py
  l10n_br_delivery_nfe/pyproject.toml
  l10n_br_delivery_nfe/security/ir.model.access.csv
  l10n_br_delivery_nfe/static/description/icon.png
  l10n_br_delivery_nfe/static/description/index.html
  l10n_br_delivery_nfe/tests/__init__.py
  l10n_br_delivery_nfe/tests/test_delivery_nfe.py
  l10n_br_delivery_nfe/tests/test_delivery_nfe_grouped.py
  l10n_br_delivery_nfe/views/nfe_document_view.xml
  l10n_br_delivery_nfe/views/product_product_view.xml
  l10n_br_delivery_nfe/views/product_template_view.xml
  l10n_br_delivery_nfe/views/stock_picking_view.xml
  l10n_br_delivery_nfe/wizards/__init__.py
  l10n_br_delivery_nfe/wizards/stock_generate_volumes.py
  l10n_br_delivery_nfe/wizards/stock_generate_volumes_view.xml
  l10n_br_delivery_nfe/wizards/stock_invoice_onshipping.py
  l10n_br_delivery_nfe/wizards/stock_invoice_onshipping_view.xml
  l10n_br_delivery_nfe/wizards/vol_stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#3582 [16.0][l10n_br_fiscal] Oca port 14.0 to 16.0 117911 (changes for MDF-e and CT-e)
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/data/ir_cron.xml
  l10n_br_fiscal/data/l10n_br_fiscal.document.type.csv
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin_fields.py
  l10n_br_fiscal/models/document_related.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_operation.py
  l10n_br_fiscal/views/document_related_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal/views/tax_definition_view.xml
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_fiscal_edi/models/document_event.py
Labels: approved, bot is merging ⏳

#3585 [16.0][MIG][l10n_br_mdfe_spec]
  .pre-commit-config.yaml
  l10n_br_mdfe_spec/README.rst
  l10n_br_mdfe_spec/__init__.py
  l10n_br_mdfe_spec/__manifest__.py
  l10n_br_mdfe_spec/i18n/l10n_br_mdfe_spec.pot
  l10n_br_mdfe_spec/i18n/pt_BR.po
  l10n_br_mdfe_spec/models/__init__.py
  l10n_br_mdfe_spec/models/spec_mixin.py
  l10n_br_mdfe_spec/models/v3_0/__init__.py
  l10n_br_mdfe_spec/models/v3_0/ev_pagto_oper_mdfe_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_aereo_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_aquaviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_ferroviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_rodoviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_tipos_basico_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/tipos_geral_mdfe_v3_00.py
  l10n_br_mdfe_spec/pyproject.toml
  l10n_br_mdfe_spec/readme/CONTRIBUTORS.md
  l10n_br_mdfe_spec/readme/DESCRIPTION.md
  l10n_br_mdfe_spec/static/description/icon.png
  l10n_br_mdfe_spec/static/description/index.html
  l10n_br_mdfe_spec/tests/__init__.py
  l10n_br_mdfe_spec/tests/test_mdfe_import.py
Labels: approved, ready to merge, bot is merging ⏳

#3586 [16.0][MIG][l10n_br_cte_spec]
  .pre-commit-config.yaml
  l10n_br_cte_spec/README.rst
  l10n_br_cte_spec/__init__.py
  l10n_br_cte_spec/__manifest__.py
  l10n_br_cte_spec/i18n/l10n_br_cte_spec.pot
  l10n_br_cte_spec/i18n/pt_BR.po
  l10n_br_cte_spec/models/__init__.py
  l10n_br_cte_spec/models/spec_mixin.py
  l10n_br_cte_spec/models/v4_0/__init__.py
  l10n_br_cte_spec/models/v4_0/cte_modal_aereo_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_aquaviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_dutoviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_ferroviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_rodoviario_os_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_rodoviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_multi_modal_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_tipos_basico_v4_00.py
  l10n_br_cte_spec/models/v4_0/evento_cte_tipos_basico_v4_00.py
  l10n_br_cte_spec/models/v4_0/tipos_geral_cte_v4_00.py
  l10n_br_cte_spec/pyproject.toml
  l10n_br_cte_spec/readme/CONTRIBUTORS.md
  l10n_br_cte_spec/readme/DESCRIPTION.md
  l10n_br_cte_spec/static/description/icon.png
  l10n_br_cte_spec/static/description/index.html
  l10n_br_cte_spec/tests/__init__.py
  l10n_br_cte_spec/tests/test_cte_import.py
Labels: approved, bot is merging ⏳

#3649 [15.0][l10n_br_fiscal] Oca port 14.0 to 15.0 117911 (changes for MDF-e and CT-e)
  l10n_br_fiscal/constants/fiscal.py
  l10n_br_fiscal/data/ir_cron.xml
  l10n_br_fiscal/data/l10n_br_fiscal.document.type.csv
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin_fields.py
  l10n_br_fiscal/models/document_related.py
  l10n_br_fiscal/models/operation.py
  l10n_br_fiscal/models/operation_line.py
  l10n_br_fiscal/models/tax_definition.py
  l10n_br_fiscal/tests/__init__.py
  l10n_br_fiscal/tests/test_operation.py
  l10n_br_fiscal/views/document_related_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_fiscal/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal/views/tax_definition_view.xml
  l10n_br_fiscal_closing/tests/test_fiscal_closing.py
  l10n_br_fiscal_edi/models/document_event.py
Labels: approved, bot is merging ⏳

#3660 [16.0][10n_br_fiscal_edi][l10n_br_nfe][l10n_br_account_nfe] varios ports da 14.0
  l10n_br_account_nfe/tests/test_nfe_with_ipi.py
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/views/document_fiscal_line_mixin_view.xml
  l10n_br_fiscal_edi/models/document_workflow.py
  l10n_br_nfe/models/document.py
  l10n_br_nfe/models/document_line.py
  l10n_br_nfe/models/invalidate_number.py
  l10n_br_nfe/models/product_product.py
  l10n_br_nfe/tests/test_nfce.py
  l10n_br_nfse_focus/tests/test_l10n_br_nfse_focus.py
Labels: approved, bot is merging ⏳

#3657 [16.0][REF][l10n_br_fiscal]: kill onchange in product.mixin
  l10n_br_fiscal/models/product_mixin.py
  l10n_br_fiscal/models/product_template.py
Labels: approved, bot is merging ⏳

#3653 [16.0][l10n_br_fiscal] l10n_br_fiscal.document.mixin.methods: convert _onchange_fiscal_operation_id to compute
  l10n_br_fiscal/models/document.py
  l10n_br_fiscal/models/document_mixin_fields.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_fiscal/models/document_move_mixin.py
  l10n_br_purchase/models/purchase_order.py
  l10n_br_sale/models/sale_order.py
  l10n_br_stock_account/models/stock_picking.py
  l10n_br_stock_account/tests/common.py
Labels: approved, bot is merging ⏳

#3647 [16.0][REF] l10n_br_account_payment_order, l10n_br_account_payment_brcobranca: Alterando o 'Código de Protesto' de Char para Objeto/l10n_br_cnab.code
  l10n_br_account_payment_brcobranca/README.rst
  l10n_br_account_payment_brcobranca/__manifest__.py
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_brcobranca/readme/HISTORY.md
  l10n_br_account_payment_brcobranca/static/description/index.html
  l10n_br_account_payment_order/README.rst
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_ailos_240_boleto_protest_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_bradesco_240_boleto_protest_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_cef_240_boleto_protest_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_itau_240_boleto_protest_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_santander_240_boleto_protest_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_sicred_240_boleto_protest_code.xml
  l10n_br_account_payment_order/data/cnab_codes/banco_unicred_240_400_boleto_protest_code.xml
  l10n_br_account_payment_order/demo/l10n_br_cnab_config_demo.xml
  l10n_br_account_payment_order/migrations/16.0.6.0.0/post-migration.py
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/readme/HISTORY.md
  l10n_br_account_payment_order/static/description/index.html
  l10n_br_account_payment_order/views/l10n_br_cnab_config_view.xml
Labels: approved, bot is merging ⏳

#3665 [16.0][REF] l10n_br_fiscal: Duplicate label conflict in Fiscal Type
  l10n_br_fiscal/models/document_line_mixin.py
Labels: bot is merging ⏳

#3666 [16.0][REF] l10n_br_stock_account: clean up test class
  l10n_br_stock_account/tests/common.py
Labels: approved, bot is merging ⏳

#3667 [14.0][DEL] l10n_br_fiscal: remove empty onchanges
  l10n_br_fiscal/models/document_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#3669 [15.0][DEL] l10n_br_fiscal: remove empty onchanges
  l10n_br_fiscal/models/document_line_mixin_methods.py
Labels: bot is merging ⏳

#3213 [14.0][FIX] l10n_br_account_payment_order: trigger CNAB info load on payment_mode_id change
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/security/ir.model.access.csv
  l10n_br_account_payment_order/tests/test_payment_order_change.py
  l10n_br_account_payment_order/wizards/__init__.py
  l10n_br_account_payment_order/wizards/account_move_payment_mode.py
  l10n_br_account_payment_order/wizards/account_move_payment_mode.xml
Labels: bot is merging ⏳, stale

#3664 [14.0] l10n_br_mdfe: include infLotacao tag on mdfe xml (required when mdfe have only one document_related)
  l10n_br_mdfe/models/document.py
  l10n_br_mdfe/models/product_product.py
  l10n_br_mdfe/views/product_product.xml
Labels: approved, bot is merging ⏳

#3672 [16.0][DEL] l10n_br_nfe: don't depend on erpbrasil.edoc.pdf anymore
  l10n_br_account_nfe/tests/test_nfe_danfe_account.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfe/report/ir_actions_report.py
  l10n_br_nfe/tests/test_nfe_danfe.py
  requirements.txt
Labels: bot is merging ⏳

#3670 [14.0][IMP] l10n_br_account_payment_order: BCO DO BRASIL CNAB 240 - Instruction and Return Codes
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_do_brasil_cnab_240.xml
  l10n_br_account_payment_order/demo/l10n_br_cnab_config_demo.xml
Labels: approved, bot is merging ⏳

#3679 [16.0][FIX] l10n_br_fiscal: refactor view company_id
  l10n_br_fiscal/views/operation_view.xml
Labels: approved, bot is merging ⏳, 16.0

#3677 [14.0][FIX] l10n_br_fiscal: refactor view company_id
  l10n_br_fiscal/views/operation_view.xml
Labels: approved, bot is merging ⏳, 14.0

#3680 [14.0][IMP] l10n_br_account: add fiscal doc invoice link
  l10n_br_account/models/account_move.py
  l10n_br_account/models/document.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/views/document_view.xml
Labels: approved, bot is merging ⏳

#3683 [15.0][FIX] l10n_br_fiscal: refactor view company_id
  l10n_br_fiscal/views/operation_view.xml
Labels: approved, bot is merging ⏳

#3681 [16.0][l10n_br_account] fiscal doc invoice link
  l10n_br_account/models/account_move.py
  l10n_br_account/models/document.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/views/document_view.xml
Labels: approved, bot is merging ⏳

#3682 [15.0][l10n_br_account] fiscal doc invoice link
  l10n_br_account/models/account_move.py
  l10n_br_account/models/document.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/views/document_view.xml
Labels: approved, bot is merging ⏳
