Repository OCA/l10n-brazil, pull requests merged in 2025-09, with the labels that each got.

#3966 [17.0][MIG] l10n_br_fiscal_certificate
  l10n_br_fiscal_certificate/README.rst
  l10n_br_fiscal_certificate/__init__.py
  l10n_br_fiscal_certificate/__manifest__.py
  l10n_br_fiscal_certificate/constants.py
  l10n_br_fiscal_certificate/hooks.py
  l10n_br_fiscal_certificate/i18n/l10n_br_fiscal_certificate.pot
  l10n_br_fiscal_certificate/i18n/pt_BR.po
  l10n_br_fiscal_certificate/models/__init__.py
  l10n_br_fiscal_certificate/models/certificate.py
  l10n_br_fiscal_certificate/models/res_company.py
  l10n_br_fiscal_certificate/models/res_config_settings.py
  l10n_br_fiscal_certificate/pyproject.toml
  l10n_br_fiscal_certificate/readme/CONTRIBUTORS.md
  l10n_br_fiscal_certificate/readme/DESCRIPTION.md
  l10n_br_fiscal_certificate/readme/HISTORY.md
  l10n_br_fiscal_certificate/readme/USAGE.md
  l10n_br_fiscal_certificate/security/ir.model.access.csv
  l10n_br_fiscal_certificate/static/description/icon.png
  l10n_br_fiscal_certificate/static/description/index.html
  l10n_br_fiscal_certificate/tests/__init__.py
  l10n_br_fiscal_certificate/tests/test_certificate.py
  l10n_br_fiscal_certificate/views/certificate_view.xml
  l10n_br_fiscal_certificate/views/res_company_view.xml
  l10n_br_fiscal_certificate/views/res_config_settings_view.xml
  requirements.txt
  test-requirements.txt
Labels: approved, migration, bot is merging ⏳, 17.0

#3970 [17.0][MIG] l10n_br_mdfe_spec
  l10n_br_mdfe_spec/README.rst
  l10n_br_mdfe_spec/__init__.py
  l10n_br_mdfe_spec/__manifest__.py
  l10n_br_mdfe_spec/i18n/l10n_br_mdfe_spec.pot
  l10n_br_mdfe_spec/i18n/pt_BR.po
  l10n_br_mdfe_spec/models/__init__.py
  l10n_br_mdfe_spec/models/spec_mixin.py
  l10n_br_mdfe_spec/models/v3_0/__init__.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_aereo_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_aquaviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_ferroviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_modal_rodoviario_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/mdfe_tipos_basico_v3_00.py
  l10n_br_mdfe_spec/models/v3_0/tipos_geral_mdfe_v3_00.py
  l10n_br_mdfe_spec/pyproject.toml
  l10n_br_mdfe_spec/readme/CONTRIBUTORS.md
  l10n_br_mdfe_spec/readme/DESCRIPTION.md
  l10n_br_mdfe_spec/static/description/icon.png
  l10n_br_mdfe_spec/static/description/index.html
  l10n_br_mdfe_spec/tests/__init__.py
  l10n_br_mdfe_spec/tests/test_mdfe_import.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 17.0

#3971 [17.0][MIG] l10n_br_cte_spec
  l10n_br_cte_spec/README.rst
  l10n_br_cte_spec/__init__.py
  l10n_br_cte_spec/__manifest__.py
  l10n_br_cte_spec/i18n/l10n_br_cte_spec.pot
  l10n_br_cte_spec/i18n/pt_BR.po
  l10n_br_cte_spec/models/__init__.py
  l10n_br_cte_spec/models/spec_mixin.py
  l10n_br_cte_spec/models/v4_0/__init__.py
  l10n_br_cte_spec/models/v4_0/cte_modal_aereo_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_aquaviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_dutoviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_ferroviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_rodoviario_os_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_modal_rodoviario_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_multi_modal_v4_00.py
  l10n_br_cte_spec/models/v4_0/cte_tipos_basico_v4_00.py
  l10n_br_cte_spec/models/v4_0/evento_cte_tipos_basico_v4_00.py
  l10n_br_cte_spec/models/v4_0/tipos_geral_cte_v4_00.py
  l10n_br_cte_spec/pyproject.toml
  l10n_br_cte_spec/readme/CONTRIBUTORS.md
  l10n_br_cte_spec/readme/DESCRIPTION.md
  l10n_br_cte_spec/static/description/icon.png
  l10n_br_cte_spec/static/description/index.html
  l10n_br_cte_spec/tests/__init__.py
  l10n_br_cte_spec/tests/test_cte_import.py
Labels: approved, migration, bot is merging ⏳, 17.0

#3981 [18.0][MIG] l10n_br_account_due_list
  l10n_br_account_due_list/README.rst
  l10n_br_account_due_list/__init__.py
  l10n_br_account_due_list/__manifest__.py
  l10n_br_account_due_list/i18n/es.po
  l10n_br_account_due_list/i18n/l10n_br_account_due_list.pot
  l10n_br_account_due_list/i18n/pt_BR.po
  l10n_br_account_due_list/models/__init__.py
  l10n_br_account_due_list/models/account_move.py
  l10n_br_account_due_list/pyproject.toml
  l10n_br_account_due_list/readme/CONFIGURE.md
  l10n_br_account_due_list/readme/CONTRIBUTORS.md
  l10n_br_account_due_list/readme/DESCRIPTION.md
  l10n_br_account_due_list/readme/HISTORY.md
  l10n_br_account_due_list/readme/INSTALL.md
  l10n_br_account_due_list/readme/ROADMAP.md
  l10n_br_account_due_list/readme/USAGE.md
  l10n_br_account_due_list/static/description/icon.png
  l10n_br_account_due_list/static/description/index.html
  l10n_br_account_due_list/static/img/l10n_br_account_due_list_payable.png
  l10n_br_account_due_list/static/img/l10n_br_account_due_list_receivable.png
  l10n_br_account_due_list/tests/__init__.py
  l10n_br_account_due_list/tests/test_payments.py
  l10n_br_account_due_list/views/account_move_view.xml
Labels: approved, migration, bot is merging ⏳, 18.0

#3978 [18.0][MIG] l10n_br_nfe_spec
  l10n_br_nfe_spec/README.rst
  l10n_br_nfe_spec/__init__.py
  l10n_br_nfe_spec/__manifest__.py
  l10n_br_nfe_spec/i18n/l10n_br_nfe_spec.pot
  l10n_br_nfe_spec/i18n/pt_BR.po
  l10n_br_nfe_spec/models/__init__.py
  l10n_br_nfe_spec/models/spec_mixin.py
  l10n_br_nfe_spec/models/v4_0/__init__.py
  l10n_br_nfe_spec/models/v4_0/leiaute_cons_sit_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_inut_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/leiaute_nfe_v4_00.py
  l10n_br_nfe_spec/models/v4_0/tipos_basico_v4_00.py
  l10n_br_nfe_spec/pyproject.toml
  l10n_br_nfe_spec/readme/CONFIGURE.md
  l10n_br_nfe_spec/readme/CONTRIBUTORS.md
  l10n_br_nfe_spec/readme/DESCRIPTION.md
  l10n_br_nfe_spec/readme/INSTALL.md
  l10n_br_nfe_spec/readme/ROADMAP.md
  l10n_br_nfe_spec/readme/USAGE.md
  l10n_br_nfe_spec/static/description/icon.png
  l10n_br_nfe_spec/static/description/index.html
  l10n_br_nfe_spec/tests/__init__.py
  l10n_br_nfe_spec/tests/test_nfe_import.py
  test-requirements.txt
Labels: approved, migration, ready to merge, bot is merging ⏳, 18.0

#4012 [16.0][FIX] l10n_br_account_nfe: permitido informar a tag pag com o tpag = 90
  l10n_br_account_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3968 [17.0][MIG] l10n_br_fiscal_dfe
  l10n_br_fiscal_dfe/README.rst
  l10n_br_fiscal_dfe/__init__.py
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_fiscal_dfe/constants/dfe.py
  l10n_br_fiscal_dfe/data/ir_cron.xml
  l10n_br_fiscal_dfe/i18n/l10n_br_fiscal_dfe.pot
  l10n_br_fiscal_dfe/i18n/pt_BR.po
  l10n_br_fiscal_dfe/models/__init__.py
  l10n_br_fiscal_dfe/models/attachment.py
  l10n_br_fiscal_dfe/models/dfe.py
  l10n_br_fiscal_dfe/models/document.py
  l10n_br_fiscal_dfe/models/res_company.py
  l10n_br_fiscal_dfe/pyproject.toml
  l10n_br_fiscal_dfe/readme/CONTRIBUTORS.md
  l10n_br_fiscal_dfe/readme/DESCRIPTION.md
  l10n_br_fiscal_dfe/security/ir.model.access.csv
  l10n_br_fiscal_dfe/static/description/icon.png
  l10n_br_fiscal_dfe/static/description/index.html
  l10n_br_fiscal_dfe/tests/__init__.py
  l10n_br_fiscal_dfe/tests/test_dfe.py
  l10n_br_fiscal_dfe/tools/__init__.py
  l10n_br_fiscal_dfe/tools/utils.py
  l10n_br_fiscal_dfe/views/dfe/dfe_views.xml
  l10n_br_fiscal_dfe/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal_dfe/views/res_company_view.xml
  requirements.txt
Labels: approved, migration, bot is merging ⏳, 17.0

#3982 [18.0][MIG] spec_driven_model
  .pre-commit-config.yaml
  spec_driven_model/README.rst
  spec_driven_model/__init__.py
  spec_driven_model/__manifest__.py
  spec_driven_model/i18n/pt_BR.po
  spec_driven_model/i18n/spec_driven_model.pot
  spec_driven_model/models/__init__.py
  spec_driven_model/models/spec_export.py
  spec_driven_model/models/spec_import.py
  spec_driven_model/models/spec_mixin.py
  spec_driven_model/models/spec_models.py
  spec_driven_model/models/spec_view.py
  spec_driven_model/pyproject.toml
  spec_driven_model/readme/CONFIGURE.md
  spec_driven_model/readme/CONTRIBUTORS.md
  spec_driven_model/readme/DESCRIPTION.md
  spec_driven_model/readme/HISTORY.md
  spec_driven_model/readme/INSTALL.md
  spec_driven_model/readme/ROADMAP.md
  spec_driven_model/readme/USAGE.md
  spec_driven_model/static/description/icon.png
  spec_driven_model/static/description/index.html
  spec_driven_model/tests/PurchaseOrderSchema.xsd
  spec_driven_model/tests/__init__.py
  spec_driven_model/tests/fake_mixin.py
  spec_driven_model/tests/fake_odoo_purchase.py
  spec_driven_model/tests/purchase_order_lib.py
  spec_driven_model/tests/spec_poxsd.py
  spec_driven_model/tests/spec_purchase.py
  spec_driven_model/tests/test_spec_model.py
  test-requirements.txt
Labels: approved, migration, bot is merging ⏳, 18.0

#4029 [17.0][REF] l10n_br_fiscal: code lint
  l10n_br_fiscal/models/comment.py
  l10n_br_fiscal/models/ibpt.py
  l10n_br_fiscal/models/invalidate_number.py
  l10n_br_fiscal/models/operation_dashboard.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: approved, bot is merging ⏳

#4027 [16.0][REF] l10n_br_fiscal: code lint
  l10n_br_fiscal/models/comment.py
  l10n_br_fiscal/models/ibpt.py
  l10n_br_fiscal/models/invalidate_number.py
  l10n_br_fiscal/models/operation_dashboard.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
Labels: approved, bot is merging ⏳

#4032 [16.0][REF] l10n_br_sale: assertAlmostEqual for amounts
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: approved, bot is merging ⏳

#4033 [16.0][FIX] l10n_br_stock_account: fix adapt type error for company
  l10n_br_stock_account/models/stock_rule.py
Labels: approved, bot is merging ⏳

#4030 [18.0][REF] l10n_br_base: Removendo aspas "" dos arquivos CSV
  l10n_br_base/data/res.city.csv
  l10n_br_base/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#4038 [16.0][REF] l10n_br_account: clean account move constants
  l10n_br_account/models/account_move.py
  l10n_br_account/models/constants.py
Labels: approved, bot is merging ⏳

#4039 [16.0][REF] l10n_br_base move some fields to specific modules
  l10n_br_base/models/res_partner.py
  l10n_br_base/views/res_partner_view.xml
  l10n_br_fiscal/models/res_partner.py
  l10n_br_fiscal/views/res_partner_view.xml
  l10n_br_hr/__manifest__.py
  l10n_br_hr/models/__init__.py
  l10n_br_hr/models/res_partner.py
  l10n_br_hr/views/res_partner_view.xml
  l10n_br_sped_base/__manifest__.py
  l10n_br_sped_base/models/__init__.py
  l10n_br_sped_base/models/res_partner.py
  l10n_br_sped_base/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#4040 [16.0][REF] l10n_br_fiscal: rename city_taxation_code
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/16.0.13.0.0/pre-migration.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/product_template.py
  l10n_br_fiscal/views/product_product_view.xml
  l10n_br_fiscal/views/product_template_view.xml
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/demo/product_demo.xml
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
Labels: approved, bot is merging ⏳

#4045 [17.0] Oca port l10n_br_base 16.0 to 17.0 ada3b8
  l10n_br_base/models/res_partner.py
  l10n_br_base/views/res_partner_view.xml
  l10n_br_fiscal/models/res_partner.py
  l10n_br_fiscal/views/res_partner_view.xml
Labels: approved, bot is merging ⏳

#3986 [18.0][MIG] l10n_br_fiscal_edi
  l10n_br_fiscal_edi/README.rst
  l10n_br_fiscal_edi/__init__.py
  l10n_br_fiscal_edi/__manifest__.py
  l10n_br_fiscal_edi/i18n/l10n_br_fiscal_edi.pot
  l10n_br_fiscal_edi/models/__init__.py
  l10n_br_fiscal_edi/models/document.py
  l10n_br_fiscal_edi/models/document_event.py
  l10n_br_fiscal_edi/models/document_workflow.py
  l10n_br_fiscal_edi/models/invalidate_number.py
  l10n_br_fiscal_edi/pyproject.toml
  l10n_br_fiscal_edi/readme/CONTRIBUTORS.md
  l10n_br_fiscal_edi/readme/DESCRIPTION.md
  l10n_br_fiscal_edi/readme/ROADMAP.md
  l10n_br_fiscal_edi/readme/USAGE.md
  l10n_br_fiscal_edi/security/ir.model.access.csv
  l10n_br_fiscal_edi/static/description/icon.png
  l10n_br_fiscal_edi/static/description/index.html
  l10n_br_fiscal_edi/tests/__init__.py
  l10n_br_fiscal_edi/tests/test_workflow.py
  l10n_br_fiscal_edi/views/document_event_report.xml
  l10n_br_fiscal_edi/views/document_event_template.xml
  l10n_br_fiscal_edi/views/document_event_view.xml
  l10n_br_fiscal_edi/views/document_view.xml
  l10n_br_fiscal_edi/views/invalidate_number_view.xml
  l10n_br_fiscal_edi/views/l10n_br_fiscal_action.xml
  l10n_br_fiscal_edi/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal_edi/wizards/__init__.py
  l10n_br_fiscal_edi/wizards/base_wizard_mixin.py
  l10n_br_fiscal_edi/wizards/document_cancel_wizard.py
  l10n_br_fiscal_edi/wizards/document_cancel_wizard.xml
  l10n_br_fiscal_edi/wizards/document_correction_wizard.py
  l10n_br_fiscal_edi/wizards/document_correction_wizard.xml
  l10n_br_fiscal_edi/wizards/document_status_wizard.xml
  l10n_br_fiscal_edi/wizards/invalidate_number_wizard.py
  l10n_br_fiscal_edi/wizards/invalidate_number_wizard.xml
Labels: approved, migration, bot is merging ⏳, 18.0

#4050 [17.0][FIX] l10n_br_fiscal_edi: fix migr to 17
  l10n_br_fiscal_edi/views/invalidate_number_view.xml
Labels: approved, bot is merging ⏳

#3973 [17.0][MIG] l10n_br_nfse
  l10n_br_nfse/README.rst
  l10n_br_nfse/__init__.py
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/constants/nfse.py
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/demo/product_demo.xml
  l10n_br_nfse/i18n/l10n_br_nfse.pot
  l10n_br_nfse/i18n/pt_BR.po
  l10n_br_nfse/models/__init__.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/product_template.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/pyproject.toml
  l10n_br_nfse/readme/CONFIGURE.md
  l10n_br_nfse/readme/CONTRIBUTORS.md
  l10n_br_nfse/readme/DESCRIPTION.md
  l10n_br_nfse/readme/INSTALL.md
  l10n_br_nfse/readme/ROADMAP.md
  l10n_br_nfse/readme/USAGE.md
  l10n_br_nfse/report/danfse.xml
  l10n_br_nfse/security/ir.model.access.csv
  l10n_br_nfse/static/description/icon.png
  l10n_br_nfse/static/description/index.html
  l10n_br_nfse/tests/__init__.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/document_view.xml
  l10n_br_nfse/views/product_product_view.xml
  l10n_br_nfse/views/product_template_view.xml
  l10n_br_nfse/views/res_company_view.xml
Labels: approved, migration, bot is merging ⏳, 17.0

#4049 [14.0][FIX/IMP] Remove Version Specifier and Disable Tour Tests (google-chrome)
  l10n_br_account_payment_brcobranca/__manifest__.py
  l10n_br_account_payment_order/README.rst
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/static/description/index.html
  l10n_br_base/__manifest__.py
  l10n_br_cnpj_search/__manifest__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/static/description/index.html
  l10n_br_cte/README.rst
  l10n_br_cte/__manifest__.py
  l10n_br_cte/static/description/index.html
  l10n_br_fiscal/README.rst
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/static/description/index.html
  l10n_br_fiscal_certificate/__manifest__.py
  l10n_br_fiscal_certificate/static/description/index.html
  l10n_br_fiscal_closing/__manifest__.py
  l10n_br_hr/__manifest__.py
  l10n_br_ie_search/__manifest__.py
  l10n_br_nfe/__manifest__.py
  l10n_br_nfse/README.rst
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/static/description/index.html
  l10n_br_nfse_barueri/__manifest__.py
  l10n_br_nfse_ginfes/__manifest__.py
  l10n_br_nfse_paulistana/__manifest__.py
  l10n_br_portal/tests/__init__.py
  l10n_br_pos/__manifest__.py
  l10n_br_pos_cfe/__manifest__.py
  l10n_br_pos_nfce/tests/__init__.py
  l10n_br_website_sale/__manifest__.py
  l10n_br_website_sale/tests/__init__.py
  l10n_br_website_sale_delivery/tests/__init__.py
  l10n_br_zip/__manifest__.py
  payment_pagseguro/tests/__init__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#3987 [18.0][MIG] l10n_br_fiscal_dfe
  l10n_br_fiscal_dfe/README.rst
  l10n_br_fiscal_dfe/__init__.py
  l10n_br_fiscal_dfe/__manifest__.py
  l10n_br_fiscal_dfe/constants/dfe.py
  l10n_br_fiscal_dfe/data/ir_cron.xml
  l10n_br_fiscal_dfe/i18n/l10n_br_fiscal_dfe.pot
  l10n_br_fiscal_dfe/i18n/pt_BR.po
  l10n_br_fiscal_dfe/models/__init__.py
  l10n_br_fiscal_dfe/models/attachment.py
  l10n_br_fiscal_dfe/models/dfe.py
  l10n_br_fiscal_dfe/models/document.py
  l10n_br_fiscal_dfe/models/res_company.py
  l10n_br_fiscal_dfe/pyproject.toml
  l10n_br_fiscal_dfe/readme/CONTRIBUTORS.md
  l10n_br_fiscal_dfe/readme/DESCRIPTION.md
  l10n_br_fiscal_dfe/security/ir.model.access.csv
  l10n_br_fiscal_dfe/static/description/icon.png
  l10n_br_fiscal_dfe/static/description/index.html
  l10n_br_fiscal_dfe/tests/__init__.py
  l10n_br_fiscal_dfe/tests/test_dfe.py
  l10n_br_fiscal_dfe/tools/__init__.py
  l10n_br_fiscal_dfe/tools/utils.py
  l10n_br_fiscal_dfe/views/dfe/dfe_views.xml
  l10n_br_fiscal_dfe/views/l10n_br_fiscal_menu.xml
  l10n_br_fiscal_dfe/views/res_company_view.xml
  requirements.txt
Labels: approved, migration, bot is merging ⏳, 18.0

#4052 [18.0][MIG] l10n_br_crm
  l10n_br_crm/README.rst
  l10n_br_crm/__init__.py
  l10n_br_crm/__manifest__.py
  l10n_br_crm/i18n/es.po
  l10n_br_crm/i18n/l10n_br_crm.pot
  l10n_br_crm/i18n/pt_BR.po
  l10n_br_crm/models/__init__.py
  l10n_br_crm/models/crm_lead.py
  l10n_br_crm/pyproject.toml
  l10n_br_crm/readme/CONFIGURE.md
  l10n_br_crm/readme/CONTRIBUTORS.md
  l10n_br_crm/readme/DESCRIPTION.md
  l10n_br_crm/readme/INSTALL.md
  l10n_br_crm/readme/ROADMAP.md
  l10n_br_crm/readme/USAGE.md
  l10n_br_crm/static/description/icon.png
  l10n_br_crm/static/description/index.html
  l10n_br_crm/tests/__init__.py
  l10n_br_crm/tests/test_crm_lead.py
  l10n_br_crm/tests/test_crm_onchange.py
  l10n_br_crm/views/crm_lead_view.xml
  l10n_br_crm/views/crm_quick_create_opportunity_form.xml
Labels: approved, migration, bot is merging ⏳, 18.0

#4019 [14.0][FIX] l10n_br_mdfe: payment information (infPag) - BCP #4016
  l10n_br_mdfe/models/document.py
  l10n_br_mdfe/tests/test_mdfe_structure.py
Labels: approved, bot is merging ⏳

#4028 [14.0][FIX] l10n_br_account_nfe: permitido informar a tag pag com o tpag = 90 - BCP #4012
  l10n_br_account_nfe/models/document.py
Labels: approved, bot is merging ⏳, 14.0, backport

#3989 [18.0][MIG] l10n_br_nfse
  l10n_br_nfse/README.rst
  l10n_br_nfse/__init__.py
  l10n_br_nfse/__manifest__.py
  l10n_br_nfse/constants/nfse.py
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/demo/product_demo.xml
  l10n_br_nfse/i18n/l10n_br_nfse.pot
  l10n_br_nfse/i18n/pt_BR.po
  l10n_br_nfse/models/__init__.py
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/product_template.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/pyproject.toml
  l10n_br_nfse/readme/CONFIGURE.md
  l10n_br_nfse/readme/CONTRIBUTORS.md
  l10n_br_nfse/readme/DESCRIPTION.md
  l10n_br_nfse/readme/INSTALL.md
  l10n_br_nfse/readme/ROADMAP.md
  l10n_br_nfse/readme/USAGE.md
  l10n_br_nfse/report/danfse.xml
  l10n_br_nfse/security/ir.model.access.csv
  l10n_br_nfse/static/description/icon.png
  l10n_br_nfse/static/description/index.html
  l10n_br_nfse/tests/__init__.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_nfse/views/document_line_view.xml
  l10n_br_nfse/views/document_view.xml
  l10n_br_nfse/views/product_product_view.xml
  l10n_br_nfse/views/product_template_view.xml
  l10n_br_nfse/views/res_company_view.xml
Labels: approved, migration, bot is merging ⏳, 18.0

#4024 [17.0][MIG] l10n_br_currency_rate_update
  l10n_br_currency_rate_update/README.rst
  l10n_br_currency_rate_update/__init__.py
  l10n_br_currency_rate_update/__manifest__.py
  l10n_br_currency_rate_update/i18n/es.po
  l10n_br_currency_rate_update/i18n/l10n_br_currency_rate_update.pot
  l10n_br_currency_rate_update/i18n/pt_BR.po
  l10n_br_currency_rate_update/models/__init__.py
  l10n_br_currency_rate_update/models/res_currency_rate_provider_bcb.py
  l10n_br_currency_rate_update/pyproject.toml
  l10n_br_currency_rate_update/readme/CONFIGURE.md
  l10n_br_currency_rate_update/readme/CONTRIBUTORS.md
  l10n_br_currency_rate_update/readme/DESCRIPTION.md
  l10n_br_currency_rate_update/readme/USAGE.md
  l10n_br_currency_rate_update/static/description/icon.png
  l10n_br_currency_rate_update/static/description/index.html
  l10n_br_currency_rate_update/tests/__init__.py
  l10n_br_currency_rate_update/tests/test_currency_rate_update_bcb.py
Labels: approved, migration, bot is merging ⏳, 17.0

#3997 [14.0][BACKPORT][MIG] l10n_br_hr_contract: Migration to 14.0
  l10n_br_hr_contract/README.rst
  l10n_br_hr_contract/__init__.py
  l10n_br_hr_contract/__manifest__.py
  l10n_br_hr_contract/data/hr_contract_admission_type_data.xml
  l10n_br_hr_contract/data/hr_contract_labor_bond_type_data.xml
  l10n_br_hr_contract/data/hr_contract_labor_regime_data.xml
  l10n_br_hr_contract/data/hr_contract_notice_termination_data.xml
  l10n_br_hr_contract/data/hr_contract_resignation_cause_data.xml
  l10n_br_hr_contract/data/hr_contract_salary_unit_data.xml
  l10n_br_hr_contract/i18n/l10n_br_hr_contract.pot
  l10n_br_hr_contract/i18n/pt_BR.po
  l10n_br_hr_contract/models/__init__.py
  l10n_br_hr_contract/models/hr_contract.py
  l10n_br_hr_contract/models/hr_contract_admission_type.py
  l10n_br_hr_contract/models/hr_contract_labor_bond_type.py
  l10n_br_hr_contract/models/hr_contract_labor_regime.py
  l10n_br_hr_contract/models/hr_contract_labor_resignation_cause.py
  l10n_br_hr_contract/models/hr_contract_labor_salary_unit.py
  l10n_br_hr_contract/models/hr_contract_notice_termination.py
  l10n_br_hr_contract/models/hr_data_abstract.py
  l10n_br_hr_contract/pyproject.toml
  l10n_br_hr_contract/readme/CONFIGURE.md
  l10n_br_hr_contract/readme/CONTRIBUTORS.md
  l10n_br_hr_contract/readme/DESCRIPTION.md
  l10n_br_hr_contract/readme/HISTORY.md
  l10n_br_hr_contract/readme/INSTALL.md
  l10n_br_hr_contract/readme/ROADMAP.md
  l10n_br_hr_contract/readme/USAGE.md
  l10n_br_hr_contract/security/ir.model.access.csv
  l10n_br_hr_contract/static/description/icon.png
  l10n_br_hr_contract/static/description/index.html
  l10n_br_hr_contract/tests/__init__.py
  l10n_br_hr_contract/tests/test_l10n_br_hr_contract.py
  l10n_br_hr_contract/views/hr_contract_view.xml
  l10n_br_hr_contract/views/l10n_br_hr_contract_action.xml
  l10n_br_hr_contract/views/l10n_br_hr_contract_menu.xml
  setup/l10n_br_hr_contract/odoo/addons/l10n_br_hr_contract
  setup/l10n_br_hr_contract/setup.py
Labels: approved, migration, ready to merge, bot is merging ⏳, 14.0, backport

#4056 [18.0][MIG] l10n_br_nfse_focus
  l10n_br_nfse_focus/README.rst
  l10n_br_nfse_focus/__init__.py
  l10n_br_nfse_focus/__manifest__.py
  l10n_br_nfse_focus/data/l10n_br_nfse_focus_cron.xml
  l10n_br_nfse_focus/i18n/l10n_br_nfse_focus.pot
  l10n_br_nfse_focus/i18n/pt_BR.po
  l10n_br_nfse_focus/models/__init__.py
  l10n_br_nfse_focus/models/document.py
  l10n_br_nfse_focus/models/res_company.py
  l10n_br_nfse_focus/pyproject.toml
  l10n_br_nfse_focus/readme/CONFIGURE.md
  l10n_br_nfse_focus/readme/CONTRIBUTORS.md
  l10n_br_nfse_focus/readme/DESCRIPTION.md
  l10n_br_nfse_focus/readme/INSTALL.md
  l10n_br_nfse_focus/readme/USAGE.md
  l10n_br_nfse_focus/static/description/icon.png
  l10n_br_nfse_focus/static/description/index.html
  l10n_br_nfse_focus/tests/__init__.py
  l10n_br_nfse_focus/tests/nfse/pdf_example.pdf
  l10n_br_nfse_focus/tests/test_l10n_br_nfse_focus.py
  l10n_br_nfse_focus/views/res_company.xml
Labels: approved, migration, bot is merging ⏳, 18.0

#4041 [16.0][REF] Renomeia campos fiscais que conflitam
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/views/account_move_view.xml
  l10n_br_account/views/fiscal_invoice_view.xml
  l10n_br_contract/__manifest__.py
  l10n_br_contract/migrations/16.0.5.0.0/pre-migration.py
  l10n_br_contract/views/contract_line.xml
  l10n_br_cte/models/document.py
  l10n_br_cte/models/document_line.py
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/16.0.14.0.0/pre-migration.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/models/document_mixin.py
  l10n_br_fiscal/models/document_mixin_methods.py
  l10n_br_fiscal/models/document_related.py
  l10n_br_fiscal/views/document_line_view.xml
  l10n_br_fiscal/views/document_view.xml
  l10n_br_nfe/models/document.py
  l10n_br_nfse/models/document.py
  l10n_br_purchase/__manifest__.py
  l10n_br_purchase/migrations/16.0.5.0.0/pre-migration.py
  l10n_br_purchase/models/purchase_order_line.py
  l10n_br_sale/__manifest__.py
  l10n_br_sale/migrations/16.0.6.0.0/pre-migration.py
  l10n_br_sale/models/sale_order_line.py
  l10n_br_sale/views/sale_view.xml
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sped_ecd/models/sped_ecd.py
  l10n_br_stock_account/__manifest__.py
  l10n_br_stock_account/migrations/16.0.3.0.0/pre-migration.py
  l10n_br_stock_account/views/stock_picking.xml
Labels: approved, bot is merging ⏳

#4078 [16.0][IMP] l10n_br_fiscal: currency as related
  l10n_br_fiscal/models/document.py
Labels: approved, bot is merging ⏳

#4079 [16.0][IMP] l10n_br_contract: inline edition support
  l10n_br_contract/views/contract_view.xml
Labels: approved, bot is merging ⏳

#4082 [16.0][REF] l10n_br_nfse: hide meths from RPC (security)
  l10n_br_nfse/models/document.py
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/models/res_company.py
  l10n_br_nfse/models/res_partner.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
Labels: approved, bot is merging ⏳

#4085 [16.0][IMP] l10n_br_fiscal: _compute_comment_ids in line
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
Labels: approved, bot is merging ⏳

#4089 [14.0][FIX] enable tests after fix chrome version
  l10n_br_portal/tests/__init__.py
  l10n_br_website_sale/tests/__init__.py
  payment_pagseguro/tests/__init__.py
Labels: approved, bot is merging ⏳

#4073 [16.0][IMP] l10n_br_account: remove taxes of the amount_total in _prepare_tax_totals
  l10n_br_account/models/account_tax.py
Labels: approved, bot is merging ⏳

#4075 [18.0][ADD] l10n_br_base_l10n_br_compat
  l10n_br_account_due_list/tests/test_payments.py
  l10n_br_base_l10n_br_compat/README.rst
  l10n_br_base_l10n_br_compat/__init__.py
  l10n_br_base_l10n_br_compat/__manifest__.py
  l10n_br_base_l10n_br_compat/pyproject.toml
  l10n_br_base_l10n_br_compat/readme/CONTRIBUTORS.md
  l10n_br_base_l10n_br_compat/readme/DESCRIPTION.md
  l10n_br_base_l10n_br_compat/static/description/index.html
  l10n_br_base_l10n_br_compat/views/res_company_view.xml
  l10n_br_base_l10n_br_compat/views/res_partner_views.xml
  l10n_br_fiscal/security/ir.model.access.csv
Labels: approved, bot is merging ⏳

#4094 [16.0] l10n_br_account: fix composite move importation
  l10n_br_account/models/account_move.py
  l10n_br_account/tests/test_account_move_lc.py
Labels: approved, bot is merging ⏳

#3963 [16.0][REF] l10n_br_fiscal, l10n_br_delivery, l10n_br_cnab_structure, l10n_br_mdfe: Command.set
  l10n_br_cnab_structure/demo/payment_mode.xml
  l10n_br_delivery/demo/l10n_br_delivery_demo.xml
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/demo/fiscal_operation_demo.xml
  l10n_br_mdfe/demo/fiscal_document_demo.xml
Labels: approved, ready to merge, bot is merging ⏳

#4087 [16.0][IMP] l10n_br_account: set account move reversal journal_id by force_fiscal_operation_id.journal_id and others
  l10n_br_account/tests/test_invoice_refund.py
  l10n_br_account/wizards/account_move_reversal.py
  l10n_br_account/wizards/account_move_reversal_view.xml
  l10n_br_purchase/hooks.py
  l10n_br_sale/hooks.py
  l10n_br_sale_commission/tests/test_l10n_br_sale_commission.py
Labels: bot is merging ⏳

#4031 [18.0][REF] l10n_br_base: Usando o método do tools para validar Chaves PIX tipo CNPJ
  l10n_br_base/models/res_partner_pix.py
  l10n_br_base/tests/test_valid_pix.py
  l10n_br_base/tools.py
Labels: approved, ready to merge, bot is merging ⏳

#4108 [17.0][REF] l10n_br_fiscal: Atualização do Domain nas regras de registros
  l10n_br_fiscal/security/fiscal_security.xml
Labels: bot is merging ⏳, backport, 17.0

#4109 [18.0][REF] l10n_br_fiscal: Atualização do Domain nas regras de registros
  l10n_br_fiscal/security/fiscal_security.xml
Labels: bot is merging ⏳, backport, 18.0

#4113 [18.0][MIG] l10n_br_hr_contract: Migration to 18.0
  l10n_br_hr_contract/README.rst
  l10n_br_hr_contract/__init__.py
  l10n_br_hr_contract/__manifest__.py
  l10n_br_hr_contract/data/hr_contract_admission_type_data.xml
  l10n_br_hr_contract/data/hr_contract_labor_bond_type_data.xml
  l10n_br_hr_contract/data/hr_contract_labor_regime_data.xml
  l10n_br_hr_contract/data/hr_contract_notice_termination_data.xml
  l10n_br_hr_contract/data/hr_contract_resignation_cause_data.xml
  l10n_br_hr_contract/data/hr_contract_salary_unit_data.xml
  l10n_br_hr_contract/i18n/l10n_br_hr_contract.pot
  l10n_br_hr_contract/i18n/pt_BR.po
  l10n_br_hr_contract/models/__init__.py
  l10n_br_hr_contract/models/hr_contract.py
  l10n_br_hr_contract/models/hr_contract_admission_type.py
  l10n_br_hr_contract/models/hr_contract_labor_bond_type.py
  l10n_br_hr_contract/models/hr_contract_labor_regime.py
  l10n_br_hr_contract/models/hr_contract_labor_resignation_cause.py
  l10n_br_hr_contract/models/hr_contract_labor_salary_unit.py
  l10n_br_hr_contract/models/hr_contract_notice_termination.py
  l10n_br_hr_contract/models/hr_data_abstract.py
  l10n_br_hr_contract/pyproject.toml
  l10n_br_hr_contract/readme/CONFIGURE.md
  l10n_br_hr_contract/readme/CONTRIBUTORS.md
  l10n_br_hr_contract/readme/DESCRIPTION.md
  l10n_br_hr_contract/readme/HISTORY.md
  l10n_br_hr_contract/readme/INSTALL.md
  l10n_br_hr_contract/readme/ROADMAP.md
  l10n_br_hr_contract/readme/USAGE.md
  l10n_br_hr_contract/security/ir.model.access.csv
  l10n_br_hr_contract/static/description/icon.png
  l10n_br_hr_contract/static/description/index.html
  l10n_br_hr_contract/tests/__init__.py
  l10n_br_hr_contract/tests/test_l10n_br_hr_contract.py
  l10n_br_hr_contract/views/hr_contract_view.xml
  l10n_br_hr_contract/views/l10n_br_hr_contract_action.xml
  l10n_br_hr_contract/views/l10n_br_hr_contract_menu.xml
Labels: approved, bot is merging ⏳

#4102 [16.0] l10n_br_fiscal...: convert _onchange_product_id_fiscal to compute
  l10n_br_account/models/account_move_line.py
  l10n_br_account/models/document_line.py
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_account/tests/test_move_edition.py
  l10n_br_account/views/account_move_view.xml
  l10n_br_account_nfe/tests/test_nfe_with_ipi.py
  l10n_br_cte/demo/fiscal_document_demo.xml
  l10n_br_delivery/demo/sale_order_demo.xml
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/demo/fiscal_document_nfse_demo.xml
  l10n_br_fiscal/models/document_line.py
  l10n_br_fiscal/models/document_line_mixin.py
  l10n_br_fiscal/models/document_line_mixin_methods.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_fiscal/tests/test_fiscal_document_nfse.py
  l10n_br_fiscal/tests/test_tax_benefit.py
  l10n_br_fiscal_subsequent_document/tests/test_subsequent_operation.py
  l10n_br_nfe/demo/fiscal_document_demo.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000022062777169.xml
  l10n_br_nfe/tests/nfe/v4_00/leiauteNFe/NFe35200159594315000157550010000000032062777166.xml
  l10n_br_nfe/tests/test_nfe_serialize.py
  l10n_br_nfe/tests/test_nfe_xml_validation.py
  l10n_br_nfse/demo/fiscal_document_demo.xml
  l10n_br_nfse/models/document_line.py
  l10n_br_nfse/tests/test_fiscal_document_nfse_common.py
  l10n_br_purchase/demo/l10n_br_purchase.xml
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_purchase_request/wizards/purchase_request_line_make_purchase_order.py
  l10n_br_purchase_stock/demo/purchase_order.xml
  l10n_br_purchase_stock/models/__init__.py
  l10n_br_purchase_stock/models/stock_rule.py
  l10n_br_sale/demo/l10n_br_sale.xml
  l10n_br_sale/models/sale_order.py
  l10n_br_sale/tests/test_l10n_br_sale.py
  l10n_br_sale/tests/test_l10n_br_sale_pricelist.py
  l10n_br_sale_commission/demo/sale_order_demo.xml
  l10n_br_sale_commission/models/commission_settlement.py
  l10n_br_sale_invoice_plan/demo/sale_order_demo.xml
  l10n_br_sale_stock/demo/sale_order_demo.xml
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_stock_account/demo/l10n_br_stock_account_demo.xml
  l10n_br_stock_account/models/stock_move.py
  l10n_br_stock_account/tests/common.py
  l10n_br_stock_account/wizards/stock_return_picking.py
Labels: approved, bot is merging ⏳
