Repository OCA/l10n-brazil, pull requests merged in 2025-02, with the labels that each got.

#3603 [14.0][FIX] l10n_br_hr: fix employee rg number
  l10n_br_hr/models/hr_employee.py
Labels: approved, bot is merging ⏳

#3612 [14.0][FIX] l10n_br_nfe: ignore check key date if there is no doc date
  l10n_br_nfe/models/document.py
Labels: approved, bot is merging ⏳

#3611 [16.0][FIX] l10n_br_fiscal_edi: Evita erro por chamar o método back2draft duas vezes
  l10n_br_fiscal_edi/models/document_workflow.py
Labels: approved, bot is merging ⏳

#3614 [14.0][IMP][l10n_br_account_payment_order][l10n_br_account_payment_brcobranca]: Add boleto write-off and devolution codes for Santander CNAB 240
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_santander_240_boleto_write_off_devolution.xml
  l10n_br_account_payment_order/demo/l10n_br_cnab_config_demo.xml
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/models/l10n_br_cnab_code.py
  l10n_br_account_payment_order/views/l10n_br_cnab_config_view.xml
Labels: approved, bot is merging ⏳

#3618 [16.0][l10n_br_account] l10n_br_account: update _sync_invoice to upstream
  l10n_br_account/models/account_move.py
  l10n_br_account/models/account_move_line.py
  l10n_br_account/tests/test_multi_localizations_invoice.py
Labels: approved, bot is merging ⏳

#3615 [16.0][MIG+IMP] l10n_br_sale: Migrando o Relatório de Vendas para incluir os campos do Brasil e incluído teste
  l10n_br_sale/report/sale_report.py
  l10n_br_sale/tests/__init__.py
  l10n_br_sale/tests/test_sale_order_report.py
Labels: approved, bot is merging ⏳

#3619 [14.0][FIX+IMP] l10n_br_sale_stock: Inform Fields that should not be used from Sale 'prepare' methods, tests
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: approved, bot is merging ⏳

#3621 [14.0][FIX] l10n_br_account_withholding: ensure unique City Hall per city when applicable
  l10n_br_account_withholding/models/res_partner.py
Labels: approved, bot is merging ⏳

#3630 [16.0]FWD] l10n_br_account_payment_order: FWD PR 3614, Add boleto write-off and devolution codes for Santander CNAB 240,
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_order/__manifest__.py
  l10n_br_account_payment_order/data/cnab_codes/banco_santander_240_boleto_write_off_devolution.xml
  l10n_br_account_payment_order/demo/l10n_br_cnab_config_demo.xml
  l10n_br_account_payment_order/models/l10n_br_cnab_boleto_fields.py
  l10n_br_account_payment_order/models/l10n_br_cnab_code.py
  l10n_br_account_payment_order/views/l10n_br_cnab_config_view.xml
Labels: approved, bot is merging ⏳

#3628 [14.0][FIX] l10n_br_fiscal: rename operation code
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/tests/test_operation.py
  l10n_br_fiscal/views/operation_view.xml
Labels: approved, bot is merging ⏳

#3624 [14.0][IMP] l10n_br_account_payment_cobranca: add seg. R details
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_order/demo/l10n_br_cnab_config_demo.xml
Labels: approved, bot is merging ⏳

#3633 [15.0][FIX] l10n_br_fiscal: rename operation code - fwp 3628
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/views/operation_view.xml
Labels: approved, 15.0, backport

#3634 [16.0][FIX] l10n_br_account_payment_order: Teste CNAB de Alteração da Data de Vencimento de mais de 1 linha
  l10n_br_account_payment_order/tests/test_base_class.py
  l10n_br_account_payment_order/tests/test_payment_order_change.py
Labels: bot is merging ⏳

#3567 [16.0][l10n_br_fiscal][IMP] l10n_br_fiscal: standardize data+demo load
  l10n_br_account/tests/test_account_move_lc.py
  l10n_br_fiscal/__init__.py
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/data/l10n_br_fiscal.ncm.csv
  l10n_br_fiscal/data/l10n_br_fiscal_cfop_data.xml
  l10n_br_fiscal/data/l10n_br_fiscal_icms_tax_definition_data.xml
  l10n_br_fiscal/data/l10n_br_fiscal_tax_icms_data.xml
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/data/simplified_tax_data.xml
  l10n_br_fiscal/demo/__init__.py
  l10n_br_fiscal/demo/city_taxation_code_demo.xml
  l10n_br_fiscal/demo/company_demo.xml
  l10n_br_fiscal/demo/fiscal_document_demo.xml
  l10n_br_fiscal/demo/fiscal_document_nfse_demo.xml
  l10n_br_fiscal/demo/fiscal_operation_demo.xml
  l10n_br_fiscal/demo/icms_tax_definition_demo.xml
  l10n_br_fiscal/demo/l10n_br_fiscal.cest-demo.csv
  l10n_br_fiscal/demo/l10n_br_fiscal.nbm-demo.csv
  l10n_br_fiscal/demo/l10n_br_fiscal.nbs-demo.csv
  l10n_br_fiscal/demo/l10n_br_fiscal.ncm-demo.csv
  l10n_br_fiscal/demo/l10n_br_fiscal_document_email.xml
  l10n_br_fiscal/demo/partner_demo.xml
  l10n_br_fiscal/demo/product_demo.xml
  l10n_br_fiscal/demo/res_users_demo.xml
  l10n_br_fiscal/demo/subsequent_operation_demo.xml
  l10n_br_fiscal/hooks.py
  l10n_br_fiscal/tests/test_fiscal_document_generic.py
  l10n_br_purchase/tests/test_l10n_br_purchase.py
  l10n_br_sale/tests/test_l10n_br_sale.py
Labels: approved, ready to merge, bot is merging ⏳

#3570 [16.0][MIG] l10n_br_sale_stock
  l10n_br_sale_stock/README.rst
  l10n_br_sale_stock/__init__.py
  l10n_br_sale_stock/__manifest__.py
  l10n_br_sale_stock/demo/l10n_br_sale_stock_demo.xml
  l10n_br_sale_stock/demo/sale_order_demo.xml
  l10n_br_sale_stock/i18n/l10n_br_sale_stock.pot
  l10n_br_sale_stock/i18n/pt_BR.po
  l10n_br_sale_stock/migrations/14.0.2.0.0/pre-migration.py
  l10n_br_sale_stock/models/__init__.py
  l10n_br_sale_stock/models/sale_order.py
  l10n_br_sale_stock/models/sale_order_line.py
  l10n_br_sale_stock/models/stock_move.py
  l10n_br_sale_stock/models/stock_picking.py
  l10n_br_sale_stock/pyproject.toml
  l10n_br_sale_stock/readme/CONFIGURE.md
  l10n_br_sale_stock/readme/CONTRIBUTORS.md
  l10n_br_sale_stock/readme/CREDITS.md
  l10n_br_sale_stock/readme/DESCRIPTION.md
  l10n_br_sale_stock/readme/HISTORY.md
  l10n_br_sale_stock/readme/INSTALL.md
  l10n_br_sale_stock/readme/ROADMAP.md
  l10n_br_sale_stock/readme/USAGE.md
  l10n_br_sale_stock/static/description/icon.png
  l10n_br_sale_stock/static/description/index.html
  l10n_br_sale_stock/tests/__init__.py
  l10n_br_sale_stock/tests/test_sale_stock.py
  l10n_br_sale_stock/wizards/__init__.py
  l10n_br_sale_stock/wizards/stock_invoice_onshipping.py
Labels: bot is merging ⏳

#3632 [16.0][FIX] l10n_br_fiscal: rename operation code - fwp 3628
  l10n_br_fiscal/data/operation_data.xml
  l10n_br_fiscal/views/operation_view.xml
Labels: bot is merging ⏳, 16.0, backport

#3635 [16.0][REM] l10n_br_sale_stock: Removendo o antigo Script de Migração da v14
  l10n_br_sale_stock/migrations/14.0.2.0.0/pre-migration.py
Labels: approved, bot is merging ⏳

#3599 [16.0][REF] l10n_br_stock_account: Não informar a Operação Fiscal Padrão quando a Empresa não é do Brasil
  l10n_br_stock_account/models/stock_picking.py
Labels: approved, bot is merging ⏳

#3637 [16.0][FIX] l10n_br_account_payment_order, l10n_br_account_payment_brcobranca: CNAB Santander 240, campos necessários para outras Instruções, FWD 3624
  l10n_br_account_payment_brcobranca/models/account_payment_line.py
  l10n_br_account_payment_order/demo/l10n_br_cnab_config_demo.xml
Labels: approved, bot is merging ⏳

#3638 [16.0][FIX] l10n_br_fiscal: rename wrong ncm xmlids
  l10n_br_fiscal/__manifest__.py
  l10n_br_fiscal/migrations/16.0.2.15.0/pre-migration.py
Labels: approved, bot is merging ⏳

#3642 [16.0][FWD+REF] l10n_br_zip: Desnecessário usar o TRY para importar Bibliotecas, FWD 2744
  l10n_br_zip/__manifest__.py
  l10n_br_zip/models/l10n_br_zip.py
Labels: approved, bot is merging ⏳
